---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/1/19 20:58
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/10/19 17:36
---

local AdBreakView = BaseDialogView:New('AdBreakView')
local this = AdBreakView
this.viewType = CanvasSortingOrderManager.LayerType.Popup_Dialog

local data = nil
this.delayTime = nil
this.hideTime  = 0

function AdBreakView.Awake()
end

local currAdid = 0
function AdBreakView.OnEnable()
    currAdid = ModelList.AdModel.delayAdid
    data = ModelList.AdModel.interstitialData
    if this.delayTime then
        LuaTimer:Remove(this.delayTime,LuaTimer.TimerType.UI)
        this.delayTime = nil
    end
    this.delayTime = LuaTimer:SetDelayFunction(1, function()
        if fun.get_active_scene().name == "SceneHome" then
            ---有个奇怪的bug，会同时触发几次，加个限时
            if this.hideTime and os.time() - this.hideTime < 1 then
                return
            end
            ModelList.AdModel:C2S_WathchAdResult(currAdid, "", "", AD_EVENTS.AD_EVENTS_PLAY_GAME, 0, nil)
            Facade.SendNotification(NotifyName.HideUI, ViewList.AdBreakView)

            this.hideTime = os.time()
            SDK.ShowInterstitialAd(currAdid, AD_EVENTS.AD_EVENTS_PLAY_GAME, data.adType, data.params)
        end
        this.delayTime = nil
    end,nil,LuaTimer.TimerType.UI)

end

function AdBreakView.OnDisable()
    currAdid = ModelList.AdModel.delayAdid
    --  ModelList.AdModel:C2S_WathchAdResult(currAdid,"","",AD_EVENT.AD_EVENT_ADVERTISE)
end


return this















