---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/12 17:50
---



require("View/Bingo/SettleModule/State/BaseSettleState")

SettleRankState = Clazz(BaseSettleState,"SettleRankState")
local this = SettleRankState
function SettleRankState:New(view)
    local o = {}
    setmetatable(o,{__index = SettleRankState})
    o.view = view
    return o
end


function SettleRankState:OnEnter(fsm,prvious,...)
    this:OpenRankView(self.view)
end

function SettleRankState:OpenRankView( view)
    ViewList.SettleRankView:SkipLoadShow(view)
end



--function SettleRankState:on_x_update()
--
--end


function SettleRankState:OnLeave(fsm)

end

function SettleRankState:FinishOperate(fsm)
    if fsm then
        --self:ChangeState(fsm,"SettleEvaluationState")
        self:ChangeState(fsm,"SettleDetailState")
        
    end
end