---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/12 17:50
---


require("View/Bingo/SettleModule/State/BaseSettleState")

SettleRocketState = Clazz(BaseSettleState,"SettleRocketState")
local this = SettleRocketState
function SettleRocketState:New(view)
    local o = {}
    setmetatable(o,{__index = SettleRocketState})
    o.view = view
    return o
end


function SettleRocketState:OnEnter(fsm,prvious,...)
    this:OpenRocketView(self.view)
end

function SettleRocketState:OpenRocketView( view)
    ViewList.SettleRocketView:SkipLoadShow(view)
    ModelList.GuideModel:OpenUI("SettleRocketView")
end



--function SettleRocketState:on_x_update()
--
--end


function SettleRocketState:OnLeave(fsm)

end

function SettleRocketState:FinishOperate(fsm)
    if fsm then
        if ModelList.BattleModel:GetCurrModel():GetSmallGameData() ~= nil then
            self:ChangeState(fsm,"SettleSmallGameState")
        else
            self:ChangeState(fsm,"SettleClimbRankState")
        end

    end
end
