---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/4/19 12:13
---

local CompetitionRankRewardItem = BaseView:New("CompetitionRankRewardItem")
local this = CompetitionRankRewardItem
this.viewType = CanvasSortingOrderManager.LayerType.None

this.auto_bind_ui_items =
{
    "rewarditem",
    "text_num",
    "double",
}

function CompetitionRankRewardItem:New()
    local o = {}
    self.__index = self
    setmetatable(o,self)
    return o
end

function CompetitionRankRewardItem:Awake()
    self:on_init()
end

function CompetitionRankRewardItem:OnEnable(params)
    self._init = true
    if self.cacheData then
        self:SetReward(self.cacheData)
    end
    fun.set_active(self.double,params and true or false)
end

function CompetitionRankRewardItem:OnDisable()
    self._init = nil
    self.cacheData = nil
end

function CompetitionRankRewardItem:SetReward(data)
    self.cacheData = data
    if self._init then
        if (data.id and data.id <100 ) or  (data[1] and data[1]<100) then
            local icon = Csv.GetItemOrResource(data.id or data[1],"more_icon")
            Cache.SetImageSprite("ItemAtlas",icon,self.rewarditem)
            --Cache.load_sprite(AssetList[icon],icon,function(tex)
            --    if tex then
            --        self.rewarditem.texture = tex.texture
            --    end
            --end)

            if (data.id and data.id  == Resource.hintTime ) or  (data[1] and data[1] == Resource.hintTime) then
                ---放大镜数量转化成时间
                local ti = data.value or data[2]
                local hrs = math.floor(ti / 3600)
                if hrs > 0 then
                    self.text_num.text = fun.NumInsertComma(hrs) .. " HRS" --tostring(data.value)
                else
                    local min = math.floor(ti / 60)
                    self.text_num.text = fun.NumInsertComma(min) .. " Min" --tostring(data.value)
                end
            elseif (data.id and data.id  == Resource.dailycoins_bonus ) or  (data[1] and data[1] == Resource.dailycoins_bonus) then
                self:SetDailyCoinsBonus()
                self.text_num.text = fun.FormatText(data)
            else
                self.text_num.text = fun.format_number(data.value or data[2]) --tostring(data.value)
            end
        else
            local icon = Csv.GetItemOrResource(data.id or data[1],"icon")
            Cache.SetImageSprite("ItemAtlas",icon,self.rewarditem)
            self.text_num.text = fun.NumInsertComma(data.value or data[2]) --tostring(data.value)
        end
    end
end

function CompetitionRankRewardItem:GetRewardItemId()
    if self.cacheData then
        return self.cacheData.id and self.cacheData.id or self.cacheData[1]
    end
    return nil
end

function CompetitionRankRewardItem:GetPosition()
    if self.go then
        return self.go.transform.position
    end
    return nil
end

function CompetitionRankRewardItem:GetIconItem()
    if self.icon_item then
        return self.icon_item
    end
    return nil
end


function CompetitionRankRewardItem:SetDailyCoinsBonus()
    if self.text_title then
        fun.set_active(self.text_title, true)
        self.text_title.text =  Csv.GetDescription(529)
    end
end


return this