--
--require "View/CommonView/RewardIconValueView"
--
--require "View/MakeFood/productState/BaseMakeFoodProductState"
--require "View/MakeFood/productState/MakeFoodProductOriginalState"
--require "View/MakeFood/productState/MakeFoodProductEnterState"
--require "View/MakeFood/productState/MakeFoodProductExitState"
--require "View/MakeFood/productState/MakeFoodProductWaitRewardState"
--
--MakeFoodProductView = BaseView:New("MakeFoodProductView","MakeFoodAtlas")
--local this = MakeFoodProductView
--this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--
--local reward_item_cache = nil
--
--this.auto_bind_ui_items = {
--    "anima",
--    "icon_product",
--    "reward_content",
--    "reward_item",
--    "btn_collect",
--    "text_name"
--}
--
--function MakeFoodProductView:Awake()
--    self:on_init()
--end
--
--function MakeFoodProductView:OnEnable()
--    Facade.RegisterView(self)
--
--    self:SetCuisinesInfo()
--
--    self:BuildFsm()
--    self._fsm:GetCurState():Enter(self._fsm)
--
--    UISound.play("cooking_reward")
--end
--
--function MakeFoodProductView:OnDisable()
--    Facade.RemoveView(self)
--    reward_item_cache = nil
--    self:DisposeFsm()
--end
--
--function MakeFoodProductView:BuildFsm()
--    self:DisposeFsm()
--    self._fsm = Fsm.CreateFsm("MakeFoodProductView",self,{
--        MakeFoodProductOriginalState,
--        MakeFoodProductEnterState,
--        MakeFoodProductExitState,
--        MakeFoodProductWaitRewardState
--    })
--    self._fsm:StartFsm("MakeFoodProductOriginalState")
--end
--
--function MakeFoodProductView:DisposeFsm()
--    if self._fsm then
--        self._fsm:Dispose()
--        self._fsm = nil
--    end
--end
--
--function MakeFoodProductView:PlayEnter()
--    AnimatorPlayHelper.Play(self.anima,"MakeFoodProductViewenter",false,function()
--        self._fsm:GetCurState():Accomplish(self._fsm)
--    end)
--end
--
--function MakeFoodProductView:PlayExit()
--    AnimatorPlayHelper.Play(self.anima,"MakeFoodProductViewexit",false,function()
--        Facade.SendNotification(NotifyName.CloseUI,this)
--    end)
--end
--
--function MakeFoodProductView:SetCuisinesInfo()
--    local cuisinesId = ModelList.ItemModel:GetMakeFoodCurrentCuisines()
--    if cuisinesId then
--        local cuisinesData = Csv.GetData("city_recipe",cuisinesId)
--        Cache.load_sprite(AssetList[cuisinesData.icon],cuisinesData.icon,function(sp)
--            self.icon_product.sprite = sp
--        end)
--        local cuisine_name = Csv.GetData("description",cuisinesData.name_description,"description")
--        self.text_name.text = cuisine_name
--        reward_item_cache = {}
--        for key, value in pairs(cuisinesData.reward_description) do
--            local itemGo = fun.get_instance(self.reward_item,self.reward_content)
--            fun.set_active(itemGo,true)
--            local view = RewardIconValueView:New(value)
--            view:SkipLoadShow(itemGo)
--            table.insert(reward_item_cache,view)
--        end
--    end
--end
--
--function MakeFoodProductView:on_btn_collect_click()
--    self._fsm:GetCurState():ClaimReward(self._fsm)
--end
--
--function MakeFoodProductView:OnClaimReward()
--    local cuisinesId = ModelList.ItemModel:GetMakeFoodCurrentCuisines()
--    if cuisinesId and cuisinesId > 0 then
--        AddLockCountOneStep()
--        ModelList.ItemModel.C2S_ExchangeIngredient(cuisinesId,ITEMS_TYPE.ITEMS_TYPE_FOOD,ModelList.CityModel:GetCity(),ModelList.CityModel:GetEnterGameMode())
--        --Facade.SendNotification(NotifyName.FoodIngredientView.ExchangeSucceed)
--    end
--end
--
--function MakeFoodProductView.OnClaimRewardSucceed()
--    local delay = 0
--    local coroutine_fun = nil
--    for key, value in pairs(reward_item_cache) do
--        coroutine_fun = function()
--            delay = delay + 0.2
--            coroutine.wait(delay)
--            Facade.SendNotification(NotifyName.ShopView.FlyRewardEffcts,value:GetPosition(),value:GetRewardItemId(),function()
--                Event.Brocast(EventName.Event_currency_change)
--            end,value:GetRewardItemIcon(),true)
--        end
--        coroutine.resume(coroutine.create(coroutine_fun))
--    end
--    coroutine_fun = function()
--        delay = delay + 0.2
--        coroutine.wait(delay)
--        this._fsm:GetCurState():Accomplish(this._fsm)
--        this._fsm:GetCurState():Exit(this._fsm)
--    end
--    coroutine.resume(coroutine.create(coroutine_fun))
--end
--
--this.NotifyList =
--{
--    {notifyName = NotifyName.FoodIngredientView.ExchangeSucceed, func = this.OnClaimRewardSucceed},
--}
--
--return this