---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/8/29 12:11
---

--- 双倍美食弹窗界面

DoubleIngredirntsPromotedView = BaseView:New('DoubleIngredirntsPromotedView');

require("State.Activity.DoubleIngredirnts.DoubleIngredirntsEnterState")
require("State.Activity.DoubleIngredirnts.DoubleIngredirntsExitState")
require("State.Activity.DoubleIngredirnts.DoubleIngredirntsIdleState")

require "View/CommonView/RemainTimeCountDown"

local this = DoubleIngredirntsPromotedView;
this.viewType = CanvasSortingOrderManager.LayerType.TopConsole

local remainTimeCountDown = RemainTimeCountDown:New()

this.auto_bind_ui_items = {
    "btn_close",
    "btn_continue",
    "anima",
    "text_reward",
    "text_tip",
    "text_endday",
    "text_purchase1",
    "text_purchase2",
}

function DoubleIngredirntsPromotedView.Awake(obj)
    --this.update_x_enabled = true
    this:on_init()
    ViewTool:SetDescription(this.text_purchase1, 8033)
    ViewTool:SetDescription(this.text_purchase2, 8034)
end

function DoubleIngredirntsPromotedView.OnEnable()
    FsmCreator:Create("DoubleIngredirntsPromotedView",this,{
        DoubleIngredirntsEnterState:New(),
        DoubleIngredirntsExitState:New(),
        DoubleIngredirntsIdleState:New(),
    })
    this._fsm:StartFsm("DoubleIngredirntsEnterState")
    UISound.play("double_food")

    this.text_reward.text = Csv.GetData("description",8031,"description")
    this.text_tip.text = Csv.GetData("description",8028,"description")

    remainTimeCountDown:StartCountDown(CountDownType.cdt5,
    math.max(0,ModelList.ActivityModel:GetActivityExpireTime(ActivityTypes.doubleFood) - os.time()),
    this.text_endday,
function()
    this:on_btn_close_click()
    end)



end

function DoubleIngredirntsPromotedView:OnDisable()
    remainTimeCountDown:StopCountDown()
end

function DoubleIngredirntsPromotedView:PlayEnter()
    this.anima:Play("in")
    SDK.double_window_open(1)
end

function DoubleIngredirntsPromotedView:PlayExit()
    this.anima:Play("out")
end

function DoubleIngredirntsPromotedView:CloseView()
    this._fsm:ChangeState("DoubleIngredirntsExitState")
end

function DoubleIngredirntsPromotedView:on_btn_close_click()
    this._fsm:GetCurState():CloseView()
end
function DoubleIngredirntsPromotedView:on_btn_continue_click()
    this._fsm:GetCurState():CloseView()
end

return this

