--
--require "View/MakeFood/CuisinesItemView"
--require "View/MakeFood/IngredientItemView"
--require "View/CommonView/RewardIconValueView"
--
--require "View/MakeFood/State/BaseMakeFoodRestaurantState"
--require "View/MakeFood/State/MakeFoodRestaurantOriginalState"
--require "View/MakeFood/State/MakeFoodRestaurantEnterState"
--require "View/MakeFood/State/MakeFoodRestaurantExitState"
--require "View/MakeFood/State/MakeFoodChangeCuisinesState"
--require "View/MakeFood/State/MakeFoodRestaurantProductState"
--require "View/MakeFood/State/MakeFoodRestaurantCityRewardState"
--
--MakeFoodRestaurantView = BaseView:New("MakeFoodRestaurantView","MakeFoodAtlas")
--local this = MakeFoodRestaurantView
--this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--
--local cuisinesItemList = nil
--local ingredientItemList = nil
--local rewardIconValueList = nil
--
--local curCuisinesId = nil
--local curRewardId = nil
--
--local make = nil
--
--this.auto_bind_ui_items = {
--    "anima",
--    "btn_goback",
--    "btn_makte",
--    "content_cuisines",
--    "cuisines_item",
--    "ingredient_item",
--    "ingredients",
--    "reward_content",
--    "reward_item",
--    "btn_left",
--    "btn_right",
--    "scroll_view",
--    "slider_reward",
--    "text_progress",
--    "btn_topreward",
--    "btn_help",
--    "make_anima",
--    "topreward_anima",
--    "bg_part1",
--    "bg_part2",
--    "bg_part3",
--    "bg_part5",
--    "cuisines_item2",
--    "reward_background",
--    "bg_part6"
--}
--
--function MakeFoodRestaurantView:HideCoverageEntity()
--    self:NotifyHideCoverageEntity()
--end
--
--function MakeFoodRestaurantView:ShowCoverageEntity()
--    self:NotifyShowCoverageEntity()
--end
--
--function MakeFoodRestaurantView:Awake(obj)
--    self:on_init()
--end
--
--function MakeFoodRestaurantView:OnEnable()
--    Facade.RegisterView(self)
--
--    --Util.SetUIImageGray(self.btn_makte, not make)
--    local width = self.transform.rect.width
--    local halfWidth = width / 2
--    self.bg_part1.sizeDelta = Vector2.New(width,self.bg_part1.sizeDelta.y)
--    self.bg_part2.sizeDelta = Vector2.New(halfWidth,self.bg_part2.sizeDelta.y)
--    self.bg_part3.sizeDelta = Vector2.New(halfWidth,self.bg_part3.sizeDelta.y)
--    self.bg_part5.sizeDelta = Vector2.New(halfWidth,self.bg_part5.sizeDelta.y)
--
--    self:SetCatalogue()
--    self:SetCuisinesReward(curCuisinesId)
--    self:SetTopReward()
--
--    self:BuildFsm()
--    self._fsm:GetCurState():Enter(self._fsm)
--
--    UISound.play_loop("food_kitchen")
--end
--
--function MakeFoodRestaurantView:OnDisable()
--    Facade.RemoveView(self)
--    self:DisposeFsm()
--    cuisinesItemList = nil
--    ingredientItemList = nil
--    rewardIconValueList = nil
--    curCuisinesId = nil
--    curRewardId = nil
--    make = nil
--
--    if self.coroutine then
--        coroutine.stop(self.coroutine)
--        self.coroutine = nil
--    end
--
--    UISound.stop_loop("food_kitchen")
--end
--
--function MakeFoodRestaurantView:BuildFsm()
--    self:DisposeFsm()
--    self._fsm = Fsm.CreateFsm("MakeFoodRestaurantView",self,{
--        MakeFoodRestaurantOriginalState,
--        MakeFoodRestaurantEnterState,
--        MakeFoodRestaurantExitState,
--        MakeFoodChangeCuisinesState,
--        MakeFoodRestaurantProductState,
--        MakeFoodRestaurantCityRewardState
--    })
--    self._fsm:StartFsm("MakeFoodRestaurantOriginalState")
--end
--
--function MakeFoodRestaurantView:DisposeFsm()
--    if self._fsm then
--        self._fsm:Dispose()
--        self._fsm = nil
--    end
--end
--
--function MakeFoodRestaurantView:PlayEnter()
--    AnimatorPlayHelper.Play(self.anima,"MakeFoodRestaurantViewenter",false,function()
--        self:SetCuisinesIngredient()
--        --[[翻页的功能不要了
--        self.luabehaviour:AddScrollRectChange(self.scroll_view.gameObject, function(value)
--            --log.r("=================================>>scroll_view  " .. value.x)
--            if value.x < 0 then
--                fun.set_active(self.btn_right.transform,true,false)
--                fun.set_active(self.btn_left.transform,false,false)
--            elseif value.x > 0 then
--                fun.set_active(self.btn_right.transform,false,false)
--                fun.set_active(self.btn_left.transform,true,false)
--            end
--        end)
--        --]]
--
--        local foodstocks = ModelList.ItemModel:GetItemByType(ItemType.food)
--        local pos = ModelList.CityModel:GetCity()
--        local data = {pos = pos, foodstocks = foodstocks}
--        SDK.food_open(data)
--    end)
--    ModelList.GuideModel:OpenUI("MakeFoodRestaurantView")
--end
--
--function MakeFoodRestaurantView:PlayExit()
--    self:ShowCoverageEntity()
--    local count = 0
--    local num = #ingredientItemList
--    local callback = function()
--        count = count + 1
--        if count == num then
--            AnimatorPlayHelper.Play(self.anima,"MakeFoodRestaurantViewexit",false,function()
--                Facade.SendNotification(NotifyName.CloseUI,this)
--                Facade.SendNotification(NotifyName.SceneCity.HomeScene_promotion)
--            end)
--        end
--    end
--    local delay = 0
--    for key, value in pairs(ingredientItemList) do
--        local exit_fun = function()
--            delay = delay + 0.05
--            coroutine.wait(delay)
--            value:PlayExit(callback)
--        end
--        self.coroutine = coroutine.resume(coroutine.create(exit_fun))
--    end
--end
--
--function MakeFoodRestaurantView:SetTopReward()
--    local cityexp = ModelList.CityModel:GetCityExp()
--    --self.slider_reward.value = cityexp / 100
--    --self.text_progress.text = string.format("%s%s",tostring(cityexp),"%")
--    self.slider_reward.value = 0
--    Anim.slide_to(self.slider_reward,self.text_progress, cityexp,1,function()
--
--    end)
--end
--
--function MakeFoodRestaurantView:SetCatalogue()
--    cuisinesItemList = {}
--    ingredientItemList = {}
--    rewardIconValueList = {}
--    local city = ModelList.CityModel:GetCity()
--    local cuisines = Csv.GetData("city",city,"city_recipe")
--    if cuisines then
--        for index, value in ipairs(cuisines) do
--            if value then
--                local itemGo = nil
--                local level = Csv.GetData("city_recipe",value,"level")
--                if level == 1 then
--                    itemGo = fun.get_instance(self.cuisines_item2,self.content_cuisines)
--                else
--                    itemGo = fun.get_instance(self.cuisines_item,self.content_cuisines)
--                end
--                local view = CuisinesItemView:New(value,index)
--                view:SkipLoadShow(itemGo)
--                cuisinesItemList[value] = view
--                if curCuisinesId == nil then
--                    curCuisinesId = value
--                end
--            end
--        end
--    end
--end
--
--function MakeFoodRestaurantView:SetCuisinesIngredient()
--    if curCuisinesId then
--        self:CurrentCuisinesItem(curCuisinesId)
--        if curCuisinesId then
--            cuisinesItemList[curCuisinesId]:ToggleOn()
--        end
--    end
--end
--
--function MakeFoodRestaurantView:CheckTopReward()
--    return ModelList.CityModel:IsCuisineReward()
--end
--
--function MakeFoodRestaurantView:OnEnterClaimTopReward()
--    local cityId = ModelList.CityModel:GetCity()
--    local cityLevel = ModelList.CityModel:GetCityLevel()
--    local data = Csv.GetCityLevel(cityId,cityLevel,ModelList.CityModel:GetEnterGameMode())
--    local rewards = data.reward
--    AnimatorPlayHelper.Play(self.topreward_anima,{"out","btn_toprewardout"},false,nil)
--    Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward,PopupViewType.show,ClaimRewardViewType.claimReward,rewards,function()
--        local cityId = ModelList.CityModel:GetCity()
--        ModelList.CityModel.C2S_ClaimCityLevelReward(cityId,ModelList.CityModel:GetEnterGameMode())
--    end,true,ClaimRewardAnimation.food)
--end
--
--function MakeFoodRestaurantView:CurrentCuisinesItem(cuisinesId,ischange)
--    if (cuisinesId and cuisinesId ~= curCuisinesId) or (#ingredientItemList == 0) then
--        curCuisinesId = cuisinesId
--        local cuisinesData = Csv.GetData("city_recipe",cuisinesId)
--        if cuisinesData then
--            local index = 0
--            local delay = 0
--            local count = 0
--            --Util.SetUIImageGray(self.btn_makte, true)
--            local callback = function()
--                count = count + 1
--                if count == index then
--                    --[[
--                    make = true
--                    for key, value in pairs(ingredientItemList) do
--                        if not value:IsActive() then
--                            make = false
--                            break
--                        end
--                    end
--                    Util.SetUIImageGray(self.btn_makte, not make)
--                    --]]
--                    self._fsm:GetCurState():Accomplish(self._fsm)
--                end
--            end
--            local init_ingredientItem = function ()
--                for key, value in pairs(cuisinesData.item) do
--                    index = index + 1
--                    if ingredientItemList[index] == nil then
--                        local itemGo = fun.get_instance(self.ingredient_item,self.ingredients)
--                        local view = IngredientItemView:New(value)
--                        view:SkipLoadShow(itemGo,false)
--                        ingredientItemList[index] = view
--                    else
--                        ingredientItemList[index]:SetData(value)
--                        fun.set_active(ingredientItemList[index].go,false,false)
--                    end
--                end
--                for i = 1, index do
--                    delay = delay + 0.01
--                    coroutine.wait(delay)
--                    fun.set_active(ingredientItemList[i].go,true,false)
--                    ingredientItemList[i]:PlayEnter(callback)
--                end
--            end
--
--            self:SetCuisinesReward(cuisinesData)
--            self.coroutine = coroutine.resume(coroutine.create(init_ingredientItem))
--
--            local dataCount = #cuisinesData.item
--            local itemCount = #ingredientItemList
--            if dataCount < itemCount then
--                for i = dataCount + 1, itemCount do
--                    fun.set_active(ingredientItemList[i].go,false,false)
--                end
--            end
--            if ischange then
--                AnimatorPlayHelper.Play(self.make_anima,"MakeFoodChange",true,nil)
--            end
--        end
--    else
--        self._fsm:GetCurState():Accomplish(self._fsm)
--    end
--end
--
--function MakeFoodRestaurantView:ChangeCuisineToggle(cuisinesId)
--    if cuisinesId then
--        curCuisinesId = cuisinesId
--        local cuisinesData = Csv.GetData("city_recipe",cuisinesId)
--        if cuisinesData then
--            local index = 0
--            for key, value in pairs(cuisinesData.item) do
--                index = index + 1
--                if ingredientItemList[index] then
--                    ingredientItemList[index]:SetData(value)
--                end
--            end
--        end
--        self:SetCuisinesReward(cuisinesData)
--    end
--end
--
--function MakeFoodRestaurantView:SetCuisinesReward(cuisinesData,isInit)
--    if type(cuisinesData) == "number" then
--        cuisinesData = Csv.GetData("city_recipe",cuisinesData)
--    end
--    if cuisinesData.id ~= curRewardId or #rewardIconValueList == 0 then
--        curRewardId = cuisinesData.id
--        local reward_count = math.max(#cuisinesData.reward_description,#rewardIconValueList)
--        for i = 1, reward_count do
--            if cuisinesData.reward_description[i] == nil then
--                if rewardIconValueList[i] then
--                    rewardIconValueList[i]:SetActive(false)
--                end
--            else
--                if rewardIconValueList[i] == nil then
--                    local itemGo = fun.get_instance(this.reward_item,this.reward_content)
--                    fun.set_active(itemGo,true)
--                    local view = RewardIconValueView:New(cuisinesData.reward_description[i])
--                    view:SkipLoadShow(itemGo)
--                    rewardIconValueList[i] = view
--                else
--                    rewardIconValueList[i]:SetActive(true)
--                    rewardIconValueList[i]:SetInfo(cuisinesData.reward_description[i])
--                end
--            end
--        end
--        Cache.SetImageSprite("MakeFoodAtlas", (cuisinesData.level == 1 and {"mGmakePRed"} or {"mGmakeP"})[1], self.reward_background)
--        fun.set_active(self.bg_part6, (cuisinesData.level == 1 and {true} or {false})[1])
--    end
--end
--
--function MakeFoodRestaurantView.OnToggleChangeCuisinesItem(cuisinesId)
--    this._fsm:GetCurState():OnChangeCuisinesItem(this._fsm,cuisinesId)
--end
--
--function MakeFoodRestaurantView:ChangeCuisineInteractive(interactive)
--    for key, value in pairs(cuisinesItemList) do
--        value:ChangeCuisines(interactive)
--    end
--end
--
--function MakeFoodRestaurantView:on_btn_goback_click()
--    self._fsm:GetCurState():Exit(self._fsm)
--end
--
--function MakeFoodRestaurantView:on_btn_makte_click()
--    self._fsm:GetCurState():MakeFood(self._fsm)
--end
--
--function MakeFoodRestaurantView:OnGotoMakeFood()
--    local canMakeFood = true
--    for key, value in pairs(ingredientItemList) do
--        if not value:IsActive() then
--            canMakeFood = false
--            break
--        end
--    end
--    if canMakeFood then
--        ModelList.ItemModel:SetMakeFoodCurrentCuisines(curCuisinesId)
--        Facade.SendNotification(NotifyName.ShowUI,ViewList.MakeFoodKitchenView,nil)
--    else
--        UIUtil.show_common_popup(931,false,function()
--            self._fsm:GetCurState():Exit(self._fsm)
--        end)
--        self._fsm:GetCurState():Accomplish(self._fsm)
--    end
--end
--
--function MakeFoodRestaurantView.OnClaimRewardSucceed()
--    for key, value in pairs(cuisinesItemList) do
--        value:Refresh()
--    end
--    ---[[
--    --local isMake = make
--    for key, value in pairs(ingredientItemList) do
--        value:UpdataInfo()
--        --if isMake then
--        --    isMake = value:IsActive()
--        --end
--    end
--    --Util.SetUIImageGray(this.btn_makte, not isMake)
--    --]]
--    this:SetTopReward()
--    this._fsm:GetCurState():Accomplish(this._fsm)
--end
--
--function MakeFoodRestaurantView.OnClaimCityLevelRewardResult()
--    this:SetTopReward()
--    Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward,PopupViewType.hide,ClaimRewardViewType.claimReward)
--    AnimatorPlayHelper.Play(this.topreward_anima,{"in","btn_toprewardin"},false,nil)
--    this._fsm:GetCurState():Accomplish(this._fsm)
--end
--
--function MakeFoodRestaurantView:on_btn_left_click()
--    if self.scroll_view.velocity.x == 0 then
--        local pos = self.content_cuisines.transform.localPosition
--        Anim.move(self.content_cuisines,pos.x + 300,pos.y,0,0.1,true,true,nil)
--    end
--end
--
--function MakeFoodRestaurantView:on_btn_right_click()
--    if self.scroll_view.velocity.x == 0 then
--        local pos = self.content_cuisines.transform.localPosition
--        Anim.move(self.content_cuisines,pos.x - 300,pos.y,0,0.1,true,true,nil)
--    end
--end
--
--function MakeFoodRestaurantView:on_btn_topreward_click()
--    local cityId = ModelList.CityModel:GetCity()
--    local cityLevel = ModelList.CityModel:GetCityLevel()
--    local data = Csv.GetCityLevel(cityId,cityLevel,ModelList.CityModel:GetEnterGameMode())
--    local rewards = data.reward
--    local params = {
--        rewards = rewards,
--        pos = self.btn_topreward.transform.position,
--        dir = RewardShowTipOrientation.up,
--        offset = Vector3.New(0,-200,0),
--        exclude = {self.btn_topreward,self.btn_help}
--    }
--    Facade.SendNotification(NotifyName.ShowUI,ViewList.RewardShowTipView,nil,false,params)
--end
--
--function MakeFoodRestaurantView:on_btn_help_click()
--    self:on_btn_topreward_click()
--end
--
--this.NotifyList =
--{
--    {notifyName = NotifyName.FoodIngredientView.ChangeCuisinesItem, func = this.OnToggleChangeCuisinesItem},
--    {notifyName = NotifyName.FoodIngredientView.ExchangeSucceed, func = this.OnClaimRewardSucceed},
--    {notifyName = NotifyName.FoodIngredientView.GoBackRestaurant,func = this.OnClaimRewardSucceed},
--    {notifyName = NotifyName.FoodIngredientView.ClaimCityLevelRewardResult, func = this.OnClaimCityLevelRewardResult}
--}
--
--return this