FakeNetData = {}

FakeNetData.battle_freespin_str = "12007:0:CNCGAxDQhgMYCiKHGQgBEAAaohgIARISCgpFMTAwMDQwMTA4EAEYASIAEhIKCkUxMDAwNDAxMDYQARgCIgASEgoKRTEwMDA0MDEwORABGAMiABISCgpFMTAwMDQwMTA5EAEYBCIAEhIKCkUxMDAwNDAxMDgQARgFIgASEgoKRTEwMDA0MDExMBABGAYiABISCgpFMTAwMDQwMTAyEAIYASIAEhIKCkUxMDAwNDAxMDIQAhgCIgASFwoKRTEwMDA0MDExMRACGAMiBVN0YWNrEhcKCkUxMDAwNDAxMTEQAhgEIgVTdGFjaxIXCgpFMTAwMDQwMTExEAIYBSIFU3RhY2sSFwoKRTEwMDA0MDExMRACGAYiBVN0YWNrEhcKCkUxMDAwNDAxMTEQAxgBIgVTdGFjaxIXCgpFMTAwMDQwMTExEAMYAiIFU3RhY2sSFwoKRTEwMDA0MDExMRADGAMiBVN0YWNrEhIKCkUxMDAwNDAxMTAQAxgEIgASEgoKRTEwMDA0MDEwNxADGAUiABISCgpFMTAwMDQwMTA2EAMYBiIAEhcKCkUxMDAwNDAxMTEQBBgBIgVTdGFjaxIXCgpFMTAwMDQwMTExEAQYAiIFU3RhY2sSFwoKRTEwMDA0MDExMRAEGAMiBVN0YWNrEhIKCkUxMDAwNDAxMDYQBBgEIgASEgoKRTEwMDA0MDEwNhAEGAUiABISCgpFMTAwMDQwMTAzEAQYBiIAEhIKCkUxMDAwNDAxMDMQBRgBIgASEgoKRTEwMDA0MDExMRAFGAIiABISCgpFMTAwMDQwMTA4EAUYAyIAEhIKCkUxMDAwNDAxMDMQBRgEIgASEgoKRTEwMDA0MDExMBAFGAUiABISCgpFMTAwMDQwMTEwEAUYBiIAEhIKCkUxMDAwNDAxMDkQBhgBIgASEgoKRTEwMDA0MDEwNRAGGAIiABIXCgpFMTAwMDQwMTExEAYYAyIFU3RhY2sSFwoKRTEwMDA0MDExMRAGGAQiBVN0YWNrEhcKCkUxMDAwNDAxMTEQBhgFIgVTdGFjaxIXCgpFMTAwMDQwMTExEAYYBiIFU3RhY2saaQoBMhIKUDEwMDA0MDEwMRgBIgYGBgYGBgYqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEyBgicxwEQARppCgE0EgpQMTAwMDQwMTAxGAEiBgUFBQUFBSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGmkKAjEwEgpQMTAwMDQwOTAxGAEiBgQFBgYFBCoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOTIFCKBqEAEaVwoCMTMSClAxMDAwNDExMDMYASIGBQQDAwQFKgpFMTAwMDQwMTExKgpFMTAwMDQwMTExKgpFMTAwMDQwMTExKgpFMTAwMDQwMTExKgEwKgEwMgUImiEQARpOCgIxNBIKUDEwMDA0MTAwNBgBIgYGBQQEBQYqCkUxMDAwNDAxMTAqCkUxMDAwNDAxMTAqCkUxMDAwNDAxMTAqATAqATAqATAyBQjSBhABGk4KAjIyEgpQMTAwMDQxMTA0GAEiBgUEBQQFBCoKRTEwMDA0MDExMSoKRTEwMDA0MDExMSoKRTEwMDA0MDExMSoBMCoBMCoBMDIFCNIGEAEaagoCMjMSClAxMDAwNDAxMDEYASIGBQYFBgUGKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxMgYInMcBEAEaagoCMjQSClAxMDAwNDAxMDEYASIGBgUGBQYFKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxMgYInMcBEAEaTgoCMzISClAxMDAwNDEwMDQYASIGBQUEBAUFKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwKgEwKgEwKgEwMgUI0gYQARpqCgIzMxIKUDEwMDA0MDEwMRgBIgYFBQYGBQUqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEyBgicxwEQARpqCgIzNBIKUDEwMDA0MDEwMRgBIgYGBgUFBgYqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEyBgicxwEQARppCgI0MRIKUDEwMDA0MDkwMRgBIgYEBQUFBQQqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkyBQigahABGmoKAjQzEgpQMTAwMDQwMTAxGAEiBgUGBgYGBSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGmoKAjQ0EgpQMTAwMDQwMTAxGAEiBgYFBQUFBioKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGk4KAjQ2EgpQMTAwMDQxMDA0GAEiBgYFBAMCASoKRTEwMDA0MDExMCoKRTEwMDA0MDExMCoKRTEwMDA0MDExMCoBMCoBMCoBMDIFCNIGEAEaTgoCNTASClAxMDAwNDExMDQYASIGBgQGBAYEKgpFMTAwMDQwMTExKgpFMTAwMDQwMTExKgpFMTAwMDQwMTExKgEwKgEwKgEwMgUI0gYQASLmBQjU0A4QABgBIhIKCkUxMDAwNDk5MDMQAhgGIgAiEgoKRTEwMDA0OTkwNRAGGAEiACISCgpFMTAwMDQ5OTA1EAYYAiIAIhIKCkUxMDAwNDk5MDUQBhgEIgAiEgoKRTEwMDA0OTkwMxAEGAYiACISCgpFMTAwMDQ5OTAzEAEYBiIAIhIKCkUxMDAwNDk5MDMQAhgFIgAiEgoKRTEwMDA0OTkwMxAFGAYiACISCgpFMTAwMDQ5OTAzEAMYBiIAIhIKCkUxMDAwNDk5MDMQBhgGIgAiEgoKRTEwMDA0OTkwMxADGAUiACISCgpFMTAwMDQ5OTAzEAUYBSIAIhIKCkUxMDAwNDk5MDUQBhgDIgAiEgoKRTEwMDA0OTkwMxAGGAUiACISCgpFMTAwMDQ5OTAzEAQYBSIAIhIKCkUxMDAwNDk5MDMQARgFIgAqCkYxMDAwNDAyMDEqCkYxMDAwNDAzMDMyhAEKCkYxMDAwNDAyMDESEgoKRTEwMDA0OTkwNRAGGAEiABISCgpFMTAwMDQ5OTA1EAYYAiIAEhIKCkUxMDAwNDk5MDUQBhgDIgASEgoKRTEwMDA0OTkwNRAGGAQiABISCgpFMTAwMDQ5OTA1EAYYBSIAEhIKCkUxMDAwNDk5MDUQBhgGIgAy/AEKCkYxMDAwNDAzMDMSEgoKRTEwMDA0OTkwMxABGAUiABISCgpFMTAwMDQ5OTAzEAEYBiIAEhIKCkUxMDAwNDk5MDMQAhgFIgASEgoKRTEwMDA0OTkwMxACGAYiABISCgpFMTAwMDQ5OTAzEAMYBSIAEhIKCkUxMDAwNDk5MDMQAxgGIgASEgoKRTEwMDA0OTkwMxAEGAUiABISCgpFMTAwMDQ5OTAzEAQYBiIAEhIKCkUxMDAwNDk5MDMQBRgFIgASEgoKRTEwMDA0OTkwMxAFGAYiABISCgpFMTAwMDQ5OTAzEAYYBSIAEhIKCkUxMDAwNDk5MDMQBhgGIgAo1NAOIgpFMTAwMDQwMTA5IgpFMTAwMDQwMTA5IgpFMTAwMDQwMTExIgpFMTAwMDQwMTA5IgpFMTAwMDQwMTA5IgpFMTAwMDQwMTA5KNTQDjDU0A44AUAASK3FqsDA/gFQACLMHQgCEAAa5xwIARISCgpFMTAwMDQwMTA5EAEYASIAEhIKCkUxMDAwNDAxMDgQARgCIgASEgoKRTEwMDA0MDExMBABGAMiABISCgpFMTAwMDQwMTEwEAEYBCIAEhIKCkUxMDAwNDAxMDMQARgFIgASEgoKRTEwMDA0MDEwNBABGAYiABISCgpFMTAwMDQwMTA5EAIYASIAEhIKCkUxMDAwNDAxMDkQAhgCIgASEgoKRTEwMDA0MDEwNxACGAMiABISCgpFMTAwMDQwMTExEAIYBCIAEhIKCkUxMDAwNDAxMDQQAhgFIgASEgoKRTEwMDA0MDEwORACGAYiABISCgpFMTAwMDQwMTA4EAMYASIAEhIKCkUxMDAwNDAxMTAQAxgCIgASEgoKRTEwMDA0MDExMBADGAMiABISCgpFMTAwMDQwMTA5EAMYBCIAEhIKCkUxMDAwNDAxMTEQAxgFIgASEgoKRTEwMDA0MDEwNBADGAYiABISCgpFMTAwMDQwMTAzEAQYASIAEhIKCkUxMDAwNDAxMDQQBBgCIgASEgoKRTEwMDA0MDEwNRAEGAMiABISCgpFMTAwMDQwMTAxEAQYBCIAEhIKCkUxMDAwNDAxMDEQBBgFIgASEgoKRTEwMDA0MDEwORAEGAYiABISCgpFMTAwMDQwMTAxEAUYASIAEhcKCkUxMDAwNDAxMDkQBRgCIgVTdGFjaxIXCgpFMTAwMDQwMTA5EAUYAyIFU3RhY2sSFwoKRTEwMDA0MDEwORAFGAQiBVN0YWNrEhcKCkUxMDAwNDAxMDkQBRgFIgVTdGFjaxISCgpFMTAwMDQwMTA1EAUYBiIAEhcKCkUxMDAwNDAxMDkQBhgBIgVTdGFjaxIXCgpFMTAwMDQwMTA5EAYYAiIFU3RhY2sSFwoKRTEwMDA0MDEwORAGGAMiBVN0YWNrEhIKCkUxMDAwNDAxMDEQBhgEIgASEgoKRTEwMDA0MDEwMRAGGAUiABIXCgpFMTAwMDQwMTA5EAYYBiIFU3RhY2saaQoBMxIKUDEwMDA0MDEwMRgBIgYCAgICAgIqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEqCkUxMDAwNDAxMDEyBgicxwEQARppCgE1EgpQMTAwMDQwMTAxGAEiBgMDAwMDAyoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGmgKATcSClAxMDAwNDA5MDEYASIGAQIDAwIBKgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5MgUIoGoQARpNCgE4EgpQMTAwMDQwOTA0GAEiBgIDBAQDAioKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoBMCoBMCoBMDIFCNIGEAEaTQoBORIKUDEwMDA0MTEwNBgBIgYDBAUFBAMqCkUxMDAwNDAxMTEqCkUxMDAwNDAxMTEqCkUxMDAwNDAxMTEqATAqATAqATAyBQjSBhABGk4KAjExEgpQMTAwMDQwODA0GAEiBgMCAQECAyoKRTEwMDA0MDEwOCoKRTEwMDA0MDEwOCoKRTEwMDA0MDEwOCoBMCoBMCoBMDIFCNIGEAEaaQoCMTISClAxMDAwNDEwMDEYASIGBAMCAgMEKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwKgpFMTAwMDQwMTEwMgUIoGoQARpOCgIxNhIKUDEwMDA0MDkwNBgBIgYCAQIBAgEqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqATAqATAqATAyBQjSBhABGmoKAjE3EgpQMTAwMDQwMTAxGAEiBgIDAgMCAyoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGmoKAjE4EgpQMTAwMDQwMTAxGAEiBgMCAwIDAioKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGk4KAjE5EgpQMTAwMDQxMTA0GAEiBgMEAwQDBCoKRTEwMDA0MDExMSoKRTEwMDA0MDExMSoKRTEwMDA0MDExMSoBMCoBMCoBMDIFCNIGEAEaTgoCMjQSClAxMDAwNDA0MDQYASIGBgUGBQYFKgpFMTAwMDQwMTA0KgpFMTAwMDQwMTA0KgpFMTAwMDQwMTA0KgEwKgEwKgEwMgUI9hMQARpXCgIyNRIKUDEwMDA0MDkwMxgBIgYBAQICAQEqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqATAqATAyBQiaIRABGk4KAjI2EgpQMTAwMDQwODA0GAEiBgICAQECAioKRTEwMDA0MDEwOCoKRTEwMDA0MDEwOCoKRTEwMDA0MDEwOCoBMCoBMCoBMDIFCNIGEAEaagoCMjcSClAxMDAwNDAxMDEYASIGAgIDAwICKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxMgYInMcBEAEaagoCMjgSClAxMDAwNDAxMDEYASIGAwMCAgMDKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxKgpFMTAwMDQwMTAxMgYInMcBEAEaTgoCMjkSClAxMDAwNDA5MDQYASIGAwMEBAMDKgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgEwKgEwKgEwMgUI0gYQARppCgIzNRIKUDEwMDA0MDkwMRgBIgYBAgICAgEqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkyBQigahABGmoKAjM3EgpQMTAwMDQwMTAxGAEiBgIDAwMDAioKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGmoKAjM4EgpQMTAwMDQwMTAxGAEiBgMCAgICAyoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMSoKRTEwMDA0MDEwMTIGCJzHARABGmkKAjQwEgpQMTAwMDQxMDAxGAEiBgQDAwMDBCoKRTEwMDA0MDExMCoKRTEwMDA0MDExMCoKRTEwMDA0MDExMCoKRTEwMDA0MDExMCoKRTEwMDA0MDExMCoKRTEwMDA0MDExMDIFCKBqEAEaTgoCNDUSClAxMDAwNDA5MDQYASIGAQIDBAUGKgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgEwKgEwKgEwMgUI0gYQARpOCgI0OBIKUDEwMDA0MDkwNBgBIgYDAQMBAwEqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqATAqATAqATAyBQjSBhABIuYFCNLTEBAAGAEiEgoKRTEwMDA0OTkwNRAGGAEiACISCgpFMTAwMDQ5OTAzEAYYAyIAIhIKCkUxMDAwNDk5MDMQAxgDIgAiEgoKRTEwMDA0OTkwMxABGAIiACISCgpFMTAwMDQ5OTA1EAYYBCIAIhIKCkUxMDAwNDk5MDMQBRgCIgAiEgoKRTEwMDA0OTkwMxAGGAIiACISCgpFMTAwMDQ5OTAzEAIYAyIAIhIKCkUxMDAwNDk5MDMQBBgCIgAiEgoKRTEwMDA0OTkwMxAEGAMiACISCgpFMTAwMDQ5OTAzEAEYAyIAIhIKCkUxMDAwNDk5MDUQBhgGIgAiEgoKRTEwMDA0OTkwMxAFGAMiACISCgpFMTAwMDQ5OTAzEAMYAiIAIhIKCkUxMDAwNDk5MDUQBhgFIgAiEgoKRTEwMDA0OTkwMxACGAIiACoKRjEwMDA0MDIwMSoKRjEwMDA0MDMwMzKEAQoKRjEwMDA0MDIwMRISCgpFMTAwMDQ5OTA1EAYYASIAEhIKCkUxMDAwNDk5MDUQBhgCIgASEgoKRTEwMDA0OTkwNRAGGAMiABISCgpFMTAwMDQ5OTA1EAYYBCIAEhIKCkUxMDAwNDk5MDUQBhgFIgASEgoKRTEwMDA0OTkwNRAGGAYiADL8AQoKRjEwMDA0MDMwMxISCgpFMTAwMDQ5OTAzEAEYAiIAEhIKCkUxMDAwNDk5MDMQARgDIgASEgoKRTEwMDA0OTkwMxACGAIiABISCgpFMTAwMDQ5OTAzEAIYAyIAEhIKCkUxMDAwNDk5MDMQAxgCIgASEgoKRTEwMDA0OTkwMxADGAMiABISCgpFMTAwMDQ5OTAzEAQYAiIAEhIKCkUxMDAwNDk5MDMQBBgDIgASEgoKRTEwMDA0OTkwMxAFGAIiABISCgpFMTAwMDQ5OTAzEAUYAyIAEhIKCkUxMDAwNDk5MDMQBhgCIgASEgoKRTEwMDA0OTkwMxAGGAMiACimpB8iCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTEiCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTAo0tMQMKakHzgBQABIrcWqwMD+AVAAIpwNCAMQABq5DAgBEhIKCkUxMDAwNDAxMDMQARgBIgASEgoKRTEwMDA0MDEwNBABGAIiABISCgpFMTAwMDQwMTExEAEYAyIAEhcKCkUxMDAwNDAxMTAQARgEIgVTdGFjaxIXCgpFMTAwMDQwMTEwEAEYBSIFU3RhY2sSFwoKRTEwMDA0MDExMBABGAYiBVN0YWNrEhIKCkUxMDAwNDAxMDkQAhgBIgASEgoKRTEwMDA0MDEwNxACGAIiABISCgpFMTAwMDQwMTA2EAIYAyIAEhIKCkUxMDAwNDAxMDUQAhgEIgASEgoKRTEwMDA0MDEwNBACGAUiABISCgpFMTAwMDQwMTExEAIYBiIAEhIKCkUxMDAwNDAxMTEQAxgBIgASEgoKRTEwMDA0MDEwNRADGAIiABISCgpFMTAwMDQwMTA5EAMYAyIAEhIKCkUxMDAwNDAxMTEQAxgEIgASEgoKRTEwMDA0MDEwMhADGAUiABISCgpFMTAwMDQwMTAyEAMYBiIAEhIKCkUxMDAwNDAxMDQQBBgBIgASEgoKRTEwMDA0MDExMBAEGAIiABIXCgpFMTAwMDQwMTEwEAQYAyIFU3RhY2sSFwoKRTEwMDA0MDExMBAEGAQiBVN0YWNrEhcKCkUxMDAwNDAxMTAQBBgFIgVTdGFjaxIXCgpFMTAwMDQwMTEwEAQYBiIFU3RhY2sSEgoKRTEwMDA0MDEwMRAFGAEiABISCgpFMTAwMDQwMTAxEAUYAiIAEhIKCkUxMDAwNDAxMDYQBRgDIgASEgoKRTEwMDA0MDEwNxAFGAQiABIXCgpFMTAwMDQwMTEwEAUYBSIFU3RhY2sSFwoKRTEwMDA0MDExMBAFGAYiBVN0YWNrEhIKCkUxMDAwNDAxMDUQBhgBIgASEgoKRTEwMDA0MDEwNRAGGAIiABISCgpFMTAwMDQwMTA3EAYYAyIAEhIKCkUxMDAwNDAxMDcQBhgEIgASEgoKRTEwMDA0MDEwMhAGGAUiABISCgpFMTAwMDQwMTAyEAYYBiIAIrMGCAAQABgBIhIKCkUxMDAwNDk5MDUQBRgBIgAiEgoKRTEwMDA0OTkwNRAFGAIiACISCgpFMTAwMDQ5OTA1EAQYAiIAIhIKCkUxMDAwNDk5MDEQBRgEIgAiEgoKRTEwMDA0OTkwNRAEGAYiACISCgpFMTAwMDQ5OTA1EAMYASIAIhIKCkUxMDAwNDk5MDUQBBgDIgAiEgoKRTEwMDA0OTkwNRAEGAEiACISCgpFMTAwMDQ5OTA1EAMYAyIAIhIKCkUxMDAwNDk5MDUQBBgFIgAiEgoKRTEwMDA0OTkwNRAEGAQiACISCgpFMTAwMDQ5OTA1EAUYBiIAIhIKCkUxMDAwNDk5MDUQAxgEIgAiEgoKRTEwMDA0OTkwNRADGAYiACISCgpFMTAwMDQ5OTAxEAUYBSIAIhIKCkUxMDAwNDk5MDUQBRgDIgAiEgoKRTEwMDA0OTkwNRADGAIiACISCgpFMTAwMDQ5OTA1EAMYBSIAKgpGMTAwMDQwMjAxKgpGMTAwMDQwMzAxMvQCCgpGMTAwMDQwMjAxEhIKCkUxMDAwNDk5MDUQAxgBIgASEgoKRTEwMDA0OTkwNRADGAIiABISCgpFMTAwMDQ5OTA1EAMYAyIAEhIKCkUxMDAwNDk5MDUQAxgEIgASEgoKRTEwMDA0OTkwNRADGAUiABISCgpFMTAwMDQ5OTA1EAMYBiIAEhIKCkUxMDAwNDk5MDUQBBgBIgASEgoKRTEwMDA0OTkwNRAEGAIiABISCgpFMTAwMDQ5OTA1EAQYAyIAEhIKCkUxMDAwNDk5MDUQBBgEIgASEgoKRTEwMDA0OTkwNRAEGAUiABISCgpFMTAwMDQ5OTA1EAQYBiIAEhIKCkUxMDAwNDk5MDUQBRgBIgASEgoKRTEwMDA0OTkwNRAFGAIiABISCgpFMTAwMDQ5OTA1EAUYAyIAEhIKCkUxMDAwNDk5MDUQBRgEIgASEgoKRTEwMDA0OTkwNRAFGAUiABISCgpFMTAwMDQ5OTA1EAUYBiIAMjQKCkYxMDAwNDAzMDESEgoKRTEwMDA0OTkwMRAFGAQiABISCgpFMTAwMDQ5OTAxEAUYBSIAKKakHyIKRTEwMDA0MDExMCIKRTEwMDA0MDExMCIKRTEwMDA0MDExMSIKRTEwMDA0MDExMCIKRTEwMDA0MDExMCIKRTEwMDA0MDExMCgAMKakHzgAQABIrcWqwMD+AVAAIukHCAQQABqGBwgBEhIKCkUxMDAwNDAxMDgQARgBIgASEgoKRTEwMDA0MDEwNhABGAIiABISCgpFMTAwMDQwMTA5EAEYAyIAEhIKCkUxMDAwNDAxMDkQARgEIgASEgoKRTEwMDA0MDEwOBABGAUiABISCgpFMTAwMDQwMTEwEAEYBiIAEhIKCkUxMDAwNDAxMDkQAhgBIgASEgoKRTEwMDA0MDEwNBACGAIiABISCgpFMTAwMDQwMTAyEAIYAyIAEhIKCkUxMDAwNDAxMDIQAhgEIgASEgoKRTEwMDA0MDEwORACGAUiABIXCgpFMTAwMDQwMTEwEAIYBiIFU3RhY2sSEgoKRTEwMDA0MDEwNxADGAEiABISCgpFMTAwMDQwMTA2EAMYAiIAEhIKCkUxMDAwNDAxMTEQAxgDIgASEgoKRTEwMDA0MDEwOBADGAQiABIXCgpFMTAwMDQwMTExEAMYBSIFU3RhY2sSFwoKRTEwMDA0MDExMRADGAYiBVN0YWNrEhIKCkUxMDAwNDAxMTAQBBgBIgASEgoKRTEwMDA0MDEwNRAEGAIiABISCgpFMTAwMDQwMTA1EAQYAyIAEhIKCkUxMDAwNDAxMDgQBBgEIgASEgoKRTEwMDA0MDExMBAEGAUiABISCgpFMTAwMDQwMTExEAQYBiIAEhcKCkUxMDAwNDAxMTAQBRgBIgVTdGFjaxIXCgpFMTAwMDQwMTEwEAUYAiIFU3RhY2sSFwoKRTEwMDA0MDExMBAFGAMiBVN0YWNrEhcKCkUxMDAwNDAxMTAQBRgEIgVTdGFjaxISCgpFMTAwMDQwMTA3EAUYBSIAEhIKCkUxMDAwNDAxMDQQBRgGIgASEgoKRTEwMDA0MDEwNBAGGAEiABISCgpFMTAwMDQwMTAyEAYYAiIAEhIKCkUxMDAwNDAxMDIQBhgDIgASEgoKRTEwMDA0MDEwMRAGGAQiABISCgpFMTAwMDQwMTAxEAYYBSIAEhIKCkUxMDAwNDAxMDIQBhgGIgAiigEIABAAGAEiEgoKRTEwMDA0OTkwNBAEGAQiACISCgpFMTAwMDQ5OTA0EAQYAyIAIhIKCkUxMDAwNDk5MDQQBBgCIgAiEgoKRTEwMDA0OTkwNBAEGAUiACISCgpFMTAwMDQ5OTA0EAYYBSIAIhIKCkUxMDAwNDk5MDQQBhgEIgAqCkYxMDAwNDAzMDQopqQfIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxKAAwpqQfOABAAEitxarAwP4BUAAihwgIBRAAGqQHCAESEgoKRTEwMDA0MDEwMRABGAEiABISCgpFMTAwMDQwMTEwEAEYAiIAEhIKCkUxMDAwNDAxMTAQARgDIgASEgoKRTEwMDA0MDEwNhABGAQiABISCgpFMTAwMDQwMTA1EAEYBSIAEhIKCkUxMDAwNDAxMDMQARgGIgASEgoKRTEwMDA0MDEwNRACGAEiABIXCgpFMTAwMDQwMTAxEAIYAiIFU3RhY2sSFwoKRTEwMDA0MDEwMRACGAMiBVN0YWNrEhcKCkUxMDAwNDAxMDEQAhgEIgVTdGFjaxIXCgpFMTAwMDQwMTAxEAIYBSIFU3RhY2sSEgoKRTEwMDA0MDEwMRACGAYiABISCgpFMTAwMDQwMTA0EAMYASIAEhIKCkUxMDAwNDAxMDYQAxgCIgASEgoKRTEwMDA0MDEwNRADGAMiABISCgpFMTAwMDQwMTA3EAMYBCIAEhIKCkUxMDAwNDAxMDMQAxgFIgASEgoKRTEwMDA0MDEwNxADGAYiABIXCgpFMTAwMDQwMTAxEAQYASIFU3RhY2sSFwoKRTEwMDA0MDEwMRAEGAIiBVN0YWNrEhcKCkUxMDAwNDAxMDEQBBgDIgVTdGFjaxISCgpFMTAwMDQwMTAzEAQYBCIAEhIKCkUxMDAwNDAxMDcQBBgFIgASEgoKRTEwMDA0MDEwNhAEGAYiABIXCgpFMTAwMDQwMTAxEAUYASIFU3RhY2sSFwoKRTEwMDA0MDEwMRAFGAIiBVN0YWNrEhcKCkUxMDAwNDAxMDEQBRgDIgVTdGFjaxISCgpFMTAwMDQwMTA0EAUYBCIAEhIKCkUxMDAwNDAxMDcQBRgFIgASEgoKRTEwMDA0MDExMBAFGAYiABIXCgpFMTAwMDQwMTAxEAYYASIFU3RhY2sSEgoKRTEwMDA0MDEwNxAGGAIiABISCgpFMTAwMDQwMTA0EAYYAyIAEhIKCkUxMDAwNDAxMDkQBhgEIgASFwoKRTEwMDA0MDEwMRAGGAUiBVN0YWNrEhcKCkUxMDAwNDAxMDEQBhgGIgVTdGFjayKKAQgAEAAYASISCgpFMTAwMDQ5OTA0EAMYBiIAIhIKCkUxMDAwNDk5MDQQBRgGIgAiEgoKRTEwMDA0OTkwNBAFGAUiACISCgpFMTAwMDQ5OTA0EAMYBSIAIhIKCkUxMDAwNDk5MDQQBBgDIgAiEgoKRTEwMDA0OTkwNBAEGAIiACoKRjEwMDA0MDMwNCimpB8iCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTEiCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTAiCkUxMDAwNDAxMTAoADCmpB84AEAASK3FqsDA/gFQACLlDQgGEAAagQ0IARISCgpFMTAwMDQwMTA1EAEYASIAEhIKCkUxMDAwNDAxMDgQARgCIgASEgoKRTEwMDA0MDEwNhABGAMiABISCgpFMTAwMDQwMTA5EAEYBCIAEhIKCkUxMDAwNDAxMDkQARgFIgASEgoKRTEwMDA0MDEwOBABGAYiABISCgpFMTAwMDQwMTA1EAIYASIAEhIKCkUxMDAwNDAxMDYQAhgCIgASEgoKRTEwMDA0MDEwNRACGAMiABIXCgpFMTAwMDQwMTEwEAIYBCIFU3RhY2sSFwoKRTEwMDA0MDExMBACGAUiBVN0YWNrEhcKCkUxMDAwNDAxMTAQAhgGIgVTdGFjaxISCgpFMTAwMDQwMTA2EAMYASIAEhIKCkUxMDAwNDAxMDYQAxgCIgASEgoKRTEwMDA0MDEwOBADGAMiABISCgpFMTAwMDQwMTEwEAMYBCIAEhIKCkUxMDAwNDAxMTAQAxgFIgASEgoKRTEwMDA0MDEwORADGAYiABIXCgpFMTAwMDQwMTEwEAQYASIFU3RhY2sSFwoKRTEwMDA0MDExMBAEGAIiBVN0YWNrEhcKCkUxMDAwNDAxMTAQBBgDIgVTdGFjaxIXCgpFMTAwMDQwMTEwEAQYBCIFU3RhY2sSEgoKRTEwMDA0MDEwMxAEGAUiABISCgpFMTAwMDQwMTA3EAQYBiIAEhIKCkUxMDAwNDAxMDgQBRgBIgASEgoKRTEwMDA0MDEwMxAFGAIiABISCgpFMTAwMDQwMTEwEAUYAyIAEhIKCkUxMDAwNDAxMTAQBRgEIgASEgoKRTEwMDA0MDEwOBAFGAUiABISCgpFMTAwMDQwMTA5EAUYBiIAEhIKCkUxMDAwNDAxMTEQBhgBIgASEgoKRTEwMDA0MDEwOBAGGAIiABISCgpFMTAwMDQwMTAzEAYYAyIAEhIKCkUxMDAwNDAxMTAQBhgEIgASEgoKRTEwMDA0MDExMBAGGAUiABISCgpFMTAwMDQwMTA4EAYYBiIAGk4KAjEwEgpQMTAwMDQwOTA0GAEiBgQFBgYFBCoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoBMCoBMCoBMDIFCNIGEAEaTgoCMTESClAxMDAwNDA2MDQYASIGAwIBAQIDKgpFMTAwMDQwMTA2KgpFMTAwMDQwMTA2KgpFMTAwMDQwMTA2KgEwKgEwKgEwMgUIpA0QARpOCgIzMxIKUDEwMDA0MDkwNBgBIgYFBQYGBQUqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqATAqATAqATAyBQjSBhABGk4KAjM4EgpQMTAwMDQwNjA0GAEiBgMCAgICAyoKRTEwMDA0MDEwNioKRTEwMDA0MDEwNioKRTEwMDA0MDEwNioBMCoBMCoBMDIFCKQNEAEaTgoCNDMSClAxMDAwNDA5MDQYASIGBQYGBgYFKgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgEwKgEwKgEwMgUI0gYQASL1Awi+LhAAGAEiEgoKRTEwMDA0OTkwNBAFGAEiACISCgpFMTAwMDQ5OTA0EAYYAiIAIhIKCkUxMDAwNDk5MDUQBRgDIgAiEgoKRTEwMDA0OTkwNBAGGAMiACISCgpFMTAwMDQ5OTA1EAUYBSIAIhIKCkUxMDAwNDk5MDQQAhgFIgAiEgoKRTEwMDA0OTkwNBAFGAIiACISCgpFMTAwMDQ5OTA1EAUYBiIAIhIKCkUxMDAwNDk5MDUQBRgEIgAiEgoKRTEwMDA0OTkwNBACGAYiACoKRjEwMDA0MDIwMSoKRjEwMDA0MDMwNDKEAQoKRjEwMDA0MDIwMRISCgpFMTAwMDQ5OTA1EAUYASIAEhIKCkUxMDAwNDk5MDUQBRgCIgASEgoKRTEwMDA0OTkwNRAFGAMiABISCgpFMTAwMDQ5OTA1EAUYBCIAEhIKCkUxMDAwNDk5MDUQBRgFIgASEgoKRTEwMDA0OTkwNRAFGAYiADKEAQoKRjEwMDA0MDMwNBISCgpFMTAwMDQ5OTA0EAIYBSIAEhIKCkUxMDAwNDk5MDQQAhgGIgASEgoKRTEwMDA0OTkwNBAFGAEiABISCgpFMTAwMDQ5OTA0EAUYAiIAEhIKCkUxMDAwNDk5MDQQBhgCIgASEgoKRTEwMDA0OTkwNBAGGAMiACjk0h8iCkUxMDAwNDAxMDIiCkUxMDAwNDAxMDIiCkUxMDAwNDAxMDciCkUxMDAwNDAxMDIiCkUxMDAwNDAxMDIiCkUxMDAwNDAxMDIovi4w5NIfOABAAEitxarAwP4BUAAi1xIIBxAAGvIRCAESEgoKRTEwMDA0MDExMBABGAEiABISCgpFMTAwMDQwMTAzEAEYAiIAEhIKCkUxMDAwNDAxMDQQARgDIgASEgoKRTEwMDA0MDExMRABGAQiABIXCgpFMTAwMDQwMTAyEAEYBSIFU3RhY2sSFwoKRTEwMDA0MDEwMhABGAYiBVN0YWNrEhIKCkUxMDAwNDAxMDUQAhgBIgASFwoKRTEwMDA0MDEwMhACGAIiBVN0YWNrEhcKCkUxMDAwNDAxMDIQAhgDIgVTdGFjaxIXCgpFMTAwMDQwMTAyEAIYBCIFU3RhY2sSFwoKRTEwMDA0MDEwMhACGAUiBVN0YWNrEhIKCkUxMDAwNDAxMDEQAhgGIgASEgoKRTEwMDA0MDExMBADGAEiABISCgpFMTAwMDQwMTA5EAMYAiIAEhIKCkUxMDAwNDAxMTEQAxgDIgASEgoKRTEwMDA0MDEwNBADGAQiABISCgpFMTAwMDQwMTA5EAMYBSIAEhIKCkUxMDAwNDAxMDcQAxgGIgASEgoKRTEwMDA0MDEwOBAEGAEiABISCgpFMTAwMDQwMTEwEAQYAiIAEhIKCkUxMDAwNDAxMTEQBBgDIgASEgoKRTEwMDA0MDEwORAEGAQiABISCgpFMTAwMDQwMTExEAQYBSIAEhIKCkUxMDAwNDAxMTAQBBgGIgASFwoKRTEwMDA0MDEwMhAFGAEiBVN0YWNrEhIKCkUxMDAwNDAxMDgQBRgCIgASEgoKRTEwMDA0MDExMRAFGAMiABIXCgpFMTAwMDQwMTAyEAUYBCIFU3RhY2sSFwoKRTEwMDA0MDEwMhAFGAUiBVN0YWNrEhcKCkUxMDAwNDAxMDIQBRgGIgVTdGFjaxISCgpFMTAwMDQwMTAzEAYYASIAEhIKCkUxMDAwNDAxMDEQBhgCIgASEgoKRTEwMDA0MDEwMRAGGAMiABISCgpFMTAwMDQwMTA2EAYYBCIAEhIKCkUxMDAwNDAxMDcQBhgFIgASFwoKRTEwMDA0MDEwMhAGGAYiBVN0YWNrGmkKATQSClAxMDAwNDAyMDEYASIGBQUFBQUFKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaagoCMTMSClAxMDAwNDAyMDEYASIGBQQDAwQFKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaagoCMTQSClAxMDAwNDAyMDEYASIGBgUEBAUGKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaagoCMjISClAxMDAwNDAyMDEYASIGBQQFBAUEKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaagoCMzISClAxMDAwNDAyMDEYASIGBQUEBAUFKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaagoCNDISClAxMDAwNDAyMDEYASIGBQQEBAQFKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaagoCNDQSClAxMDAwNDAyMDEYASIGBgUFBQUGKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyMgYInMcBEAEaVwoCNDYSClAxMDAwNDAyMDMYASIGBgUEAwIBKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgpFMTAwMDQwMTAyKgEwKgEwMgUItEIQASKWBQj4tAsQABgBIhIKCkUxMDAwNDk5MDIQBRgEIgAiEgoKRTEwMDA0OTkwMhAFGAMiACISCgpFMTAwMDQ5OTA1EAYYAiIAIhIKCkUxMDAwNDk5MDIQAxgDIgAiEgoKRTEwMDA0OTkwMhADGAUiACISCgpFMTAwMDQ5OTA1EAYYBCIAIhIKCkUxMDAwNDk5MDIQAxgEIgAiEgoKRTEwMDA0OTkwNRAGGAEiACISCgpFMTAwMDQ5OTA1EAYYBiIAIhIKCkUxMDAwNDk5MDIQBRgFIgAiEgoKRTEwMDA0OTkwNRAGGAUiACISCgpFMTAwMDQ5OTAyEAQYBSIAIhIKCkUxMDAwNDk5MDUQBhgDIgAiEgoKRTEwMDA0OTkwMhAEGAMiACISCgpFMTAwMDQ5OTAyEAQYBCIAKgpGMTAwMDQwMjAxKgpGMTAwMDQwMzAyMoQBCgpGMTAwMDQwMjAxEhIKCkUxMDAwNDk5MDUQBhgBIgASEgoKRTEwMDA0OTkwNRAGGAIiABISCgpFMTAwMDQ5OTA1EAYYAyIAEhIKCkUxMDAwNDk5MDUQBhgEIgASEgoKRTEwMDA0OTkwNRAGGAUiABISCgpFMTAwMDQ5OTA1EAYYBiIAMsABCgpGMTAwMDQwMzAyEhIKCkUxMDAwNDk5MDIQAxgDIgASEgoKRTEwMDA0OTkwMhADGAQiABISCgpFMTAwMDQ5OTAyEAMYBSIAEhIKCkUxMDAwNDk5MDIQBBgDIgASEgoKRTEwMDA0OTkwMhAEGAQiABISCgpFMTAwMDQ5OTAyEAQYBSIAEhIKCkUxMDAwNDk5MDIQBRgDIgASEgoKRTEwMDA0OTkwMhAFGAQiABISCgpFMTAwMDQ5OTAyEAUYBSIAKNyHKyIKRTEwMDA0MDEwNiIKRTEwMDA0MDEwNiIKRTEwMDA0MDEwOSIKRTEwMDA0MDEwNiIKRTEwMDA0MDEwNiIKRTEwMDA0MDEwNij4tAsw3IcrOAFAAEitxarAwP4BUAAi2ggICBAAGvUHCAESFwoKRTEwMDA0MDEwNhABGAEiBVN0YWNrEhIKCkUxMDAwNDAxMDIQARgCIgASEgoKRTEwMDA0MDEwMhABGAMiABISCgpFMTAwMDQwMTA0EAEYBCIAEhIKCkUxMDAwNDAxMTEQARgFIgASEgoKRTEwMDA0MDEwNRABGAYiABIXCgpFMTAwMDQwMTA2EAIYASIFU3RhY2sSFwoKRTEwMDA0MDEwNhACGAIiBVN0YWNrEhIKCkUxMDAwNDAxMTAQAhgDIgASEgoKRTEwMDA0MDEwMhACGAQiABISCgpFMTAwMDQwMTAyEAIYBSIAEhcKCkUxMDAwNDAxMDYQAhgGIgVTdGFjaxIXCgpFMTAwMDQwMTA5EAMYASIFU3RhY2sSEgoKRTEwMDA0MDEwNxADGAIiABISCgpFMTAwMDQwMTA2EAMYAyIAEhIKCkUxMDAwNDAxMTEQAxgEIgASEgoKRTEwMDA0MDEwOBADGAUiABIXCgpFMTAwMDQwMTA5EAMYBiIFU3RhY2sSFwoKRTEwMDA0MDEwNhAEGAEiBVN0YWNrEhcKCkUxMDAwNDAxMDYQBBgCIgVTdGFjaxIXCgpFMTAwMDQwMTA2EAQYAyIFU3RhY2sSEgoKRTEwMDA0MDEwORAEGAQiABISCgpFMTAwMDQwMTA4EAQYBSIAEhcKCkUxMDAwNDAxMDYQBBgGIgVTdGFjaxIXCgpFMTAwMDQwMTA2EAUYASIFU3RhY2sSFwoKRTEwMDA0MDEwNhAFGAIiBVN0YWNrEhcKCkUxMDAwNDAxMDYQBRgDIgVTdGFjaxISCgpFMTAwMDQwMTA4EAUYBCIAEhIKCkUxMDAwNDAxMTEQBRgFIgASFwoKRTEwMDA0MDEwNhAFGAYiBVN0YWNrEhcKCkUxMDAwNDAxMDYQBhgBIgVTdGFjaxISCgpFMTAwMDQwMTAxEAYYAiIAEhIKCkUxMDAwNDAxMDEQBhgDIgASFwoKRTEwMDA0MDEwNhAGGAQiBVN0YWNrEhcKCkUxMDAwNDAxMDYQBhgFIgVTdGFjaxIXCgpFMTAwMDQwMTA2EAYYBiIFU3RhY2saaQoBNxIKUDEwMDA0MDYwMRgBIgYBAgMDAgEqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYyBgjohAEQARpOCgI0NRIKUDEwMDA0MDYwNBgBIgYBAgMEBQYqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYqCkUxMDAwNDAxMDYqATAqATAqATAyBQikDRABIggIjJIBEAAYASjomSwiCkUxMDAwNDAxMDkiCkUxMDAwNDAxMDkiCkUxMDAwNDAxMTEiCkUxMDAwNDAxMDkiCkUxMDAwNDAxMDkiCkUxMDAwNDAxMDkojJIBMOiZLDgAQABIrcWqwMD+AVAAIvUJCAkQABqRCQgBEhIKCkUxMDAwNDAxMTAQARgBIgASFwoKRTEwMDA0MDEwORABGAIiBVN0YWNrEhcKCkUxMDAwNDAxMDkQARgDIgVTdGFjaxIXCgpFMTAwMDQwMTA5EAEYBCIFU3RhY2sSFwoKRTEwMDA0MDEwORABGAUiBVN0YWNrEhcKCkUxMDAwNDAxMDkQARgGIgVTdGFjaxISCgpFMTAwMDQwMTA5EAIYASIAEhIKCkUxMDAwNDAxMDQQAhgCIgASEgoKRTEwMDA0MDEwMhACGAMiABISCgpFMTAwMDQwMTAyEAIYBCIAEhIKCkUxMDAwNDAxMDkQAhgFIgASFwoKRTEwMDA0MDEwORACGAYiBVN0YWNrEhIKCkUxMDAwNDAxMDIQAxgBIgASEgoKRTEwMDA0MDEwMhADGAIiABISCgpFMTAwMDQwMTA3EAMYAyIAEhIKCkUxMDAwNDAxMTAQAxgEIgASEgoKRTEwMDA0MDEwMxADGAUiABISCgpFMTAwMDQwMTA5EAMYBiIAEhIKCkUxMDAwNDAxMDgQBBgBIgASEgoKRTEwMDA0MDExMBAEGAIiABISCgpFMTAwMDQwMTA1EAQYAyIAEhIKCkUxMDAwNDAxMDUQBBgEIgASEgoKRTEwMDA0MDEwOBAEGAUiABISCgpFMTAwMDQwMTEwEAQYBiIAEhIKCkUxMDAwNDAxMDkQBRgBIgASEgoKRTEwMDA0MDEwNxAFGAIiABISCgpFMTAwMDQwMTA5EAUYAyIAEhIKCkUxMDAwNDAxMDYQBRgEIgASEgoKRTEwMDA0MDEwMxAFGAUiABISCgpFMTAwMDQwMTAxEAUYBiIAEhcKCkUxMDAwNDAxMDkQBhgBIgVTdGFjaxISCgpFMTAwMDQwMTExEAYYAiIAEhIKCkUxMDAwNDAxMDQQBhgDIgASEgoKRTEwMDA0MDEwMxAGGAQiABISCgpFMTAwMDQwMTExEAYYBSIAEhIKCkUxMDAwNDAxMDgQBhgGIgAaTQoBMhIKUDEwMDA0MDkwNBgBIgYGBgYGBgYqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqATAqATAqATAyBQjSBhABGk4KAjEwEgpQMTAwMDQwOTA0GAEiBgQFBgYFBCoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoBMCoBMCoBMDIFCNIGEAEaTgoCMjQSClAxMDAwNDA5MDQYASIGBgUGBQYFKgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgpFMTAwMDQwMTA5KgEwKgEwKgEwMgUI0gYQARpOCgIzMxIKUDEwMDA0MDkwNBgBIgYFBQYGBQUqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqCkUxMDAwNDAxMDkqATAqATAqATAyBQjSBhABGk4KAjQzEgpQMTAwMDQwOTA0GAEiBgUGBgYGBSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoKRTEwMDA0MDEwOSoBMCoBMCoBMDIFCNIGEAEiBwiaIRAAGAEogrssIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxIgpFMTAwMDQwMTAxKJohMIK7LDgAQABIrcWqwMD+AVAAIv0GCAoQARqaBggBEhcKCkUxMDAwNDAxMDEQARgBIgVTdGFjaxIXCgpFMTAwMDQwMTAxEAEYAiIFU3RhY2sSFwoKRTEwMDA0MDEwMRABGAMiBVN0YWNrEhIKCkUxMDAwNDAxMDcQARgEIgASEgoKRTEwMDA0MDEwMxABGAUiABISCgpFMTAwMDQwMTExEAEYBiIAEhIKCkUxMDAwNDAxMDkQAhgBIgASEgoKRTEwMDA0MDEwNxACGAIiABISCgpFMTAwMDQwMTA2EAIYAyIAEhIKCkUxMDAwNDAxMDUQAhgEIgASEgoKRTEwMDA0MDEwNBACGAUiABISCgpFMTAwMDQwMTExEAIYBiIAEhIKCkUxMDAwNDAxMDUQAxgBIgASEgoKRTEwMDA0MDEwNxADGAIiABISCgpFMTAwMDQwMTAzEAMYAyIAEhIKCkUxMDAwNDAxMDcQAxgEIgASFwoKRTEwMDA0MDEwMRADGAUiBVN0YWNrEhcKCkUxMDAwNDAxMDEQAxgGIgVTdGFjaxISCgpFMTAwMDQwMTEwEAQYASIAEhcKCkUxMDAwNDAxMDEQBBgCIgVTdGFjaxIXCgpFMTAwMDQwMTAxEAQYAyIFU3RhY2sSFwoKRTEwMDA0MDEwMRAEGAQiBVN0YWNrEhcKCkUxMDAwNDAxMDEQBBgFIgVTdGFjaxISCgpFMTAwMDQwMTA2EAQYBiIAEhcKCkUxMDAwNDAxMDEQBRgBIgVTdGFjaxISCgpFMTAwMDQwMTA0EAUYAiIAEhIKCkUxMDAwNDAxMDcQBRgDIgASEgoKRTEwMDA0MDExMBAFGAQiABIXCgpFMTAwMDQwMTAxEAUYBSIFU3RhY2sSFwoKRTEwMDA0MDEwMRAFGAYiBVN0YWNrEhIKCkUxMDAwNDAxMDgQBhgBIgASEgoKRTEwMDA0MDEwMxAGGAIiABISCgpFMTAwMDQwMTEwEAYYAyIAEhIKCkUxMDAwNDAxMTAQBhgEIgASEgoKRTEwMDA0MDEwOBAGGAUiABISCgpFMTAwMDQwMTA5EAYYBiIAIgYIABAAGAEogrssIgpFMTAwMDQwMTExIgpFMTAwMDQwMTExIgpFMTAwMDQwMTExIgpFMTAwMDQwMTExIgpFMTAwMDQwMTExIgpFMTAwMDQwMTExKAAwgrssOABAAkitxarAwP4BUAA="

FakeNetData.SpinTestData =  {
    data = {
        nextStacks = {
            [1] = 104,
            [2] = 107,
            [3] = 108,
            [4] = 104,
            [5] = 104,
            [6] = 104},
        isLastFreeSpin = false,
        feature = "",
        totalBet = 1000000,
    isFreeSpin = false,
    resumeBet = 0,
    cost = 1000000,
    totalWin = 1100000,
    nextMsgIds = {
        [1] = 11000},
    totalWinType = 0,
    resultSteps = {
        [1] = {
            step = 1,
            results = {
                [1] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 6,
                        [2] = 6,
                        [3] = 6,
                        [4] = 6,
                        [5] = 6,
                        [6] = 6},
                    elements = {
                        [1] = 107,
                        [2] = 107,
                        [3] = 107,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "2"
                },
                [2] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 5,
                        [2] = 5,
                        [3] = 5,
                        [4] = 5,
                        [5] = 5,
                        [6] = 5},
                    elements = {
                        [1] = 106,
                        [2] = 106,
                        [3] = 106,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "4"
                },
                [3] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 3,
                        [2] = 4,
                        [3] = 5,
                        [4] = 5,
                        [5] = 4,
                        [6] = 3},
                    elements = {
                        [1] = 107,
                        [2] = 107,
                        [3] = 107,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "9"
                },
                [4] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 4,
                        [2] = 5,
                        [3] = 6,
                        [4] = 6,
                        [5] = 5,
                        [6] = 4},
                    elements = {
                        [1] = 106,
                        [2] = 106,
                        [3] = 106,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "10"
                },
                [5] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 4,
                        [2] = 5,
                        [3] = 4,
                        [4] = 5,
                        [5] = 4,
                        [6] = 5},
                    elements = {
                        [1] = 106,
                        [2] = 106,
                        [3] = 106,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "21"
                },
                [6] = {
                    prizes = {
                        multiple = 1,
                        coins = 200000},
                    lineRoute = {
                        [1] = 5,
                        [2] = 5,
                        [3] = 4,
                        [4] = 4,
                        [5] = 5,
                        [6] = 5},
                    elements = {
                        [1] = 106,
                        [2] = 106,
                        [3] = 106,
                        [4] = 106,
                        [5] = 0,
                        [6] = 0},
                    lineId = "32"
                },
                [7] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 5,
                        [2] = 5,
                        [3] = 6,
                        [4] = 6,
                        [5] = 5,
                        [6] = 5},
                    elements = {
                        [1] = 106,
                        [2] = 106,
                        [3] = 106,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "33"
                },
                [8] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 6,
                        [2] = 6,
                        [3] = 5,
                        [4] = 5,
                        [5] = 6,
                        [6] = 6},
                    elements = {
                        [1] = 107,
                        [2] = 107,
                        [3] = 107,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "34"
                },
                [9] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 4,
                        [2] = 5,
                        [3] = 5,
                        [4] = 5,
                        [5] = 5,
                        [6] = 4},
                    elements = {
                        [1] = 106,
                        [2] = 106,
                        [3] = 106,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "41"
                },
                [10] = {
                    prizes = {
                        multiple = 1,
                        coins = 100000},
                    lineRoute = {
                        [1] = 6,
                        [2] = 4,
                        [3] = 6,
                        [4] = 4,
                        [5] = 6,
                        [6] = 4},
                    elements = {
                        [1] = 107,
                        [2] = 107,
                        [3] = 107,
                        [4] = 0,
                        [5] = 0,
                        [6] = 0},
                    lineId = "50"
                }
            },
            prizes = {
                freespin = 0,
                features = {
                    [1] = "F100040201"},
                coins = 1100000,
                splitElements = {},
                elements = {
                    [1] = {
                        value = "",
                        row = 5,
                        elementId = 9905,
                        col = 6},
                    [2] = {
                        value = "",
                        row = 1,
                        elementId = 9905,
                        col = 6},
                    [3] = {
                        value = "",
                        row = 6,
                        elementId = 9905,
                        col = 6},
                    [4] = {
                        value = "",
                        row = 4,
                        elementId = 9905,
                        col = 6},
                    [5] = {
                        value = "",
                        row = 3,
                        elementId = 9905,
                        col = 6},
                    [6] = {
                        value = "",
                        row = 2,
                        elementId = 9905,
                        col = 6}
                },
                multiple = 1
            },
            elements = {
                [1] = {
                    value = "",
                    row = 1,
                    elementId = 105,
                    col = 1},
                [2] = {
                    value = "",
                    row = 2,
                    elementId = 9901,
                    col = 1},
                [3] = {
                    value = "",
                    row = 3,
                    elementId = 9901,
                    col = 1},
                [4] = {
                    value = "",
                    row = 4,
                    elementId = 106,
                    col = 1},
                [5] = {
                    value = "",
                    row = 5,
                    elementId = 106,
                    col = 1},
                [6] = {
                    value = "Stack",
                    row = 6,
                    elementId = 107,
                    col = 1},
                [7] = {
                    value = "",
                    row = 1,
                    elementId = 105,
                    col = 2},
                [8] = {
                    value = "",
                    row = 2,
                    elementId = 107,
                    col = 2},
                [9] = {
                    value = "",
                    row = 3,
                    elementId = 107,
                    col = 2},
                [10] = {
                    value = "",
                    row = 4,
                    elementId = 107,
                    col = 2},
                [11] = {
                    value = "",
                    row = 5,
                    elementId = 106,
                    col = 2},
                [12] = {
                    value = "",
                    row = 6,
                    elementId = 107,
                    col = 2},
                [13] = {
                    value = "",
                    row = 1,
                    elementId = 109,
                    col = 3},
                [14] = {
                    value = "",
                    row = 2,
                    elementId = 109,
                    col = 3},
                [15] = {
                    value = "",
                    row = 3,
                    elementId = 106,
                    col = 3},
                [16] = {
                    value = "",
                    row = 4,
                    elementId = 106,
                    col = 3},
                [17] = {
                    value = "",
                    row = 5,
                    elementId = 9901,
                    col = 3},
                [18] = {
                    value = "",
                    row = 6,
                    elementId = 9901,
                    col = 3},
                [19] = {
                    value = "",
                    row = 1,
                    elementId = 107,
                    col = 4},
                [20] = {
                    value = "",
                    row = 2,
                    elementId = 107,
                    col = 4},
                [21] = {
                    value = "",
                    row = 3,
                    elementId = 106,
                    col = 4},
                [22] = {
                    value = "",
                    row = 4,
                    elementId = 106,
                    col = 4},
                [23] = {
                    value = "",
                    row = 5,
                    elementId = 108,
                    col = 4},
                [24] = {
                    value = "",
                    row = 6,
                    elementId = 108,
                    col = 4},
                [25] = {
                    value = "",
                    row = 1,
                    elementId = 111,
                    col = 5},
                [26] = {
                    value = "",
                    row = 2,
                    elementId = 109,
                    col = 5},
                [27] = {
                    value = "",
                    row = 3,
                    elementId = 109,
                    col = 5},
                [28] = {
                    value = "",
                    row = 4,
                    elementId = 104,
                    col = 5},
                [29] = {
                    value = "",
                    row = 5,
                    elementId = 104,
                    col = 5},
                [30] = {
                    value = "",
                    row = 6,
                    elementId = 9901,
                    col = 5},
                [31] = {
                    value = "",
                    row = 1,
                    elementId = 9901,
                    col = 6},
                [32] = {
                    value = "",
                    row = 2,
                    elementId = 111,
                    col = 6},
                [33] = {
                    value = "",
                    row = 3,
                    elementId = 111,
                    col = 6},
                [34] = {
                    value = "",
                    row = 4,
                    elementId = 108,
                    col = 6},
                [35] = {
                    value = "",
                    row = 5,
                    elementId = 108,
                    col = 6},
                [36] = {
                    value = "",
                    row = 6,
                    elementId = 103,
                    col = 6}
            },
            totalWin = 1100000
        }
    },
        balance = 33231985797391,
        settled = true,
        spinTimes = 1,
        winCoins = 1100000,
        winType = 0,
        stickyElements = {}
    },
    id = 10020,
    code = 0,
    debugstr = "MSG_SLOTS_BETTING   :10020"
}
FakeNetData.fetch_task_complete = {
    history = {
        grades = {},
        tasks = {}
    },
    taskInfo = {
        taskGroup = 1,
        createTime = 1557814373,
        rewarded = false,
        failed = false,
        taskDesc = "Spin 80 times",
        taskType = 2,
        target = 80,
        uid = 1402406,
        maxSpinTimes = 0,
        expireTime = 1557849600,
        betSummary = 800000,
        taskGrade = 2,
        taskId = "Q22103",
        balance = 0,
        completed = true,
        spinTimes = 80,
        progress = 80 },
    weekInfo = {
        points = 0,
        prizes = {
            [1] = {
                enableTime = 0,
                target = 500,
                rewarded = false,
                completed = false },
            [2] = {
                enableTime = 1558195200,
                target = 1000,
                rewarded = false,
                completed = false }
        }
    }
}

FakeNetData.fetch_task_complete_3 = {
    history = {
        grades = {
            [1] = "1"},
        tasks = {
            [1] = "Q22104",
            [2] = "Q22201"}
    },
    taskInfo = {
        taskGroup = 3,
        createTime = 1557906527,
        rewarded = false,
        failed = false,
        taskDesc = "Win 10,800,247,000 coins in free spin",
        taskType = 2,
        target = 10800247000,
        uid = 1402405,
        maxSpinTimes = 0,
        expireTime = 1557936000,
        betSummary = 80000000,
        taskGrade = 2,
        taskId = "Q22305",
        balance = 2700061800,
        completed = true,
        spinTimes = 4,
        byPercent = true,
        progress = 10800247000},
    weekInfo = {
        points = 170,
        prizes = {
        [1] = {
            enableTime = 0,
            target = 500,
            rewarded = false,
            completed = false},
        [2] = {
            enableTime = 1558195200,
            target = 1000,
            rewarded = false,
            completed = false}
        }
    }
}

FakeNetData.fetch_task_unselected_3 = {
    history = {
        grades = {
            [1] = "1",
            [2] = "2"},
        tasks = {}
        },
    taskInfo = {
        expireTime = 0,
        taskGroup = 0,
        createTime = 0,
        rewarded = false,
        byPercent = false,
        betSummary = 0,
        taskDesc = "",
        taskGrade = 0,
        taskId = "",
        target = 0,
        failed = false,
        completed = false,
        spinTimes = 0,
        taskType = 2,
        progress = 0,
        maxSpinTimes = 0},
    weekInfo = {
        points = 250,
        prizes = {
        [1] = {
            enableTime = 0,
            target = 500,
            rewarded = false,
            completed = false},
        [2] = {
            enableTime = 1558195200,
            target = 1000,
            rewarded = false,
            completed = false}
        }
    }
}

FakeNetData.fetch_task_selected_3 = {
    history = {
        grades = {
            [1] = "1",
            [2] = "2"},
        tasks = {}
    },
    taskInfo = {
        taskGroup = 1,
        createTime = 1557907204,
        rewarded = false,
        failed = false,
        taskDesc = "Win 80 times",
        taskType = 2,
        target = 80,
        uid = 1402405,
        maxSpinTimes = 0,
        expireTime = 1557936000,
        betSummary = 0,
        taskGrade = 3,
        taskId = "Q23104",
        balance = 0,
        completed = false,
        spinTimes = 0,
        byPercent = false,
        progress = 0},
    weekInfo = {
        points = 250,
        prizes = {
        [1] = {
            enableTime = 0,
            target = 500,
            rewarded = false,
            completed = false},
        [2] = {
            enableTime = 1558195200,
            target = 1000,
            rewarded = false,
            completed = false}
        }
    }
}

FakeNetData.task_award = {
    prizes = {
        [1] = {
            type = 1,
            count = 60000,
            balance = 3955935,
            itemId = "I101" },
        [2] = {
            type = 7,
            count = 20,
            balance = 20,
            itemId = "I701" }
    }
}

FakeNetData.task_week_award = {
    node = 1,
    prizes = {
        [1] = {
            type = 1,
            count = 100000,
            balance = 800000,
            itemId = "I101" },
    }
}

-- 第一个周奖励

-- -- 已完成+未领取
-- FakeNetData.fetch_1 = DeepCopy(FakeNetData.fetch_task_selected)
-- FakeNetData.fetch_1.weekInfo.prizes[1].completed = true
-- FakeNetData.fetch_1.weekInfo.prizes[1].rewarded = false
-- FakeNetData.fetch_1.weekInfo.prizes[2].completed = false
-- FakeNetData.fetch_1.weekInfo.prizes[2].rewarded = false
-- -- 领取结果
-- FakeNetData.week_1 = DeepCopy(FakeNetData.task_week_award)
-- -- 已完成+已领取
-- FakeNetData.fetch_2 = DeepCopy(FakeNetData.fetch_task_selected)
-- FakeNetData.fetch_2.weekInfo.prizes[1].completed = true
-- FakeNetData.fetch_2.weekInfo.prizes[1].rewarded = true
-- FakeNetData.fetch_2.weekInfo.prizes[2].completed = false
-- FakeNetData.fetch_2.weekInfo.prizes[2].rewarded = false

-- 第二个周奖励

-- 已完成+未领取
-- FakeNetData.fetch_3 = DeepCopy(FakeNetData.fetch_task_selected)
-- FakeNetData.fetch_3.weekInfo.prizes[1].completed = true
-- FakeNetData.fetch_3.weekInfo.prizes[1].rewarded = true
-- FakeNetData.fetch_3.weekInfo.prizes[2].completed = true
-- FakeNetData.fetch_3.weekInfo.prizes[2].rewarded = false
-- -- 领取结果
-- FakeNetData.week_2 = DeepCopy(FakeNetData.task_week_award)
-- FakeNetData.week_2.node = 2
-- -- 已完成+已领取
-- FakeNetData.fetch_4 = DeepCopy(FakeNetData.fetch_task_selected)
-- FakeNetData.fetch_4.weekInfo.prizes[1].completed = true
-- FakeNetData.fetch_4.weekInfo.prizes[1].rewarded = true
-- FakeNetData.fetch_4.weekInfo.prizes[2].completed = true
-- FakeNetData.fetch_4.weekInfo.prizes[2].rewarded = true

FakeNetData.fetch_complete = {
    history = {
        grades = {
            [1] = "1",
            [2] = "2",
            [3] = "3",
        },
        tasks = {
            [1] = "Q30001",
            [2] = "Q30002",
            [3] = "Q30003"
        }
    },
    taskInfo = {
        taskGroup = 1,
        createTime = 1557814373,
        rewarded = false,
        failed = false,
        taskDesc = "",
        taskType = 2,
        target = 0,
        uid = 1402406,
        maxSpinTimes = 0,
        expireTime = 1557849600,
        betSummary = 0,
        taskGrade = 2,
        taskId = "",
        balance = 0,
        completed = false,
        spinTimes = 0,
        progress = 0,
    },
    weekInfo = {
        points = 0,
        prizes = {
            [1] = {
                enableTime = 0,
                target = 500,
                rewarded = false,
                completed = false },
            [2] = {
                enableTime = 1558195200,
                target = 1000,
                rewarded = false,
                completed = false }
        },
    },
}