--auto generate by C# editor: Tools/自动生成AssetList.lua脚本
local AssetList = {}
local this = AssetList
------------------asset map,key to assetbundle_name-----------------
----------------------------Assets\Bundles\Modules------------------------------------------
this.BisonBingoView = "modules/bison/inhotmodule/abprefab/bisonbingoview"
this.BisonHallView = "modules/bison/inhotmodule/abprefab/bisonhallview"
this.BisonHelpView = "modules/bison/inhotmodule/abprefab/bisonhelpview"
this.BisonJackpot = "modules/bison/inhotmodule/abprefab/bisonjackpot"
this.BisonReadyView = "modules/bison/inhotmodule/abprefab/bisonreadyview"
this.BisonSettleView = "modules/bison/inhotmodule/abprefab/bisonsettleview"
this.GiftPackBisonBuffView = "modules/bison/inhotmodule/abprefab/giftpackbisonbuffview"
this.Play27HallBackground = "modules/bison/inhotmodule/abprefab/play27hallbackground"
this.play27zhandou = "modules/bison/inhotmodule/abprefab/play27zhandou"
this.FunctionIcon = "modules/bison/inhotmodule/abprefab/pass/functionicon"
this.PassHelperView = "modules/bison/inhotmodule/abprefab/pass/passhelperview"
this.PassPurchaseView = "modules/bison/inhotmodule/abprefab/pass/passpurchaseview"
this.PassReceivedView = "modules/bison/inhotmodule/abprefab/pass/passreceivedview"
this.PassRewardView = "modules/bison/inhotmodule/abprefab/pass/passrewardview"
this.PassShowTipView = "modules/bison/inhotmodule/abprefab/pass/passshowtipview"
this.PassTaskView = "modules/bison/inhotmodule/abprefab/pass/passtaskview"
this.PassView = "modules/bison/inhotmodule/abprefab/pass/passview"
this.Rewarditem = "modules/bison/inhotmodule/abprefab/pass/rewarditem"
this.cEntBisonBuffSaleIcon = "modules/bison/inhotmodule/texture/abtexture/centbisonbuffsaleicon"
this.SceneBison = "modules/bison/inhotmodule/scene/scenebison"
this.Bisonskill1 = "modules/bison/inhotmodule/effect/abprefab/bisonskill1"
this.Bisonskill2deng = "modules/bison/inhotmodule/effect/abprefab/bisonskill2deng"
this.Bisonskill2dengget = "modules/bison/inhotmodule/effect/abprefab/bisonskill2dengget"
this.Bisonxiaoka = "modules/bison/inhotmodule/effect/abprefab/bisonxiaoka"
this.mati01 = "modules/bison/inhotmodule/effect/materials/mati01"
this.mati02 = "modules/bison/inhotmodule/effect/materials/mati02"
this.mati02add = "modules/bison/inhotmodule/effect/materials/mati02add"
this.PowerupIcon077 = "modules/bison/inhotmodule/effect/materials/powerupicon077"
this.suipian = "modules/bison/inhotmodule/effect/materials/suipian"
this.BisonPassTaskAtlas = "modules/bison/inhotmodule/atlas/bisonpasstaskatlas"
this.BisonPopupAtlas = "modules/bison/inhotmodule/atlas/bisonpopupatlas"
this.BisonPurchaseAtlas = "modules/bison/inhotmodule/atlas/bisonpurchaseatlas"
this.GiftPackBisonBuffAtlas = "modules/bison/inhotmodule/atlas/giftpackbisonbuffatlas"

return this
