---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/12/26 15:31
---
---local setmetatable = setmetatable
---
local GameCardView = require("View.Bingo.UIView.CardView.GameCardView")
GuideGameGardView = GameCardView:New();
local this = GuideGameGardView;
this.name = "GuideGameGardView"

local SignIndex = 1
local number = {}

this.battleType = 2


function GuideGameGardView:OnEnable(bingoView, bingosiRef, is_open_search)
    --self:GetEffectContainer():LoadNormalCardData(this.parent.Bg)
    self:BaseEnable(bingoView, bingosiRef, is_open_search)
    LuaTimer:SetDelayFunction(2, function()
        self:SetDefaultOpenCell()
    end,nil,LuaTimer.TimerType.BattleUI)
end


function GuideGameGardView:FirstBattleReady()
    Event.Brocast(EventName.Magnifier_Default_Attribute,true)
    fun.save_value(ModelList.PlayerInfoModel:GetUid()..MCT.HangUpAutoPowerConfig, 1)
    Event.Brocast(Notes.CARD_COLLIDER_OPEN,false)
    this:AddDropAction()    
    local number1 =  Csv.GetData("beginner_powerup",this.battleType-1,"card1")
    local  number2 =  Csv.GetData("beginner_powerup",this.battleType-1,"card2")
    number = {}
    table.insert(number,number1)
    table.insert(number,number2)
    SignIndex = 1
end



function GuideGameGardView:SecondtBattleReady()
    log.r("this.battleType-1"..this.battleType)
    local number1 =  Csv.GetData("beginner_powerup",this.battleType-1,"card1")
    local  number2 =  Csv.GetData("beginner_powerup",this.battleType-1,"card2")
    number = {}
    table.insert(number,number1)
    table.insert(number,number2)
    SignIndex = 1
end


function GuideGameGardView:GuideBattleReady()
    --this:InitSearch(true)
    Event.Brocast(EventName.Magnifier_Default_Attribute,true)
    Event.Brocast(Notes.CARD_COLLIDER_OPEN,false)
    this:AddDropAction()
    --log.r("FirstBattleReady")
    local number1 =  Csv.GetData("beginner_powerup",this.battleType-1,"card1")
    local number2 =  Csv.GetData("beginner_powerup",this.battleType-1,"card2")
    number = {}
    table.insert(number,number1)
    table.insert(number,number2)
    SignIndex = 1
end

function GuideGameGardView:AddDropAction()
    this:AddGuideAction (this.ShowNeedClickNumber)
end

function GuideGameGardView.ShowNeedClickNumber( type ,path)
    ModelList.GuideModel.GuideAction( type,path )
end

function GuideGameGardView:FirstBattlePowerReady()
    Event.Brocast(Notes.CARD_COLLIDER_OPEN,true)
end

--随机涂抹卡牌
function GuideGameGardView:RandomSignToCards(count)
    return this:GuideResetRandomSignToCards(count)
end


--------------------Guide--------------------------------

--随机涂抹卡牌
function GuideGameGardView:GuideResetRandomSignToCards(count)
    local info = {}
    local roundData = this.model:GetRoundData()
    local orderIndex = 0
    for k, v in pairs(roundData) do
        orderIndex  = orderIndex + 1
        local empty_cell = {}
        local getIndex = 1
        for m = 1, #number[orderIndex][SignIndex] do
            for i = 1, #v.cards do
                if v.cards[i].num == number[orderIndex][SignIndex][m] then
                    getIndex = v.cards[i].index
                    break
                end
            end
            local temp = { num = number[orderIndex][SignIndex][m], index = getIndex, gift = 0 }
            table.insert(empty_cell, temp)
        end

        local extra_nums_table = {}
        if #empty_cell < count and #empty_cell > 0 then
            count = #empty_cell
        end
        if #empty_cell >= count then
            for i = 1, count do
                local random_index = math.random(1, #empty_cell)
                local curr_data = empty_cell[random_index]
                table.insert(extra_nums_table, curr_data.num)
                --local add_gift_cell = this.cardMap[tonumber(k)][curr_data.index]
                this:OnClickCardIgnoreJudgeByIndex(k, curr_data.index,0)
                table.remove(empty_cell, random_index)
            end
            local extra_info = { cardId = k, nums = extra_nums_table }
            table.insert(info, extra_info)
        else
            log.r("没有空格子 涂抹卡牌")
        end
    end
    SignIndex = SignIndex +1
    ModelList.GuideModel.GuideAction(1, "")
    return info
end

----卡牌上创建道具
--function GuideGameGardView:CreateItemsToCards(itemid)
--    local info = {}
--    local detail = Csv.GetData("item", itemid)
--    local roundData = this.model:GetRoundData()
--    local orderIndex = 0
--    for k, v in pairs(roundData) do
--        orderIndex  = orderIndex + 1
--        local empty_cell = {}
--        local getIndex = 1
--        local gift = {}
--        for m = 1, #number[orderIndex][SignIndex] do
--            for i = 1, #v.cards do
--                if v.cards[i].num == number[orderIndex][SignIndex][m] then
--                    getIndex = v.cards[i].index
--                    gift = v.cards[i].gift
--                    break
--                end
--            end
--            local temp = { num = number[orderIndex][SignIndex][m], index = getIndex, gift = gift }
--            table.insert(empty_cell, temp)
--        end
--
--        local index = 1
--        local curr_data = empty_cell[index]
--        local nums_table = { curr_data.num }
--        local extra_info = { cardId = k, nums = nums_table }
--        table.insert(info, extra_info)
--        local add_gift_cell = this.cardMap[tonumber(k)][curr_data.index]
--        if detail["result"][0] == 1 then
--            this.model:SetRoundGiftData(k, curr_data.index, itemid, curr_data.num, detail["result"][1])
--        end
--        if itemid == 1041 then
--            this.model:SetRoundGiftData(k, curr_data.index, itemid, curr_data.num, 0, 1)
--        else
--            this.model:SetRoundGiftData(k, curr_data.index, itemid, curr_data.num)
--        end
--        local add_gift_cell = self:GetCardCell(cardId, pos)
--        Event.Brocast(EventName.CardItem_Cell_Add_Item,detail["icon"], detail["item_type"])
--    end
--    SignIndex = SignIndex + 1
--    return info
--end

-------------------------------------------------------------

function GuideGameGardView:SetGuideBattleType(type)
    this.battleType = type
    if this.battleType == 2 or this.battleType == 22 or this.battleType == 102  then
        this:FirstBattleReady()
    elseif this.battleType == 3  or this.battleType == 23 or this.battleType == 103  then
        this:SecondtBattleReady()
    end
end

return this