---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/6/25 19:28
---


--- 基础玩法小丑卡逻辑

local BaseLogicJoker = { name = "BaseLogicJoker" }
BaseLogicJoker.__index = BaseLogicJoker
local this = BaseLogicJoker
this.moduleName = "BaseLogicJoker"


function BaseLogicJoker:InitLogic()
    self.triggerDoubleCoin = false
end

function BaseLogicJoker:New(name)
    local o = { name = name }
    setmetatable(o, { __index = BaseLogicJoker })
    return o
end

function BaseLogicJoker:BaseInit()
    self.triggerDoubleCoin = false
end

function BaseLogicJoker:Clear()
    self:BaseClear()
end

function BaseLogicJoker:BaseClear()
    self.triggerDoubleCoin = false

end

function BaseLogicJoker:GetDoubleCoin()
    if not self.triggerDoubleCoin then
        self.triggerDoubleCoin = true
        --- 需要隐藏其他卡的双倍金币图标
        Event.Brocast(EventName.Event_Hide_Other_Joker_Double_Coin)

    end

end


function BaseLogicJoker:Register()
    --Event.AddListener(EventName.Event_Get_Joker_Double_Coin,self.AddLogicBowlDrink,self)
end

function BaseLogicJoker:UnRegister()
    --Event.RemoveListener(EventName.Event_Get_Joker_Double_Coin,self.AddLogicBowlDrink,self)
end

return this