---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/7/18 18:54
---


local SettleTransitionEnterState = Clazz(BaseFsmState,"SettleTransitionEnterState")

function SettleTransitionEnterState:OnEnter(fsm,previous,...)
    fsm:GetOwner():OpenRound1()
    --fsm:GetOwner():PlayTimeStart()
    if fsm then
        self:ChangeState(fsm,"SettleTransitionExitState")
    end
end

function SettleTransitionEnterState:OnLeave(fsm)

end

return SettleTransitionEnterState