---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/10 15:08
---
local SGDataComp = {}
local this = SGDataComp

function SGDataComp:Init()
    this:Clear()
    local currGameId = ModelList.BattleModel:GetCurrModel():GetBattleExtraInfo("mainMiniGameId")
    if currGameId ~= 1 then  --- supermatch通过其他方式实现,后续的小游戏才有这个dataComp
        local dataCompName = Csv.GetData("minigame_time", currGameId, "datacmp_name")
        if dataCompName and dataCompName ~= "" then
            this.dataComp = require("Model.ModelPart.SmallGame." .. dataCompName)
            this.dataComp:Init()
        end
    end
end

function SGDataComp:Clear()
    if this.dataComp then
        this.dataComp:ClearData()
        this.dataComp = nil
    end
end

function SGDataComp:GetCurrSmallGameComp()
    return this.dataComp
end

---小火箭完成，如果有小游戏数据，则返回小游戏数据
function SGDataComp:GetSmallGameData()
    return this.dataComp and this.dataComp:GetSmallGameData() or nil
end

---正式结算后，如果有小游戏数据，则返回小游戏数据
function SGDataComp:GetSmallGameData2()
    return this.dataComp and this.dataComp:GetSmallGameData2() or nil
end

function SGDataComp:GetExtraSmallGameData()
    return this.dataComp and this.dataComp:GetExtraSmallGameData() or nil
end

function SGDataComp:ReqSGInfo(...)
    if this.dataComp then
        this.dataComp:ReqSGInfo(...)
    end
end

function SGDataComp.ResponeSmallGameData(msgType, code, data)
    if msgType == "BallShaker" then --收到摇球机小游戏数据
        if this.dataComp.ResponeBallShaker then
            this.dataComp.ResponeBallShaker(code, data)
        end
    elseif msgType == "BallShakerResult" then ---返回摇球机小游戏结果
        if this.dataComp.ResponeBallShakerResult then
            this.dataComp.ResponeBallShakerResult(code, data)
        end
    elseif msgType == "MoneyBuilding" then ---返回摇球机小游戏结果
        if this.dataComp.ResponeMansionInfo then
            this.dataComp.ResponeMansionInfo(code, data)
        end
    elseif msgType == "MoneyBuildingSpin" then ---返回摇球机小游戏结果
        if this.dataComp.ResponeMansionSpin then
            this.dataComp.ResponeMansionSpin(code, data)
        end
    end
end

function SGDataComp:ShowMainView()
    local currGameId = ModelList.BattleModel:GetCurrModel():GetBattleExtraInfo("mainMiniGameId")
    if not currGameId then
        currGameId = ModelList.SmallGameModel.GetCurrentGameId()
    end
    local mainView = Csv.GetData("minigame_time", currGameId, "minigame_mainview")
    if not ViewList[mainView] then
        ViewList[mainView] = require("View.Bingo.SettleModule.UIView.SmallGame.Normal."..mainView)
    end
    return ViewList[mainView]
end

return SGDataComp
