---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 8/11/2024 上午 11:05
---


local BingoOrderState = Clazz(BaseFsmState, "BingoOrderState")
local this = BingoOrderState

local speedCoefficientMap={
    {{1.4, 1.1, 1, 1.1, 1.4}, 1},
    {{2.2, 1.4, 1, 1.4, 2.2}, 1},
    {{2, 1, 1, 1, 2}, 1},
    {{2.2, 1.4, 1, 1.4, 2.2}, 1},
    {{1.4, 1.1, 1, 1.1, 1.4}, 1},
    {{1.4, 1.1, 1, 1.1, 1.4}, 1},
    {{2.2, 1.4, 1, 1.4, 2.2}, 1},
    {{2, 1, 1, 1, 2}, 1},
    {{2.2, 1.4, 1, 1.4, 2.2}, 1},
    {{1.4, 1.1, 1, 1.1, 1.4}, 1},
    {{2, 1, 1, 1, 2}, 1},
    {{2, 1, 1, 1, 2}, 1},
    {{1, 1, 1, 1}, 1},
}

function BingoOrderState:New()
    local o = {}
    setmetatable(o, { __index = BingoOrderState })
    return o
end

function BingoOrderState:InitState()
end

function BingoOrderState:OnEnter(fsm, previous)
    log.EditorLog("enter  BingoOrderState")
    self._fsm = fsm
    self._owner = fsm:GetOwner()
    self.cardId, self.bingoOrder = self._owner:GetCurrBingoCellsInfo()
    self.bingoPathReward = self._owner:GetCurrBingoPathReward()
    if self.bingoOrder then
        if type(self.bingoOrder) == "number" then
            self:ShowLineEffect(self.bingoOrder)
        else
            ---备用方法,目前不启用
            coroutine.start(function ()
                for i = 1, #self.bingoOrder do
                    ---出现白色底线
                    self:ShowLineEffect(self.bingoOrder[i])
                    coroutine.wait(5)
                end
            end)
        end
    end
end

function BingoOrderState:ShowLineEffect(bingoId)
    --居中的格子ID
    local centerPos = 13
    --方向
    local direction = 1
    if bingoId == 1 then
        centerPos = 11
        direction = 1
    elseif bingoId == 2 then
        centerPos = 12
        direction = 1
    elseif bingoId == 3 then
        centerPos = 13
        direction = 1
    elseif bingoId == 4 then
        centerPos = 14
        direction = 1
    elseif bingoId == 5 then
        centerPos = 15
        direction = 1
    elseif bingoId == 6 then
        centerPos = 3
        direction = 2
    elseif bingoId == 7 then
        centerPos = 8
        direction = 2
    elseif bingoId == 8 then
        centerPos = 13
        direction = 2
    elseif bingoId == 9 then
        centerPos = 18
        direction = 2
    elseif bingoId == 10 then
        centerPos = 23
        direction = 2
    elseif bingoId == 11 then
        centerPos = 13
        direction = 3
    elseif bingoId == 12 then
        centerPos = 13
        direction = 4
    elseif bingoId == 13 then
        centerPos = 13
        direction = 5
    end
    self.BingoIndexes = self:GetBingoCellsIndex(bingoId)
    self:PlayLineEffect(self.cardId, centerPos, direction)
end

function BingoOrderState:GetSpeedCoefficient(bingoOrder, cellIdx)
    local coefficentList = speedCoefficientMap[bingoOrder]
    if not coefficentList then
        return 1
    end
    local idx = 1
    local bingoRule = Csv.GetData("client_bingo_rule", 1, "content")
    for i, v in ipairs(bingoRule[bingoOrder]) do
        if v == cellIdx then
            idx = i
        end
    end

    return coefficentList[1][idx] * coefficentList[2]
end

---
function BingoOrderState:PlayEffect(effectType)
    if effectType == 1 then ---金币全部飞向火车头

    end
end

---播放划线动效
---@param centerPos : 居中格子的坐标
---@param direction : 方向:1横向2竖3斜左4斜右5四角
function BingoOrderState:PlayLineEffect(cardId, centerCellIndex, direction)
    local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCardCell(cardId, centerCellIndex)
    BattleEffectCache:GetPrefabFromPoolOrCache("GoldenTrainhuaxian", cell, function (go)
        if fun.is_not_null(go) then
            ---有缩放
            local target = self._fsm:GetOwner():GetNode1()
            fun.set_same_world_scale_with(go, target)
            local scale = fun.get_gameobject_scale(go, true)
            log.r("scale", scale.x, scale.y)

            local anima = fun.get_component(go, fun.ANIMATOR)
            anima:Play("huaxian" .. direction)
            UISound.play("goldentrainbingolink")
        end

        LuaTimer:SetDelayFunction(2, function ()
            BattleEffectPool:Recycle("GoldenTrainhuaxian", go)
            self:CheckSpecialItem()
            --self:PlayFlyCoinsEffect()
        end)
    end, 2)
end

---检查2X mini道具
function BingoOrderState:CheckSpecialItem()
    local hasMini = false
    local hasDouble = false
    local pathReward = self:GetCurrBingoMarkedPos()
    if pathReward then
        for i = 1, #pathReward do
            if pathReward[i].hasMini then
                ---mini道具
                self:CellOpenWithMiniEffect(pathReward[i].pos)
                hasMini = true
            elseif pathReward[i].hasDouble then
                ---2X道具
                self:CellOpenWith2XEffect(pathReward[i].pos)
                hasDouble = true
            end
            self._owner:SetCardProgress(false, pathReward[i].rewardValue)
        end
    end

    if hasDouble then
        LuaTimer:SetDelayFunction(2, function ()
            self:LineCellsPlay2XEffect()
        end)
    elseif hasMini then
        LuaTimer:SetDelayFunction(2, function ()
            self:PlayFlyCoinsEffect()
        end)
    else
        self:PlayFlyCoinsEffect()
    end
end

--- 解锁格子上mini效果
function BingoOrderState:CellOpenWithMiniEffect(pos)
    local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCellBgEffect(self.cardId, pos)
    if cell then
        local anima = fun.get_component(cell, fun.ANIMATOR)
        anima:Play("baomini")
        ---设置奖励内容
        local refer = fun.get_component(cell, fun.REFER)
        local num = refer:Get("text_reward")
        local curModel = ModelList.BattleModel:GetCurrModel()
        local reward = curModel:GetMiniReward()
        num.text = reward
        local curModel = ModelList.BattleModel:GetCurrModel()
        fun.DelayPlaySound(curModel.Const.soundDelayTime2, "goldentrainbonusbreak")
    end
end

--- 格子上展示2x效果
function BingoOrderState:CellOpenWith2XEffect(pos)
    local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCellBgEffect(self.cardId, pos)
    if cell then
        local anima = fun.get_component(cell, fun.ANIMATOR)
        anima:Play("baoDouble")
        local curModel = ModelList.BattleModel:GetCurrModel()
        fun.DelayPlaySound(curModel.Const.soundDelayTime2, "goldentrainbonusbreak")
    end
end

--- 整行格子上展示2x效果
function BingoOrderState:LineCellsPlay2XEffect()
    local pathReward = self:GetCurrBingoMarkedPos()
    if pathReward and #pathReward > 0 then
        for i = 1, #pathReward do
            local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCellBgEffect(self.cardId, pathReward[i].pos)
            if cell then
                local refer = fun.get_component(cell, fun.REFER)
                if refer then
                    if pathReward[i].hasMini then
                        refer:Get("anima"):Play("TextDoublemini")
                        ---设置奖励内容
                        local num = refer:Get("text_reward")
                        local from = tonumber(refer:Get("text_reward").text)
                        local to = from * 2
                        Anim.do_smooth_int2(num, from, to, 1, DG.Tweening.Ease.Linear, nil, function ()
                            num.text = to
                        end)
                    elseif pathReward[i].hasDouble then
                        refer:Get("anima"):Play("TextDoubleDouble")
                    else
                        refer:Get("anima"):Play("TextDouble")
                        ---设置奖励内容
                        local num = refer:Get("text_reward")
                        local from = tonumber(refer:Get("text_reward").text)
                        local to = from * 2
                        Anim.do_smooth_int2(num, from, to, 1, DG.Tweening.Ease.Linear, nil, function ()
                            num.text = to
                        end)

                        self._fsm:GetOwner():DelayPlayShake(1.5)
                    end
                end
            end
        end

        local curModel = ModelList.BattleModel:GetCurrModel()
        fun.DelayPlaySound(curModel.Const.soundDelayTime5, "goldentrainnumadd")

        LuaTimer:SetDelayFunction(2, function ()
            self:PlayFlyCoinsEffect()
        end)
    else
        LuaTimer:SetDelayFunction(2, function ()
            self:PlayFlyCoinsEffect()
        end)
    end
end

---金币全部飞向火车头效果
function BingoOrderState:PlayFlyCoinsEffect()
    if self.BingoIndexes then
        self.flyCoinsCount = 0
        self.totalCoinsCount = #self.BingoIndexes

        local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCardCell(self.cardId, 13)
        local centerPos = nil
        if cell then
            centerPos = fun.get_localposition(cell)
        else
            centerPos = Vector3.New(0, 0, 0)
        end
        local curModel = ModelList.BattleModel:GetCurrModel()
        fun.DelayPlaySound(curModel.Const.soundDelayTime3, "goldentraincoinsflyin")
        coroutine.start(function ()
            for i = 1, #self.BingoIndexes do
                log.EditorLog("PlayFlyCoinsEffect " .. self.cardId .. "  " .. self.BingoIndexes[i])
                if not self._owner:HadFlyCoins() then
                    local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCellBgEffect(self.cardId,
                        self.BingoIndexes[i])
                    if cell then
                        log.r("totalCoinsCount " .. self.totalCoinsCount)
                        local currPos = fun.get_localposition(cell.transform.parent)
                        local factor = self:GetSpeedCoefficient(self.bingoOrder, self.BingoIndexes[i])
                        Anim.move_by_speed(cell, centerPos.x - currPos.x, centerPos.y - currPos.y, 480 * factor, true,
                            DG.Tweening.Ease.InBack, function ()
                                fun.set_active(cell, false)
                                self:FlyCoinCount(true)
                            end)

                        --coroutine.wait(0.1)
                    else
                        self.totalCoinsCount = self.totalCoinsCount - 1
                        self:FlyCoinCount(false)
                    end
                else
                    self.totalCoinsCount = self.totalCoinsCount - 1
                    self:FlyCoinCount(false)
                end
            end
            log.r("PlayFlyCoinsEffect", self.BingoIndexes)
        end)

        --for i = 1, #self.BingoIndexes do
        --    local cell = ViewList.GoldenTrainBingoView:GetCardView():GetCellBgEffect(self.cardId, self.BingoIndexes[i])
        --    log.EditorLog("PlayFlyCoinsEffect " .. self.cardId .. "  " .. self.BingoIndexes[i])
        --    if cell then
        --        self.totalCoinsCount = self.totalCoinsCount + 1
        --        Anim.move_by_speed(cell, 0, 0, 5, true, 28, function ()
        --            fun.set_active(cell, false)
        --            self:FlyCoinCount()
        --        end)
        --
        --
        --        Anim.delay_move(cell, Vector3.New(0, 0, 0), 0.3, (self.totalCoinsCount - 1) * 0.3, true, function ()
        --            fun.set_active(cell, false)
        --            self:FlyCoinCount()
        --        end)
        --
        --        --Anim.move(cell, 0, 0, 0, 0.5, true, true, function ()
        --        --    fun.set_active(cell, false)
        --        --    self:FlyCoinCount()
        --        --end)
        --    end
        --end
        --log.r("PlayFlyCoinsEffect", self.BingoIndexes)
    end
end

---金币飞行计数
function BingoOrderState:FlyCoinCount(isRealFly)
    --self.totalCoinsCount = self.totalCoinsCount - 1
    if isRealFly then
        self.flyCoinsCount = self.flyCoinsCount + 1
    end
    if self.flyCoinsCount == 1 then
        local defaultItem = ViewList.GoldenTrainBingoView:GetCardView():GetCard(self.cardId):GetDefaultItem()
        log.EditorLog("GrowTrainState  PlayEffect  defaultItem")
        if defaultItem then
            --- 设置火车的数字
            local anima = fun.get_component(defaultItem, fun.ANIMATOR)
            if anima then
                log.EditorLog("GrowTrainState  PlayEffect  shou")
                anima:Play("shou")
                self._owner:DelayPlayShake(1)
            end
            self:PlayNumGrowEffect(defaultItem)
            UISound.play("goldentrainaddreward")
        end
    end

    log.EditorLog("PlayFlyCoinsEffect totalCoinsCount " .. self.totalCoinsCount)
    if self.totalCoinsCount <= self.flyCoinsCount then
        if self._fsm then
            self._fsm:ChangeState("GrowTrainState")
        else
            log.e("no self fsm")
        end
    end
end

function BingoOrderState:GetBingoCellsIndex(id)
    local markedPos = {}
    if self.bingoPathReward.markedPos then
        for i = 1, #self.bingoPathReward.markedPos do
            table.insert(markedPos, self.bingoPathReward.markedPos[i].pos)
        end
    end
    table.sort(markedPos)
    return markedPos
    --local data = Csv.GetData("client_bingo_rule", 1, "content")
    --return data[id]
end

function BingoOrderState:on_x_update()
    if anima then
        if anima:GetCurrentAnimatorStateInfo(0):IsName("idle") then
            this:stop_x_update()
            this:PlayOver()
        end
    end
end

function BingoOrderState:Finish()

end

function BingoOrderState:OnLeave(fsm)
    self._fsm = nil
    self._owner = nil
    self._posX = nil
end

function BingoOrderState:Dispose()
    self:OnLeave(nil)
end

function BingoOrderState:GetCurrBingoMarkedPos()
    return self.bingoPathReward.markedPos
end

--- 卡牌中间火车头播放数字增长效果
function BingoOrderState:PlayNumGrowEffect(item)
    local ref = fun.get_component(item, fun.REFER)
    if ref then
        local num = ref:Get("text_reward")
        local sourNum, targetNum = self._owner:GetCardProgress()

        Anim.do_smooth_int2(num, sourNum, targetNum, 1, DG.Tweening.Ease.Linear, nil, function ()

        end)
        self._owner:RefreshCardProgress()
    end
end

return this
