---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/14 18:30
---

require("View/Bingo/EffectPool/BattleEffectPool")
local CardCallNumberEffect = Clazz(ClazzBase, "CardCallNumberEffect")

local this = CardCallNumberEffect

function CardCallNumberEffect:Init(cardView)
    this.cardView = cardView
    --当前去掉了此功能
    --this:InitStar()
end

function CardCallNumberEffect:CallNumberFlyStartToPowerUp()

end

function CardCallNumberEffect:GetBingoView()
    return this.cardView:GetParentView()
end

function CardCallNumberEffect:InitStar()
    this.StarTrailsList = {}
    Cache.load_prefabs(AssetList["StarTrails"], "StarTrails", function(obj)
        --- 从firebase收集到的报错
        ---see https://console.firebase.google.com/u/0/project/live-party-bingo/crashlytics/app/android:live.party.bingo.free.vegas.online.jackpot.casino.game/issues/636fb0d916847630eb7d709d8aac3586?time=last-thirty-days&versions=1.14%20(44);1.14%20(43);1.14%20(42)&sessionEventKey=64E6F4A302A900010DB234D67B666F89_1849213956905898540
        if not fun.is_null(obj) and not  this:GetBingoView()  and not  this:GetBingoView():GetEffectObjContainerGO() then
            GoPool.CreatePool("StarTrails", 5, 5, obj, this:GetBingoView():GetEffectObjContainerGO())
        end
    end)
end

function CardCallNumberEffect:RecycleStarTrailsObj()
    if this.StarTrailsList and #this.StarTrailsList > 0 then
        if this.firstStar then
            this.firstStar = false
            Event.Brocast(EventName.CallNumber_Star_End_To_PowerUp)
        end
        local o = this.StarTrailsList[1]
        BattleEffectPool:Recycle("StarTrails", o)
        table.remove(this.StarTrailsList, 1)
    end
end

return this