---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/10/17 12:38
---

---  夏威夷玩法 格子盖章效果
local BaseFlyItemEffect =  require("View.Bingo.EffectModule.Card.FlyItemEffect.BaseFlyItemEffect")
local HawaiiFlyItemEffect = BaseFlyItemEffect:New("HawaiiFlyItemEffect")
setmetatable(HawaiiFlyItemEffect,BaseFlyItemEffect)
local this = HawaiiFlyItemEffect

local DrinkType = {red = 1,green = 2,yellow = 3,purple = 4}

function HawaiiFlyItemEffect:Remove()
    Event.RemoveListener(EventName.Event_Collect_Item_By_Sign,self.FlyItemToBowl,self)
    Event.RemoveListener(EventName.Event_Collect_Item_By_Skill,self.FlyIceBucketToBowl,self)
    Event.RemoveListener(EventName.Event_Show_Skill_Bingo,this.PlayFreezer,self)
end


function HawaiiFlyItemEffect:Register()
    Event.AddListener(EventName.Event_Collect_Item_By_Sign,self.FlyItemToBowl,self)
    Event.AddListener(EventName.Event_Collect_Item_By_Skill,self.FlyIceBucketToBowl,self)
    Event.AddListener(EventName.Event_Show_Skill_Bingo,this.PlayFreezer,self)
end

function HawaiiFlyItemEffect:FlyItemToBowl(cardId, cellIndex)
    this:CreateDrinks(cardId,cellIndex)
end

    --- 再格子底部创建 酒水道具
function HawaiiFlyItemEffect:CreateDrinks(cardId, cellIndex)
    local drinkItem = self.model:GetRoundData(cardId,cellIndex):GetDrinks()
    local totalCount = 0
    for i = 1, #drinkItem do
        if Csv.GetData("item",drinkItem[i].id,"result")[1] == 12 then
            totalCount = totalCount + 1
        end
    end
        if not self:GetCardView() then return end
    local order = 0
    for i = 1, #drinkItem do
        local data = Csv.GetData("item",drinkItem[i].id)
        if data.result[1] == 12 then
            if data.result[2] >4 then
                this:CreateDrink(cardId, cellIndex,data.result[2] )
            elseif data.result[2] <=4  then
                order = order + 1
                if  not self:GetCardView():IsDrinkMax(cardId,data.result[2]) then
                    this:CreateDrink(cardId, cellIndex,data.result[2],false  ,totalCount,order)
                else
                    this:CreateDrink(cardId, cellIndex,data.result[2] ,true ,totalCount,order)
                end
            end
        end
    end
end

function  HawaiiFlyItemEffect:GetDrinkFlyTime(cardId,drinkType,fly)
    local targetPos = self:GetCardView():GetWineBowlPos(cardId,drinkType)
    local dis = Vector3.Distance(targetPos,fly.transform.position)
    return (dis / 4) * 1.2, targetPos
end

local function GetGiftAnimaName(totalCount,order)
    if totalCount == 1 or (totalCount == 3 and order == 3) then
        return "in1"
    elseif totalCount == 2 then
        return "in2"..order
    elseif totalCount == 3 and order <= 2 then
        return "in2"..order
    else
        return "in1"
    end
end

function HawaiiFlyItemEffect:CreateDrink( cardId, cellIndex,drinkType,isOver,totalCount,order)
    local effectName = ""
    if drinkType == 1 then  -- 红色酒杯
        effectName ="bingoclickred"
    elseif drinkType== 2 then
        effectName ="bingoclickgreen"
    elseif drinkType == 3 then
        effectName ="bingoclickyellow"
    elseif drinkType == 4 then
        effectName ="bingoclickpurple"
    elseif drinkType == 5 then
        effectName ="XWYyaojiuqi"
    end
    local obj = self.model:GetRoundData(cardId, cellIndex):GetCellObj()
    local flyObj =  BattleEffectPool:GetAndBind(effectName,obj,cardId,5,true)
    local flyAnim = fun.get_component(flyObj,fun.ANIMATOR)
    if isOver then
        flyAnim:Play("over")
    else
        Event.Brocast(EventName.Event_Logic_Collect_Item,cardId,cellIndex,drinkType,1)
        Event.Brocast(EventName.Event_Sign_Cell_Background,drinkType,cardId,cellIndex)
        flyAnim:Play(GetGiftAnimaName(totalCount, order))
        LuaTimer:SetDelayFunction(0.8, function()
            if not self:GetCardView() then return end
            fun.set_same_position_with(flyObj.transform.parent.gameObject, self:GetCardView():GetCardCell(tonumber(cardId), cellIndex))
            local moveTime, targetPos = self:GetDrinkFlyTime(cardId, drinkType, flyObj)
            local coverObj = UnityEngine.GameObject.New()
            fun.set_parent(coverObj, flyObj.transform.parent, true)
            coverObj.transform.position = targetPos
            local localTargetPos = fun.get_gameobject_pos(coverObj, true)
            localTargetPos = localTargetPos - fun.get_child(flyObj.transform, 0).localPosition
            Destroy(coverObj)
            Anim.move(flyObj, localTargetPos.x, localTargetPos.y, localTargetPos.z, moveTime, true, true, function()
                flyAnim:Play("out")
                Event.Brocast(EventName.Event_View_Collect_Item, cardId, drinkType)
                UISound.play("hawaii_Pour")
            end)
        end)

    end
end

--- 第二版冰桶表现
function HawaiiFlyItemEffect:FlyIceBucketToBowl(iceObj,cardId,drintType)
    --local moveTime ,targetPos = self:GetDrinkFlyTime(cardId,drintType,iceObj)
    --local temp = UnityEngine.GameObject.New()
    --fun.set_parent(temp,iceObj.transform.parent.gameObject)
    --temp.transform.position = targetPos
    --targetPos = temp.transform.localPosition
    --Anim.move(iceObj.gameObject,targetPos.x,targetPos.y,targetPos.z,moveTime,true,true,function()
    --    --iceObj:Play("out")
    --    Event.Brocast(EventName.Event_View_Collect_Item,cardId,drintType)
    --    UISound.play("hawaii_Pour")
    --end)
    Event.Brocast(EventName.Event_View_Collect_Item,cardId,drintType)
    UISound.play("hawaii_Pour")
    --Destroy(temp)
end

function HawaiiFlyItemEffect:PlayFreezer(cardId,cellIndex)
    local target = self.model:GetRoundData(cardId, cellIndex):GetCellObj()
    local drinkType = BattleLogic.GetLogicModule(LogicName.Card_logic):GetSingleBingoBowl(cardId)
    Event.Brocast(EventName.Event_Logic_Collect_Item,cardId,cellIndex,drinkType,1,true)
    BattleEffectCache:GetSkillPrefabFromCache("XWYyaojiuqi", target, function(Ob)
        local flyAnim = fun.get_component(Ob,fun.ANIMATOR)
        UISound.play("hawaii_Cocktail")
        LuaTimer:SetDelayFunction(2.5, function()
            --local drinkType = this:GetCardView():GetClosestMaxBowl(cardId)
            fun.set_same_position_with(Ob.transform.parent.gameObject, self:GetCardView():GetCardCell(tonumber(cardId), cellIndex))
            local moveTime, targetPos = self:GetDrinkFlyTime(cardId, drinkType, Ob)
            local coverObj = UnityEngine.GameObject.New()
            fun.set_parent(coverObj, Ob.transform.parent, true)
            coverObj.transform.position = targetPos
            local localTargetPos = fun.get_gameobject_pos(coverObj, true)
            Destroy(coverObj)
            Anim.move(Ob, localTargetPos.x, localTargetPos.y, 0, moveTime, true, true, function()
                flyAnim:Play("out")
                Event.Brocast(EventName.Event_View_Collect_Item, cardId, drinkType, true)
            end)
        end)
    end,5,cardId,false,true)
end

return this



