---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/11/22 11:12
---
local BaseLogicCard = require("Combat.BattleLogic.Base.BaseLogicCard")

--- 圣诞玩法卡牌逻辑
local  ChristmasLogicCard = BaseLogicCard:New("ChristmasLogicCard")

local this = ChristmasLogicCard
this.moduleName = "ChristmasLogicCard"

--- 酒水数量
local bowlTable={}
--- 禁止点击卡牌
local forbidClickTable={}
--- 最大酒水量
local MaxDrinkCount = 4

function ChristmasLogicCard:InitLogic()
    self.model =  ModelList.BattleModel:GetCurrModel()
    self:InitCardBowls()
    forbidClickTable = {0,0,0,0}
    self:BaseInit()
end

function ChristmasLogicCard:InitCardBowls()
    local cardCount = self.model:GetCardCount()
    for i = 1, cardCount do
        bowlTable[i] = {0,0,0,0}
    end
end

function ChristmasLogicCard:Register()
    Event.AddListener(EventName.Event_Logic_Collect_Item,self.AddLogicBowlDrink,self)
end

function ChristmasLogicCard:UnRegister()
    Event.RemoveListener(EventName.Event_Logic_Collect_Item,self.AddLogicBowlDrink,self)
end

--- 增加收集物
function ChristmasLogicCard:AddLogicBowlDrink(cardId,cellIndex,bowlType,addCount,isMax)
    cardId = tonumber(cardId)
    if  isMax then
        addCount = MaxDrinkCount - bowlTable[cardId][bowlType]
        ModelList.BattleModel:GetCurrModel():GetRoundData(cardId):AddHawaiiExtData(cardId,bowlType,addCount)
    end
    if bowlType == 1 then
        bowlTable[cardId][bowlType] = bowlTable[cardId][bowlType] + addCount
    elseif bowlType == 2 then
        bowlTable[cardId][bowlType] = bowlTable[cardId][bowlType] + addCount
    elseif bowlType == 3 then
        bowlTable[cardId][bowlType] = bowlTable[cardId][bowlType] + addCount
    elseif bowlType == 4 then
        bowlTable[cardId][bowlType] = bowlTable[cardId][bowlType] + addCount
    elseif bowlType == 5 then
        bowlTable[cardId][bowlType] = bowlTable[cardId][1] + addCount
        bowlTable[cardId][bowlType] = bowlTable[cardId][2] + addCount
        bowlTable[cardId][bowlType] = bowlTable[cardId][3] + addCount
        bowlTable[cardId][bowlType] = bowlTable[cardId][5] + addCount
    end
    if not ModelList.BattleModel:GetCurrModel():GetRoundData(cardId):GetForbid() and
            bowlTable[cardId][1] >= MaxDrinkCount and bowlTable[cardId][2] >= MaxDrinkCount and
            bowlTable[cardId][3] >= MaxDrinkCount and bowlTable[cardId][4] >= MaxDrinkCount then
        ModelList.BattleModel:GetCurrModel():GetRoundData(cardId):SetForbid()
        ModelList.BattleModel:GetCurrModel():GetRoundData(cardId):BeJackpot()
        this:CheckDoubleJackpotHandle(cardId)
        this:CheckAllCardBeJackpotHandle(cardId)
    end
end

--- 另一侧有jackpot卡牌
function ChristmasLogicCard:IsOtherSideHaveOneJackpot(currCardId)
    local otherJackpotId = 0
    if self.model:GetCardCount() == 4 then
        local forbidCount = 0
        for i = 1, 4 do
            if  self.model:GetRoundData(i):GetForbid() then
                forbidCount = forbidCount + 1
                if i ~= currCardId then
                    otherJackpotId = i
                end
            end
        end
        if forbidCount == 2 and not (currCardId <= 2 and otherJackpotId <= 2) and not (currCardId >= 3 and otherJackpotId >= 3) then
            return otherJackpotId
        else
            return 0
        end
    else
        return 0
    end
end

--- 是否全部卡牌达成jackpoat
function ChristmasLogicCard:IsAllJackpot()
    local cardCount = self.model:GetCardCount()
    for i = 1, cardCount do
        if not self.model:GetRoundData(i):GetForbid() then
            return false
        end
    end
    return true
end

--- 4卡游戏时，若有两张卡达成jackpot，则移动2张达成jackpot的卡片，到3、4卡的位置
function ChristmasLogicCard:CheckAllCardBeJackpotHandle(currCardId)
    --- 这里补充，假如第一次小火箭触发了全部jackpot，就忽略下一次小火箭
    if ModelList.BattleModel:IsRocket() then return end
    if self:IsAllJackpot() then
        if ModelList.BattleModel:IsGameing() then
            ModelList.BattleModel:GetCurrModel():SetReadyState(2)
            LuaTimer:SetDelayFunction(2,function()
                ModelList.BattleModel:GetCurrModel():ReqQuitBingoGame(false)
            end)
        end
    end
end

--- 4卡游戏时，若有两张卡达成jackpot，则移动2张达成jackpot的卡片，到3、4卡的位置
function ChristmasLogicCard:CheckDoubleJackpotHandle(currCardId)
    if ModelList.BattleModel:IsRocket() then return end
    local otherJackpotId =self:IsOtherSideHaveOneJackpot(currCardId)
    if otherJackpotId ~= 0 then
        BattleLogic.GetLogicModule(LogicName.SwitchLogic):StartHideJackpotCardBackground(currCardId,otherJackpotId)
    end
end

--- 取消两个Jackpot的卡牌后移
function ChristmasLogicCard:StopCardBackMove()
    if this.loopMoveCard then
        LuaTimer:Remove(this.loopMoveCard)
    end
end


--- 获取可以达成单bingo的收集物类型
function ChristmasLogicCard:GetSingleBingoBowl(cardId)
    cardId = tonumber(cardId)
    for i = 1, #bowlTable[cardId] do
        if bowlTable[cardId][i] < MaxDrinkCount then
            return i
        end
    end
    return 0
end

--- 获取所有收集物数量
function ChristmasLogicCard:GetBowlCount(cardId)
    cardId = tonumber(cardId)
    for i = 1, #bowlTable[cardId] do
        return bowlTable[cardId]
    end
end

--- 获取有收集物的格子ID列表
function ChristmasLogicCard:GetCellsByMaterialType(cardId, bowlType)
    local itemId = 31000 + bowlType
    return ModelList.ChristmasGameModel:GetRoundData(cardId):GetHiddenItemCells( itemId)
end

--- 获取卡牌bingo数量
function ChristmasLogicCard:GetBowlBingoCount(cardId)
    cardId = tonumber(cardId)
    local bingoCount = 0
    if bowlTable and bowlTable[cardId] then
        for m = 1, #bowlTable[cardId] do
            if bowlTable[cardId][m] >= MaxDrinkCount then
                bingoCount = bingoCount + 1
            end
        end
    end
    return bingoCount
end

return this