--auto generate by C# editor: Tools/自动生成AssetList.lua脚本
local AssetList = {}
local this = AssetList
------------------asset map,key to assetbundle_name-----------------
----------------------------Assets\Bundles\Modules------------------------------------------
this.GiftPackSolitaireBuffView = "modules/solitaire/inhotmodule/abprefab/giftpacksolitairebuffview"
this.Play35HallBackground = "modules/solitaire/inhotmodule/abprefab/play35hallbackground"
this.play35zhandou = "modules/solitaire/inhotmodule/abprefab/play35zhandou"
this.Solitairebingo = "modules/solitaire/inhotmodule/abprefab/solitairebingo"
this.SolitaireBingoView = "modules/solitaire/inhotmodule/abprefab/solitairebingoview"
this.SolitaireEmpty = "modules/solitaire/inhotmodule/abprefab/solitaireempty"
this.SolitaireHallView = "modules/solitaire/inhotmodule/abprefab/solitairehallview"
this.SolitaireHelpView = "modules/solitaire/inhotmodule/abprefab/solitairehelpview"
this.SolitaireJackpot = "modules/solitaire/inhotmodule/abprefab/solitairejackpot"
this.SolitaireJackpotEnable = "modules/solitaire/inhotmodule/abprefab/solitairejackpotenable"
this.SolitaireReadyView = "modules/solitaire/inhotmodule/abprefab/solitairereadyview"
this.SolitaireSettlebingo = "modules/solitaire/inhotmodule/abprefab/solitairesettlebingo"
this.SolitaireSettleView = "modules/solitaire/inhotmodule/abprefab/solitairesettleview"
this.FunctionIcon = "modules/solitaire/inhotmodule/abprefab/pass/functionicon"
this.PassHelperView = "modules/solitaire/inhotmodule/abprefab/pass/passhelperview"
this.PassPurchaseView = "modules/solitaire/inhotmodule/abprefab/pass/passpurchaseview"
this.PassReceivedView = "modules/solitaire/inhotmodule/abprefab/pass/passreceivedview"
this.PassRewardView = "modules/solitaire/inhotmodule/abprefab/pass/passrewardview"
this.PassShowTipView = "modules/solitaire/inhotmodule/abprefab/pass/passshowtipview"
this.PassTaskView = "modules/solitaire/inhotmodule/abprefab/pass/passtaskview"
this.PassView = "modules/solitaire/inhotmodule/abprefab/pass/passview"
this.Rewarditem = "modules/solitaire/inhotmodule/abprefab/pass/rewarditem"
this.SolitaireDlpBj = "modules/solitaire/inhotmodule/texture/abtexture/solitairedlpbj"
this.SceneSolitaire = "modules/solitaire/inhotmodule/scene/scenesolitaire"
this.SolitaireGetxiaoka = "modules/solitaire/inhotmodule/effect/abprefab/solitairegetxiaoka"
this.Solitaireskill2beike = "modules/solitaire/inhotmodule/effect/abprefab/solitaireskill2beike"
this.Solitaireskill2beikeget = "modules/solitaire/inhotmodule/effect/abprefab/solitaireskill2beikeget"
this.Solitaireskillyu = "modules/solitaire/inhotmodule/effect/abprefab/solitaireskillyu"
this.Solitaireskillyubiaoji = "modules/solitaire/inhotmodule/effect/abprefab/solitaireskillyubiaoji"
this.Solitaireskillyuget = "modules/solitaire/inhotmodule/effect/abprefab/solitaireskillyuget"
this.puke_shuidi = "modules/solitaire/inhotmodule/effect/materials/puke_shuidi"
this.puke_suipian = "modules/solitaire/inhotmodule/effect/materials/puke_suipian"
this.GiftPackSolitaireBuffAtlas = "modules/solitaire/inhotmodule/atlas/giftpacksolitairebuffatlas"
this.SolitaireBingoAtlas = "modules/solitaire/inhotmodule/atlas/solitairebingoatlas"
this.SolitaireHallAtlas = "modules/solitaire/inhotmodule/atlas/solitairehallatlas"
this.SolitairePassTaskAtlas = "modules/solitaire/inhotmodule/atlas/solitairepasstaskatlas"
this.SolitairePopupAtlas = "modules/solitaire/inhotmodule/atlas/solitairepopupatlas"
this.SolitairePurchaseAtlas = "modules/solitaire/inhotmodule/atlas/solitairepurchaseatlas"

return this
