---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2024/1/3 14:25
---

local HallCityBannerItem = require "View/HallCityBanner/HallCityBannerItem"
local WinZoneBannerItemInMainView = HallCityBannerItem:New("WinZoneBannerItemInMainView")
local this = WinZoneBannerItemInMainView
local base = HallCityBannerItem



function WinZoneBannerItemInMainView:OnEnable()
    base.OnEnable(self)
    Facade.RegisterViewEnhance(self)
end

function WinZoneBannerItemInMainView:OnDisable()
    base.OnDisable(self)
    Facade.RemoveViewEnhance(self)
end

function WinZoneBannerItemInMainView:GetLeftTime()

    return nil
end

function WinZoneBannerItemInMainView:HitBannerFunc()
    if ViewList.HallCityView then
        ViewList.HallCityView:on_btn_winzone_click()
        log.e("WinZoneBannerItemInMainView:HitBannerFunc()1")
    end
end

function WinZoneBannerItemInMainView:OnDiamondPromotionActivityEnd(data)
    log.log("WinZoneBannerItemInMainView:WinZoneBannerItemInMainView", self.bannerId)
    Event.Brocast(NotifyName.HallCityBanner.RemoveBannerItem, self.bannerId)
    if ViewList.BravoHelpGuideView == nil or  ViewList.BravoHelpGuideView.go == nil then
        Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward,PopupViewType.show,ClaimRewardViewType.CollectReward,data,function()

            Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward, PopupViewType.hide, ClaimRewardViewType.CollectReward)
        end)
    end
end

this.NotifyEnhanceList = {
    --  {notifyName = NotifyName.BravoGuideHelp.DeepLinkHit, func = this.OnDiamondPromotionActivityEnd},
}

return this