---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/11/15 16:42
---

local BaseLogicSwitchCard = {name = "BaseLogicSwitchCard" }
local this = BaseLogicSwitchCard

BaseLogicSwitchCard.__index = BaseLogicSwitchCard


function BaseLogicSwitchCard:InitLogic()
    self.model = ModelList.BattleModel:GetCurrModel()
    self.isSwitching = false
    --- 数据集合
    self.data = {}
    self.currShowMap = 0  --当前展示默认地图
    --- 小卡牌
    self.switchItems = nil
    --- 是否能切换
    self.can_switch = true
    --- 是否正在切换中
    self.isSwitching = false
    --- 当前展示中的卡牌id集合
    self.curr_show_card = {}
    --- 当前城市切换索引,1-前面  2-后面
    self.curr_show_card_index = 1
    --- 背后的卡牌起始索引
    self.back_card_stard_index = 3
    self.PageOneCardIds = {1,2}
    self.BackTwoCardIds = {3,4}
    self:InitShowingCard()
end

--- 初始化展示的卡牌ID分组
function BaseLogicSwitchCard:InitShowingCard()
    local data = self.model:GetCards()
    if #data == 1 then
        self.curr_show_card[1] = { data[1].cardId, -1 }
        self.back_card_stard_index = 1
    elseif #data == 2 then
        self.curr_show_card[1] = { data[1].cardId, data[2].cardId }
        self.back_card_stard_index = 2
    elseif #data == 4 then
        if ModelList.BattleModel:IsHangUp() then
            self.curr_show_card[1] = { data[1].cardId, data[2].cardId,data[3].cardId, data[4].cardId }
            self.curr_show_card[2] = { }
            self.back_card_stard_index = 0
        else
            self.curr_show_card[1] = { data[1].cardId, data[2].cardId }
            self.curr_show_card[2] = { data[3].cardId, data[4].cardId }
            self.back_card_stard_index = 3
        end
    elseif #data == 8 then
        self.curr_show_card[1] = { data[1].cardId, data[2].cardId, data[3].cardId, data[4].cardId, data[5].cardId, data[6].cardId, data[7].cardId, data[8].cardId }
        self.curr_show_card[2] = { }
        self.back_card_stard_index = 0
    elseif #data == 12 then
        self.curr_show_card[1] = { data[1].cardId, data[2].cardId,data[3].cardId, data[4].cardId ,data[5].cardId, data[6].cardId,data[7].cardId,data[8].cardId }
        self.curr_show_card[2] = { data[9].cardId, data[10].cardId ,data[11].cardId, data[12].cardId }
        self.back_card_stard_index = 9
    elseif #data == 16 then
        self.curr_show_card[1] = { data[1].cardId, data[2].cardId,data[3].cardId, data[4].cardId , data[5].cardId, data[6].cardId,data[7].cardId, data[8].cardId}
        self.curr_show_card[2] = { data[9].cardId, data[10].cardId,data[11].cardId, data[12].cardId, data[13].cardId, data[14].cardId,data[15].cardId, data[16].cardId }
        self.back_card_stard_index = 9
    end
    self.curr_show_card_index = 1
end

--- 检查卡ID是否正在展示
function BaseLogicSwitchCard:IsShowing(cardId)
    ---小火箭界面，一律卡牌正面展示中
    if ModelList.BattleModel:IsRocket() then
        return true
    end
    --- 没有第二页卡牌，一律正面展示中
    if not self.curr_show_card or #self.curr_show_card == 0 then
        return true
    end
    if self.curr_show_card[self.curr_show_card_index] then
        for i = 1, #self.curr_show_card[self.curr_show_card_index] do
            if self.curr_show_card[self.curr_show_card_index][i] == cardId then
                return true
            end
        end
    end
    return false
end

--- 同步最新的卡牌分布
function BaseLogicSwitchCard:SyncPage()
    self.curr_show_card[1] = self.PageOneCardIds
    self.curr_show_card[2] = self.BackTwoCardIds
end

--- 开始切换卡牌
function BaseLogicSwitchCard:StartSwitchCard()
    if self.isSwitching then  return   end
    if ModelList.BattleModel:GetCurrModel():GetReadyState() >=2 then return end
    self.isSwitching = true
    self.curr_show_card_index = self.curr_show_card_index + 1
    if self.curr_show_card_index >= 3 then
        self.curr_show_card_index = 1
    end
    Event.Brocast(EventName.Event_Switch_Card,self.curr_show_card_index)
end

--- 结束切换卡牌
function BaseLogicSwitchCard:EndSwitchCard()
    self.isSwitching = false
end

--- 第一页卡牌的ids
function BaseLogicSwitchCard:GetPageOneCardIds()
    return self.PageOneCardIds
end


--- 第二页卡牌的ids
function BaseLogicSwitchCard:GetPageTwoCardIds()
    return self.BackTwoCardIds
end

--- 展示第一页卡牌
function BaseLogicSwitchCard:IsShowPageOne()
    return  self.curr_show_card_index == 1
end

function BaseLogicSwitchCard:New(name)
    local o = {name = name}
    setmetatable(o,{__index = BaseLogicSwitchCard})
    return o
end

---
function BaseLogicSwitchCard:GetsCurrCardOrder()
end

return this