---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/3/15 12:25
---

--- 随机盖章

local BaseSkill =  require("View.Bingo.CardModule.Skill.BaseSkill")

local RandomSignSkill = BaseSkill:New("RandomSignSkill")
setmetatable(RandomSignSkill,BaseSkill)
local this = RandomSignSkill

this.skillRocketGetIndex = 1
local function CurrRocketIndex()
    local index = this.skillRocketGetIndex
    this.skillRocketGetIndex = this.skillRocketGetIndex +1
    if this.skillRocketGetIndex>3 then this.skillRocketGetIndex = 1 end
    return index
end

function RandomSignSkill:ShowSkill (cardId, cellIndex, powerId,serverExtraPos)
    local pos = ConvertCellIndexToServerPos(cellIndex)
    local extraPos = { }
    local cardIndex = tonumber(cardId)
    --if serverExtraPos then log.r("serverExtraPos   "..serverExtraPos) end
    if serverExtraPos  then
        extraPos = BattleTool.GetExtraPos(serverExtraPos)
    else
        this.powerUpData = ModelList.BattleModel:GetCurrModel():LoadGameData().powerUpData
        for i = 1, #this.powerUpData do
            if powerId == this.powerUpData[i].powerUpId then
                for m = 1, #this.powerUpData[i].cardPowerUpEffect do
                    if this.powerUpData[i].cardPowerUpEffect[m].cardId == cardIndex and
                            fun.is_include(pos, this.powerUpData[i].cardPowerUpEffect[m].posList) then
                        extraPos = this.powerUpData[i].cardPowerUpEffect[m].extraPos
                        break
                    end
                end
            end
            if extraPos then break end
        end
    end
    this.cardView = ModelList.BattleModel:GetCurrBattleView():GetCardView()
    this.cardPower = self:GetCardPower()
    for i = 1, #extraPos do
        local targetObj = this.cardView:GetCardCell(tonumber(cardId), cellIndex)
        local newPos = ConvertServerPos(extraPos[i])
        local endPos = this.cardView:GetCardCell(tonumber(cardId), newPos)
        BattleEffectCache:GetSkillPrefabFromCache("HangSkillTaril", targetObj, function(obj)

            LuaTimer:SetDelayFunction(2, function()
                BattleEffectCache:GetSkillPrefabFromCache("HangSkillGet", endPos, function(ob)
                    local objAnima = fun.get_component(ob, fun.ANIMATOR)
                    if objAnima then
                        objAnima:Play("Get" .. CurrRocketIndex())
                    end
                    LuaTimer:SetDelayFunction(1.6, function()
                        this.cardView:OnClickCardIgnoreJudgeByIndex(cardId, newPos, powerId)
                        this.cardPower:ChangeCellState(cardId, newPos, this.CellState.Signed)
                    end,nil,LuaTimer.TimerType.Battle)
                end, 3)
            end,nil,LuaTimer.TimerType.Battle)
        end, 5, cardId)

    end
end

return this