---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/8 16:37
--- 卡牌动效 主入口
local EffectEntry = Clazz(ClazzBase, "EffectEntry")
local this = EffectEntry

local cardSignEffect = nil
local cardFlyItemEffect = nil
local cardBingoEffect = nil
local cardCoinEffect = nil
local cardSignSupplement = require("View/Bingo/EffectModule/Card/CardEffectSupplement/CardSignSupplement")
local cardRocketEffect = require("View/Bingo/EffectModule/Card/CardRocketEffect")
local delayAnima = require("View/Bingo/EffectModule/Card/CardDelayAnima")
local cardJackpot = require("View/Bingo/EffectModule/Card/CardJackpotEffect")
local callNumber = require("View/Bingo/EffectModule/Card/CardCallNumberEffect")
local cardCellEffect = require("View/Bingo/EffectModule/Card/CardCellEffect")
local cardWish = require("View/Bingo/EffectModule/Card/CardWishEffect")
local cardJoker = require("View/Bingo/EffectModule/Card/CardJokerEffect")
local cardSuperMatch = require("View/Bingo/EffectModule/Card/CardSuperMatchEffect")
local gameOpenCardPack = require("View/Bingo/EffectModule/BattleOpen/CardPackageEnterGameEffect")

this.CellsChipObj = nil
local chipScale = 1
local needWish = false

local InitCellsChip = function()
    if not this.CellsChipObj then
        this.CellsChipObj = {}
        local cells = this.cardView:GetCardCell()
        for k, v in pairs(cells) do
            local cardId = tonumber(k)
            this.CellsChipObj[cardId] = {}
            for i = 1, 25 do
                this.CellsChipObj[cardId][i] = nil
            end
        end
        if ModelList.BattleModel:GetGameType() == PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
            chipScale = 0.45
        else
            chipScale = 1
        end
    end
end

function EffectEntry:LoadEffectRequire()
    local gameType = ModelList.BattleModel:GetGameCityPlayID()
    local data = Csv.GetData("new_game_mode", gameType)
    cardSignEffect = require("View.Bingo.EffectModule.Card.SignEffect." .. data["cellsigntype"])
    cardFlyItemEffect = require("View.Bingo.EffectModule.Card.FlyItemEffect." .. data["flyitemeffect"])
    cardBingoEffect = require("View.Bingo.EffectModule.Card.BingoEffect." .. data["cardbingoeffect"])
    cardCoinEffect = require("View.Bingo.EffectModule.Card.CoinEffect." .. data["card_coin_effect"])
    needWish = Csv.GetData("new_game_card", gameType, "need_wish") ~= 0 and true or false
end

--- @param cardView : GameCardView
function EffectEntry:SetCardView(cardView)
    this.cardView = cardView
    this:LoadEffectRequire()
    cardSignEffect:SetCardView(cardView, this)
    cardFlyItemEffect:SetCardView(cardView, this)
    cardBingoEffect:SetCardView(cardView, this)
    cardRocketEffect:SetCardView(cardView, this)
    delayAnima:SetCardView(cardView, this)
    cardCoinEffect:SetCardView(cardView, this)
    cardJackpot:Init(cardView, this)
    callNumber:Init(cardView, this)
    cardCellEffect:Init(cardView, this)
    cardWish:Init(cardView, this)
    cardJoker:Init(cardView, this)
    cardSuperMatch:Init(cardView, this)
    LuaTimer:SetDelayFunction(1, function()
        InitCellsChip()
    end,nil,LuaTimer.TimerType.Battle)
    cardSignSupplement:Init()
end

function EffectEntry:GetCellChip(cardId, index, cardCell)
    cardId = tonumber(cardId)
    --- View/Bingo/EffectModule/Card/EffectEntry:75: attempt to index field 'CellsChipObj' (a nil value)  修复收集的报错
    if this.CellsChipObj == nil then
        InitCellsChip()
    end
    if this.CellsChipObj[cardId][index] == nil then
        --从cell预制体中取
        local effectObj = cardSignEffect:GetSignEffectObj(cardId, index, cardCell)
        local anim = fun.get_component(effectObj, fun.ANIMATOR)
        
        --下面是战斗中实例化ef_Bingo_click的代码
        --local eff = BattleEffectPool:Get("ef_Bingo_click", cardCell)
        --BattleEffectPool:CoroutineCheckCoverEffect()
        --this:SetBingoJokerSkin(eff, cardId, index)
        --local anim = fun.get_component(eff, fun.ANIMATOR)
        --local map = this.cardView:GetIdToMap(cardId)
        --local ref_temp = fun.get_component(map, fun.REFER)
        --local ChipsContainer = ref_temp:Get("ChipsContainer")
        --fun.set_parent(eff, ChipsContainer, false)
        --fun.set_gameobject_scale(eff, chipScale, chipScale, 1)
        
        this.CellsChipObj[cardId][index] = anim
    end
    return this.CellsChipObj[cardId][index]
end

--- 设置小丑机台的bingo特效
function EffectEntry:SetBingoJokerSkin(eff, cardId, index)
    local refTemp = fun.get_component(eff, fun.REFER)
    if refTemp then
        local isJokerArea = ModelList.BattleModel:GetCurrModel():GetRoundData(cardId, index):IsJokerArea()
        local playType = ModelList.BattleModel:GetGameType()
        local checkType = playType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS
        if ModelList.BattleModel.GetIsJokerMachine() then
            coroutine.start(function()
                if isJokerArea then
                    if fun.is_not_null(refTemp) then SetJokerSkin3(refTemp:Get("b_click_01"), "JokerBattleAtlas", "bClickClownC01") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_click_02"), "JokerBattleAtlas", "bClickClownC02") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_click_03"), "JokerBattleAtlas", "bClickClownC03") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_bingo_01"), "JokerBattleAtlas", "bBingopClownC01") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_bingo_02"), "JokerBattleAtlas", "bBingopClownC02") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_bingo_03"), "JokerBattleAtlas", "bBingopClownC03") end
                    if not checkType then
                        coroutine.wait(0.2)
                        if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_jackpot_01"), "JokerBattleAtlas", "bJackpotClownC01") end
                        coroutine.wait(0.2)
                        if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_jackpot_02"), "JokerBattleAtlas", "bJackpotClownC02") end
                        coroutine.wait(0.2)
                        if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_jackpot_03"), "JokerBattleAtlas", "bJackpotClownC03") end
                    end
                else
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_click_01"), "JokerBattleAtlas", "bClickClown01") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_click_02"), "JokerBattleAtlas", "bClickClown02") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_click_03"), "JokerBattleAtlas", "bClickClown03") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_bingo_01"), "JokerBattleAtlas", "bBingopClown01") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_bingo_02"), "JokerBattleAtlas", "bBingopClown02") end
                    coroutine.wait(0.2)
                    if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_bingo_03"), "JokerBattleAtlas", "bBingopClown03") end
                    if not checkType then
                        coroutine.wait(0.2)
                        if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_jackpot_01"), "JokerBattleAtlas", "bJackpotClown01") end
                        coroutine.wait(0.2)
                        if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_jackpot_02"), "JokerBattleAtlas", "bJackpotClown02") end
                        coroutine.wait(0.2)
                        if fun.is_not_null (refTemp) then SetJokerSkin3(refTemp:Get("b_jackpot_03"), "JokerBattleAtlas", "bJackpotClown03") end
                    end
                end
            end)
        end
    end
end

function EffectEntry:on_x_update()
    delayAnima:on_x_update()
end

function EffectEntry:OnDisable()
    delayAnima:OnDisable()
    if cardCoinEffect then
        cardCoinEffect:OnDisable()
    end

    this.CellsChipObj = nil
    needWish = false
end

function EffectEntry:AddDelayAnima(ani, play_name, delay, duration, signType, cardid, pos)
    delayAnima:AddDelayAnima(ani, play_name, delay, duration, signType, cardid, pos)
end

function EffectEntry:DelayPlayEffectEntry()
    for k, v in pairs(this.cardView.delayPlayEffectEntry) do
        v.ani:Play(v.play_name)
    end
    this.cardView.delayPlayEffectEntry = {}
end


--显示盖章效果
function EffectEntry:SignEffectEntry(cardCell, signType, delay, self_bingo)
    cardSignEffect:SignEffectEntry(cardCell, signType, delay, self_bingo)
end

function EffectEntry:ShowMisseffect(cardId, cellIndex)
    cardRocketEffect:ShowMisseffect(cardId, cellIndex)
end

function EffectEntry:ShowPerfectEffect(cardId)
    cardRocketEffect:ShowPerfectEffect(cardId)
end

function EffectEntry:InitFlyCoins(mapIndex, pos, box)
    cardCoinEffect:InitFlyCoins(mapIndex, pos, box)
end

function EffectEntry:InitFlyIcons(mapIndex, pos, box)
    cardCoinEffect:InitFlyCoins(mapIndex, pos, box, true)
end

function EffectEntry:InitFlySuperMatchRewards(mapIndex, pos, box)
    --superMatchRewardEffect:InitFlyCoins(mapIndex, pos, box)
end

function EffectEntry:SignCardEffect(cardId, index, cardCell, signType, delay, self_bingo, giftLen)
    cardSignEffect:SignCardEffect(cardId, index, cardCell, signType, delay, self_bingo, giftLen)
end

function EffectEntry:HideCellChild(ref_temp)
    cardSignEffect:HideCellChild(ref_temp)
end

--jackpot 发光特效
function EffectEntry:PlayJackpotShine()
    cardJackpot:PlayShine()
end

-- 是否有正在飞行的金币
function EffectEntry:HasFlyCoinCount()
    return cardCoinEffect:HasCoinCountInPool()
end

-- 是否有正在飞行的金币
function EffectEntry:ClearCoinPool()
    return cardCoinEffect:ClearCoinPool()
end

-- 是否有正在飞行的金币
function EffectEntry:HasFlySuperMatchCount()
    --if superMatchRewardEffect then
    --    return superMatchRewardEffect:HasCoinCountInPool()
    --end
    return false
end

function EffectEntry:ShowClickCellTip(cell, kick_error, num, doubleNum, cardid, cellIndex)
    cardSignEffect:ShowClickCellTip(cell, kick_error, num, doubleNum, cardid, cellIndex)
end

function EffectEntry:GetCellEffect(cardId, cellIndex, effType)
    if effType == 1 then
        -- 普通get
        local obj = BattleEffectPool:Get("CellGet")
        BattleEffectPool:DelayRecycle("CellGet", obj, 2)
        cardSignSupplement:SetEffectScale(obj)
    elseif effType == 2 then
        --快速点击
        local obj = BattleEffectPool:Get("CellGetFast")
        BattleEffectPool:DelayRecycle("CellGetFast", obj, 2)
    end
end

function EffectEntry:ShowBingo(bingoData, cb)
    cardBingoEffect:ShowBingoOrJackpot(bingoData, cb)
end

function EffectEntry:PlayWish(cardId, cellIndex, isSelfBingoCell)
    if not needWish then
        return
    end
    --local cells = this.cardView:GetCardCell(cardId, cellIndex)
    if not ModelList.BattleModel:GetCurrModel():IsWishState(cardId, cellIndex) then
        cardWish:PlayCellWish(cardId, cellIndex, isSelfBingoCell)
        ModelList.BattleModel:GetCurrModel():ChangeWishState(cardId, cellIndex)
    end
end

function EffectEntry:HideWish(cardId, cellIndex)
    if not needWish then
        return
    end
    local cells = this.cardView:GetCardCell(cardId, cellIndex)
    if ModelList.BattleModel:GetCurrModel():IsWishState(cardId, cellIndex) then
        cardWish:HideCellWish(cells)
        ModelList.BattleModel:GetCurrModel():ChangeWishState(cardId, cellIndex, 0)
    end
end

---已触发wish效果的格子,只播放双数字  wish效果
function EffectEntry:PlayDoubleNumWish(cellRef)
    if not needWish then
        return
    end
    cardWish:OnlyDoubleNumPlayWish(cellRef)
end

--- 小丑机台，播放双倍金币奖励效果
function EffectEntry:PlayJokerDoubleCoin()
    cardJoker:PlayJokerDoubleCoin()
end

--- 小丑机台，隐藏其他卡双倍金币奖励图标
function EffectEntry:PlayHideJokerDoubleCoin()
    cardJoker:PlayHideJokerDoubleCoin()
end

---小丑机台展示区域奖励效果
function EffectEntry:PlayGetJokerBonuses(cardId, cellIndex)
    cardJoker:PlayGetJokerBonuses(cardId, cellIndex)
end

---小丑机台展示区域奖励效果
function EffectEntry:PlayGetJokerBonuses1(cardId, cellIndex)
    cardJoker:PlayGetJokerBonuses1(cardId, cellIndex)
end

---小丑机台展示吹吹卷效果
function EffectEntry:PlayGetJokerBlowRoll(cardId, cellIndex, data)
    cardJoker:PlayGetJokerBlowRoll(cardId, cellIndex, data)
end

---小丑机台展示彩球叫号器效果
function EffectEntry:PlayGetJokerBallSprayer(callBack)
    cardJoker:PlayGetJokerBallSprayer(callBack)
end

---小丑机台展示彩球叫号器效果
function EffectEntry:PlayGetJokerBallSprayerFly(signCellData)
    cardJoker:PlayGetJokerBallSprayerFly(signCellData)
end

---小丑机台展示彩球叫号器效果
function EffectEntry:PlayGetJokerBallSprayerFlyOver()
    cardJoker:PlayGetJokerBallSprayerFlyOver()
end

---小丑区域盖章效果
function EffectEntry:PlayJokerAreaGetEffect(cardId, cellIndex)
    cardJoker:PlayJokerAreaGetEffect(cardId, cellIndex)
end

---小丑区域盖章效果
function EffectEntry:PlayJokerFlyItemsToBox(cardId, cellIndex, data)
    cardJoker:PlayJokerFlyItems(cardId, cellIndex, data)
end

---小丑区域盖章效果
function EffectEntry:PlayHideJokerCellBg(cardId, data)
    cardJoker:PlayHideJokerCellBg(cardId, data)
end

---小丑 炸弹
function EffectEntry:PlayDetonateBomb(cardId, cellIndex, data)
    cardJoker:PlayDetonateBomb(cardId, cellIndex, data)
end

---小丑 资源锤
function EffectEntry:PlayResourceHammer(cardId, cellIndex, data)
    cardJoker:PlayResourceHammer(cardId, cellIndex, data)
end

--- 进入游戏后，卡包入场效果
function EffectEntry:GameOpenCardPack(cb)
    gameOpenCardPack:Check(cb)
end

--- 机器人卡牌上播放super match 合作特效
function EffectEntry:CardSuperMatchEffect(cardId, cellIndex, ball, number)
    if cardSuperMatch then
        local cells = this.cardView:GetCardCell(cardId, cellIndex)
        cardSuperMatch:PlayCellSuperMatch(cells, cardId, cellIndex, ball, number)
    end
end

--- 玩家卡牌上播放super match 合作特效
function EffectEntry:PlaySmallCardSuperMatchEffect(cardId, cellIndex, ball, number)
    if cardSuperMatch then
        local cells = this.cardView:GetParentView():GetSwitchView(): GetSmallCardObj(cardId, cellIndex)
        cardSuperMatch:PlayPlayerSmallCellSuperMatch(cells, cardId, cellIndex, ball, number)
    end
end

function EffectEntry.Register()
    --Event.AddListener(EventName.CardEffect_Jackpot_Shine, this.PlayJackpotShine)
    Event.AddListener(EventName.CardSingEffect_CellTip, this.ShowClickCellTip)
    Event.AddListener(EventName.CardBingoEffect_ShowBingo, this.ShowBingo)
    Event.AddListener(EventName.CardBingoEffect_ShowWish, this.PlayWish)
    Event.AddListener(EventName.CardBingoEffect_CancelShowWish, this.HideWish)
    --Event.AddListener(EventName.CardBingoEffect_DoubleNumWish, this.PlayDoubleNumWish)
    Event.AddListener(EventName.Event_Hide_Other_Joker_Double_Coin, this.PlayHideJokerDoubleCoin)
    Event.AddListener(EventName.Event_Get_Joker_Double_Coin, this.PlayJokerDoubleCoin)
    Event.AddListener(EventName.Event_Get_Joker_Bonuses, this.PlayGetJokerBonuses)
    Event.AddListener(EventName.Event_Get_Joker_Blow_Roll, this.PlayGetJokerBlowRoll)
    Event.AddListener(EventName.Event_Play_Joker_BallSprayer, this.PlayGetJokerBallSprayer)
    Event.AddListener(EventName.Event_Play_Joker_BallSprayer_Fly, this.PlayGetJokerBallSprayerFly)
    Event.AddListener(EventName.Event_Play_Joker_BallSprayer_Over, this.PlayGetJokerBallSprayerFlyOver)
    Event.AddListener(EventName.Event_Joker_Bonuses_Click_Effect, this.PlayJokerAreaGetEffect)
    Event.AddListener(EventName.Event_Joker_Fly_Item_To_Box, this.PlayJokerFlyItemsToBox)
    Event.AddListener(EventName.Event_Joker_Hide_BallSprayerIcon, this.PlayHideJokerCellBg)
    Event.AddListener(EventName.Event_Game_Open_Card_Pack_Enter, this.GameOpenCardPack)
    Event.AddListener(EventName.Event_Joker_Detonate_Bomb, this.PlayDetonateBomb)
    Event.AddListener(EventName.Event_Joker_Resource_Hammer, this.PlayResourceHammer)
    if ModelList.BattleModel.GetBattleSuperMatch() then
        if not EventName.Event_Card_Super_Match then
            local packageRequire = require("View/Bingo/UIView/SuperMatch/SuperMatchBattlePackage")
            packageRequire:Init()
        end
        Event.AddListener(EventName.Event_Card_Super_Match, this.CardSuperMatchEffect)
        Event.AddListener(EventName.Event_Super_Match_Switch_Card_Effect, this.PlaySmallCardSuperMatchEffect)
    end
end

function EffectEntry.UnRegister()
    --Event.RemoveListener(EventName.CardEffect_Jackpot_Shine, this.PlayJackpotShine)
    Event.RemoveListener(EventName.CardSingEffect_CellTip, this.ShowClickCellTip)
    Event.RemoveListener(EventName.CardBingoEffect_ShowBingo, this.ShowBingo)
    Event.RemoveListener(EventName.CardBingoEffect_ShowWish, this.PlayWish)
    Event.RemoveListener(EventName.CardBingoEffect_CancelShowWish, this.HideWish)
    --Event.RemoveListener(EventName.CardBingoEffect_DoubleNumWish, this.PlayDoubleNumWish)
    Event.RemoveListener(EventName.Event_Hide_Other_Joker_Double_Coin, this.PlayHideJokerDoubleCoin)
    Event.RemoveListener(EventName.Event_Get_Joker_Double_Coin, this.PlayJokerDoubleCoin)
    Event.RemoveListener(EventName.Event_Get_Joker_Bonuses, this.PlayGetJokerBonuses)
    Event.RemoveListener(EventName.Event_Get_Joker_Blow_Roll, this.PlayGetJokerBlowRoll)
    Event.RemoveListener(EventName.Event_Play_Joker_BallSprayer, this.PlayGetJokerBallSprayer)
    Event.RemoveListener(EventName.Event_Play_Joker_BallSprayer_Fly, this.PlayGetJokerBallSprayerFly)
    Event.RemoveListener(EventName.Event_Play_Joker_BallSprayer_Over, this.PlayGetJokerBallSprayerFlyOver)
    Event.RemoveListener(EventName.Event_Joker_Bonuses_Click_Effect, this.PlayJokerAreaGetEffect)
    Event.RemoveListener(EventName.Event_Joker_Fly_Item_To_Box, this.PlayJokerFlyItemsToBox)
    Event.RemoveListener(EventName.Event_Joker_Hide_BallSprayerIcon, this.PlayHideJokerCellBg)
    Event.RemoveListener(EventName.Event_Game_Open_Card_Pack_Enter, this.GameOpenCardPack)
    Event.RemoveListener(EventName.Event_Joker_Detonate_Bomb, this.PlayDetonateBomb)
    Event.RemoveListener(EventName.Event_Joker_Resource_Hammer, this.PlayResourceHammer)
    if ModelList.BattleModel.GetBattleSuperMatch() then
        Event.RemoveListener(EventName.Event_Card_Super_Match, this.CardSuperMatchEffect)
        Event.RemoveListener(EventName.Event_Super_Match_Switch_Card_Effect, this.PlaySmallCardSuperMatchEffect)
    end
    this:RemoveAllEffect()
end

function EffectEntry:RemoveAllEffect()
    if cardSignEffect then
        cardSignEffect:Remove()
    end
    if cardFlyItemEffect then
        cardFlyItemEffect:Remove()
    end
end

function EffectEntry:CheckEffectShowOver()
    local ret = true
    if cardFlyItemEffect and cardFlyItemEffect.CheckAllAnimShowOver then
        ret = ret and cardFlyItemEffect:CheckAllAnimShowOver()
    end
    return ret
end

return this
