---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/10/8 12:35
---
local CardInput = require("View.Bingo.CardModule.BaseModules.CardInput")
local  NormalCardInput = CardInput:New("NormalCardInput")
local this = NormalCardInput


return this