---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/12/14 17:08
---
local CallNumberBaseState = require("View/Bingo/CallNumberState/CallNumberBaseState")
local CallNumberSortState = Clazz(CallNumberBaseState,"CallNumberSortState")
local this = CallNumberSortState
function CallNumberSortState:New()
    local o = {}
    setmetatable(o,{__index = CallNumberSortState})
    return o
end


function CallNumberSortState:InitState()

end

function CallNumberSortState:OnEnter(fsm)
    --self._fsm = fsm
    --self._owner = fsm:GetOwner()
end

function CallNumberSortState:OnLeave(fsm)
    --self._fsm = nil
    --self._owner = nil
end

function CallNumberSortState:Dispose()
    self:OnLeave(nil)
end

return this
