--auto generate by C# editor: Tools/自动生成AssetList.lua脚本
local AssetList = {}
local this = AssetList
------------------asset map,key to assetbundle_name-----------------
----------------------------Assets\Bundles\Modules------------------------------------------
this.Play29HallBackground = "modules/scratchwinner/inhotmodule/abprefab/play29hallbackground"
this.play29zhandou = "modules/scratchwinner/inhotmodule/abprefab/play29zhandou"
this.ScratchWinnerBingoView = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerbingoview"
this.ScratchWinnerExtraBallView = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerextraballview"
this.ScratchWinnerExtraBallViewicon = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerextraballviewicon"
this.ScratchWinnerExtraBallViewiconzhong = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerextraballviewiconzhong"
this.ScratchWinnerHallView = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerhallview"
this.ScratchWinnerHelpView = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerhelpview"
this.ScratchWinnerJackpot = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerjackpot"
this.ScratchWinnerReadyView = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnerreadyview"
this.ScratchWinnerSettleView = "modules/scratchwinner/inhotmodule/abprefab/scratchwinnersettleview"
this.FunctionIcon = "modules/scratchwinner/inhotmodule/abprefab/pass/functionicon"
this.GiftPackScratchWinnerBuffView = "modules/scratchwinner/inhotmodule/abprefab/pass/giftpackscratchwinnerbuffview"
this.PassHelperView = "modules/scratchwinner/inhotmodule/abprefab/pass/passhelperview"
this.PassPurchaseView = "modules/scratchwinner/inhotmodule/abprefab/pass/passpurchaseview"
this.PassReceivedView = "modules/scratchwinner/inhotmodule/abprefab/pass/passreceivedview"
this.PassRewardView = "modules/scratchwinner/inhotmodule/abprefab/pass/passrewardview"
this.PassShowTipView = "modules/scratchwinner/inhotmodule/abprefab/pass/passshowtipview"
this.PassTaskView = "modules/scratchwinner/inhotmodule/abprefab/pass/passtaskview"
this.PassView = "modules/scratchwinner/inhotmodule/abprefab/pass/passview"
this.Rewarditem = "modules/scratchwinner/inhotmodule/abprefab/pass/rewarditem"
this.GoldRushDlpBg = "modules/scratchwinner/inhotmodule/texture/abtexture/goldrushdlpbg"
this.SceneScratchWinner = "modules/scratchwinner/inhotmodule/scene/scenescratchwinner"
this.ScratchWinnerBingobingo = "modules/scratchwinner/inhotmodule/effect/abprefab/scratchwinnerbingobingo"
this.ScratchWinnerEmpty = "modules/scratchwinner/inhotmodule/effect/abprefab/scratchwinnerempty"
this.ScratchWinnergetxiaoka = "modules/scratchwinner/inhotmodule/effect/abprefab/scratchwinnergetxiaoka"
this.ScratchWinnerskill1jinbi = "modules/scratchwinner/inhotmodule/effect/abprefab/scratchwinnerskill1jinbi"
this.ScratchWinnerskill1shaoziget = "modules/scratchwinner/inhotmodule/effect/abprefab/scratchwinnerskill1shaoziget"
this.ScratchWinnersuipian = "modules/scratchwinner/inhotmodule/effect/materials/scratchwinnersuipian"
this.ScratchWinnersuipianCT = "modules/scratchwinner/inhotmodule/effect/materials/scratchwinnersuipianct"
this.ScratchWinnersuipianjinbi = "modules/scratchwinner/inhotmodule/effect/materials/scratchwinnersuipianjinbi"
this.ScratchWinnersuipianjinbi1 = "modules/scratchwinner/inhotmodule/effect/materials/scratchwinnersuipianjinbi1"
this.ScratchWinnersuipianjinbi2 = "modules/scratchwinner/inhotmodule/effect/materials/scratchwinnersuipianjinbi2"
this.ScratchWinnersuipianjinbi3 = "modules/scratchwinner/inhotmodule/effect/materials/scratchwinnersuipianjinbi3"
this.GiftPackScratchWinnerBuffAtlas = "modules/scratchwinner/inhotmodule/atlas/giftpackscratchwinnerbuffatlas"
this.ScratchWinnerExtraBallAtlas = "modules/scratchwinner/inhotmodule/atlas/scratchwinnerextraballatlas"
this.ScratchWinnerPassTaskAtlas = "modules/scratchwinner/inhotmodule/atlas/scratchwinnerpasstaskatlas"
this.ScratchWinnerPopupAtlas = "modules/scratchwinner/inhotmodule/atlas/scratchwinnerpopupatlas"
this.ScratchWinnerPurchaseAtlas = "modules/scratchwinner/inhotmodule/atlas/scratchwinnerpurchaseatlas"

return this
