---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/4/4 10:14
---


local CompetitionRankItem = BaseView:New("CompetitionRankItem")
local this = CompetitionRankItem
this.viewType = CanvasSortingOrderManager.LayerType.None

local flyScoreView = nil

this.auto_bind_ui_items ={
    "img_head",
    "text_thValue",
    "text_userName",
    "text_rewards",
    "btn_item",
    "TopRank1",
    "TopRank2",
    "TopRank3",
    "RewardType",
    "DoubleGift",
    "DoubleCollect",
    "imageFrame",
}

function CompetitionRankItem:New(isSettle)
    local o = {}
    self.__index = self
    setmetatable(o,self)
    o._isSettle = isSettle
    return o
end

function CompetitionRankItem:Awake()
    self:on_init()
end

function CompetitionRankItem:OnEnable()
    self._init = true
    --self:SetRankData(self._data,self._data.order)
end

function CompetitionRankItem:OnDisable()
    self:OnDispose()
    self._init = nil
    self._data = nil
    self._posOffset = nil
    self.flyScore = nil
    self.lightEffect = nil
    self.FadeLightEffect = nil
    flyScoreView = nil
end

function CompetitionRankItem:IsMyRank()
    return false
end

function CompetitionRankItem:SetLayerIndex(index)
    if self.go then
        self.go.transform:SetSiblingIndex(index)
    end
end

function CompetitionRankItem:SetRankData(data,parentView)
    self._data = data or self._data
    self._parentView = parentView
    if self._init and self._data then
        self:SetOrderSuffix()
        if self._data.nickname == nil or self._data.nickname == "" then
            self.text_userName.text = self:GetNickName()
        elseif self._data.robot == 0 then
            self.text_userName.text = "You"
        else
            self.text_userName.text = self._data.nickname
        end
        self.text_rewards.text = fun.NumInsertComma(self._data.score)
        Cache.SetImageSprite("HeadAtlas",self:GetHeadIcon(),self.img_head)
        self:SetHeadFrame(self._data)
        self:SetRewardItem()
        local maxRewardRankStr = Csv.GetData("competition",ModelList.CompetitionModel:GetCompetitionGroupId(),"reward")
        local   ts = string.reverse(maxRewardRankStr)
        local _, i = string.find(ts, '-')
        local  m = string.len(ts) - i + 1
        local maxRewardRank = tonumber(string.sub(maxRewardRankStr, m+1,m+1))
        if self._data.order <= 3 then
            self.RewardType.sprite =  AtlasManager:GetSpriteByName("CompetitionCookieAtlas","BsCookiePmLb0"..self._data.order)
        elseif self._data.order <= maxRewardRank then
            self.RewardType.sprite =  AtlasManager:GetSpriteByName("CompetitionCookieAtlas","BsCookiePmLb04")
        else
            self.RewardType.sprite =  AtlasManager:GetSpriteByName("CompetitionCookieAtlas","BsCookiePmLb05")
        end
        fun.set_active(self.DoubleGift,self:IsDoubleGiftBuff())
        fun.set_active(self.DoubleCollect,self:IsDoubleCollectBuff())
        --log.r("DoubleGift   "..tostring(self:IsDoubleGiftBuff()) )
        --log.r("DoubleCollect   ".. tostring(self:IsDoubleCollectBuff()))
    end
end

function CompetitionRankItem:SetHeadFrame(data)
    local myUid = ModelList.PlayerInfoModel:GetUid()
    local model = ModelList.PlayerInfoSysModel
    if myUid == tonumber(data.uid) then
        model:LoadOwnFrameSprite(self.imageFrame)
    else
        local useFrameName = model:GetCheckFrame(nil , data.uid)
        model:LoadTargetFrameSpriteByName(useFrameName ,self.imageFrame)
    end
end

function CompetitionRankItem:IsDoubleGiftBuff()
    if self._data.gameProps and #self._data.gameProps>0 then
        for i = 1, #self._data.gameProps do
            if self._data.gameProps[i] == RESOURCE_TYPE.RESOURCE_TYPE_DOUBLE_COMPETITION_REWARD then
                return true
            end
        end
    end
    return false
end

function CompetitionRankItem:IsDoubleCollectBuff()
    if self._data.gameProps and #self._data.gameProps>0 then
        for i = 1, #self._data.gameProps do
            if self._data.gameProps[i] == RESOURCE_TYPE.RESOURCE_TYPE_DOUBLE_COMPETITION then
                return true
            end
        end
    end
    return false
end

function CompetitionRankItem:SetRewardType()
    return fun.get_strNoEmpty(self._data.avatar, Csv.GetData("robot_name",self._data.robotId,"name"))
end

function CompetitionRankItem:GetHeadIcon()
    local avator = fun.get_strNoEmpty(self._data.avatar, Csv.GetData("robot_name",self._data.uid,"icon"))
    return fun.get_strNoEmpty(avator, "xxl_head016")
end


function CompetitionRankItem:GetNickName()
    local avator = fun.get_strNoEmpty(self._data.nickname, Csv.GetData("robot_name",self._data.uid,"name"))
    return fun.get_strNoEmpty(avator, string.format("User_%s",self._data.uid))
end

function CompetitionRankItem:LoadLightEffect(callback)
    Cache.load_prefabs(AssetList["TournamentSettleViewTail"],"TournamentSettleViewTail",function(obj)
        if obj then
            self.lightEffect = fun.get_instance(obj,self.go)
            fun.set_rect_anchored_position(self.lightEffect,0,0)
            if callback then
                callback()
            end
        end
    end)
end

function CompetitionRankItem:FadeOutLightEffect()
    Cache.load_prefabs(AssetList["TournamentSettleViewShow"],"TournamentSettleViewShow",function(obj)
        if obj then
            if self.lightEffect then
                fun.set_active(self.lightEffect.transform,false)
            end
            self.FadeLightEffect = fun.get_instance(obj,self.go)
            fun.set_rect_anchored_position(self.FadeLightEffect,0,0)
        end
    end)
end

function CompetitionRankItem:FlyScore(callback,targetScore)
end

function CompetitionRankItem:SetRankOrder(order)
    fun.set_active(self.TopRank1,order == 1)
    fun.set_active(self.TopRank2,order == 2)
    fun.set_active(self.TopRank3,order == 3)
    fun.set_active(self.text_thValue,order >3)
end

function CompetitionRankItem:SetOrderSuffix()
    local order = self._data.order
    self.text_thValue.text = tostring(self._data.order)
    self:SetRankOrder(order)
end

function CompetitionRankItem:SetOrder(order)
    if self._data then
        self._data.order = order
        self:SetOrderSuffix()
    end
end

function CompetitionRankItem:SetOrderDataOnly(order)
    if self._data then
        self._data.order = order
        self:SetOrderSuffix()
    end
end

function CompetitionRankItem:GetOrder()
    if self._data then
        return self._data.order
    end
    return 1
end

function CompetitionRankItem:SetRewardItem()

end

function CompetitionRankItem:SetTopReward()

end

function CompetitionRankItem:OnDispose()

end

function CompetitionRankItem:on_btn_item_click()
    self:ShowRewardItems()
end

--- 气泡弹窗提示奖励物品
function CompetitionRankItem:ShowRewardItems()
    if self._data and self._parentView then
        self._parentView:ShowPopup(self._data.order,self.RewardType)
    end
end

function CompetitionRankItem:GetPos()
    if self.go then
        return self.go.transform.localPosition
    end
end

function CompetitionRankItem:GetUid()
    if self._data then
        return self._data.uid
    end
end

function CompetitionRankItem:GetPosY()
    if self.go then
        return self.go.transform.localPosition.y
    end
end

function CompetitionRankItem:DoSmoothRankOrderNum(targetOrder,time,ease,updatCallback, finishCallback)
    if self._data then
        Anim.do_smooth_int2(self.text_thValue,self._data.order,targetOrder,time,ease,updatCallback,finishCallback)
    end
end

function CompetitionRankItem:ChangeOrder(order1,order2)
    if self._data.order < order1 and self._data.order >= order2 then
        self._data.order = self._data.order + 1
        self:SetOrderSuffix()
    end
end

function CompetitionRankItem:CachePosOffset(offset)
    self._posOffset = offset
end

function CompetitionRankItem:SetPosByOffset(pos)
    if self._posOffset then
        fun.set_gameobject_pos(self.go,0,pos - self._posOffset,0,true)
    end
end

return this