---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/7/26 12:11
---


local CardsSummaryItems = BaseChildView:New() --Clazz(BaseChildView,"CardsSummaryItems")

function CardsSummaryItems:New(go,reapData,matureNoReap)
    self = {}
    setmetatable(self,{__index = CardsSummaryItems})
    self._data = reapData
    self._matureNoReap = matureNoReap
    self:Init(go)
    return self
end

function CardsSummaryItems:Init(go)
    self._gameObject = go
    local ref = fun.get_component(go.transform,fun.REFER)
    if ref then
        self.content = ref:Get("content")
        self.img_reap = ref:Get("img_reap")
        --self.text_data = ref:Get("text_data")
    end
    --self.text_data.text = tostring(self._matureNoReap)

    if self._data then
        for k,v in pairs(self._data.cards) do
            local go = fun.get_instance(self.img_reap,self.content)
            if v.sign > 1 then
                local img = go:GetComponent(fun.IMAGE) --fun.get_component(go,fun.IMAGE)
                if img then
                    local sp_name, atlasName = "", "BingoAtlas"
                    if v.self_bingo then
                        sp_name, atlasName = self:GetSelfBingoSmallCellName(v.sign)
                    else
                        sp_name, atlasName = self:GetSmallCellName(v.sign)
                    end
                    img.sprite = AtlasManager:GetSpriteByName(atlasName, sp_name)
                end
            end
            fun.set_active(go,true,0)

            local x = math.modf((v.index-1)/5)
            local y = math.modf((v.index-1)%5)
            fun.set_gameobject_pos(go,25.375*x,-21.125*y,0,true)
        end
    end
    --self.img_reap.gameObject:SetActive(false)
end


function CardsSummaryItems:InitBingoAwards(parent)

end

function CardsSummaryItems:GetSmallCellName(sign)
    local playType = ModelList.BattleModel:GetGameType()
    if playType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        return sign == 3 and "WinzoneBvictoryX" or "WinzoneBbingoX", "WinZoneBattleAtlas"
    else
        return sign == 3 and "b_jackpot_small" or "b_bingo01_small", "BingoAtlas"
    end
end

---selfBingoÆå×Ó»»Æ¤
function CardsSummaryItems:GetSelfBingoSmallCellName(sign)
    local playType = ModelList.BattleModel:GetGameType()
    if playType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        --WinZone
        return sign == 3 and "WinzoneBvictoryX" or "WinzoneBbingopcardX", "WinZoneBattleAtlas"
    else
        return sign == 3 and "b_jackpot02_small" or "b_bingo02_small", "BingoAtlas"
    end
end

function CardsSummaryItems:OnDispose()
    self._gameObject = nil
    self.content = nil
    self.img_reap = nil
    --self.text_data = nil
    self._data = nil
    self._matureNoReap = nil
end

return CardsSummaryItems