---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/3/8 17:01
---


local  CardGuide = Clazz(ClazzBase,"CardGuide")
local this = CardGuide

function CardGuide:SetCardView(cardView)
    this.cardView = cardView
    this.model =  ModelList.BattleModel:GetCurrModel()
end


function CardGuide:DoGuideAction(cell ,num)
    if this.cardView.GuideAction then
        this.cardView.GuideAction(0, this:GetPath(cell))
    end
end

function CardGuide:GetPath(cell)
    local path= cell.transform.name
    local obj = cell
    while obj.transform.parent ~= nil do
        if obj.transform.parent.name == "NormalNode" then
            break
        end
        path = obj.transform.parent.name .."/"..path
        obj = obj.transform.parent
    end
    return path
end


function CardGuide.Register()
    Event.AddListener(EventName.Guide_Click_Card_Cell, this.DoGuideAction)
end

function CardGuide.UnRegister()
    Event.RemoveListener(EventName.Guide_Click_Card_Cell, this.DoGuideAction)
end


function CardGuide.OnDisable()
end


return this