---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/10/19 17:36
---

local GiftPackBaseView = require("View.GiftPack.GiftPackBaseView")
local  GiftPackRocketSingleView = GiftPackBaseView:New('GiftPackRocketSingleView', "GiftPackRocketAtlas")
local this = GiftPackRocketSingleView
this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
this.second_atlas_name = "GiftPackAtlas"

local data = nil
local click_interval = 0.5

this.auto_bind_ui_items = {
    "btn_close",
    "left_time_txt",
    "btn_buy",
    "text_time",
    "text_coin",
    "reward_type_icon",
    "reward_type_icon2",
    "GiftPackOneView",
    "buy_txt",
    "BonusOrMore",
    "cityExp"
}

function GiftPackRocketSingleView:Awake()
    this:on_init()
    self._isInit = true
    --- 修复部分机型首次进入界面不显示问题
    if self._reshowAfterInit then
        self._reshowAfterInit = nil
        self:ShowDetailGift()
    end
end

function GiftPackRocketSingleView.OnEnable()
    this:BuildFsm(this)
    this:Bi_Tracker()
end


local SetBuyBtnDescripe = function( btnObj ,des)
    if #des >0 and des ~="0" then
        local content = fun.find_child(btnObj,"Image/des")
        local txt = fun.get_component(content,"Text")
        if txt then
            txt.text = des
        end
        fun.set_active(content.transform.parent,true)
    else
        local content = fun.find_child(btnObj,"Image")
        fun.set_active(content,false)
    end
end

function GiftPackRocketSingleView:ShowDetailGift()
    if self._isInit then
        data = ModelList.GiftPackModel:GetShowGiftPack()
        this:SetProduct(data.pId,data.giftInfo)
        this:SetLeftTime(data.giftInfo[1].expireTime)
    else
        self._reshowAfterInit = true
    end
end

function GiftPackRocketSingleView:SetProduct(pId,giftInfo)
    local xls = nil
    for _,v in pairs(Csv.pop_up) do
        if v.gift_id == pId then
            for i = 1, #giftInfo do
                if giftInfo[i].id == _ then
                    xls = v
                    break
                end
            end
        end
    end
    local item1 = xls.item_description[1][1]
    --local icon1 = Csv.GetData("resources", tonumber(item1) ,'icon')
    local icon1 = Csv.GetItemOrResource( tonumber(item1),"icon")
	if self.reward_type_icon then
		self.reward_type_icon.sprite = AtlasManager:GetSpriteByName("ItemAtlas", icon1)
	end
    --this.text_time.text = xls.item_description[1][2]
    this:SetContent(item1,self.text_time,xls.item_description[1][2])
    local item2 = xls.item_description[2][1]
    --local icon2 = Csv.GetData("resources", tonumber(item2),"icon")
    local icon2 = Csv.GetItemOrResource( tonumber(item2),"icon")
    if self.reward_type_icon2 then
		self.reward_type_icon2.sprite = AtlasManager:GetSpriteByName("ItemAtlas", icon2)
	end
    --this.text_coin.text = xls.item_description[2][2]
    this:SetContent(item2,self.text_coin,xls.item_description[2][2])
    this:SetBtn(xls.price)
    this:SetBounsAndMore(xls.bonus,xls.more)

    SetBuyBtnDescripe(self.btn_buy,xls.limit_description)

    if data.giftInfo[1].canBuyCount <=0 then
        this:CloseUIShiny(self.btn_buy)
        Util.SetUIImageGray(self.btn_buy,true)
    elseif   this:OpenUIShiny(self.btn_buy) then
        Util.SetUIImageGray(self.btn_buy,false)
    end

    if #xls.item_description >= 3 then
        fun.set_active(this.cityExp, true)
        local item4 = xls.item_description[3][1]
        local vipexp = fun.find_child(this.cityExp, "vipexp")
        local text = fun.get_component(vipexp, "Text")
        this:SetContent(item4, text, xls.item_description[3][2])
    else
        fun.set_active(this.cityExp, false)
    end
end

function GiftPackRocketSingleView:SetLeftTime(endTimeStamp)
    local start_time = ModelList.PlayerInfoModel.get_cur_server_time()
    this.endTime = endTimeStamp - start_time
    if this.loopTime  then
        LuaTimer:Remove(this.loopTime)
        this.loopTime = nil
    end
    this.loopTime = LuaTimer:SetDelayLoopFunction(0, 1, -1, function()
        if self.left_time_txt then
            self.left_time_txt.text = fun.SecondToStrFormat(this.endTime)
            this.endTime = this.endTime - 1
            if this.endTime  <= 0 then
                this.on_btn_close_click()
                Event.Brocast(EventName.Event_Gift_Update)
            end
        end
    end,nil,nil,LuaTimer.TimerType.UI)
end

function GiftPackRocketSingleView:SetBtn(price)
    self.buy_txt.text = "$" .. price
end

function GiftPackRocketSingleView:SetBounsAndMore(bonus, more)
    if this.bonusAndMore == nil then
        this.bonusAndMore = require("View/GiftPack/GiftPackBonusAndMore")
    end
    this.bonusAndMore:SetData(self.BonusOrMore, bonus, more)
end

function GiftPackRocketSingleView:SetContent(id,txt,content)
    if not txt then
		return;
	end
	id = tonumber(id)
    if id == 3 then  --放大镜，不需要数字加逗号
        txt.text = content
    else
        txt.text = fun.formatNum(tonumber(content))
    end
end



function GiftPackRocketSingleView.OnDisable()
    --Facade.RemoveView(this)
    this:stop_x_update()
    --Event.Brocast(Notes.CARD_COLLIDER_OPEN, true)
end

function GiftPackRocketSingleView.OnDestroy()
    this:Destroy()
end

function GiftPackRocketSingleView:on_close()
    this:stop_x_update()
    --Event.Brocast(Notes.CARD_COLLIDER_OPEN, true)
end

function GiftPackRocketSingleView:CloseFunc()
    --this.main_effect:Play("end")
    Facade.SendNotification(NotifyName.HideDialog, this)

end

function GiftPackRocketSingleView:ShowTip(tipName)

end

function GiftPackRocketSingleView:InitTip()

end

function GiftPackRocketSingleView:CutDonwTarget()
    this:CloseFunc()
    this.main_effect:Play("end")
end

function GiftPackRocketSingleView:on_btn_sure_click()
    if this.sure_cb then
        this.sure_cb()
    end
    Facade.SendNotification(NotifyName.HideDialog, this)
    GameObject.Destroy(self.go)
    last_click_time = UnityEngine.Time.time
    --end
end

function GiftPackRocketSingleView:on_btn_cancle_click()
    if this.cancel_cb then
        this.cancel_cb()
    end
    Facade.SendNotification(NotifyName.HideDialog, this)
    GameObject.Destroy(self.go)
    last_click_time = UnityEngine.Time.time
    --end
end

function GiftPackRocketSingleView:on_btn_close_click()
    if this._fsm:GetCurName() == "GiftPackShowState" then return end
    if this.loopTime then
        LuaTimer:Remove(    this.loopTime)
        this.loopTime = nil
    end
    Facade.SendNotification(NotifyName.CloseUI, ViewList.GiftPackRocketSingleView)
    --fun.set_active(self.go,false)
    --GameObject.Destroy(self.go)
    ModelList.GiftPackModel:CloseView()

end
this.last_click_time = 0
function GiftPackRocketSingleView:on_btn_buy_click()
    if this._fsm:GetCurName() ~= "GiftPackEnterState" then return end
    local click_time = UnityEngine.Time.time
    if click_time - this.last_click_time > click_interval then
        ModelList.GiftPackModel:ReqEditorBuySucess(data.pId,data.giftInfo[1].id)
        this.last_click_time = UnityEngine.Time.time
    end
end

function  GiftPackRocketSingleView:OnBuySuccess(needClose,itemData)
    this:ChangeState(this,"GiftPackShowState",itemData)
    --if needClose then
    --    if fun.get_active_self(this.go) then
    --        this:ChangeState("GiftPackShowState",itemData)
    --    end
    --else
    --    this:ShowDetailGift()
    --end
end

function  GiftPackRocketSingleView:GetGiftPos(id)
    return this.text_time.transform.position,this.text_coin.transform.position,this.cityExp.transform.position,nil
end

return this
















