---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/10/19 17:36
---
local GiftPackBaseView = require("View.GiftPack.GiftPackBaseView")
local GiftPackDoubleView = GiftPackBaseView:New('GiftPackDoubleView',"GiftPackAtlas")
local this = GiftPackDoubleView
this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--this.second_atlas_name = "GiftPackAtlas"

local data =  nil
local product_list = {}
local canUpBuy = true
local canDownBuy = true
local click_interval = 0.5

this.auto_bind_ui_items = {
    "left_time_txt",
    "up_reward_txt2",
    "up_reward_txt1",
    "up_BonusOrMore",
    "btn_up_buy",
    "up_buy_txt",
    "down_BonusOrMore",
    "btn_down_buy",
    "GiftPackTwoView",
    "down_buy_txt",
    "down_reward_txt1",
    "down_reward_txt2",
    "up_reward_icon1",
    "up_reward_icon2",
    "down_reward_icon2",
    "down_reward_icon1",
    "btn_close",
    "cityExp1",
    "cityExp2"
}


function GiftPackDoubleView:Awake(obj)
    this:on_init()
    self._isInit = true
    --- 修复部分机型首次进入界面不显示问题
    if self._reshowAfterInit then
        self._reshowAfterInit = nil
        self:ShowDetailGift()
    end
end

function GiftPackDoubleView.OnEnable()
    --Facade.RegisterView(this)
    --this.update_x_enabled = true
    --this:start_x_update()
    this:BuildFsm(this)
    this:Bi_Tracker()
end

function GiftPackDoubleView:on_x_update()
end

function GiftPackDoubleView:ShowDetailGift()
    if self._isInit then
        data = ModelList.GiftPackModel:GetShowGiftPack()
        if data then
            this:CollectProduct(data.pId,data.giftInfo)
            this:SetUpProduct(product_list[1])
            this:SetDownProduct(product_list[2])
            this:SetLeftTime(data.giftInfo[1].expireTime)
        end
    else
        self._reshowAfterInit = true
    end
end




function GiftPackDoubleView:CollectProduct(pId,giftInfo)
    product_list = {}
    for _, v in pairs(Csv.pop_up) do
        if pId == v.gift_id then
            for i = 1, #giftInfo do
                if giftInfo[i].id == _ then
                    table.insert(product_list, v.id)
                    break
                end
            end
        end
    end
    table.sort(product_list)
end

local SetBuyBtnDescripe = function( btnObj ,des)
    if #des >0 and des ~="0" then
        local content = fun.find_child(btnObj,"Image/des")
        local txt = fun.get_component(content,"Text")
        if txt then
            txt.text = "$"..des
        end
        fun.set_active(content.transform.parent,true)
    else
        local content = fun.find_child(btnObj,"Image")
        fun.set_active(content,false)
    end
end

local SetCityExp = function( btnObj ,item_description,count)
    if #item_description >count-1 then
        fun.set_active(btnObj, true)
        local vipexp = fun.find_child(btnObj, "vipexp")
        local text = fun.get_component(vipexp, "Text")
        text.text = fun.formatNum( item_description[count][2] )
    else
        fun.set_active(btnObj, false)
    end
end

function GiftPackDoubleView.GetItemOrResource(id,param)
    if id > 1000 then
        return  Csv.GetData("item",id,param),"ItemAtlas"
    else
        return Csv.GetData("resources",id,"pop_up"),"CommonAtlas"
    end
end

function GiftPackDoubleView:SetUpProduct(id)
    local xls = Csv.GetData("pop_up", id)
    local item1 = xls.item_description[1][1]
    --local icon1 = Csv.GetData("resources", tonumber(item1), 'icon')
    local icon1 ,atlasName = self.GetItemOrResource( tonumber(item1),"icon")
    self.up_reward_icon1.sprite = AtlasManager:GetSpriteByName(atlasName, icon1)
    this:SetContent(item1,self.up_reward_txt1,xls.item_description[1][2])
    local item2 = xls.item_description[2][1]
    --local icon2 = Csv.GetData("resources", tonumber(item2) ,'icon')
    local icon2,atlasName = self.GetItemOrResource( tonumber(item2),"icon")
    self.up_reward_icon2.sprite = AtlasManager:GetSpriteByName(atlasName, icon2)
    this:SetContent(item2,self.up_reward_txt2,xls.item_description[2][2])
    self.up_buy_txt.text = "$"..xls.price
    canUpBuy = true
    local data = ModelList.GiftPackModel:GetGiftById(id)
    if data.canBuyCount <=0 then
        this:CloseUIShiny(self.btn_up_buy)
        Util.SetUIImageGray(self.btn_up_buy,true)
        canUpBuy = false
    elseif  this:OpenUIShiny(self.btn_up_buy) then
        Util.SetUIImageGray(self.btn_up_buy,false)
    end
    this:SetBounsAndMore(self.up_BonusOrMore,xls.bonus,xls.more)
    SetBuyBtnDescripe(self.btn_up_buy,xls.limit_description)
    SetCityExp(this.cityExp1,xls.item_description,3)
end

function GiftPackDoubleView:SetDownProduct(id)
    local xls = Csv.GetData("pop_up", id)
    local item1 = xls.item_description[1][1]
    --local icon1 = Csv.GetData("resources", tonumber(item1) ,'icon')
    local icon1,atlasName = self.GetItemOrResource( tonumber(item1),"icon")
    self.down_reward_icon1.sprite = AtlasManager:GetSpriteByName(atlasName, icon1)
    --this.down_reward_txt1.text = xls.item_description[1][2]
    this:SetContent(item1,self.down_reward_txt1,xls.item_description[1][2])
    local item2 = xls.item_description[2][1]
    --local icon2 = Csv.GetData("resources", tonumber(item2),"icon")
    local icon2,atlasName = self.GetItemOrResource( tonumber(item2),"icon")
    self.down_reward_icon2.sprite = AtlasManager:GetSpriteByName(atlasName, icon2)
    self.down_reward_txt2.text = xls.item_description[2][2]
    this:SetContent(item2,self.down_reward_txt2,xls.item_description[2][2])
    self.down_buy_txt.text = "$"..xls.price
    canDownBuy = true
    local data = ModelList.GiftPackModel:GetGiftById(id)

    if data.canBuyCount <=0 then
        this:CloseUIShiny(self.btn_down_buy)
        Util.SetUIImageGray(self.btn_down_buy,true)
        canDownBuy = false
    elseif   this:OpenUIShiny(self.btn_down_buy) then
        Util.SetUIImageGray(self.btn_down_buy,false)
    end
    this:SetBounsAndMore(self.down_BonusOrMore,xls.bonus,xls.more)
    SetBuyBtnDescripe(self.btn_down_buy,xls.limit_description)
    SetCityExp(this.cityExp2,xls.item_description,3)
end

function GiftPackDoubleView:SetLeftTime(endTimeStamp)
    local start_time = ModelList.PlayerInfoModel.get_cur_server_time()
    this.endTime = endTimeStamp - start_time
    if this.loopTime  then
        LuaTimer:Remove(this.loopTime)
        this.loopTime = nil
    end
    this.loopTime  = LuaTimer:SetDelayLoopFunction(0, 1, -1, function()
        if self.left_time_txt then
            self.left_time_txt.text = fun.SecondToStrFormat(this.endTime)
            this.endTime = this.endTime - 1
            if this.endTime  <= 0 then
                this.on_btn_close_click()
                Event.Brocast(EventName.Event_Gift_Update)
            end
        end
    end,nil,nil,LuaTimer.TimerType.UI)
end

function GiftPackDoubleView:SetContent(id,txt,content)
    id = tonumber(id)
    if id == 3  then  --放大镜，不需要数字加逗号
        txt.text = content
    else
        txt.text = fun.formatNum((content))
    end
end

function GiftPackDoubleView:SetBounsAndMore(obj, bonus, more)
    if this.bonusAndMore == nil then
        this.bonusAndMore = require("View/GiftPack/GiftPackBonusAndMore")
    end
    ----log.r("type  22 "..type(bonus).."    "..type(more))
    this.bonusAndMore:SetData(obj, bonus, more)
end


function GiftPackDoubleView.OnDisable()
    --Facade.RemoveView(this)
    this:stop_x_update()
    --Event.Brocast(Notes.CARD_COLLIDER_OPEN,true)
end


function GiftPackDoubleView.OnDestroy()
    this:Destroy()
end

function GiftPackDoubleView:on_close()
    this:stop_x_update()
    --Event.Brocast(Notes.CARD_COLLIDER_OPEN,true)
end

function GiftPackDoubleView:CloseFunc()
    --this.main_effect:Play("end")
    Facade.SendNotification(NotifyName.CloseUI, this)

end


function GiftPackDoubleView:CutDonwTarget()
    this:CloseFunc()
    this.main_effect:Play("end")
end

function GiftPackDoubleView:on_btn_close_click()
    if this._fsm:GetCurName() == "GiftPackShowState" then return end
    if this.loopTime then
        LuaTimer:Remove(    this.loopTime)
        this.loopTime = nil
    end
    Facade.SendNotification(NotifyName.CloseUI, ViewList.GiftPackDoubleView)
    ModelList.GiftPackModel:CloseView()
end

this.last_click_time1 = 0
function GiftPackDoubleView:on_btn_up_buy_click()
    if this._fsm:GetCurName() ~= "GiftPackEnterState" then return end
    if canUpBuy then
        local click_time = UnityEngine.Time.time
        if click_time - this.last_click_time1 > click_interval then
            ModelList.GiftPackModel:ReqEditorBuySucess(data.pId,product_list[1])
            this.last_click_time1 = UnityEngine.Time.time
        end
    else
        UIUtil.show_common_popup(8020,true)
    end
end


this.last_click_time2 = 0
function GiftPackDoubleView:on_btn_down_buy_click()
    if this._fsm:GetCurName() ~= "GiftPackEnterState" then return end
    if canDownBuy then
        local click_time = UnityEngine.Time.time
        if click_time - this.last_click_time2 > click_interval then
            ModelList.GiftPackModel:ReqEditorBuySucess(data.pId,product_list[2])
            this.last_click_time2 = UnityEngine.Time.time
        end
        --this:on_btn_close_click()
    else
        --Facade.SendNotification(NotifyName.Common.PopupDialog, 8020, 1);
        UIUtil.show_common_popup(8020,true)
    end
end

function GiftPackDoubleView:CloseUIShiny(obj)
    local uishiny = fun.get_component(obj,"UIShiny")
    if uishiny then
        uishiny.enabled = false
    end
end


function  GiftPackDoubleView:OnBuySuccess(needClose,itemData)
    this:ChangeState(this,"GiftPackShowState",itemData)
end

function  GiftPackDoubleView:GetGiftPos(id)
    if id == product_list[1] then
        local vipexp = fun.find_child(this.cityExp1, "vipexp")
        return fun.get_gameobject_pos(this.up_reward_txt1,false), fun.get_gameobject_pos(this.up_reward_txt2,false),
        fun.get_gameobject_pos(vipexp,false), nil
    elseif id == product_list[2] then
        local vipexp = fun.find_child(this.cityExp2, "vipexp")
        return fun.get_gameobject_pos(this.down_reward_icon1,false), fun.get_gameobject_pos(this.down_reward_icon2,false), fun.get_gameobject_pos(vipexp,false), nil
    else
        local vipexp = fun.find_child(this.cityExp1, "vipexp")
        return fun.get_gameobject_pos(this.br_reward_txt,false),fun.get_gameobject_pos(this.br_cost_txt,false),
        fun.get_gameobject_pos( vipexp,false),nil
    end
end

return this




















