---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/27 14:11
---

local PayLoadingView = BaseView:New("PayLoadingView","NewPayAtlas")
local this = PayLoadingView
this.viewType = CanvasSortingOrderManager.LayerType.Tips

this.auto_bind_ui_items = {
    "btn_close",
    "loading",
    "Frame",
    "btn_continue_pay",
    "btn_completed",
    "Price",
    "SafeArea",
    "actionPart",
    "loadingPanel",
    "loadingAnima",
    "productName",
}

function PayLoadingView:Awake()
    self:on_init()
    self.openTime = os.time()
end

function PayLoadingView:OnEnable(params)
    self:Register()
    self.preGetResult = false
    self.tryGetSignature = false
    self.paySuccess = false
    if params then
        LuaFramework.GameManager.ShowMainPay(params.payExtra,PurchaseHelper.WebviewCallBack)

        local productItem = self:GetProductName()
        if productItem ~= nil then
            self.productName.text = productItem
        end
        SDK.TrackWebEvent("web_view_open",{
            balancecoin = ModelList.ItemModel.get_coin(),
            balancediamond = ModelList.ItemModel.get_diamond(),
            price = self:GetPrice(),
            itemid = productItem,
        })
        self.enableData = deep_copy(params)
        if self and fun.is_not_null(self.Price) then
            self.Price.text = self.enableData.data.price
        elseif fun.is_not_null(this.Price) then
            this.Price.text = self.enableData.data.price
        end
    end
    Facade.SendNotification(NotifyName.ShopView.CloseLoadingView)
    ---测试代码
    --self.showTime = os.time()
    --fun.set_active(self.go,false)
end

function PayLoadingView:GetProductName()
    local type,product_name = PurchaseHelper.GetPurchasingInfo()
    local productItem
    if type == 1 then
        if ModelList.MainShopModel.cacheShopItemId then
            local productId = Csv.GetData("shop", ModelList.MainShopModel.cacheShopItemId, "product_id")
            if productId then
                productItem = Csv.GetData("appstorepurchaseconfig", productId, "product_name")
            end
        end
    elseif type == 2 then
        local productId = Csv.GetData("pop_up", PurchaseHelper.save_shopItem.id, "product_id")
        if productId then
            productItem = Csv.GetData("appstorepurchaseconfig", productId, "product_name")
        end
    else
        if product_name then
            productItem = product_name
        end
    end
    return productItem
end

function PayLoadingView:on_btn_close_click()
    if self.showTime and os.time() - self.showTime >= 3 then
        --Facade.SendNotification(NotifyName.CloseUI, self)
        self:TryOrderVerification()
        self:Report(3)
    end
end

function PayLoadingView:on_btn_continue_pay_click()
    if self.showTime and os.time() - self.showTime >= 3 then
        ModelList.PlayerInfoModel:C2SPing(function(success)
            if success then
                if  self.enableData then
                    if(Network.isConnect) then
                        LuaFramework.GameManager.ShowMainPay( self.enableData.payExtra,PurchaseHelper.WebviewCallBack)
                        local productItem = self:GetProductName()
                        SDK.TrackWebEvent("web_view_open",{
                            balancecoin = ModelList.ItemModel.get_coin(),
                            balancediamond = ModelList.ItemModel.get_diamond(),
                            price = self:GetPrice(),
                            itemid = productItem,
                        })
                        self:Report(1)
                    end
                end
            end
        end)
    end
end

function PayLoadingView:on_btn_completed_click()
    if self.showTime and os.time() - self.showTime >= 3 then
        self:TryOrderVerification()
        self:Report(2)
    end
end


function PayLoadingView:ShowLoading()
    self:WaitLoadingEffect()
end

--- 启动超时等待
function PayLoadingView:WaitLoadingEffect()
    fun.set_active(self.loading,true)
    self.waitTimer = LuaTimer:SetDelayFunction(10,function()
        fun.set_active(self.loading,false)
        self.waitTimer = nil
    end)
end


function PayLoadingView:on_close()
    LuaFramework.GameManager.CloseMainPay()
    if self.waitTimer then
        LuaTimer:Remove(self.waitTimer)
        self.waitTimer = nil
    end
    if self.delayLoadingAnima then
        LuaTimer:Remove(self.delayLoadingAnima)
        self.delayLoadingAnima = nil
    end

    self:UnRegister()
end

function PayLoadingView:PayResult(result)
    if result then
        fun.set_active(self.btn_continue_pay,false)
        if fun.is_not_null(self.btn_completed) then
            local pos = fun.get_localposition(self.btn_completed)
            self.btn_completed.transform.localPosition = Vector3.New(0, pos.y , 0)
        end
        self.paySuccess = true
        if PurchaseHelper.extraData then
            local extraData = (PurchaseHelper.extraData)
            if extraData then
                self.payment_method = extraData.data.payMethod
            end
        end
    end
end

function PayLoadingView:CloseWebView()
    --- 播放等待
    fun.set_active(self.SafeArea,true)
    if self.paySuccess then
        self.showTime = os.time()
        self.loadingAnima.enabled = true
    else
        self.showTime = 0
    end

    if fun.is_not_null(self.actionPart) then
        self.actionPart.alpha = 1
    end
    self.delayLoadingAnima = LuaTimer:SetDelayFunction(3,function()
        if fun.is_not_null(self.loadingAnima) then
            self.loadingAnima.enabled = false
            self.delayLoadingAnima = nil
        end
    end)

    local productItem = self:GetProductName()
    SDK.TrackWebEvent("web_view_wait_open",{
        price = self:GetPrice(),
        itemid = productItem,
    })
end

function PayLoadingView:ActiveView()
    fun.set_active(self.SafeArea,true)

end
--- 3003返回验证
function PayLoadingView:PaySignatureResult(code,data)
    --- 当前订单,非主动请求验签,缓存起来
    if data and data.pid and self.enableData and not self.tryGetSignature and data.pid == self.enableData.data.pid and not self.preGetResult then
        self.preGetResult = true
        self.preCode = code
        self.preData = data
        --- 已经收到,重置支付状态
        PurchaseHelper.payResult = 0
        --- 重置支付成功/失败回调
        ModelList.MainShopModel.ResetNewPayCallBack(nil,nil)
    end
end

--- 播放转圈等待网络返回表现
function PayLoadingView:WaitSignatureVerification()
    if self.luaDelay then
        LuaTimer:Remove(self.luaDelay)
        self.luaDelay = nil
    end
    fun.set_active(self.loadingPanel,true)
    self.luaDelay = LuaTimer:SetDelayFunction(5,function()
        fun.set_active(self.loadingPanel,false)
    end)
    self.tryGetSignature = true
end

local function PaySuccess()
    PurchaseHelper.IAP_success_cb()
    Facade.SendNotification(NotifyName.CloseUI, this)
end

local function PayFail(code)
    if code == -99 then --网络问题,

    elseif code == 1045 then  -- 已经下发了
        Facade.SendNotification(NotifyName.CloseUI, this)
    else
        Facade.SendNotification(NotifyName.ShowUI,ViewList.PayResultView)
        Facade.SendNotification(NotifyName.CloseUI, this)
    end
end


function PayLoadingView:TryOrderVerification()
    if PurchaseHelper.payResult and PurchaseHelper.payResult == 1 then
        --PurchaseHelper.payResult = 0
        --PurchaseHelper.IAP_success_cb()
        self:WaitSignatureVerification()
        ModelList.MainShopModel.C2S_NotifyServerIAPSuccess(nil,self.enableData.data.id, self.enableData.data.pid, nil, nil, nil,
                PaySuccess,
                PayFail
        )
    elseif self and self.preGetResult then ---提前获得数据,关闭后直接表现
        ModelList.MainShopModel.ResetNewPayCallBack(
                PaySuccess,
                PayFail)
        Message.DispatchMessage(3003, self.preCode,self.preData);
    else
        --- 未支付,关闭界面
        ModelList.MainShopModel.Purchasing_failure_new()
        PurchaseHelper.IAP_failure_cb()
        Facade.SendNotification(NotifyName.CloseUI, this)
    end
end


--- click_type 1:Later 2:contact us 3:关闭弹窗
--- 上报对应的支付方式,获取到明确的
function PayLoadingView:Report(click_type)
    local productItem = self:GetProductName()
    local web_open_type = 1
    if self.paySuccess then web_open_type = 2 end
    SDK.TrackWebEvent("web_view_wait_click",{
        payment_method = self.payment_method or "",
        web_open_type = web_open_type,
        click_type = click_type,
        price = self:GetPrice(),
        itemid = productItem,
        payment_waittime =  os.time() - self.openTime,
    })
end

function PayLoadingView:GetPrice()
    if PurchaseHelper.save_data then
        if PurchaseHelper.save_data.price then
            return PurchaseHelper.save_data.price
        elseif PurchaseHelper.save_data.currency then
            return PurchaseHelper.save_data.currency
        elseif PurchaseHelper.save_data.data then
            if PurchaseHelper.save_data.data.price then
                return PurchaseHelper.save_data.data.price
            elseif PurchaseHelper.save_data.data.currency then
                return PurchaseHelper.save_data.data.currency
            end
        end
    end
    return 0
end


function PayLoadingView:Register()
    Event.AddListener(EventName.Event_New_Pay_Result,self.PayResult,self)
    Event.AddListener(EventName.Event_Close_Web_View,self.CloseWebView,self)
    Event.AddListener(EventName.Event_Show_Pay_Loading_View,self.ActiveView,self)
    Event.AddListener(EventName.Event_New_Pay_Signature_Result,self.PaySignatureResult,self)
end

function PayLoadingView:UnRegister()
    Event.RemoveListener(EventName.Event_New_Pay_Result,self.PayResult,self)
    Event.RemoveListener(EventName.Event_Close_Web_View,self.CloseWebView,self)
    Event.RemoveListener(EventName.Event_Show_Pay_Loading_View,self.ActiveView,self)
    Event.RemoveListener(EventName.Event_New_Pay_Signature_Result,self.PaySignatureResult,self)
end

return this

