---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/7/9 17:48
---

---@短令牌任务完成

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder,"")
local this = PopupOrder

function PopupOrder.Execute(arg)
    local currId = ModelList.GameActivityPassModel.GetCurrentId()
    local taskList = ModelList.GameActivityPassModel.GetTaskData(currId)
    if taskList then
        local hasReard = false
        for i = 1, #taskList do
            if taskList[i].completed  and  not taskList[i].rewarded then
                hasReard = true
                break
            end
        end
        if hasReard then
            Event.AddListener(EventName.Event_popup_PopupShortPass_finish,PopupOrder.Finish,this)
            --Facade.SendNotification(NotifyName.ShowUI,ViewList.TaskView,nil,nil,false)
            Facade.SendNotification(NotifyName.GamePlayShortPassView.ShowGamePlayShortPassView,"PassTaskView")
            return
        end
    end
    PopupOrder.Finish()

end

function PopupOrder.Finish()
    Event.RemoveListener(EventName.Event_popup_PopupShortPass_finish,PopupOrder.Finish,this)
    log.g("brocast  EventName.Event_popup_order_finish ")
    Event.Brocast(EventName.Event_popup_order_finish,true)
end

return PopupOrder