---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/6/16 15:53
---


---- 小丑卡吹吹卷入场效果

local BaseCardJokerEffect  =  require("View.Bingo.EffectModule.CardJoker.BaseCardJokerEffect")

local JokerBlowRollEnterEffect = BaseCardJokerEffect:New()
local this = JokerBlowRollEnterEffect

function JokerBlowRollEnterEffect:New()
    local o = { isLoaded = false, changeSceneClear = true,direction =nil ,targetCell = nil, objTable = {},directionTable = {}}
    self.__index = self
    setmetatable(o, self)
    return o
end

local function SetBlowScaleByPlayId(obj)
    local playId = ModelList.BattleModel:GetGameCityPlayID()
    local scale = Csv.GetData("game_joker_setting",playId,"blow_roll_scale")  or 1
    fun.set_gameobject_scale(obj,scale,scale,scale)
end

---基类继承
function JokerBlowRollEnterEffect:SetInfo(info,parentObj,parentRef)
    self.data = info
    local obj1 = parentRef:GetPreloadPrefab("clowndaoju_juanjuana")
    local obj2 = parentRef:GetPreloadPrefab("clowndaoju_juanjuanb")
    local targetObj = nil
    for i = 1, #self.data.cardPowerUpEffect do
        local prefabName = "clowndaoju_juanjuana"
        targetObj = obj1
        if self.data.cardPowerUpEffect[i].posList and #self.data.cardPowerUpEffect[i].posList == 3 then
            prefabName = "clowndaoju_juanjuanb"
            targetObj = obj2
        end
        if targetObj then
            local newobj = fun.get_instance(targetObj)
            if newobj then
                fun.set_parent(newobj,parentObj,true)
                table.insert(self.objTable,newobj)
                SetBlowScaleByPlayId(newobj)
            end
        else
            Cache.load_prefabs(AssetList[prefabName],prefabName,function (prefab)
                if prefab then
                    local obj = fun.get_instance(prefab)
                    if obj then
                        fun.set_parent(obj,parentObj,true)
                        table.insert(self.objTable,obj)
                        SetBlowScaleByPlayId(obj)
                    end
                end
            end)
        end
    end

end

--- 播放吹吹卷入场效果
function JokerBlowRollEnterEffect:Play()
    if self.objTable and #self.objTable > 0 then
        for i = 1, #self.objTable do
            fun.set_active(self.objTable[i],true)
        end
    end
    LuaTimer:SetDelayFunction(1,function ()
        self:Fly()
    end)
end

function JokerBlowRollEnterEffect:Fly()
    if self.objTable and #self.objTable > 0 then
        for i = 1, #self.objTable do
            local direction =  self:GetBlowDirection(self.data.cardPowerUpEffect[i].posList)
            table.insert(self.directionTable,direction)
            local clientPos = ConvertServerPos(direction.firstPos)
            for m = 1, #self.data.cardPowerUpEffect[i].posList do
                local localPos = ConvertServerPos(self.data.cardPowerUpEffect[i].posList[m])
                self:SetCellChange(self.data.cardPowerUpEffect[i].cardId,localPos,3,clientPos,direction,self.data.cardPowerUpEffect[i].posList)
            end
             local targetCell = self:GetJokerCellObj(self.data.cardPowerUpEffect[i].cardId, clientPos)
            if targetCell then
                fun.set_parent(self.objTable[i],targetCell.transform)
                Anim.move(self.objTable[i],0,0,0,1,true,1,function ()
                    self:PlayRotate(i)
                    self:PlayEffect(targetCell)
                end)
            end
        end
    end


end


function JokerBlowRollEnterEffect:PlayEffect(targetCell)
    Cache.load_prefabs(AssetList["clowndaoju_getxiao"],"clowndaoju_getxiao",function (prefab)
        if prefab then
            local obj = fun.get_instance(prefab)
            if obj  then
                if targetCell then
                    fun.set_parent(obj,targetCell.transform,true)
                end
                fun.set_active(obj,true)
                SetBlowScaleByPlayId(obj)
                Destroy(obj,2)
            end
        end
    end)
end



function JokerBlowRollEnterEffect:PlayRotate(index)
    local animator = fun.get_component(self.objTable[index] ,fun.ANIMATOR)
    local direction = self.directionTable[index]
    if animator and direction then
        if direction.direction == 1 then
            animator:Play("up")
        elseif direction.direction == 2 then
            animator:Play("down")
        elseif direction.direction == 3 then
            animator:Play("left")
        elseif direction.direction == 4 then
            animator:Play("right")
        end
        LuaTimer:SetDelayFunction(0.3,function ()
            self:PlayOver()
        end)
    else
        self:PlayOver()
    end
end

function JokerBlowRollEnterEffect:PlayOver()
    --log.r("JokerBallSprayerEnterEffect:PlayOver")
end

---根据方位获取朝向
---始终保持朝向卡牌中心
function JokerBlowRollEnterEffect:GetBlowDirection(posList)
    local costMin = 100
    local costMax = 0
    local direction = {firstPos = 0,direction = 0 }
    local maxCostPos = 0
    local minCostPos = 0
    for i = 1, #posList do
        local x = math.floor(posList[i]/10)
        local y = posList[i]%10
        local cost = math.abs(x - 3) + math.abs(y - 3)
        if cost < costMin then
            costMin = cost
            minCostPos = posList[i]
        end
        if cost > costMax then
            costMax = cost
            direction.firstPos = posList[i]
            maxCostPos = posList[i]
        end
    end
    ---计算四个朝向，1：上，2：下，3：左，4：右
    local maxPosCostX = math.floor(direction.firstPos/10)
    local maxPosCostY = direction.firstPos%10
    local minPosCostX = math.floor( minCostPos/10)
    local minPosCostY =  minCostPos%10
    if maxPosCostX - minPosCostX == 0 then
        if maxPosCostY - minPosCostY > 0 then
            direction.direction = 2
        else
            direction.direction = 1
        end
    else
        if maxPosCostX - minPosCostX > 0 then
            direction.direction = 4
        else
            direction.direction = 3
        end
    end
    --log.r("direction.direction"..direction.direction)
    --log.r("direction.firstPos"..direction.firstPos)
    return direction
end

---预加载依赖的资源
function JokerBlowRollEnterEffect:PreloadDependResource(callBack,callback2,index)
    --Cache.load_prefabs(AssetList["clowndaoju_juanjuana"], "clowndaoju_juanjuana", function(prefab)
    --    Cache.load_prefabs(AssetList["clowndaoju_juanjuanb"], "clowndaoju_juanjuanb", function(prefab)
    --        Cache.load_prefabs(AssetList["clowndaoju_getxiao"], "clowndaoju_getxiao", function(prefab)
    --            if callBack then
    --                callBack()
    --            end
    --        end)
    --    end)
    --end)

    this:CoroutineLoadResource(function()
        --coroutine.wait(index)
        Cache.load_prefabs(AssetList["clowndaoju_juanjuana"], "clowndaoju_juanjuana", function(prefab)
            if prefab then
                local instance = fun.get_instance(prefab)
                log.r("instance clowndaoju_juanjuana")
                if callback2 then
                    callback2(instance,"clowndaoju_juanjuana")
                end
            end
        end)
        --coroutine.wait(0.5)
        --WaitForFixedUpdate()
        Cache.load_prefabs(AssetList["clowndaoju_juanjuanb"], "clowndaoju_juanjuanb", function(prefab)
            if prefab then
                local instance = fun.get_instance(prefab)
                log.r("instance clowndaoju_juanjuanb")
                if callback2 then
                    callback2(instance,"clowndaoju_juanjuanb")
                end
            end
        end)
        --coroutine.wait(0.5)
        --WaitForFixedUpdate()
        Cache.load_prefabs(AssetList["clowndaoju_getxiao"], "clowndaoju_getxiao", function(prefab)
            if prefab then
                local instance = fun.get_instance(prefab)
                log.r("instance clowndaoju_getxiao")
                if callback2 then
                    callback2(instance,"clowndaoju_getxiao")
                end
            end
        end)
        if callBack then
            callBack()
        end
    end)


end

return this