---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/18 16:34
---


local ExitState = Clazz(BaseFsmState, "ExitState")
local this = ExitState

function ExitState:New()
    local o = {}
    setmetatable(o, { __index = ExitState })
    return o
end

function ExitState:ExitState()
end

function ExitState:OnEnter(fsm, previous )
    self._fsm = fsm
end

function ExitState:OnSpin()

end

function ExitState:OnReceiveSpin()
end


function ExitState:OnChangeBet(changeType)

end
function ExitState:OnStopIdle()

end

function ExitState:OnResumeIdle()

end


function ExitState:OnLeave(fsm)
    self._fsm = nil
    self._owner = nil
end

function ExitState:Dispose()
    self:OnLeave(nil)
end

return this
