---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/4/2 15:42
---

local Command = {}

function Command.Execute(notifyName,scene_name,callback)
    UISound.stop("pop")
    UISound.unload_loading_res()
    local city = ModelList.CityModel:GetCity()
    --local atlas = string.format("City%sBattleIngredientAtlas",city)
    --Cache.unload_ab(AssetList[atlas])
    Cache.unload_ab(AssetList["BingoAtlas"])
    Cache.unload_ab(AssetList["SettleAtlas"])
    AssetManager.unload_game_res()

    local gameType = ModelList.BattleModel:GetGameType()
    local loadingView = ViewList.SceneLoadingGameView
    if gameType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        loadingView = ViewList.WinZoneLoadingGameView
    end
    Facade.SendNotification(NotifyName.CloseUI, loadingView)
end

return Command