--auto generate by C# editor: Tools/自动生成AssetList.lua脚本
local AssetList = {}
local this = AssetList
------------------asset map,key to assetbundle_name-----------------
----------------------------Assets\Bundles\Modules------------------------------------------
this.FunctionIconMoneyMansion = "modules/gotyou/inhotmodule/abprefab/functioniconmoneymansion"
this.GotYouBingoView = "modules/gotyou/inhotmodule/abprefab/gotyoubingoview"
this.GotYouHallView = "modules/gotyou/inhotmodule/abprefab/gotyouhallview"
this.GotYouHelpView = "modules/gotyou/inhotmodule/abprefab/gotyouhelpview"
this.GotYouJackpot = "modules/gotyou/inhotmodule/abprefab/gotyoujackpot"
this.GotYouJackpotHelperView = "modules/gotyou/inhotmodule/abprefab/gotyoujackpothelperview"
this.GotYouReadyView = "modules/gotyou/inhotmodule/abprefab/gotyoureadyview"
this.GotYouSettleView = "modules/gotyou/inhotmodule/abprefab/gotyousettleview"
this.Play32HallBackground = "modules/gotyou/inhotmodule/abprefab/play32hallbackground"
this.play32zhandou = "modules/gotyou/inhotmodule/abprefab/play32zhandou"
this.FunctionIcon = "modules/gotyou/inhotmodule/abprefab/pass/functionicon"
this.GiftPackGotYouBuffView = "modules/gotyou/inhotmodule/abprefab/pass/giftpackgotyoubuffview"
this.PassHelperView = "modules/gotyou/inhotmodule/abprefab/pass/passhelperview"
this.PassPurchaseView = "modules/gotyou/inhotmodule/abprefab/pass/passpurchaseview"
this.PassReceivedView = "modules/gotyou/inhotmodule/abprefab/pass/passreceivedview"
this.PassRewardView = "modules/gotyou/inhotmodule/abprefab/pass/passrewardview"
this.PassShowTipView = "modules/gotyou/inhotmodule/abprefab/pass/passshowtipview"
this.PassTaskView = "modules/gotyou/inhotmodule/abprefab/pass/passtaskview"
this.PassView = "modules/gotyou/inhotmodule/abprefab/pass/passview"
this.Rewarditem = "modules/gotyou/inhotmodule/abprefab/pass/rewarditem"
this.GotYouSmallGameHelpView = "modules/gotyou/inhotmodule/abprefab/smallgame/gotyousmallgamehelpview"
this.GotYouSmallGameView = "modules/gotyou/inhotmodule/abprefab/smallgame/gotyousmallgameview"
this.PigDjsMoon2 = "modules/gotyou/inhotmodule/texture/abtexture/pigdjsmoon2"
this.PigDjsYun01 = "modules/gotyou/inhotmodule/texture/abtexture/pigdjsyun01"
this.PigDlpBg = "modules/gotyou/inhotmodule/texture/abtexture/pigdlpbg"
this.PigGameBG02 = "modules/gotyou/inhotmodule/texture/abtexture/piggamebg02"
this.PigGameBG04 = "modules/gotyou/inhotmodule/texture/abtexture/piggamebg04"
this.SceneGotYou = "modules/gotyou/inhotmodule/scene/scenegotyou"
this.GotYouBingobingo = "modules/gotyou/inhotmodule/effect/abprefab/gotyoubingobingo"
this.GotYouBingobingoClown = "modules/gotyou/inhotmodule/effect/abprefab/gotyoubingobingoclown"
this.GotYouEmpty = "modules/gotyou/inhotmodule/effect/abprefab/gotyouempty"
this.GotYougetxiaoka = "modules/gotyou/inhotmodule/effect/abprefab/gotyougetxiaoka"
this.GotYouskill01get = "modules/gotyou/inhotmodule/effect/abprefab/gotyouskill01get"
this.GotYouWolf = "modules/gotyou/inhotmodule/effect/abprefab/gotyouwolf"
this.GotYouWolfweiba = "modules/gotyou/inhotmodule/effect/abprefab/gotyouwolfweiba"
this.GiftPackGotYouBuffAtlas = "modules/gotyou/inhotmodule/atlas/giftpackgotyoubuffatlas"
this.GotYouBingoAtlas = "modules/gotyou/inhotmodule/atlas/gotyoubingoatlas"
this.GotYouHallAtlas = "modules/gotyou/inhotmodule/atlas/gotyouhallatlas"
this.GotYouJackpotHelperAtlas = "modules/gotyou/inhotmodule/atlas/gotyoujackpothelperatlas"
this.GotYouPassTaskAtlas = "modules/gotyou/inhotmodule/atlas/gotyoupasstaskatlas"
this.GotYouPopupAtlas = "modules/gotyou/inhotmodule/atlas/gotyoupopupatlas"
this.GotYouPurchaseAtlas = "modules/gotyou/inhotmodule/atlas/gotyoupurchaseatlas"
this.GotYouSmallGameAtlas = "modules/gotyou/inhotmodule/atlas/gotyousmallgameatlas"
this.GotYouSmallGameGuideAtlas = "modules/gotyou/inhotmodule/atlas/gotyousmallgameguideatlas"
this.GotYouSmallGameHelpAtlas = "modules/gotyou/inhotmodule/atlas/gotyousmallgamehelpatlas"

return this
