--auto generate by C# editor: Tools/自动生成AssetList.lua脚本
local AssetList = {}
local this = AssetList
------------------asset map,key to assetbundle_name-----------------
----------------------------Assets\Bundles\Modules------------------------------------------
this.HorseRacingBingoView = "modules/horseracing/inhotmodule/abprefab/horseracingbingoview"
this.HorseRacingHallView = "modules/horseracing/inhotmodule/abprefab/horseracinghallview"
this.HorseRacingHelpView = "modules/horseracing/inhotmodule/abprefab/horseracinghelpview"
this.HorseRacingJackpot = "modules/horseracing/inhotmodule/abprefab/horseracingjackpot"
this.HorseRacingReadyView = "modules/horseracing/inhotmodule/abprefab/horseracingreadyview"
this.HorseRacingSettleView = "modules/horseracing/inhotmodule/abprefab/horseracingsettleview"
this.Play28HallBackground = "modules/horseracing/inhotmodule/abprefab/play28hallbackground"
this.play28zhandou = "modules/horseracing/inhotmodule/abprefab/play28zhandou"
this.FunctionIcon = "modules/horseracing/inhotmodule/abprefab/pass/functionicon"
this.GiftPackHorseRacingBuffView = "modules/horseracing/inhotmodule/abprefab/pass/giftpackhorseracingbuffview"
this.PassHelperView = "modules/horseracing/inhotmodule/abprefab/pass/passhelperview"
this.PassPurchaseView = "modules/horseracing/inhotmodule/abprefab/pass/passpurchaseview"
this.PassReceivedView = "modules/horseracing/inhotmodule/abprefab/pass/passreceivedview"
this.PassRewardView = "modules/horseracing/inhotmodule/abprefab/pass/passrewardview"
this.PassShowTipView = "modules/horseracing/inhotmodule/abprefab/pass/passshowtipview"
this.PassTaskView = "modules/horseracing/inhotmodule/abprefab/pass/passtaskview"
this.PassView = "modules/horseracing/inhotmodule/abprefab/pass/passview"
this.Rewarditem = "modules/horseracing/inhotmodule/abprefab/pass/rewarditem"
this.GoldRushDlpBg = "modules/horseracing/inhotmodule/texture/abtexture/goldrushdlpbg"
this.GreenLPBG = "modules/horseracing/inhotmodule/texture/abtexture/greenlpbg"
this.SceneHorseRacing = "modules/horseracing/inhotmodule/scene/scenehorseracing"
this.HorseRacingBingobingo = "modules/horseracing/inhotmodule/effect/abprefab/horseracingbingobingo"
this.HorseRacingBingobingoClown = "modules/horseracing/inhotmodule/effect/abprefab/horseracingbingobingoclown"
this.HorseRacingEmpty = "modules/horseracing/inhotmodule/effect/abprefab/horseracingempty"
this.HorseRacinggetxiaoka = "modules/horseracing/inhotmodule/effect/abprefab/horseracinggetxiaoka"
this.HorseRacingskill1shaozi = "modules/horseracing/inhotmodule/effect/abprefab/horseracingskill1shaozi"
this.HorseRacingskill1shaoziget = "modules/horseracing/inhotmodule/effect/abprefab/horseracingskill1shaoziget"
this.HorseRacingskill2gongjian = "modules/horseracing/inhotmodule/effect/abprefab/horseracingskill2gongjian"
this.Horsekousao = "modules/horseracing/inhotmodule/effect/materials/horsekousao"
this.Horseqizi = "modules/horseracing/inhotmodule/effect/materials/horseqizi"
this.Horsestiao = "modules/horseracing/inhotmodule/effect/materials/horsestiao"
this.Horsesuipian = "modules/horseracing/inhotmodule/effect/materials/horsesuipian"
this.Horsesuipian02 = "modules/horseracing/inhotmodule/effect/materials/horsesuipian02"
this.GiftPackHorseRacingBuffAtlas = "modules/horseracing/inhotmodule/atlas/giftpackhorseracingbuffatlas"
this.HorseRacingPassTaskAtlas = "modules/horseracing/inhotmodule/atlas/horseracingpasstaskatlas"
this.HorseRacingPopupAtlas = "modules/horseracing/inhotmodule/atlas/horseracingpopupatlas"
this.HorseRacingPurchaseAtlas = "modules/horseracing/inhotmodule/atlas/horseracingpurchaseatlas"

return this
