---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/10/19 17:36
---
local CommonPopupView = require("View.CommonTipView.CommonPopupView")
local CommonGlobalPopupView = CommonPopupView:New()
local this = CommonGlobalPopupView
this.viewType = CanvasSortingOrderManager.LayerType.Popup_Dialog
this.sure_cb = nil
this.cancel_cb = nil
--local this = CommonGlobalPopupView;


this.auto_bind_ui_items = {
    "btn_sure",
    "btn_cancle",
    "content",
    "title",
    "btn_close"
}

this.sure_cb = nil
this.cancel_cb = nil

--params @oktype  0:普通双按钮  1: 普通单按钮    2: 错误双按钮  3: 错误单按钮    4: 全局双按钮    5: 全局单按钮
function CommonGlobalPopupView:SetInfo(go, content, isSingleBtn, sure_cb, cancel_cb, params)
    if content then
        local tip_type = Csv.GetData("description", content, "params") or "1"
        local content = Csv.GetData("description", content, "description")
        if tip_type == "2" then self.title.sprite = AtlasManager:GetSpriteByName("BingoBangPopupAtlas", "TYAYS")
        elseif tip_type == "3" then self.title.sprite = AtlasManager:GetSpriteByName("BingoBangPopupAtlas", "TYERROR")
        else self.title.sprite = AtlasManager:GetSpriteByName("BingoBangPopupAtlas", "TYTips")  end
        self.title:SetNativeSize()
        fun.set_child_layer(self.go,"FakeUI")
        if tip_type == "2" then self.title.sprite = AtlasManager:GetSpriteByName("BingoBangPopupAtlas", "TYAYS")
        elseif tip_type == "3" then self.title.sprite = AtlasManager:GetSpriteByName("BingoBangPopupAtlas", "TYERROR")
        elseif tip_type == "1" then self.title.sprite = AtlasManager:GetSpriteByName("BingoBangPopupAtlas", "TYTips")  end
        self.title:SetNativeSize()
        local count = select(2, string.gsub(content, "%%s", ""))
        if params and #params > 0 and count> 0 and count== #params then
            content = string.format(content, unpack(params))
        end
        self.content.text = content
        self.sure_cb = sure_cb
        self.cancel_cb = cancel_cb
        if isSingleBtn then
            fun.set_active(self.btn_cancle, false)
            local pos = fun.get_gameobject_pos(self.btn_sure, true)
            fun.set_gameobject_pos(self.btn_sure, 0, pos.y, pos.z, true)
        end
    end
end


function CommonGlobalPopupView:GetRootView()
	if  SceneViewManager.gobal_layer == nil then
		SceneViewManager.gobal_layer = UnityEngine.GameObject.FindWithTag("GlobalUiRoot")
	end
	local parent =   SceneViewManager.gobal_layer
	return parent
end


function CommonGlobalPopupView.NewPop(comonPopup)
    --如果o为false或者o为nil，则让o为{}
    comonPopup = comonPopup or {viewName ="CommonPopupView",atlasName = "BingoBangPopupAtlas"}
    setmetatable(comonPopup,{__index = this})
    if comonPopup.go ~= nil then log.e ("NewPop   not nil ") end
    return comonPopup
end

return this
