---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/6/27 11:00
---
---@class  ApplicationGuideInfo
local ApplicationGuideInfo = {}
local this = ApplicationGuideInfo
ApplicationGuideInfo.__index = ApplicationGuideInfo
--- Finger效果
this.FingerEffect = nil
--- 各个介绍面板
this.Middle = nil
this.LeftBottom = nil
this.RightUp = nil
this.RightBottom = nil
this.MaskObj = nil

function ApplicationGuideInfo:New()
    local o = {}
    setmetatable(o, { __index = ApplicationGuideInfo })
    return o
end

function ApplicationGuideInfo.SetData(self, data)
    self.data = data
end

function ApplicationGuideInfo.AddData(self,data)
    if not self.data then
        self.data ={}
        self.data[1] = data
    else
        self.data[#self.data+1] = data
    end
end

function ApplicationGuideInfo.GetEndLevel(self)
    if not self.data then
        return 1
    else
        local currLevel = 1
        for i = 1, #self.data do
            if currLevel< self.data[i].end_level then
                currLevel = self.data[i].end_level
            end
        end
        return currLevel
    end
    return 1
end


function ApplicationGuideInfo:Init(data)
end


local function SetTipContent(data)
    local res = Split(data.contentparam, "#")
    local currParent = nil
    fun.set_active(this.LeftBottom, false)
    fun.set_active(this.Middle, false)
    fun.set_active(this.RightBottom, false)
    fun.set_active(this.RightUp, false)
    if data.contentparam and #data.contentparam > 1 then
        if fun.starts(data.contentparam, "14") then
            currParent = this.LeftBottom
        elseif fun.starts(data.contentparam, "13") then
            currParent = this.Middle
        elseif fun.starts(data.contentparam, "12") then
            currParent = this.RightBottom
        elseif fun.starts(data.contentparam, "11") then
            currParent = this.RightUp
        end
        this.MaskObj = currParent
        fun.set_active(currParent, true)
        if #res > 2 then
            fun.set_transform_pos(currParent.transform, res[3], res[4], 0, true)
        else
            fun.set_transform_pos(currParent.transform, 0, 0, 0, true)
        end
        local textTip = fun.find_child(currParent, "FunctionShowTipView/root/background/text_tip")
        if textTip then
            local tip = fun.get_component(textTip, "Text")
            if tip then
                tip.text = data.content
            end
        end
    end
end

local function PlayMaskExit(obj)
    if obj and not Util.IsNull(obj) and fun.get_active_self(obj) then
        local anim = fun.get_component(obj, fun.ANIMATOR)
        if anim then
            anim:Play("exit")
        end
    end
end

local function HideTipContent()
    if fun.is_not_null(this.FingerAnim) then
        if this.FingerAnim then
            if not Util.IsNull(this.FingerAnim) then
                this.FingerAnim:Play(this.FingerAnimName .. "exit")
                this.FingerAnim = nil
            else
                this.FingerAnim = nil
            end
            log.y("hide finger")
        end
        PlayMaskExit(this.Middle)
        PlayMaskExit(this.LeftBottom)
        PlayMaskExit(this.RightUp)
        PlayMaskExit(this.RightBottom)
    end
end


---  显示第一场战斗的powerup 手指提示
function ApplicationGuideInfo:PlayFingerEffect(targetObj,isExit,data,isDestory)
    if ModelList.GuideModel:IsGuiding() then return end
    local CallBack = function(targetObj,isExit,data)
        if not Util.IsNull(this.FingerEffect ) then
            if targetObj and targetObj.transform then
                log.y("show finger")
                SetTipContent(data)
                if targetObj.transform.parent then
                    fun.set_parent(this.FingerEffect, targetObj.transform.parent)
                else
                    fun.set_parent(this.FingerEffect, targetObj.transform)
                end
                fun.SetAsLastSibling(this.FingerEffect)
                fun.set_same_position_with(this.FingerEffect, targetObj)
                fun.set_active(this.FingerEffect.gameObject, false)
                fun.set_active(this.FingerEffect.gameObject, true)
                local gd = fun.find_child(this.FingerEffect.gameObject, "GD")
                local anim = fun.get_component(gd.gameObject, fun.ANIMATOR)
                if data.form == 0 then
                    fun.set_active(gd.gameObject, false)
                else
                    fun.set_active(gd.gameObject, true)
                    local animName = "Up"
                    if data.form == 2 then
                        animName = "Right"
                    elseif data.form == 3 then
                        animName = "Left"
                    elseif data.form == 3 then
                        animName = "Down"
                    end
                    if anim then
                        anim:Play(animName .. "enter")
                        this.FingerAnim = anim
                        this.FingerAnimName = animName
                    end
                end
            end
            if isExit then
                HideTipContent()
                if isDestory then
                    Destroy(this.FingerEffect,0.5)
                    this.FingerEffect = nil
                end
            end
        end
    end
    if ( (not this.FingerEffect  or Util.IsNull(this.FingerEffect) ) and targetObj )  then
        Cache.load_prefabs(AssetList["ApplicationFinger"], "ApplicationFinger", function(obj)
            local Parent = GameObject.Find("GameManager/GlobalUI/Parent")
            this.FingerEffect = fun.get_instance(obj, Parent)
            this.Middle = fun.find_child(this.FingerEffect, "Middle")
            this.LeftBottom = fun.find_child(this.FingerEffect, "LeftBottom")
            this.RightUp = fun.find_child(this.FingerEffect, "RightUp")
            this.RightBottom = fun.find_child(this.FingerEffect, "RightBottom")
            CallBack(targetObj, isExit, data)
        end)
    else
        CallBack(targetObj, isExit,data)
    end
end


---  隐藏第一场战斗的powerup 手指提示
function ApplicationGuideInfo:HideFirstBattlePowerFinger()
    local Arrow =  GameObject.Find("GameManager/GlobalUI/Parent/GuideView/Panel/Arrow")
    if not Util.IsNull(Arrow) then
        local arrowAnima = fun.get_component(Arrow.gameObject, fun.ANIMATOR)
        arrowAnima:Play("exit")
    end
end

function ApplicationGuideInfo:Remove()
end

---@param viewName  string 界面名字
---@param str_view  string 获取界面的方法
function ApplicationGuideInfo: CheckViewBackground(viewName,str_view)
    if str_view and str_view ~="0" then
        local fu = _G[str_view]()
        return CanvasSortingOrderManager.IsViewBackGround(fu.viewType,fu.go)
    elseif ViewList[viewName] then
        return CanvasSortingOrderManager.IsViewBackGround(ViewList[viewName].viewType,ViewList[viewName].go)
    else
        return false
    end
end

function ApplicationGuideInfo:IsSatisfy(condition,data)
   
    if self:CheckViewBackground(data.view,data.string_view) then
        return false
    end
  
    if data.end_level < ModelList.PlayerInfoModel:GetLevel() then
       
        return false
    end

    --开放等级
    if data.open_level > ModelList.PlayerInfoModel:GetLevel() then
       
        return false 
    end 

    if condition == 4 then
        if data.param == "0" then
            return false
        end
        local view = GetFunctionViewRef(data.param)
        if view and view.img_reddot and view.img_reddot.gameObject.activeInHierarchy then
            return true
        end
    elseif condition == 5 then
        return ModelList.regularlyAwardModel:IsRegularlyAwardMature()
    elseif condition == 6 then
        local betrate = ModelList.CityModel:GetBetRate()
        local maxrate =  ModelList.CityModel:GetMaxRateOpen()
        --maxbet 可以点击状态
        return betrate < maxrate 
    elseif condition == 0 then
        return ModelList.ApplicationGuideModel.IsInputSilence(data.delay_time)
    end
    return false
end

function ApplicationGuideInfo.CheckHide(view,str_view)
    if this:CheckViewBackground(view,str_view) then
        this:PlayFingerEffect(nil,true)
    end
end

function ApplicationGuideInfo:CheckShow(view,str_view)
    if not this:CheckViewBackground(view,str_view) then
        self:DelayCheck()
    end
end

function ApplicationGuideInfo:DelayCheck()

end

---@return GameObject 获取应用引导的界面
function ApplicationGuideInfo:GetGuideView(data)
    if #data.path  >0  and data.path[1] ~="0" then
        if fun.starts(data.path[1],"MainCityScene") then
            local childPath = "CanvasScene/GameScene/" .. data.path[1]
            local obj = GameObject.Find(childPath)
            return obj
        else
            local view = nil
            if data.string_view ~="0" then
                view = _G[data.string_view]().go
            else
                view = ViewList[data.view].go
            end
            if view then
                local childPath = string.gsub(data.path[1], data.view .. "/", "")
                local obj = fun.find_child(view, childPath)
                return obj
            end
        end
    end
    return nil
end

return this


