---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/6/27 15:35
---


local ApplicationGuideInfo = require("Guide.ApplicationGuide.ApplicationGuideInfo")
---@class  HallMainViewGuide : ApplicationGuideInfo
local HallMainViewGuide = ApplicationGuideInfo:New()
local this = HallMainViewGuide

function HallMainViewGuide:Init()
    this:Register()
    this:DelayCheck()
    log.r("HallMainViewGuide:Init")
end

local function RemoveDelay()
    if this.delay_show then
        LuaTimer:Remove(this.delay_show)
        this.delay_show = nil
    end
end

function HallMainViewGuide:Remove()
    --this:Register()
    RemoveDelay()
    this:PlayFingerEffect(nil,true,nil,true)
    log.r("HallMainViewGuide:Remove")
    this:UnRegister()
end

function HallMainViewGuide:DelayCheck()
    RemoveDelay()
    this.delay_show = LuaTimer:SetDelayFunction(this.data[1].delay_time,function()
        this.delay_show = nil
        this:Check()
    end,nil,LuaTimer.TimerType.UI)
end

function HallMainViewGuide:Check()
    local showFinger = false
    --判断现在是否已解锁bet
    local canStart,_temp = ModelList.CityModel:GetCanStartGame()

    if canStart == true then 
        for i = 1, #this.data do
            if this:IsSatisfy(this.data[i].startcondition,this.data[i])  then
                local view = this:GetGuideView(this.data[i])
                this:PlayFingerEffect(view,false,this.data[i])
                showFinger = true
                return
            end
        end
    end 

    
    if not showFinger then
        this:DelayCheck()
    end
end

function HallMainViewGuide:DelayShowFinger(isStart)
    if isStart then
        if this.delay_show then
            LuaTimer:Remove(this.delay_show)
            this.delay_show = nil
        end
        this:PlayFingerEffect(nil, true)
        this.delay_show = LuaTimer:SetDelayFunction(this.data[1].delay_time, function()
            local view = ViewList[this.data[1].view].go
            if view then
                for i = 1, #this.data[1].path do
                    local childPath = string.gsub(this.data[1].path[i], this.data[1].view .. "/", "")
                    local obj = fun.find_child(view, childPath)
                    if fun.get_active_self(obj) then
                        if not CanvasSortingOrderManager.IsViewBackGround(ViewList.HallMainView.viewType,ViewList.HallMainView.go) then
                            log.r("RoomNoAction  show finger")
                            this:PlayFingerEffect(obj, false,this.data[1])
                        else
                            this:PlayFingerEffect(nil, true)
                        end
                        break
                    end
                end
            end
            this.delay_show = nil
        end)
    else
        this:PlayFingerEffect(nil, true)
        if this.delay_show then
            LuaTimer:Remove(this.delay_show)
            this.delay_show = nil
        end
    end
end

function HallMainViewGuide:Register()
    Event.AddListener(EventName.ApplicationGuide_ResetFinger, this.DelayShowFinger)
end

function HallMainViewGuide:UnRegister()
    Event.RemoveListener(EventName.ApplicationGuide_ResetFinger, this.DelayShowFinger)
end

return this