---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/4/9 18:26
---



local ClimbRankPowerState = Clazz(BaseFsmState, "ClimbRankPowerState")
local this = ClimbRankPowerState

local PlayTime = {1.5,1.5,1.5}
local RewardType = {Refund = 1, FastDuba =2,PerfectDuba = 3}

function ClimbRankPowerState:New()
    local o = {}
    setmetatable(o, { __index = ClimbRankPowerState })
    return o
end

function ClimbRankPowerState:InitState()
end

local baseSettleReward = nil
local addCound = 0
local cardCount = 0

function ClimbRankPowerState:OnEnter(fsm, previous )
    local settleData = ModelList.BattleModel:GetCurrModel():GetSettleData().groupSettleReward
    baseSettleReward = settleData.powerUpSettleReward
    addCound = 0
    cardCount = #fsm:GetOwner():GetCards()
    this._fsm = fsm
    this:PlayDuba(fsm)
end

local GetCoinItemCount = function(gift)
    local count = 0
    for i = 1, #gift do
        if gift[i] == 1046 then
            count = count + 1
        end
    end
    return count
end


---@see 展示点击金币奖励
local GetRefundCoin = function(cardId)
    local data = ModelList.BattleModel:GetCurrModel():GetRoundData(cardId)
    local itemCount = 0
    for i = 1, #data.cards do
        if data.cards[i].sign>0 and #data.cards[i].gift>0 then
            itemCount = itemCount + GetCoinItemCount(data.cards[i].gift)
        end
    end
    --itemCount = 8
    this._fsm:GetOwner():SetAddReward(cardId, 8,itemCount )
end



local GetRewardContent = function(cardId,rewardType)
    if rewardType == RewardType.Refund then
        GetRefundCoin(cardId)
    end
end



function ClimbRankPowerState:PlayDuba(fsm )
    -- 0315 playDuBA暂时不知道为什么这样 
    if #baseSettleReward.refundPowerUp > 0 and baseSettleReward.refundPowerUp[1].value > 0 then
        for i = 1, cardCount do
            GetRewardContent(i,RewardType.Refund,fsm)
        end
        addCound  = baseSettleReward.refundPowerUp[1].value
        fsm:GetOwner():SetAddCountTxt(addCound)
        local PlayNext = function()
            this:PalyEnd()
        end
        fsm:GetOwner():PlayRewardJump(PlayNext)
    else
        this:PalyEnd()
    end

   -- this:PalyEnd()
end



function ClimbRankPowerState:PalyEnd( )
    self:ChangeState(this._fsm,"ClimbRankJackpotState")
    if addCound <= 0 then

    else

    end
end


function ClimbRankPowerState:Finish()

end


function ClimbRankPowerState:OnLeave(fsm)
    this._fsm = nil
    self._owner = nil
    self._posX = nil
end

function ClimbRankPowerState:Dispose()
    self:OnLeave(nil)
end

return this