--
--TopQuickTaskFlyRewardView = BaseView:New("TopQuickTaskFlyRewardView")
--local this = TopQuickTaskFlyRewardView
--this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--
--this.auto_bind_ui_items = {
--    "root",
--    "img_coverage"
--}
--
--function TopQuickTaskFlyRewardView:Awake()
--    self:on_init()
--end
--
--function TopQuickTaskFlyRewardView:OnEnable(params)
--    if params then
--        params:FlyCooky(self.root)
--    end
--end
--
--function TopQuickTaskFlyRewardView:OnDisable()
--
--end
--
--return this