---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/8/24 11:03
---
local GMModel = BaseModel:New("GMModel")
local this = GMModel
local Input = UnityEngine.Input
local KeyCode = UnityEngine.KeyCode

this.is_show = false
this.isSaveBattleData = false
this.IsAutoBattle = false
this.IsAutoSign = false

local o = nil
function GMModel:InitData()
    if fun.IsEditor() or log.enabled then
        self.update = xp_call(function ()
            self:on_x_update()
        end)
        this.is_show = false
        self.update_x_handler = UpdateBeat:CreateListener(self.update)
        UpdateBeat:AddListener(self.update_x_handler)
        this:Regiseter()
    end
end

local readAll = function (file)
    local f = assert(io.open(file, "rb"))
    local content = f:read("*all")
    f:close()
    return content
end

function serialize(obj)
    local lua = ""
    local t = type(obj)
    if t == "number" then
        lua = lua .. obj
    elseif t == "boolean" then
        lua = lua .. tostring(obj)
    elseif t == "string" then
        lua = lua .. string.format("%q", obj)
    elseif t == "table" then
        lua = lua .. "{"
        for k, v in pairs(obj) do
            lua = lua .. "[" .. serialize(k) .. "]=" .. serialize(v) .. ","
        end
        local metatable = getmetatable(obj)
        if metatable ~= nil and type(metatable.__index) == "table" then
            for k, v in pairs(metatable.__index) do
                lua = lua .. "[" .. serialize(k) .. "]=" .. serialize(v) .. ","
            end
        end
        lua = lua .. "}"
    elseif t == "nil" then
        return nil
    else
        error("can not serialize a " .. t .. " type.")
    end
    return lua
end

--function table2string(tablevalue)
--    local stringtable = serialize(tablevalue)
--    print(stringtable)
--    return stringtable
--end

--local data = {["a"] = "a", ["b"] = "b", [1] = 1, [2] = 2, ["t"] = {1, 2, 3}}
--local string = table2string(data)

function GMModel:on_btn_loadFile_click()
    local path = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/data"
    local data = readAll(path)
    local ret = JsonToTable(data)
    --local ret = loadstring("return "..data)()
    local text = ret
    Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_VICTORY_BEATS, 0, ret)
    LuaTimer:SetDelayFunction(1, function ()
        ModelList.GameModel:ShowSettle()
    end)

    local playid = ret.playId -- ModelList.CityModel.GetPlayIdByCity(1)
    local gameType = Csv.GetData('city_play', playid, "play_type")
    local cityId = Csv.GetData('city_play', playid, "city_id")
    ModelList.BattleModel:SetGameType(playid)
    ModelList.CityModel.SetPlayId(playid)

    --编辑器模式下load asset
    if GameUtil.is_windows_editor() then
        local modularData = table.find(Csv["modular"], function (k, v)
            return v.city_play_id == playid
        end)
        ModelList.BattleModel.RequireModuleLua(modularData.modular_name)
    end

    local procedure = nil
    if gameType == PLAY_TYPE.PLAY_TYPE_NORMAL then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_DEFAULT, 0, text)
        procedure = ProcedureNormalGame:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_COCKTAIL then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_COCKTAIL, 0, text)
        procedure = ProcedureHawaiiGame:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_CHRISTMAS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_CHRISTMAS, 0, text)
        procedure = ProcedureChristmasGame:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GREEN_HEAD then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_GREEN_HEAD, 0, text)
        local ProcedureLeeToleMan = require "Procedure/ProcedureLeeToleMan"
        procedure = ProcedureLeeToleMan:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_WOLF then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_WOLF, 0, text)
        local ProcedureLeeToleMan = require "Procedure/ProcedureSingleWolf"
        procedure = ProcedureLeeToleMan:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_AUTO, 0, text)
        procedure = ProcedureHangUp:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_JEWEL_QUEEN then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_JEWEL_QUEEN, 0, text)
        procedure = ProcedureGemQueen:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_LOOK_FOR_CANDY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_LOOK_FOR_CANDY, 0, text)
        procedure = ProcedureCandy:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_NEW_CHRISTMAS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_NEW_CHRISTMAS, 0, text)
        procedure = ProcedureNewChristmas:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_VICTORY_BEATS, 0, text)
        procedure = ProcedureWinZone:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GOLDEN_PIGGY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_GOLDEN_PIGGY, 0, text)
        procedure = ProcedureGoldenPig:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GOLDEN_DRAGON then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_GOLDEN_DRAGON, 0, text)
        procedure = ProcedureDragonFortune:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_NEW_GREEN_HEAD then
        Message.DispatchMessage(MSG_ID.MSG_GAME_NEW_GREEN_HEAD, 0, text)
        procedure = ProcedureNewLeetoleMan:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_EASTER_DAY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_EASTER_DAY, 0, text)
        procedure = ProcedureEaster:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_VOLCANO_PATH then
        Message.DispatchMessage(MSG_ID.MSG_GAME_VOLCANO_PATH, 0, text)
        procedure = ProcedureVolcano:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_MINING then
        Message.DispatchMessage(MSG_ID.MSG_GAME_MINING, 0, text)
        procedure = ProcedureMoleMiner:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_BISON then
        Message.DispatchMessage(MSG_ID.MSG_GAME_BISON, 0, text)
        procedure = ProcedureBison:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_HORSE_RACE then
        Message.DispatchMessage(MSG_ID.MSG_GAME_HORSE_RACE, 0, text)
        procedure = ProcedureHorseRacing:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_SCRATCH_WINNER then
        Message.DispatchMessage(MSG_ID.MSG_GAME_SCRATCH_WINNER, 0, text)
        procedure = ProcedureScratchWinner:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GOLD_TRAIN then
        Message.DispatchMessage(MSG_ID.MSG_GAME_GOLD_TRAIN, 0, text)
        procedure = ProcedureGoldenTrain:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_CHRISTMAS_SYNTHESIS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_CHRISTMAS_SYNTHESIS, 0, text)
        local christmasSyn = require("Procedure/ProcedureChristmasSynthesis")
        procedure = christmasSyn:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_THREE_PIGS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_THREE_PIGS, 0, text)
        local pd = require("Procedure/ProcedureGotYou")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_LET_THEM_ROLL then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_LET_THEM_ROLL, 0, text)
        local pd = require("Procedure/ProcedureLetemRoll")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_PIGGY_BANK then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_PIGGY_BANK, 0, text)
        local pd = require("Procedure/ProcedurePiggyBank")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_SOLITAIRE then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_SOLITAIRE, 0, text)
        local pd = require("Procedure/ProcedureSolitaire")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_MONOPOLY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_MONOPOLY, 0, text)
        local pd = require("Procedure/ProcedureMonopoly")
        procedure = pd:New()
    end

    if gameType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        Facade.SendNotification(NotifyName.ShowUI, ViewList.WinZoneLoadingGameView, nil, nil, procedure)
    else
        Facade.SendNotification(NotifyName.ShowUI, ViewList.SceneLoadingGameView, nil, nil, procedure)
    end

    Facade.SendNotification(NotifyName.CloseUI, ViewList.BattleDataTestView)
    BingoBangEntry.IsReplayBattle = true
end

function GMModel.SetBattleLoadData(data)
    local ret = JsonToTable(data)
    --local ret = loadstring("return "..data)()
    local text = ret
    Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_VICTORY_BEATS, 0, ret)
    LuaTimer:SetDelayFunction(1, function ()
        ModelList.GameModel:ShowSettle()
    end)

    local playid = ret.playId -- ModelList.CityModel.GetPlayIdByCity(1)
    local gameType = Csv.GetData('city_play', playid, "play_type")
    local cityId = Csv.GetData('city_play', playid, "city_id")
    ModelList.BattleModel:SetGameType(playid)
    ModelList.CityModel.SetPlayId(playid)

    --编辑器模式下load asset
    if GameUtil.is_windows_editor() then
        local modularData = table.find(Csv["modular"], function (k, v)
            return v.city_play_id == playid
        end)
        if modularData then
            ModelList.BattleModel.RequireModuleLua(modularData.modular_name)
        end
    end

    local procedure = nil
    if gameType == PLAY_TYPE.PLAY_TYPE_NORMAL then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_DEFAULT, 0, text)
        procedure = ProcedureNormalGame:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_COCKTAIL then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_COCKTAIL, 0, text)
        procedure = ProcedureHawaiiGame:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_CHRISTMAS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_CHRISTMAS, 0, text)
        procedure = ProcedureChristmasGame:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GREEN_HEAD then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_GREEN_HEAD, 0, text)
        local ProcedureLeeToleMan = require "Procedure/ProcedureLeeToleMan"
        procedure = ProcedureLeeToleMan:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_WOLF then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_WOLF, 0, text)
        local ProcedureLeeToleMan = require "Procedure/ProcedureSingleWolf"
        procedure = ProcedureLeeToleMan:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_AUTO, 0, text)
        procedure = ProcedureHangUp:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_JEWEL_QUEEN then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_JEWEL_QUEEN, 0, text)
        procedure = ProcedureGemQueen:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_LOOK_FOR_CANDY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_LOOK_FOR_CANDY, 0, text)
        procedure = ProcedureCandy:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_NEW_CHRISTMAS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_NEW_CHRISTMAS, 0, text)
        procedure = ProcedureNewChristmas:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_VICTORY_BEATS, 0, text)
        procedure = ProcedureWinZone:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GOLDEN_PIGGY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_GOLDEN_PIGGY, 0, text)
        procedure = ProcedureGoldenPig:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_GOLDEN_DRAGON then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_GOLDEN_DRAGON, 0, text)
        procedure = ProcedureDragonFortune:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_NEW_GREEN_HEAD then
        Message.DispatchMessage(MSG_ID.MSG_GAME_NEW_GREEN_HEAD, 0, text)
        procedure = ProcedureNewLeetoleMan:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_EASTER_DAY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_EASTER_DAY, 0, text)
        procedure = ProcedureEaster:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_VOLCANO_PATH then
        Message.DispatchMessage(MSG_ID.MSG_GAME_VOLCANO_PATH, 0, text)
        procedure = ProcedureVolcano:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_MINING then
        Message.DispatchMessage(MSG_ID.MSG_GAME_MINING, 0, text)
        procedure = ProcedureMoleMiner:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_LET_THEM_ROLL then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_LET_THEM_ROLL, 0, text)
        local pd = require("Procedure/ProcedureLetemRoll")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_PIGGY_BANK then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_PIGGY_BANK, 0, text)
        local pd = require("Procedure/ProcedurePiggyBank")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_SOLITAIRE then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_SOLITAIRE, 0, text)
        local pd = require("Procedure/ProcedureSolitaire")
        procedure = pd:New()
    elseif gameType == PLAY_TYPE.PLAY_TYPE_MONOPOLY then
        Message.DispatchMessage(MSG_ID.MSG_GAME_LOAD_MONOPOLY, 0, text)
        local pd = require("Procedure/ProcedureMonopoly")
        procedure = pd:New()
    end

    if gameType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        Facade.SendNotification(NotifyName.ShowUI, ViewList.WinZoneLoadingGameView, nil, nil, procedure)
    else
        Facade.SendNotification(NotifyName.ShowUI, ViewList.SceneLoadingGameView, nil, nil, procedure)
    end

    Facade.SendNotification(NotifyName.CloseUI, ViewList.BattleDataTestView)
    BingoBangEntry.IsReplayBattle = true
end

function GMModel:on_btn_loadRoundFile()
    local path = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/rounddata"
    local data = LoadJson(path)
    --local ret = JsonToTable(data)
    local round = ModelList.GameModel:GetRoundData()
    round = data
end

local startId = 1

function GMModel:on_x_update()
    if Input.GetKeyUp(KeyCode.F1) then

    end
    if Input.GetKeyUp(KeyCode.F2) then
        --local data = ModelList.ChristmasSynthesisModel:GetWishCellInfoList(1)
        --print(data)
    end
    if Input.GetKeyUp(KeyCode.F3) then
        Facade.SendNotification(NotifyName.ShowDialog, ViewList.BattleDataTestView)
    end
    if Input.GetKeyUp(KeyCode.F4) then
        Facade.SendNotification(NotifyName.ShowDialog, ViewList.GMView)
    end
    if Input.GetKeyUp(KeyCode.F5) then
        --ModelList.CityModel.SetPlayId(nil)
        Event.Brocast(EventName.Event_Close_Web_View, true)
        Facade.SendNotification(NotifyName.ShopView.CloseLoadingView)
    end
    if Input.GetKeyUp(KeyCode.F6) then
        --local path = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/settle1"
        --local ret = LoadJson(path)
        --Message.DispatchMessage(MSG_ID.MSG_GAME_COMMON_PRE_SETTLE, 0, ret)
        --local data = "{\"orderId\":\"1719907965438298\",\"transactionId\":\"int_hkdmj6pd7gxnmpl5lxu\",\"payChannel\":\"Airwallex\",\"amount\":\"2.99\",\"currency\":\"USD\",\"sku\":\"1-1003\",\"isTest\":true,\"purchaseTime\":1719907788}{\"orderId\":\"1719907965438298\",\"transactionId\":\"int_hkdmj6pd7gxnmpl5lxu\",\"payChannel\":\"Airwallex\",\"amount\":\"2.99\",\"currency\":\"USD\",\"sku\":\"1-1003\",\"isTest\":true,\"purchaseTime\":1719907788}{\"orderId\":\"1719907965438298\",\"transactionId\":\"int_hkdmj6pd7gxnmpl5lxu\",\"payChannel\":\"Airwallex\",\"amount\":\"2.99\",\"currency\":\"USD\",\"sku\":\"1-1003\",\"isTest\":true,\"purchaseTime\":1719907788}{\"orderId\":\"1719907965438298\",\"transactionId\":\"int_hkdmj6pd7gxnmpl5lxu\",\"payChannel\":\"Airwallex\",\"amount\":\"2.99\",\"currency\":\"USD\",\"sku\":\"1-1003\",\"isTest\":true,\"purchaseTime\":1719907788}"
        --local path = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/pay"
        ----local ret = LoadJson(path)
        --local data = LoadFile(path)
        --
        --PurchaseHelper.payResult = 1
        --Event.Brocast(EventName.Event_New_Pay_Result, true)
        --PurchaseHelper.extraData = data
    end
    if Input.GetKeyUp(KeyCode.F7) then
        --Message.DispatchMessage(3003, 0, {
        --    sku = "1003",
        --    reward = { {
        --                   value = 230000,
        --                   id = 2
        --               },
        --               {
        --                   value = 240,
        --                   id = 10
        --               }
        --    },
        --    index = "1003",
        --    itemId = "1003",
        --    count = 1,
        --    channel = 0,
        --    pid = ViewList.PayLoadingView.enableData.data.pid
        --});
    end
    --跳转到推荐玩法大厅
    if Input.GetKeyUp(KeyCode.F8) then
        --local tmpData = table.find(Csv["feature_enter"], function (k, v)
        --    return v.featured_entrance == 1
        --end)
        --tmpData = tmpData or Csv["feature_enter"][#Csv["feature_enter"]]
        --local PlayData = Csv.GetData("city_play", tmpData.city_play)
        --local tmpmodData = Csv.GetData("modular", tmpData.modular_id)
        --if (tmpmodData ~= nil and tmpmodData.modular_name ~= nil) then
        --    ModelList.BattleModel.RequireModuleLua(tmpmodData.modular_name)
        --end
        --Facade.SendNotification(NotifyName.SpecialGameplay.CloseSpecialGameplayView)
        --Facade.SendNotification(NotifyName.SceneCity.Click_City_Enter, nil, PlayData.city_id, tmpData.city_play)
    end
    if Input.GetKeyUp(KeyCode.F9) then
        --if BattleMachineList.MachineEnabled then
        --    local view = ModelList.BattleModel:GetCurrBattleView().cardView
        --    view:GmSignTest()
        --else
        --    this:on_btn_loadFile_click()
        --end
    end
    if Input.GetKeyUp(KeyCode.F10) then

    end
    if Input.GetKeyUp(KeyCode.F11) then
        --local path = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/settle1"
        --local path2 = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/settle2"
        --if Util.IsFileExist(path2) then
        --    local ret = LoadJson(path)
        --    if ret then
        --        Message.DispatchMessage(MSG_ID.MSG_GAME_COMMON_SETTLE, 0, ret)
        --    end
        --    --Util.DeleteFile(path)
        --elseif Util.IsFileExist(path2) then
        --    local ret = LoadJson(path)
        --    if ret then
        --        Message.DispatchMessage(MSG_ID.MSG_GAME_COMMON_SETTLE, 0, ret)
        --    end
        --end
        --
        --this:SimulateSmallGame()
        --Event.Brocast(EventName.Event_Receive_Game_Settle_Data)
    end
    --所有格子盖章
    if Input.GetKeyUp(KeyCode.F12) then
        if BingoBangEntry.IsInBattle and not this.isInF12 then
            this.isInF12 = true
            coroutine.start(function()
                local cardCount = ModelList.BattleModel:GetCurrModel():GetCardCount()
                local view = ModelList.BattleModel:GetCurrBattleView().cardView
                for i = 1, 25 do
                    coroutine.wait(0.1)
                    view:OnClickCardIgnoreJudgeByIndex(startId, i, 0)
                end
                startId = startId + 1
                if startId > cardCount then
                    startId = 1
                end
                this.isInF12 = false
            end)
        end
    end
    
    --游戏加速
    if Input.GetKeyUp(KeyCode.T) then
        if UnityEngine.Time.timeScale == 1 then
            UnityEngine.Time.timeScale = 3
        else
            UnityEngine.Time.timeScale = 1
        end
    end
    --游戏减速
    if Input.GetKeyUp(KeyCode.Y) then
        local tar = UnityEngine.Time.timeScale + 0.2
        if tar > 1 then
            tar = 0.2
        end
        UnityEngine.Time.timeScale = tar
    end
    --无
    if Input.GetKeyUp(KeyCode.B) then

    end
    
    this:GetHorizonMove()
end

local gestureDetector3 = {}
local gestureCount3 = 0

function GMModel:GetHorizonMove()
    if UnityEngine.Application.platform == UnityEngine.RuntimePlatform.Android then
        if (Input.touches.Length ~= 1) then
            gestureDetector3 = {}
            gestureCount3 = 0
        else
            if (Input.touches[0].phase == UnityEngine.TouchPhase.Canceled or Input.touches[0].phase == UnityEngine.TouchPhase.Ended) then
                gestureDetector3 = {}
            elseif Input.touches[0].phase == UnityEngine.TouchPhase.Moved then
                local p = Input.touches[0].position
                if (#gestureDetector3 == 0 or (p.x - gestureDetector3[#gestureDetector3].x) > 50) then
                    table.insert(gestureDetector3, p)
                end
            end
        end
    else
        if Input.GetMouseButtonUp(0) then
            gestureDetector3 = {}
            gestureCount3 = 0;
        else
            if (Input.GetMouseButton(0)) then
                local p = Vector2.New(Input.mousePosition.x, Input.mousePosition.y);
                if (#gestureDetector3 == 0 or (p.x - gestureDetector3[#gestureDetector3].x) > 50) then
                    table.insert(gestureDetector3, p)
                end
            end
        end
    end

    if (#gestureDetector3 < 10) then
        return
    end
    local d1 = gestureDetector3[1]
    local d2 = gestureDetector3[#gestureDetector3]
    if d2.x - d1.x > 500 and math.abs(d2.y - d1.y) < 100 then
        if not GameUtil.is_windows_editor() then
            Facade.SendNotification(NotifyName.ShowDialog, ViewList.GMView)
        end
        gestureDetector3 = {}
        gestureCount3 = 0
    end
end

function GMModel:Reset()
    this.is_show = false
end

function GMModel:Regiseter()
    Event.AddListener(EventName.Test_Normal_Auto_Up, this.AutoUp)
    Event.AddListener(EventName.Test_SettleDetailView, this.AutoSettleDetail)
    Event.AddListener(EventName.Test_PuzzleView, this.AutoPuzzleView)
    Event.AddListener(EventName.Test_SettleRocket, this.AutoSettleRocket)
end

function GMModel:AutoBuyPowerUp()
    local _genre = math.random(1, 3)
    ModelList.CityModel:SetCardNumber(_genre)
    Facade.SendNotification(NotifyName.HallCity.ShowPowerUpView, false)
end

function GMModel:OpenAutoBattle(viewName)
    if this.IsAutoBattle then
        if viewName == "HallMainView" then
            ModelList.CityModel.C2S_FetchPowerUp()
            LuaTimer:SetDelayFunction(1, function ()
                --local gear = math.random(1, 3)
                --ModelList.CityModel.C2S_BuyPowerUpCards(gear)
                this:AutoBuyPowerUp()
            end)

            --LuaTimer:SetDelayFunction(2, function()
            --    local a = math.random(1, 30)
            --    local b = 1
            --    if a > 20 then
            --        b = 4
            --    elseif a > 10 then
            --        b = 2
            --    end
            --    ModelList.CityModel:SetCardNumber(b)
            --    local cardNum = ModelList.CityModel:GetCardNumber()
            --    log.r("ReqEnterGame cardNum   " .. cardNum .. "   random " .. b)
            --    ModelList.GameModel.ReqEnterGame()
            --end)
        elseif viewName == "GameBingoView" then

        end
    end
end

function GMModel:AutoUp()
    if not this.IsAutoBattle and not this.IsAutoSign then
        return
    end
    if ModelList.BattleModel:GetGameType() ~= PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        LuaTimer:SetDelayFunction(0.5, function ()
            log.y("GMModel:AutoUp")
            ModelList.BattleModel:GetCurrBattleView().powerView:UsePowerUpCard()
            --ViewList.GameBingoView.powerView:UsePowerUpCard()
        end)
    end
end

function GMModel:AutoSettleDetail()
    if not this.IsAutoBattle then
        return
    end
    if ModelList.BattleModel:GetGameType() ~= PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        ViewList.SettleDetailView:on_btn_continue_click()
        --log.r("AutoSettleDetail")
    end
end

function GMModel:AutoPuzzleView(cView)
    if not this.IsAutoBattle then
        return
    end
    if ModelList.BattleModel:GetGameType() ~= PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        LuaTimer:SetDelayFunction(0.5, function ()
            cView:on_btn_addPieces_click()
        end)
    end
end

function GMModel:AutoSettleRocket()
    if not this.IsAutoBattle then
        return
    end
    if ModelList.BattleModel:GetGameType() ~= PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        local randomNum = math.random(1, 2)
        if randomNum == 1 then
            ViewList.SettleRocketView:on_btn_rocket_click()
        else
            ViewList.SettleRocketView:on_btn_skip_click()
        end
    end
end

function GMModel:AutoEnterBattle()
    if this.IsAutoBattle then
        LuaTimer:SetDelayFunction(2, function ()
            ModelList.BattleModel.SendMessage(MSG_ID.MSG_SHOP_GM, { cmd = "item#2#1000" });
            Facade.SendNotification(NotifyName.HallMainView.PlayCardsClick, math.random(1, 3))
        end)

        LuaTimer:SetDelayFunction(5, function ()
            ModelList.BattleModel.SendMessage(MSG_ID.MSG_SHOP_GM, { cmd = "item#1#1000" });
            local geap = math.random(1, 3)
            if geap == 1 then
                ViewList.HallMainView._hallFunction:Getplay1card():OnPlayCardsClick()
            elseif geap == 2 then
                ViewList.HallMainView._hallFunction:Getplay2card():OnPlayCardsClick()
            elseif geap == 3 then
                ViewList.HallMainView._hallFunction:Getplay4card():OnPlayCardsClick()
            end
            LuaTimer:SetDelayFunction(2, function ()
                local geap = math.random(1, 3)
                if ViewList.PowerUpViewGoldNova.go then
                    ViewList.PowerUpViewGoldNova:OnClickDrawCard(geap)
                elseif ViewList.PowerUpViewMaster.go then
                    ViewList.PowerUpViewMaster:OnClickDrawCard(geap)
                elseif ViewList.PowerUpViewSilver.go then
                    ViewList.PowerUpViewSilver:OnClickDrawCard(geap)
                elseif ViewList.PowerUpView.go then
                    ViewList.PowerUpView:OnClickDrawCard(geap)
                end
            end)

            --ModelList.CityModel.C2S_BuyPowerUpCards(math.random(1, 3))
        end)
        LuaTimer:SetDelayFunction(10, function ()
            local a = math.random(1, 30)
            local b = 1
            if a > 20 then
                b = 4
            elseif a > 10 then
                b = 2
            end
            ModelList.CityModel:SetCardNumber(b)
            local cardNum = ModelList.CityModel:GetCardNumber()
            --log.r("ReqEnterGame cardNum   "..cardNum.."   random "..b)
            --ModelList.VolcanoModel:ReqEnterGame()
            ModelList.BattleModel:ReqEnterGame()
        end)
    end
end

function GMModel:AutoExitBattle(type)
    if this.IsAutoBattle then
        if type == 1 then
            LuaTimer:SetDelayFunction(15, function ()
                ViewList.TournamentSettleView:on_btn_continue_click()
            end)
        else
            local offsetTime = 0
            if type == 3 then offsetTime = 13 end
            LuaTimer:SetDelayFunction(4 + offsetTime, function ()
                --ViewList.PuzzleView:OnAddPieces()
                TopCurrencyView:on_btn_goback_click()
                ViewList.TopConsoleView:on_btn_goback_click()
            end)
            --LuaTimer:SetDelayFunction(5.5+offsetTime, function()
            --    ViewList.PuzzleView:on_btn_addPieces_click()
            --end)
        end
    end
end

--- 自动下发结算信息
function GMModel:AutoReplaySettle()
    local path = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/settle1"
    local path2 = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/settle2"
    if Util.IsFileExist(path) then
        local ret = LoadJson(path)
        if ret then
            Message.DispatchMessage(MSG_ID.MSG_GAME_COMMON_PRE_SETTLE, 0, ret)
        end
        --Util.DeleteFile(path)
    elseif Util.IsFileExist(path2) then
        local ret = LoadJson(path)
        if ret then
            Message.DispatchMessage(MSG_ID.MSG_GAME_COMMON_SETTLE, 0, ret)
        end
    end

    this:SimulateSmallGame()
end

function GMModel:SimulateSmallGame()
    local playType = ModelList.BattleModel:GetGameType()
    if playType == PLAY_TYPE.PLAY_TYPE_SCRATCH_WINNER then
        ---加载刮刮奖摇奖信息
        local path3 = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") .. "/tool/moni/ScratchWinnerExtraBall"
        if Util.IsFileExist(path3) then
            --[[  解析源数据的方式
            local data = readAll(path3)
            local body = Base64.decode(data)
            local ret = Proto.decode(5202, body)
            Message.DispatchMessage(5202, RET.RET_SUCCESS, ret)
            --]]

            local ret = LoadJson(path3)
            if ret then
                Message.DispatchMessage(MSG_ID.MSG_GAME_BALL_SHAKER_INFO, 0, ret)
            end
        end
    elseif playType == PLAY_TYPE.PLAY_TYPE_GOLD_TRAIN then
        ---加载金币火车信息
        local path3 = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") ..
        "/tool/moni/GoldenTrainSmallGameData"
        if Util.IsFileExist(path3) then
            --[  解析源数据的方式
            local data = readAll(path3)
            local body = Base64.decode(data)
            local ret = Proto.decode(5204, body)
            Message.DispatchMessage(5204, RET.RET_SUCCESS, ret)
            --]]

            --[[  解析json数据的方式
            local ret = LoadJson(path3)
            if ret then
                Message.DispatchMessage(MSG_ID.MSG_GAME_GOLD_TRAIN_SETTLE, 0, ret)
            end
            --]]
        end
    elseif playType == PLAY_TYPE.PLAY_TYPE_CHRISTMAS_SYNTHESIS then
        ---加载刮刮奖摇奖信息
        local path3 = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") ..
        "/tool/moni/ChristmasSynthesisExtraBall"
        if Util.IsFileExist(path3) then
            ---[[  解析源数据的方式
            local data = readAll(path3)
            local body = Base64.decode(data)
            local ret = Proto.decode(5401, body)
            Message.DispatchMessage(5401, RET.RET_SUCCESS, ret)
            ---]]

            --local ret = LoadJson(path3)
            --if ret then
            --    Message.DispatchMessage(MSG_ID.MSG_GAME_BALL_SHAKER_INFO, 0, ret)
            --end
        end
    else
        --[[揺球器 主城小游戏
        local path3 = string.gsub(UnityEngine.Application.dataPath, "/Assets", "") ..
        "/tool/moni/SGExtraBall"
        if Util.IsFileExist(path3) then
            local data = readAll(path3)
            local body = Base64.decode(data)
            local ret = Proto.decode(5401, body)
            Message.DispatchMessage(5401, RET.RET_SUCCESS, ret)
        end
        ---]]
    end
end

function GMModel:IsGMAutoBattle()
    return this.IsAutoBattle
end

local function GetRoot(transform)
    local result = transform.name;
    local parent = transform.parent;
    while (parent ~= nil) do
        result = parent.name .. "." .. result
        parent = parent.parent;
    end
    return result;
end


function GMModel:PrintAllObjects()
    local allObjects = UnityEngine.Object.FindObjectsOfType(typeof(UnityEngine.Object))
    for i = 0, allObjects.Length - 1 do
        log.r(GetRoot(allObjects[i].transform))
    end
end

return this
