---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/18 16:08
---

local SuperMatchBingoEffectView = BaseChildView:New();
local this = SuperMatchBingoEffectView;

this.parent = nil

this.currNum = 0
this.isPlaying = false
local max_head = 1
this.show_time = 1
this.quick_reduce_bingoleft = false
this.quick_reduce_bingoleft_time = 0
this.quick_reduce_time2 = 0
this.quick_reduce_total_time = 0
this.quick_reduce_bingoleft_time_interval = 0
this.bingosleftSoundOrder = 1

this.leftTxt = nil
local lastBingoTime = 0
local MaxBingoleftCount = 0
local currLeftCount = 0

function SuperMatchBingoEffectView:Init(obj, bingoView)
    this:on_init(obj,bingoView)
    this.parent = bingoView
    MaxBingoleftCount = #ModelList.BattleModel:GetCurrModel():LoadGameData().bingoLeftTick
    currLeftCount = MaxBingoleftCount
    this.isPlaying = false
    this:Register()
    lastBingoTime = 0
end

function SuperMatchBingoEffectView:Register()
    Event.AddListener(Notes.QUICK_REDUCE_BINGOSILEFT, self.StartQuickReduceBingosileft)
    Event.AddListener(EventName.Bingo_Refresh_Other_BingoCount, self.RefreshBingoCount)
end

function SuperMatchBingoEffectView:UnRegisterEvent()
    Event.RemoveListener(Notes.QUICK_REDUCE_BINGOSILEFT, self.StartQuickReduceBingosileft)
    Event.RemoveListener(EventName.Bingo_Refresh_Other_BingoCount, self.RefreshBingoCount)
end

function SuperMatchBingoEffectView.OnDisable()

end

function SuperMatchBingoEffectView.OnDestroy()
    this.currNum = 0
    lastBingoTime = 0
    this.isPlaying = false
    this.show_time = 1
    this.quick_reduce_bingoleft = false
    this.quick_reduce_bingoleft_time = 0
    this.quick_reduce_time2 = 0
    this.quick_reduce_total_time = 0
    this.quick_reduce_bingoleft_time_interval = 0
    this:UnRegisterEvent()
    this:Close()
    this:Destroy()
end

function SuperMatchBingoEffectView.RefreshBingoCount(owner, num, next)
    this:SetData(num, next)
end

--
function SuperMatchBingoEffectView:SetData (num, next)
    this.currNum = this.currNum + num
    if not next or next < 0 then
        return
    end
    if this.currNum > 0 and not this.isPlaying then
        this:StartCountdown(num)
    end
end

function SuperMatchBingoEffectView:StartCountdown(num)
    if not num  then  num = 1 end
    this:SetHead(num)
    currLeftCount= currLeftCount - num
    --log.r("currLeftCount  "..currLeftCount)
    this:PlayBingosLeftSound()
    this.isPlaying = true
    if currLeftCount == 0 then
        this:StopCountdown()
    else
        this.currNum = this.currNum - num
        this.isPlaying = false
        if this.currNum <= 0 or currLeftCount  == 0 then
            this:StopCountdown()
        else
            this:StartCountdown()
        end
    end

end

function SuperMatchBingoEffectView:SetHead(num)
    local normal_speed = 1
    for i = 2, this.currNum do
        normal_speed = normal_speed + 0.3
        if normal_speed >= 2 then
            normal_speed = 2
            break
        end
    end
    Facade.SendNotification(NotifyName.Bingo.REFRSH_BINGOSI_CHANGE, num)
    -- 单独为这个声音加速
    local mana = UnityEngine.GameObject.Find("GameManager")
    if mana then
        local obj = fun.find_child(mana, "bingosleft.mp3")
        if obj then
            local ad = fun.get_component(obj, "AudioSource")
            if ad and ad.gameObject.name == "bingosleft.mp3" then
                ad.pitch = normal_speed
                --log.r(ad.name.."   speed  "..normal_speed)
            end
        end
    end
end

function SuperMatchBingoEffectView:StopCountdown()
    --log.r("StopCountdown ")
    if this.timerId then
        LuaTimer:Remove(this.timerId)
        this.timerId = nil
    end
end

function SuperMatchBingoEffectView:on_x_update()
    if this.quick_reduce_bingoleft then
        this:QuickReduceBingosileft()
    end
end

-- 开始快速减少bingoleft数量
function SuperMatchBingoEffectView.StartQuickReduceBingosileft()
    local leftNum = this:GetParentView().bingosleftView:GetCurrBingoLeftNum()
    local leftCount = this.currNum + leftNum
    if leftCount > 0 then
        this.quick_reduce_bingoleft = true
        this.quick_reduce_total_time = MCT.delay_to_show_settle - 0.1
        this.quick_reduce_bingoleft_time = 0
        this.quick_reduce_bingoleft_time_interval = this.quick_reduce_total_time / leftCount
        this.quick_reduce_time2 = this.quick_reduce_bingoleft_time_interval
    end
end

function SuperMatchBingoEffectView:QuickReduceBingosileft()
    this.quick_reduce_bingoleft_time = this.quick_reduce_bingoleft_time + UnityEngine.Time.deltaTime
    if this.quick_reduce_bingoleft_time < this.quick_reduce_total_time then
        if this.quick_reduce_bingoleft_time >= this.quick_reduce_time2 then
            this.quick_reduce_time2 = this.quick_reduce_time2 + this.quick_reduce_bingoleft_time_interval
            Facade.SendNotification(NotifyName.Bingo.REFRSH_BINGOSI_CHANGE)
        end
    else
        Facade.SendNotification(NotifyName.Bingo.REFRSH_BINGOSI_CHANGE,100)
        this.quick_reduce_bingoleft = false
    end
end

function SuperMatchBingoEffectView:GetBingoLeftView()
    return this:GetParentView().bingosleftView
end




local GetSoundOrder = function()
    if currLeftCount > 50 then
        this.bingosleftSoundOrder = 1
    elseif currLeftCount > 30 then
        this.bingosleftSoundOrder = 2
    elseif currLeftCount > 30 then
        this.bingosleftSoundOrder = 3
    elseif currLeftCount > 15 then
        this.bingosleftSoundOrder = 4
    elseif currLeftCount > 10 then
        this.bingosleftSoundOrder = 5
    elseif currLeftCount > 8 then
        this.bingosleftSoundOrder = 6
    elseif currLeftCount > 6 then
        this.bingosleftSoundOrder = 7
    elseif currLeftCount > 4 then
        this.bingosleftSoundOrder = 8
    elseif currLeftCount == 4 then
        this.bingosleftSoundOrder = 9
    else
        this.bingosleftSoundOrder = 10
    end
end


function SuperMatchBingoEffectView:PlayBingosLeftSound()
    GetSoundOrder()
    UISound.play("bingosleft" .. this.bingosleftSoundOrder)
end

return this