---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2024/3/28 10:20
---

--- 赛车活动弹窗
local CarQuestConst = require "View/CarQuest/CarQuestConst"

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder, "")

function PopupOrder.Execute(occasion)
    PopupOrder.occasion = occasion
    local racingData = ModelList.CarQuestModel:GetRacingData()
    --local data = ModelList.CompetitionModel:GetPlayerOptions()
    if not racingData or (racingData and not racingData.isOpen) then
        PopupOrder.Finish()
        return
    end

    --local selfLevel = ModelList.PlayerInfoModel:GetLv()
    --local needLevel = 0 -- Csv.GetLevelOpenByType(19,0)
    --local myLabel = ModelList.PlayerInfoModel:GetUserType()
    --if myLabel and myLabel > 0 then
    --    needLevel = Csv.GetData("level_open",29,"pay_openlevel")
    --else
    --    needLevel = Csv.GetData("level_open",29,"openlevel")
    --end
    --if selfLevel < needLevel or not racingData  then
    if not racingData then
        PopupOrder.Finish()
        return
    end
    --racingData.id= ""
    if racingData.id == "" then  -- 没有选择，弹出选择窗
        Event.AddListener(EventName.Event_popup_car_quest_finish, PopupOrder.Finish)
        Facade.SendNotification(NotifyName.ShowUI, ViewList.ActivitesChoiceView)
    else
        PopupOrder.Execute2(occasion)
    end
end

function PopupOrder.FinishChoice()

end

function PopupOrder.Execute2(occasion)
    --选择赛车

    ---判断是否当日首次
    local isDayFirst = false
    local popDay = fun.read_value("carquest_popday", "")
    local currentDate = os.date("%Y-%m-%d")
    if (popDay == "" or popDay ~= currentDate) then
        isDayFirst = true
    end


    local racingData = ModelList.CarQuestModel:GetRacingData()
    if racingData.isOver and racingData.isOver == 0 then -- 赛车还在进行中
        local cb = function ()
            PopupOrder.Finish()
        end
        -- 从战斗返回需要展示
        if occasion == PopupOrderOccasion.enterHallFromBattle then
            if ModelList.BattleModel:GetEnterBattleFail() then --这里不应该成立，但怕万一
                PopupOrder.Finish()
            elseif ModelList.CarQuestModel:GetOilDrumCollectRecordChange() then
                ViewList.CarQuestMainView:SetEnterMode(CarQuestConst.EnterMode.afterBattle)
                ViewList.CarQuestMainView:SetFinishCb(cb)
                ViewList.CarQuestMainView:SetReadyState(true)
                Facade.SendNotification(NotifyName.ShowUI, ViewList.CarQuestMainView)
                PopupOrder.RefreshPopDay("carquest_popday")
            else
                PopupOrder.Finish()
            end
        elseif racingData.roundReward and #racingData.roundReward > 0  then
            ViewList.CarQuestMainView:SetEnterMode(CarQuestConst.EnterMode.beforeRewardResend)
            ViewList.CarQuestMainView:SetFinishCb(cb)
            ViewList.CarQuestMainView:SetReadyState(true)
            Facade.SendNotification(NotifyName.ShowUI, ViewList.CarQuestMainView)
            PopupOrder.RefreshPopDay("carquest_popday")
        else
            PopupOrder.Finish()
        end
    elseif racingData.isOver and racingData.isOver == 1 then
        Event.AddListener(EventName.Event_popup_car_quest_finish, PopupOrder.Finish)
        -- --前三名数据明确弹a界面，
        -- --前三名数据并不明确 弹b界面,

        local cb = function ()
            if racingData.rankReward and #racingData.rankReward > 0 then
                --弹出奖励界面 再选择
                local poptype = 2 --排名结束奖励
                Facade.SendNotification(NotifyName.ShowUI, ViewList.CompetitionQuestOpenBoxView, nil, nil, poptype)
            else
                local flag = ModelList.CarQuestModel:GetIsRacingRankTop()
                --直接弹出
                if flag then
                    Facade.SendNotification(NotifyName.ShowUI, ViewList.CompetitionQuestRankView)
                else
                    Facade.SendNotification(NotifyName.ShowUI, ViewList.CompetitionQuestRank2View)
                end
            end
        end

        if occasion == PopupOrderOccasion.enterHallFromBattle then
            if ModelList.BattleModel:GetEnterBattleFail() then
                PopupOrder.Finish()
                ModelList.BattleModel:SetEnterBattleFail()
                return
            elseif ModelList.CarQuestModel:GetOilDrumCollectRecordChange() then
                ViewList.CarQuestMainView:SetEnterMode(CarQuestConst.EnterMode.afterBattle)
            else
                PopupOrder.Finish()
                ModelList.BattleModel:SetEnterBattleFail()
                return
            end
        else
            ViewList.CarQuestMainView:SetEnterMode(CarQuestConst.EnterMode.beforeRewardResend)
        end

        ViewList.CarQuestMainView:SetFinishCb(cb)
        Facade.SendNotification(NotifyName.ShowUI, ViewList.CarQuestMainView)
    else
        PopupOrder.Finish()
    end
    ModelList.BattleModel:SetEnterBattleFail() --选择赛车
end

function PopupOrder.Finish()
    Event.RemoveListener(EventName.Event_popup_car_quest_finish, PopupOrder.Finish)
    ModelList.CompetitionModel:SaveOldProgress()
    log.g("brocast  EventName.Event_popup_order_finish  PopupCompetitionOrder")
    Event.Brocast(EventName.Event_popup_order_finish, true)
end

return PopupOrder
