---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/28 15:12
---
require("Combat/Machine/BingoOrderMachine")
require("Combat.Machine.CallNumber.CallNumberMachine")

local UploadBattleData = { }
local this = UploadBattleData

--- 打包战斗数据
function UploadBattleData:PackFinalCardInfo( roundData )
    local finalCardInfo = {}
    
    --格子数据
    for k, v in pairs(roundData) do
        local cardId = tonumber( k)
        --local cardMarkedPos = {}
        --local cardNotMarkedPos = {}
        local cardPos = {}
        local cardReward = {}
        for m = 1, #v.cards do
            local itemReward = {}
            local pos = ConvertCellIndexToServerPos(m)
            local mark = v.cards[m].mark
            --table.each(v.cards[m].resourceHammerGift, function(itemId)
            --    table.insert(itemReward, { id = itemId, value = 1 })
            --end)
            for p = 1, #v.cards[m].gift do
                table.insert(itemReward, { id = v.cards[m].gift[p], value = 1 })
            end
            for p = 1, #v.cards[m].hide_gift do
                table.insert(itemReward, { id = v.cards[m].hide_gift[p].id, value = 1 })
            end
            --for p = 1, #v.cards[m].basket do
            --    for q = 1, #v.cards[m].basket[p].reward do
            --        table.insert(itemReward, { id = v.cards[m].basket[p].reward[q].id, value = v.cards[m].basket[p].reward[q].value })
            --    end
            --end
            table.insert(cardPos, { pos = pos, markState = mark, itemReward = itemReward })
        end
        
        --卡牌奖励数据
        local cardsInfo = ModelList.BattleModel:GetCurrModel():LoadGameData().cardsInfo
        local cardInfo = table.find(cardsInfo, function(cardID, info)
            return info. cardId == cardId
        end)
        cardReward = cardInfo and cardInfo.cardReward or {}

        local tempCardInfo = {
            cardId = cardId,
            cardPos = cardPos,
            cardReward = cardReward,
        }
        --金币火车额外数据
        --if ModelList.BattleModel:GetCurrModel():GetGameType() == PLAY_TYPE.PLAY_TYPE_GOLD_TRAIN then
        --    tempCardInfo.bingoPath = ModelList.BattleModel:GetCurrModel():GetBingoOrderByCardId(cardId, true)
        --end
        table.insert(finalCardInfo, tempCardInfo)
    end
    return finalCardInfo
end

function UploadBattleData:GetRobotsOrder()
    return BingoOrderMachine.GetRobotsOrder()
end


function UploadBattleData:GetFastClickInfo()
    return CallNumberMachine.GetFastClickData()
end

--- 常规数据外的额外数据
function UploadBattleData:GetExtInfo(roundData)
    local auto_state = fun.read_value(ModelList.PlayerInfoModel:GetUid() .. MCT.HangUpAutoPowerConfig, 1)
    local ext = { cardHitCocktailTransform = {}, powerupAuto = auto_state ,doubleNumber = {} }
    for k, v in pairs(roundData) do
        local cardExtInfo = v:GetExtInfo()
        if cardExtInfo and cardExtInfo.cardHitCocktailTransform then
            for m = 1, #cardExtInfo.cardHitCocktailTransform do
                table.insert(ext.cardHitCocktailTransform, cardExtInfo.cardHitCocktailTransform[m])
            end
        end
        if cardExtInfo and cardExtInfo.doubleNumber then
            for m = 1, #cardExtInfo.doubleNumber do
                table.insert(ext.doubleNumber, cardExtInfo.doubleNumber[m])
            end
        end
        table.each(cardExtInfo.uploadData, function(extraData, extraKey)
            ext[extraKey] = ext[extraKey] or {}
            table.each(extraData, function(v)
                table.insert(ext[extraKey], v)
            end)
        end)
    end
    return TableToJson(ext)
end

return this
