
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/8/14 12:05
---

FBRecommendView = BaseDialogView:New("FBRecommendView","FBRecommendAtlas")
local this = FBRecommendView
this.viewType = CanvasSortingOrderManager.LayerType.TopConsole

this.auto_bind_ui_items = {
    "btn_close",
    "btn_fb_connect",
    "main_anim"
}

function FBRecommendView:Awake()
    this:on_init()
end

function FBRecommendView:OnEnable()
    Facade.RegisterView(this)
end

function FBRecommendView:OnDisable()
    Facade.RemoveView(this)
    Event.Brocast(EventName.Event_previous_enter_homescene,true)
    this.doLogin = nil
end

function FBRecommendView:on_close()

end

function FBRecommendView:OnDestroy()
    LuaTimer:ClearTaskList(this.delay_action)
    this.delay_action = nil
    this.close_action = nil
    this.bind_action = nil
    this:Close()
end

function FBRecommendView:ToClose()
    if this.close_action then
        this.close_action()
        this.close_action = nil
    end

    this.main_anim:Play("end")
    this.delay_action = this.delay_action or {}
    this.delay_action[#this.delay_action + 1] = LuaTimer:SetDelayFunction(0.31, function()
        --fun.set_active(this.go,false)
        Facade.SendNotification(NotifyName.CloseUI,this)
    end)
end

function FBRecommendView:on_btn_close_click()
    --[[
    if Http.get_session_is_empty() then
        ModelList.loginModel.GuestLogin()
    end
    --]]
    this:ToClose()
end
function FBRecommendView:on_btn_fb_connect_click()
    if not this.doLogin then
        this.doLogin = true
        ModelList.loginModel.FbLogin(function(code)
            this.doLogin = false
            if code and code == RET.RET_ACCOUNT_BIND_NOT_CURRENT then
                UIUtil.show_common_error_popup(9037,true,function()
                    ModelList.loginModel.user_logout()
                end)
            else
                UIUtil.show_common_error_popup(8010,true,nil)
            end
        end,function()
            this:ToClose()
        end)
    end
end

function FBRecommendView.OnUserLogoutRespone(data)
    if data == RET.RET_FAILED then --这里等于1是成功的，不要看字面意思
        ModelList.loginModel.LogoutHandle()
        Facade.SendNotification(NotifyName.ShowUI,ViewList.SceneLoadingGameView,nil,nil,JumpSceneType.ToLogin)
    end
end

this.NotifyList = {
    {notifyName = NotifyName.Login.LogoutRespone,func = this.OnUserLogoutRespone}
}

return this

