---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/17 14:37
---

--- SuperMactch活动卡牌加载
local  CardLoad = Clazz(ClazzBase,"CardLoad")
local this = CardLoad
this.number_img_num = 10 --数字的图片数量

--- 初始卡牌上掉落的所有道具Obj
this.total_cell_gift = {}
--- 初始卡牌上的道具
this.all_flash_gift = {}

function CardLoad:SetCardView(cardView)
    this.cardView = cardView
end

--普通战斗卡牌加载
function CardLoad:LoadNormalCardData()
    local count = #this.cardView.loadData.cardsInfo
    for i = 1, count do
        local obj = this.cardView:GetCardMap(i)
        --this:InitCardChild(obj, this.cardView.loadData.cardsInfo[i].cardId)
        this.cardView.idToMap[tostring(this.cardView.loadData.cardsInfo[i].cardId)] = obj
    end
    for i = count+1, 4 do
        local obj = this.cardView:GetCardMap(i)
        if obj then
            fun.set_active(obj,false)
        end
    end
    this:InitCardChildData()
end


--初始化卡牌棋局子部分
function CardLoad:InitCardChildData ()
    this.total_cell_gift = {}
    this.all_flash_gift = {}
    this.model = ModelList.BattleModel:GetCurrModel()
    --- 生成卡牌棋局格子数据,不做表现
    --this:SetLogicRoundData()
    --- 设置卡牌初始形态
    if this.cardView then
        this.cardView:InitCardOver(false)
    end
    --coroutine.start(function()
    --    for k, v in pairs(this.cardView.loadData.cardsInfo) do
    --        for m, n in ipairs(v.numbers) do
    --            local item_info_list = {}
    --            for p, q in pairs(v.cardNumberReward) do
    --                if q.number == n and q.items then
    --                    item_info_list = q.items
    --                    break
    --                end
    --            end
    --            this:LoadCardData(v.cardId, m, n, item_info_list)
    --            WaitForEndOfFrame()
    --        end
    --        this:LoadCardReward(v.cardId, v.cardReward)
    --    end
    --    if this.cardView then
    --        this.cardView:InitCardOver(true)
    --    end
    --end)

    if this.cardView then
        this.cardView:InitCardOver(true)
    end
end

--- 仅初始化卡牌棋局格子数据
function CardLoad:SetLogicRoundData()
    for k, v in pairs(this.cardView.loadData.cardsInfo) do
        for m, n in ipairs(v.numbers) do
            local item_info_list = {}
            for p, q in pairs(v.cardNumberReward) do
                if q.number == n and q.items then
                    item_info_list = q.items
                    break
                end
            end
            this: OnlyLoadCardData(v.cardId, m, n, item_info_list)
        end
    end
end

local GetItemInfo = function(itemId)
    if itemId < 1000 then
        return Csv.GetData("resources", itemId),false
    elseif 4 == math.floor(itemId/10000000) then
        local item_id = Csv.GetData("item_synthetic",itemId,"itemid")
        return Csv.GetData("item",item_id),true
    else
        return Csv.GetData("item", itemId),true
    end
end

--- 每个道具的信息
local function CreateGiftInfo(obj,anim,itemId,count,mapIndex,cellIndex)
    table.insert(this.total_cell_gift, {obj = obj,anim = anim, itemId = itemId,num = count,mapIndex = mapIndex,cellIndex = cellIndex})
end
--- 赛季令牌经验
local function CreateFlashGiftInfo(obj,anim,itemId,count)
    table.insert(this.all_flash_gift, {obj = obj,anim = anim, itemId = itemId,num = count})
end

--- 赛季令牌经验
local function CreateFlashClone(card_reference,cell_reference)
    local flashParent = nil
    local obj = nil
    if cell_reference and cell_reference:Get("flash_clone")  then
        flashParent = cell_reference:Get("flash_clone")
        obj = fun.get_instance(cell_reference:Get("flash_clone"), flashParent)
    else
        flashParent = fun.find_child(cell_reference:Get("gift").transform,"flash_parent")
        obj = fun.get_instance(card_reference:Get("flash_clone"), flashParent)
    end
    obj.gameObject.name = "flash_clone"
    if ModelList.BattleModel:IsHangUp() then
        fun.set_gameobject_scale(obj, 0.6, 0.6, 1)
        fun.set_gameobject_pos(obj, 0,0,0,true)
    else
        fun.set_gameobject_pos(obj, -53.6,-35.1,0,true)
    end
    return obj
end

-- 杯赛道具(与赛季令牌使用相同动画，所以这里直接使用令牌的obj)
local function CreateCompetitionItemInfo(card_reference,anim,itemId,count,cell_reference)
    local flashParent = cell_reference:Get("gift")
    local obj = fun.get_instance(card_reference:Get("flash_clone"), flashParent,true)
    obj.gameObject.name = string.format("competition_clone-%s", itemId)
    --obj = fun.get_instance(obj, obj.transform.parent, true)

    --右下角
    local curModel = ModelList.BattleModel:GetCurrModel()
    local offsetX, offsetY = curModel:GetQuestItemOffsetPos(itemId)
    fun.set_rect_local_pos(obj, offsetX, offsetY, 0)
    local scale = curModel:GetQuestItemScale()
    fun.set_gameobject_scale(obj, scale, scale, 1)

    local image = fun.get_component_in_child(obj, UnityEngine.UI.Image)
    if fun.is_not_null(image) then
        local spriteName = Csv.GetItemOrResource(itemId, "icon")
        if not fun.is_empty_str(spriteName) then
            Cache.GetSpriteByName("GameItemAtlas", spriteName, function(sprite)
                if not fun.is_null(sprite) then
                    image.sprite = sprite
                    image:SetNativeSize()
                    fun.set_gameobject_scale(image.gameObject, 0.3, 0.3, 1)
                end
            end)
        end
    end

    table.insert(this.all_flash_gift, {obj = obj,anim = anim, itemId = itemId,num = count})
end

-- WinZone道具
local function CreateWinZoneItem(card_reference, anim, itemId, count, cell_reference)
    local flashParent = cell_reference:Get("gift")
    local obj = fun.get_instance(card_reference:Get("flash_clone"), flashParent, true)
    obj.gameObject.name = "winzone_clone"

    --左上角
    local curModel = ModelList.BattleModel:GetCurrModel()
    local offsetX, offsetY = curModel:GetWinZoneItemOffsetPos()
    local scale = curModel:GetWinZoneItemScale()
    fun.set_rect_local_pos(obj, offsetX, offsetY, 0)
    fun.set_gameobject_scale(obj, scale, scale, 1)

    local image = fun.get_component_in_child(obj, UnityEngine.UI.Image)
    if fun.is_not_null(image) then
        local spriteName = Csv.GetItemOrResource(itemId, "icon")
        if not fun.is_empty_str(spriteName) then
            Cache.GetSpriteByName("GameItemAtlas", spriteName, function(sprite)
                if not fun.is_null(sprite) then
                    image.sprite = sprite
                    image:SetNativeSize()
                    fun.set_gameobject_scale(image.gameObject, 0.5, 0.5, 1)
                    --fun.set_recttransform_native_size(obj, 80, 80)
                end
            end)
        end
    end

    table.insert(this.all_flash_gift, { obj = obj, anim = anim, itemId = itemId, num = count })
end

--- 仅设置单个卡牌数，不做表现层修改
---@param item_info_list table  卡牌奖励
function CardLoad:OnlyLoadCardData (mapIndex, cellIndex, number, item_info_list)

end



--加载所有卡牌数据
---@param item_info_list table  卡牌奖励
function CardLoad:LoadCardData (mapIndex, cellIndex, number, item_info_list)

    --this:LoadCellNumber(number,ref_temp)

    --this:AddCellRewardBind(gift_obj, item_info_list)
end





--获取卡牌棋局子部分
function CardLoad:InitCardChild (cardPar, tCardId)
    local ref_temp = cardPar:GetComponent(fun.REFER)
    this.model = ModelList.BattleModel:GetCurrModel()
    local cellmap = {}
    for i = 1, 25, 1 do
        local cardCell = ref_temp:GetByIndex(i)
        table.insert(cellmap, cardCell)
        this.model:GetRoundData(tCardId,i):BindObj(cardCell)
    end
    this.cardView:SetCardCell(tCardId,cellmap)
end


function CardLoad:StartDropCellItemEffect()

end

--检查放大镜，决定是否播放放大镜出场动效
function CardLoad.CheckMirror()

end

function CardLoad.Register()
    --Event.AddListener(EventName.PowerUpEffect_FoodBagFlyToCard,this.FoodBagFlyToCard)
    --Event.AddListener(EventName.CardEffect_Drop_All_Cell_Item,this.StartDropCellItemEffect)
    --Event.AddListener( Notes.START_MIRROR_CHECK,this.CheckMirror)
end

function CardLoad.UnRegister()
    --Event.RemoveListener(EventName.CardEffect_Drop_All_Cell_Item,this.StartDropCellItemEffect)
    --Event.RemoveListener(EventName.PowerUpEffect_FoodBagFlyToCard,this.FoodBagFlyToCard)
    --Event.RemoveListener( Notes.START_MIRROR_CHECK,this.CheckMirror)
end

function CardLoad:OnDisable()
    this.UnRegister()
end


--- 优化项：把卡牌Bingo字母的高亮特效单独放置
function CardLoad:RepositionCardLetterEffect(mapList,effectNode)

end

return this