--
--require "State/Common/CommonState"
--
--local QuickTaskPromotedView = BaseView:New("QuickTaskPromotedView","QuickTaskPromotedAtlas")
--local this = QuickTaskPromotedView
--this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--
--this.auto_bind_ui_items = {
--    --"quickTask",
--    "img_rewardIcon",
--    "btn_close",
--    "btn_continue",
--    "text_collect",
--    "text_grandPrize",
--    "text_rewardValue",
--    "anima"
--}
--
--function QuickTaskPromotedView:Awake()
--    self:on_init()
--end
--
--function QuickTaskPromotedView:OnEnable(params)
--    --local _topQuickTask = TopQuickTaskView:New()
--    --_topQuickTask:SkipLoadShow(self.quickTask)
--
--    local task_data = nil
--    for key, value in pairs(Csv.task) do
--        if value.task_type == TaskToggle.quick then
--            if not task_data or value.id > task_data.id then
--                task_data = value
--            end
--        end
--    end
--    if task_data then
--        local reward_icon = "cIconCoins02"
--        if task_data.reward[1][1] == Resource.diamon then
--            reward_icon = "cIconGems02"
--        end
--        --Cache.SetImageSprite("CommonAtlas","",self.img_rewardIcon)
--        self.text_rewardValue.text = tostring(task_data.reward[1][2])
--    end
--
--    local quickTask = ModelList.ActivityModel:GetQuickTaskActive()
--    if quickTask then    --如果为负数直接显示为0
--        self.text_collect.text = string.format("Collect %s Cookies to win the reward!",tonumber(quickTask.target) - tonumber(quickTask.progress) >=0 and tonumber(quickTask.target) - tonumber(quickTask.progress) or 0 )
--    end
--
--    CommonState.BuildFsm(self,"QuickTaskPromotedView")
--    self._fsm:GetCurState():DoOriginalAction(self._fsm,"CommonState1State",function()
--        AnimatorPlayHelper.Play(self.anima,{"QuickTaskPromotedViewstart","QuickTaskPromotedViewstart"},false,function()
--            self._fsm:GetCurState():DoCommonState1Action(self._fsm,"CommonOriginalState")
--        end)
--    end)
--end
--
--function QuickTaskPromotedView:OnDisable()
--    Event.Brocast(EventName.Event_popup_activity_finish)
--    CommonState.DisposeFsm(self)
--end
--
--function QuickTaskPromotedView:on_btn_close_click()
--    self._fsm:GetCurState():DoOriginalAction(self._fsm,"CommonState1State",function()
--        AnimatorPlayHelper.Play(self.anima,{"QuickTaskPromotedViewend","QuickTaskPromotedViewend"},false,function()
--            Facade.SendNotification(NotifyName.CloseUI,this)
--        end)
--    end)
--end
--
--function QuickTaskPromotedView:on_btn_continue_click()
--    self:on_btn_close_click()
--end
--
--return this