---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/12 11:38
---

local GameBingosLeftView = BaseView:New('GameBingosLeftView')
local this = GameBingosLeftView;
this.__index = this
this.auto_bind_ui_items = {
    "BingosiLeftBig",
    "BingosiLeftMid",
    "BingosiAnima",
    "red_call_number",
}
this.currCount = 0

function GameBingosLeftView:New()
    local o = {}
    o.__index = self
    setmetatable(o, this)
    return o
end

function GameBingosLeftView.Awake()
    Facade.RegisterView(this)
end

local IsOpenRedBingoleft = true

function GameBingosLeftView.OnEnable()
    this.model = ModelList.BattleModel:GetCurrModel()
    this.currCount = this.model:LoadGameData().bingoLeft
    this.targetNum = this.currCount
    IsOpenRedBingoleft = (not ModelList.GuideModel:IsFirstBattle())
end

--function GameBingosLeftView.OnDisable()
--    --Facade.RemoveView(this)
--end

function GameBingosLeftView.OnDestroy()
    Facade.RemoveView(this)
    this:Close()
    this.coroutine = nil
end

function GameBingosLeftView.ShowBingosleft(completeCb)
    local leftdata = this.model:LoadBingoLeftData()
    this:CalOtherBingoCount(leftdata)
end

function GameBingosLeftView:CalOtherBingoCount(leftdata)
    local myBingoCount = 0
    if leftdata.bingo then
        for i = 1, #leftdata.bingo do
            if leftdata.bingo[i].type == 1 then
                myBingoCount = myBingoCount + 1
            end
        end
    end
    if myBingoCount > 0 then
        this.ShowBingosileftChang(myBingoCount)
    end
    local otherBingoCount = leftdata.bingoChange - myBingoCount
    if leftdata.bingoLeft == 0 then
        Event.Brocast(Notes.QUICK_REDUCE_BINGOSILEFT)
    end
    Event.Brocast(EventName.Bingo_Refresh_Other_BingoCount, otherBingoCount, leftdata.next)
end

local function ShowBigBingosileft(count)
    if IsOpenRedBingoleft and count <= 15 then
        this.BingosiLeftBig.spriteAsset = this.red_call_number.spriteAsset
    end
    this.BingosiLeftBig.text = tostring(count)
    --log.y("ShowBigBingosileft    " .. tostring(count))
end

local function ShowMidBingosileft(count)
    if IsOpenRedBingoleft and count <= 15 then
        this.BingosiLeftMid.spriteAsset = this.red_call_number.spriteAsset
    end
    this.BingosiLeftMid.text = tostring(count)
    --log.y("ShowMidBingosileft    " .. tostring(count))
end


--计算当前其他人触发的Bingo数量
function GameBingosLeftView.ShowBingosileftChang(num)
    if num == nil then
        num = 1
    end
    if this.currCount >= 0 then
        if num > 1 and this.currCount - 1 >= 0 then
            ShowBigBingosileft(this.currCount - 1)
        else
            ShowBigBingosileft(this.currCount)
        end
    end
    this.currCount = this.currCount - num
    --log.g("ShowBingosileftChang   "..num.."       "..this.currCount)
    if this.currCount >= 0 then
        ShowMidBingosileft(this.currCount)
    else
        ShowMidBingosileft(0)
    end
    if this.currCount > 15 or (ModelList.GuideModel:IsFirstBattle() and this.currCount >= 0) then
        this.BingosiAnima:SetInteger("count", 10)
        this.BingosiAnima:Play("otherbingo", -1, 0)
        --log.g("ShowBingosileftChang  otherbingo   ")
    elseif this.currCount >= 0 then
        this.BingosiAnima:SetInteger("count", this.currCount)
        this.BingosiAnima:Play("otherbingo5")
       -- log.g("ShowBingosileftChang  otherbingo5 ")
    end

    Event.Brocast(EventName.Bingo_Refresh_BingoCount, this.currCount)
end

function GameBingosLeftView.OnForcedExitBingoLeft()
    this.BingosiAnima:SetInteger("count", 0)
    this.BingosiAnima:Play("otherbingo5")
end

--bingosileft涨至最大效果
function GameBingosLeftView.StartNumberAddToMaxEffect ()
    this.BingosiLeftBig.text = 0
    local start_num = 0.05   --20次
    LuaTimer:SetDelayLoopFunction(0, 0.15, 21, function()
        local p = math.pow(start_num, 2)
        local p2 = tonumber(p)
        if p2 >= 1 then
            p2 = 1
        end
        p2 = math.ceil(p2 * this.targetNum)
        start_num = start_num + 0.05
        this.BingosiLeftBig.text = tostring(p2)
    end,nil, nil,LuaTimer.TimerType.Battle)
end

-- bingosileft数量为0
function GameBingosLeftView:ReduceBingosiToZero ()
    --    log.r("RefreshBingosi")
    local leftObj = fun.find_child(this.Bingosi, "BingosiLeft")
    local leftTxt = fun.get_component(leftObj, "Text")
    --leftTxt.text = "0"
end

function GameBingosLeftView:GetCurrBingoLeftNum()
    if this.currCount <0 then
        return 0
    end
    return this.currCount
end

function GameBingosLeftView:CoroutineEnable()
    if this.coroutine ~= nil then
        coroutine.stop(this.coroutine)
    end
    this.coroutine = nil
    this.coroutine = coroutine.start(function()
        coroutine.wait(1)
        if self and fun.is_not_null(self.go) then
            this.oriPos = fun.get_localposition(self.go)
            fun.set_gameobject_pos(self.go,10000,10000,0,true)
            fun.set_active(self.go, true)
        end
        coroutine.wait(1)
        if self and fun.is_not_null(self.go) and this.oriPos then
            --fun.set_active(self.go, false)
            fun.set_gameobject_pos(self.go,this.oriPos.x,this.oriPos.y,this.oriPos.z,true)
        end
        this.coroutine = nil
    end)
end

this.NotifyList = {
    { notifyName = NotifyName.Bingo.Sync_Bingos, func = this.ShowBingosleft },
    { notifyName = NotifyName.Bingo.REFRSH_BINGOSI_CHANGE, func = this.ShowBingosileftChang },
    { notifyName = NotifyName.Bingo.StartBingosleftIncrease, func = this.StartNumberAddToMaxEffect },
    { notifyName = NotifyName.Bingo.QuickReduceBingosiToZero, func = this.ReduceBingosiToZero },
    {notifyName = NotifyName.Bingo.ForcedExitBingoLeft, func = this.OnForcedExitBingoLeft }
}

return this