--require "State/Common/CommonState"
--local TopQuickTaskView = require("View/CommonView/TopQuickTaskView")
--local QuickTaskDetailView = BaseView:New("QuickTaskDetailView","QuickTaskPromotedAtlas")
--local this = QuickTaskDetailView
--this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--
--this.auto_bind_ui_items = {
--    "btn_close",
--    "btn_help",
--    "content",
--    "detail_item",
--    "quickTask",
--    "anima",
--    "scroll"
--}
--
--function QuickTaskDetailView:Awake()
--    self:on_init()
--end
--
--function QuickTaskDetailView:OnEnable(params)
--    local _topQuickTask = TopQuickTaskView:New()
--    _topQuickTask:SkipLoadShow(self.quickTask)
--
--    local task_data = {}
--    local step = 0
--    for key, value in pairs(Csv.task) do
--        if value.task_type == TaskToggle.quick then
--            step = step + 1
--            table.insert(task_data,value)
--        end
--    end
--    table.sort(task_data,function(a,b)
--        return a.id > b.id
--    end)
--
--    local quickTask = ModelList.ActivityModel:GetQuickTaskActive()
--    local detail_item = require "View/Task/QuickTaskDetailItem"
--    local pos_index = 0
--    for index, value in ipairs(task_data) do
--        local go = fun.get_instance(self.detail_item.transform,self.content)
--        fun.set_active(go.transform,true,false)
--        local item = detail_item:New(value,step)
--        step = step - 1
--        item:SkipLoadShow(go)
--        if quickTask.id == value.id then
--            pos_index = index
--        end
--    end
--
--    CommonState.BuildFsm(self,"QuickTaskPromotedView")
--    self._fsm:GetCurState():DoOriginalAction(self._fsm,"CommonState1State",function()
--    AnimatorPlayHelper.Play(self.anima,"QuickTaskPromotedViewstart",false,0.2,function()
--            self.scroll:StopMovement()
--            Anim.move(self.content,0,math.max(0,pos_index - 1) * 165,0,0.1,true,true,function()
--                self.scroll.inertia = true
--            end)
--        end,function()
--            self._fsm:GetCurState():DoCommonState1Action(self._fsm,"CommonOriginalState")
--        end)
--    end)
--end
--
--function QuickTaskDetailView:OnDisable()
--    CommonState.DisposeFsm(self)
--end
--
--function QuickTaskDetailView:on_btn_close_click()
--    self._fsm:GetCurState():DoOriginalAction(self._fsm,"CommonState1State",function()
--        AnimatorPlayHelper.Play(self.anima,{"QuickTaskPromotedViewend","QuickTaskPromotedViewend"},false,function()
--            Facade.SendNotification(NotifyName.CloseUI,this)
--        end)
--    end)
--end
--
--function QuickTaskDetailView:on_btn_help_click()
--    Facade.SendNotification(NotifyName.ShowUI,ViewList.QuickTaskPromotedView)
--end
--
--return this