---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/9/1 18:13
---
local SettleBaseState = require("State/Settle/SettleBaseState")
local SettleOneState = Clazz(SettleBaseState,"SettleOneState")

function SettleOneState:ClickDrawCard(fsm,gear)
    if fsm then
        fsm:GetOwner():OnClickDrawCard(gear)
    end
end

function SettleOneState:TurnPage(fsm,dir)
    if fsm then
        fsm:GetOwner():OnTurnPage(dir)
    end
end

function SettleOneState:DrawCard(fsm,waitCount)
    if fsm then
        self:ChangeState(fsm,"PowerUpDrawCardState",waitCount)
    end
end

function SettleOneState:Play(fsm)
    if fsm then
        fsm:GetOwner():OnPlay()
    end
end

function SettleOneState:OnEnter(fsm)

end
return SettleOneState