--auto generate by C# editor: Tools/自动生成AssetList.lua脚本
local AssetList = {}
local this = AssetList
------------------asset map,key to assetbundle_name-----------------
----------------------------Assets\Bundles\Modules------------------------------------------
this.GoldenTrainBingoView = "modules/goldentrain/inhotmodule/abprefab/goldentrainbingoview"
this.GoldenTrainHallView = "modules/goldentrain/inhotmodule/abprefab/goldentrainhallview"
this.GoldenTrainHelpView = "modules/goldentrain/inhotmodule/abprefab/goldentrainhelpview"
this.GoldenTrainReadyView = "modules/goldentrain/inhotmodule/abprefab/goldentrainreadyview"
this.GoldenTrainSettleView = "modules/goldentrain/inhotmodule/abprefab/goldentrainsettleview"
this.Play30HallBackground = "modules/goldentrain/inhotmodule/abprefab/play30hallbackground"
this.play30zhandou = "modules/goldentrain/inhotmodule/abprefab/play30zhandou"
this.SettleGoldenTrainPerformanceView = "modules/goldentrain/inhotmodule/abprefab/settlegoldentrainperformanceview"
this.SettleGoldenTrainPerformanceVieweffect = "modules/goldentrain/inhotmodule/abprefab/settlegoldentrainperformancevieweffect"
this.FunctionIcon = "modules/goldentrain/inhotmodule/abprefab/pass/functionicon"
this.GiftPackGoldenTrainBuffView = "modules/goldentrain/inhotmodule/abprefab/pass/giftpackgoldentrainbuffview"
this.PassHelperView = "modules/goldentrain/inhotmodule/abprefab/pass/passhelperview"
this.PassPurchaseView = "modules/goldentrain/inhotmodule/abprefab/pass/passpurchaseview"
this.PassReceivedView = "modules/goldentrain/inhotmodule/abprefab/pass/passreceivedview"
this.PassRewardView = "modules/goldentrain/inhotmodule/abprefab/pass/passrewardview"
this.PassShowTipView = "modules/goldentrain/inhotmodule/abprefab/pass/passshowtipview"
this.PassTaskView = "modules/goldentrain/inhotmodule/abprefab/pass/passtaskview"
this.PassView = "modules/goldentrain/inhotmodule/abprefab/pass/passview"
this.Rewarditem = "modules/goldentrain/inhotmodule/abprefab/pass/rewarditem"
this.GoldRushDlpBg = "modules/goldentrain/inhotmodule/texture/abtexture/goldrushdlpbg"
this.SceneGoldenTrain = "modules/goldentrain/inhotmodule/scene/scenegoldentrain"
this.GoldenTrainBingobingo = "modules/goldentrain/inhotmodule/effect/abprefab/goldentrainbingobingo"
this.GoldenTrainEmpty = "modules/goldentrain/inhotmodule/effect/abprefab/goldentrainempty"
this.GoldenTraingetxiaoka = "modules/goldentrain/inhotmodule/effect/abprefab/goldentraingetxiaoka"
this.GoldenTrainhuaxian = "modules/goldentrain/inhotmodule/effect/abprefab/goldentrainhuaxian"
this.GoldenTrainskill1yinzhang = "modules/goldentrain/inhotmodule/effect/abprefab/goldentrainskill1yinzhang"
this.GoldenTrainskill2lanbi = "modules/goldentrain/inhotmodule/effect/abprefab/goldentrainskill2lanbi"
this.CoinTrain1Bullion00 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion00"
this.CoinTrain1Bullion01 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion01"
this.CoinTrain1Bullion02 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion02"
this.CoinTrain1Bullion03 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion03"
this.CoinTrain1Bullion04 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion04"
this.CoinTrain1Bullion05 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion05"
this.CoinTrain1Bullion06 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion06"
this.CoinTrain1Bullion07 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion07"
this.CoinTrain1Bullion_zhuan03 = "modules/goldentrain/inhotmodule/effect/materials/cointrain1bullion_zhuan03"
this.CoinTrainLian01 = "modules/goldentrain/inhotmodule/effect/materials/cointrainlian01"
this.CoinTrainLian02 = "modules/goldentrain/inhotmodule/effect/materials/cointrainlian02"
this.CoinTrainLiansui = "modules/goldentrain/inhotmodule/effect/materials/cointrainliansui"
this.kuan01 = "modules/goldentrain/inhotmodule/effect/materials/kuan01"
this.ScratchWinnersuipian = "modules/goldentrain/inhotmodule/effect/materials/scratchwinnersuipian"
this.GiftPackGoldenTrainBuffAtlas = "modules/goldentrain/inhotmodule/atlas/giftpackgoldentrainbuffatlas"
this.GoldenTrainPassTaskAtlas = "modules/goldentrain/inhotmodule/atlas/goldentrainpasstaskatlas"
this.GoldenTrainPerformanceAtlas = "modules/goldentrain/inhotmodule/atlas/goldentrainperformanceatlas"
this.GoldenTrainPopupAtlas = "modules/goldentrain/inhotmodule/atlas/goldentrainpopupatlas"
this.GoldenTrainPurchaseAtlas = "modules/goldentrain/inhotmodule/atlas/goldentrainpurchaseatlas"

return this
