---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/4/14 12:33
---

--- 杯赛历史奖励弹窗

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder,"")
local this = PopupOrder

function PopupOrder.Execute(occasion)
    if occasion ~= PopupOrderOccasion.changeCity and
            ModelList.CompetitionModel:HasHistoryReward() then
        Event.AddListener(EventName.Event_popup_competition_history,PopupOrder.Finish)
        --Event.Brocast(EventName.Event_show_competition_history)
        ModelList.CompetitionModel.ShowCompetitionHistoryRankInfo()
    else
        PopupOrder.Finish()
    end
end

function PopupOrder.Finish()
    Event.RemoveListener(EventName.Event_popup_competition_finish,PopupOrder.Finish)
    log.g("brocast  EventName.Event_popup_order_finish ")
    Event.Brocast(EventName.Event_popup_order_finish,true)
end

return PopupOrder