---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zlc.
--- DateTime: 2020/8/6 14:31
---


BaseSceneLoadingView = BaseGobalView:New('BaseSceneLoadingView');
local this = BaseSceneLoadingView;

this.__index = this;

--创建View对象--
function BaseSceneLoadingView:New(viewName, atlasName)
    local o = {viewName = viewName, atlasName = atlasName, isShow = false, isLoaded = false,changeSceneClear = false}
    self.__index = self
    setmetatable(o, self)
    return o
end

function BaseSceneLoadingView:on_x_update()
    if this.loadingScene == false then --延迟到下一帧执行跳转场景
        this.loadingScene = true
        this:LoadScene(this:getNextSceneName())
    end
    if this.operation == nil then
        return
    end

    this:update_process()

    -- this.operation.allowSceneActivation = false
    local absProcess =  math.abs(1-this.curProcess)
    
    -- log.r("absProcess:",absProcess," can_next_step",this.can_next_step)
    if absProcess<0.01 and this.can_next_step == true then
        this:load_scene()
        this:stop_x_update()
    end

end


function BaseSceneLoadingView:load_scene()
    -- this.operation.allowSceneActivation = true
    if this.operation then
        this.operation:UnSuspend()
    end
end

function BaseSceneLoadingView:update_process()
    if this.curProcess< this:getTargetProcess() then
        -- log.r(Time.deltaTime * this.process_move_speed)
        --this.curProcess = this.curProcess + Time.deltaTime * this.process_move_speed --Time.deltaTime受帧率影响
        this.curProcess = this.curProcess + 1/60 * this.process_move_speed --使得不受帧率影响
        this.curProcess = this.curProcess-this.curProcess%0.001   --保留3位小数
      
        if(this.curProcess>this:getTargetProcess())then
            this.curProcess = this:getTargetProcess()
        end
    end
    this:setProcess(this.curProcess)
end

function BaseSceneLoadingView:on_init_UI()
    this.can_next_step = false
    this.curProcess = 0.1
    this:setProcess(this.curProcess)
    this.loadingScene = false
    this.process_move_speed = ArtConfig.BaseSceneLoading_Process_Move_Speed
end

function BaseSceneLoadingView:setProcess(value) 
    value = math.min(value,1)
    if(not fun.is_null(this.slider_progress))then
        this.slider_progress.value = value
    end
    
    if(not fun.is_null(this.txt_progress))then
        -- log.r(value)
        this.txt_progress.text = tostring(math.floor(value*100)).."%"
    end 
end

--缓存资源
function BaseSceneLoadingView:LoadScene(SceneName,procedure)
    print("============================================>>BaseSceneLoadingView " .. SceneName)
    --预加载场景
    LoadSceneAsync(SceneName,procedure,function(operation)
        this.operation = operation
        -- this.operation.allowSceneActivation = false
    end)
    this:LoadSceneRes(function ()
        this.can_next_step  = true
    end)
end
function BaseSceneLoadingView:getTargetProcess()
    if this.operation == nil then
        return 0.1
    end
    -- return this.operation.progress + 0.1
    return this.operation.Progress + 0.1
end
function BaseSceneLoadingView:getNextSceneName()---for override
    return "SceneHome"
end
function BaseSceneLoadingView:LoadSceneRes(callBack) ---for override
    ------加载混音器
end
function BaseSceneLoadingView:SetLoadingTips(tipStr) 

    if(this.invoke_tips ~=nil)then
        this.invoke_tips:Stop()
        this.invoke_tips = nil
    end

    this.invoke_tips = this:register_invoke_repeat(function()
        if(this.loadingNumIdx ==nil)then
            this.loadingNumIdx = 1
        end

        this.loadingNumIdx = (this.loadingNumIdx)%4
        if(this.loadingNumIdx==0)then this.loadingNumIdx = 1 end
        local str = tipStr
        for i=1,this.loadingNumIdx do
            str = str.."."
        end
        this.loadingNumIdx = this.loadingNumIdx+1

        this.txt_tips.text = str
    end,0.3)
end

return this