---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/5/17 19:32
---
require("Scene/CityHomeScene")
local GuideSceneLoadingGameView = BaseSceneLoadingView:New("SceneLoadingGameView","SceneLoadingGameAtlas")
local this = GuideSceneLoadingGameView

this.isCleanRes = true
this.enable_time = 0
this.is_load_next  = false
this.total_time =0
this.curr_index = 0
this.loadRes = 0
---@field JumpSceneType
local JumpSceneType = {None = 0, ToHomeScene = 1,ToNormalGame = 2,ToHangUpGame = 3}
local jumpSceneType = JumpSceneType.ToNormalGame
this.isLoadBattleRes = false

this.sprite_container = nil


function GuideSceneLoadingGameView:Awake()
    --GuideSceneLoadingGameView.RegCommand()
    this:on_init()
    this.on_init_ui()
    this.loadRes =0
    this.isLoadBattleRes = false
    this:load_res()
    UISound.stop_bgm()
    jumpSceneType = JumpSceneType.ToNormalGame
end

function GuideSceneLoadingGameView:OnEnable()
    this.update_x_enabled = true
    this:start_x_update()
    this.on_init_ui()
    this.enable_time = 0
    this.is_load_next = false
    this:ReadyEnterBattle()
    this:Register()
end

function GuideSceneLoadingGameView.on_init_ui()
    this:on_init_battle_ui()
end

function GuideSceneLoadingGameView.FadeIn()
    local canvas_group = fun.get_component(this.go,fun.CANVAS_GROUP)
    if canvas_group then
        Anim.canvas_group_do_fade_loop(canvas_group,0, 1, 1,0.2,0, function()
            --this:LoadSceneGame()
        end)
    else
        --this:LoadSceneGame()
    end
end

function GuideSceneLoadingGameView.OnLoadSceneComplete()
    this.FadeOut()
end

function GuideSceneLoadingGameView.FadeOut()
    this:FadeOutForBattle()
end

function GuideSceneLoadingGameView:load_scene()
    if(this.isLoad==nil)then this.isLoad = false end
    if(not this.isLoad)then
        this.isLoad = true
        -- this.operation.allowSceneActivation = true
        this.operation:UnSuspend()
        this.FadeOut()
    end
end

function GuideSceneLoadingGameView:getNextSceneName()
    return "SceneGame"
end


local AddLoadPercent = function()

    this.loadRes =  this.loadRes + 1
    log.r("AddLoadPercent   "..this.loadRes)
end

function GuideSceneLoadingGameView:load_res()
    this.loadRes = 0
    AssetManager.load_audiomixer(function()
        AddLoadPercent()
    end)
    UISound.load_guide_res(function()
        AddLoadPercent()
    end)
    UISound.load_machine_and_commonUI_res(function()
        AddLoadPercent()
    end)
    AssetManager.load_guide_common_res(function() --加载通用ab资源
        AddLoadPercent()
    end)
    AssetManager.load_game_res(function()
        AddLoadPercent()
    end)
    this:InitCityBg()
    this.isLoadBattleRes = true
end

function GuideSceneLoadingGameView:InitCityBg()
    local packageId =  tostring(ModelList.CityModel:GetCity())
    this:LoadCityBackgrounnd("city" .. packageId .. "zhandou")
end

function GuideSceneLoadingGameView:LoadCityBackgrounnd(bg_name)
    if bg_name then
        local bg = AssetList[bg_name] --string.format("luaprefab_textures_battleground",bg_name)
        Cache.load_prefabs(bg, bg_name, function(objs)
            if ViewList.GameBingoView.go then
                local clone = fun.get_instance(objs, ViewList.GameBingoView.go.transform)
                fun.set_gameobject_scale(clone, 1, 1, 1)
            end
        end)
    end
end


function GuideSceneLoadingGameView:on_x_update()
    this:on_x_update_battle()
end

function GuideSceneLoadingGameView:on_x_update_battle()
    if not this.is_load_next and ModelList.BattleModel:IsReadyEnterScene() then
        this.is_load_next = true
        log.r("GuideSceneLoadingGameView   load  battle")
        LoadSceneAsync(this:getNextSceneName(),ProcedureNormalGame:New(),function(operation)
            this.operation = operation
            --local game_type = ModelList.BattleModel:GetGameType()
            --if game_type == 2 then
            --    UISound.load_hangup_res()
            --end
            AddLoadPercent()
        end)
    end
    if this.loadRes >= 6  then
        this.loadRes = 0
        if this.operation then
            -- this.operation.allowSceneActivation = true
            this.operation:UnSuspend()
            ProcedureManager.ShowReadyView()
            this:FadeOut()
        else
            SDK.send_error_log_to_server("not load guide battle scene operation")
        end
        this:FadeOut()
    end


end




function GuideSceneLoadingGameView:CheckLoadError()
    this.enable_time = this.enable_time - UnityEngine.Time.deltaTime
    if this.enable_time <= 0 then
        ModelList.BattleModel:BackToHallScene()
        this:FadeOut()
    end
end


function GuideSceneLoadingGameView:OnDestroy()
    this:UnRegister()
    this:Close()
end




-------------------------------------------------enter Battle ----------------------------------

function GuideSceneLoadingGameView:ReadyEnterBattle()
    Facade.SendNotification(NotifyName.PreLoadMachineRes)
    UISound.load_loading_res(function()
        --UISound.play("pop")
    end)
    Cache.Load_Atlas(AssetList["BingoAtlas"],"BingoAtlas")
    Cache.Load_Atlas(AssetList["SettleAtlas"],"SettleAtlas")
    this.enable_time = MCT.load_game_time_out
end

function GuideSceneLoadingGameView:on_init_battle_ui()

end

function GuideSceneLoadingGameView:FadeOutForBattle()
    UISound.unload_lobby_res()
    local canvas_group = fun.get_component(this.go,fun.CANVAS_GROUP)
    if canvas_group then


        Anim.canvas_group_do_fade_loop(canvas_group,1, 0.3, 1,0.2,0, function()
            UISound.stop("pop")
            this:Close();
            UISound.unload_loading_res()
        end)
    else
        UISound.stop("pop")
        this:Close();
        UISound.unload_loading_res()
    end
    GlobalBattleMachineList.StartBattleGlobalMachine()
    Facade.SendNotification(NotifyName.CloseUI,self)
end


function GuideSceneLoadingGameView:Register()
    Event.AddListener(EventName.Event_Loading_Game_Receive_Battle_Data,this.OnReceiveBattleData)
end

function GuideSceneLoadingGameView:UnRegister()
    Event.RemoveListener(EventName.Event_Loading_Game_Receive_Battle_Data,this.OnReceiveBattleData)
end

function GuideSceneLoadingGameView:OnReceiveBattleData()
    if this.isLoadBattleRes  then
        AssetManager.load_res_after_receive_battle_data()
    end
end

return this






