---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/7/2 11:26
---

require("View/GameLoading/BaseSceneLoadingView")
require("Combat.BattlePackage")
require("View/Bingo/EffectPool/BattleEffectPool")
require("View/Bingo/EffectPool/BattleEffectCache")
--require("Combat.GlobalBattleMachineList")

JumpSceneType = { None = 0, ToHomeScene = 1, ToNormalGame = 2, ToHangUpGame = 3, ToLogin = 4, Stop = 5, AutoLogin = 6 }

local SceneLoadingGameView = BaseSceneLoadingView:New("SceneLoadingGameView", "SceneLoadingGameAtlas")
local this = SceneLoadingGameView

this.is_load_next = false
this.total_time = 0
this.curr_index = 0
this.loadRes = 0
local checkFrame = 0
local jumpSceneType = JumpSceneType.None
this.isCleanRes = true
this.isLoadBattleRes = false

this.auto_bind_ui_items = {
    "view"
}
this.animNames = {
    enterActionName = "SceneLoadingGameViewenter",
    enterClipName = "efSceneLoadingGameViewenter",
    exitActionName = "efSceneLoadingGameViewexit",
    exitClipName = "efSceneLoadingGameViewexit",
}
this.sprite_container = nil
this.StopLoading = false
this.eneterAnimOver = false
this.enableParams = nil
this.isEnabled = false
this.MusicName = "pop"

function SceneLoadingGameView:CreateInstance(viewName, atlasName)
    local instance = {}
    instance.className = name
    instance.base = self
    instance.viewName = viewName
    instance.atlasName = atlasName
    setmetatable(instance, { __index = self })
    return instance
end

function SceneLoadingGameView:Awake(obj)
    Facade.RegisterView(self)
    self:on_init()
    self:on_init_ui()
    self:InitParams()

    self:LoadUISound()
    UISound.stop_bgm()
    self:CheckEnableAnima()
end

function SceneLoadingGameView:InitParams()
    self.loadRes = 0
    self.eneterAnimOver = false
    self.enableParams = nil
    self.isLoadBattleRes = false
    jumpSceneType = 0
    self:SetTimer(1)
end

function SceneLoadingGameView:OnReceiveBattleData()
    if self.isLoadBattleRes then
        AssetManager.load_res_after_receive_battle_data()
    end
end

function SceneLoadingGameView:OnEnable(params)
    if not self.isEnabled then
        self.enableParams = params
        self.isEnabled = true
        self:Register()
        self.StopLoading = false
        checkFrame = 0
        self:SetTimer(1)
        ModelList.ApplicationGuideModel.ClearAllGuide()
        AnimatorPlayHelper.Play(self.view, { self.animNames.enterActionName, self.animNames.enterClipName }, false, function()
            LuaTimer:SetDelayFunction(1.6, function()
                self.eneterAnimOver = true
            end, true, LuaTimer.TimerType.UI)
        end)
        self.update_x_enabled = true
        self:start_x_update()
        Cache.clear_atlas_reference_to_cache_dic()
    end
    --Done LwangZg 资源卸载
    -- resMgr:UnloadAssetBundle("LoginAtlas", true)
    ResourcesManager:UnloadAsset("LoginAtlas", true)
end

function SceneLoadingGameView:on_init_ui()
    if jumpSceneType == JumpSceneType.ToHomeScene or jumpSceneType == JumpSceneType.ToLogin then
        self:on_init_home_ui()
    elseif jumpSceneType == JumpSceneType.None then
        self:on_init_battle_ui()
        self:on_init_home_ui()
    else
        self:on_init_battle_ui()
    end
end

function SceneLoadingGameView.OnLoadSceneComplete(self)
    self:FadeOut()
end

function SceneLoadingGameView:FadeOut(fadeOutCallback)
    log.log("SceneLoadingGameView:FadeOut jumpSceneType is ", jumpSceneType)
    local tempJumpSceneType = jumpSceneType
    self:stop_x_update()
    self:InitParams()
    self:UnRegCommand()
    self.fadeOutCallback = fadeOutCallback
    AnimatorPlayHelper.Play(self.view, { self.animNames.exitActionName, self.animNames.exitClipName }, false, function()
        if tempJumpSceneType == JumpSceneType.ToLogin then
            self:FaceOutForLogin()
        elseif tempJumpSceneType == JumpSceneType.ToHomeScene then
            self:FadeOutForHome()
        else
            self:FadeOutForBattle()
        end
    end)
end

function SceneLoadingGameView:load_scene()
    if (self.isLoad == nil) then
        self.isLoad = false
    end
    if (not self.isLoad) then
        self.isLoad = true
        -- self.scenehandle.allowSceneActivation = true
        self.scenehandle:UnSuspend()
        log.r("self.scenehandle.allowSceneActivation  true")
        self:FadeOut()
    end
end

function SceneLoadingGameView:getNextSceneName()
    local game_type = ModelList.BattleModel:GetGameCityPlayID()
    return Csv.GetData("new_city_play", game_type, "scenes_name")
end

function SceneLoadingGameView:LoadUISound()
    if BingoBangEntry.IsInEnterBattleSequence then
        return
    end
    
    self.loadRes = 0
    log.g("self.loadRes   " .. self.loadRes)
    UISound.load_machine_and_commonUI_res()
end

function SceneLoadingGameView:load_res()
    AssetManager.load_game_res(function()
        self.loadRes = self.loadRes + 1
        log.g("self.loadRes   " .. self.loadRes)
    end)
    self.isLoadBattleRes = true
end

function SceneLoadingGameView:EnterAnimaOver()
    if self.StopLoading then
        log.r("enterAnimaOver stop loading")
        return
    end
    self:on_init_ui()
    self:SetTimer(1)
    self.is_load_next = false
    if self.enableParams == JumpSceneType.ToLogin then
        jumpSceneType = JumpSceneType.ToLogin
        self:LoadSceneLogin()
    elseif fun.get_active_scene().name == "SceneHome" or ModelList.GuideModel:IsGuideMainView() then
        jumpSceneType = JumpSceneType.ToNormalGame
        if BingoBangEntry.IsInEnterBattleSequence then
            return
        end
        AssetManager.unload_lobby_res_for_enter_game()
        if not string.is_empty(self.MusicName) then
            UISound.load_loading_res(function()
                --UISound.play("pop")
                UISound.play(self.MusicName)
            end)
        end
        LuaTimer:SetDelayFunction(0.5, function()
            self:load_res()
            self:ReadyEnterBattle()
        end)
        --self:load_res()
        --self:ReadyEnterBattle()
    elseif self.enableParams == JumpSceneType.ToLogin then

    else
        jumpSceneType = JumpSceneType.ToHomeScene
        self:ReadyEnterHall()
    end
end
local aaa = false
function SceneLoadingGameView:on_x_update()
    if self.eneterAnimOver then
        self:EnterAnimaOver()
        self.eneterAnimOver = false
    end
    if jumpSceneType == JumpSceneType.None then
        return
    end
    if jumpSceneType == JumpSceneType.ToNormalGame then
        if aaa == false then
            aaa = true
            log.r("==========JumpSceneType.ToNormalGame=====================  self:on_x_update_battle")
        end
        self:on_x_update_battle()
    else
        self:on_x_update_home()
    end
end

local function LoadPuAudioList(puName, sound_ab_list)
    local puName = UISound.load_sound_data_in_need(puName)
    if puName then
        table.insert(sound_ab_list, puName.asset_path)
    end
    return sound_ab_list
end

function SceneLoadingGameView:LoadSceneAsync(procedure)
    checkFrame = os.time()
    self.scenehandle = nil
    LoadSceneAsync(self:getNextSceneName(), procedure,function(operation)
        self.scenehandle = operation
        log.g("self.loadRes   " .. self.loadRes)
        local game_type = ModelList.BattleModel:GetGameCityPlayID()
        local soundResName = Csv.GetData("new_game_music", game_type)

        if not soundResName then
            self.loadRes = self.loadRes + 1
            log.g("self.loadRes   " .. self.loadRes)
            return
        end
        --- 预加载战斗开场需要的音效
        local sound_ab_list = deep_copy(soundResName.music)
        --- 加载小丑音效
        if ModelList.BattleModel.GetIsJokerMachine() or ModelList.CityModel:IsMaxBetRate() then
            sound_ab_list = fun.add_table(sound_ab_list, soundResName.joker_music)
            local jokerready = UISound.load_sound_data_in_need("jokerready")
            if jokerready then
                table.insert(sound_ab_list, jokerready.asset_path)
            end
        end
        sound_ab_list = LoadPuAudioList("rewardflyincase", sound_ab_list)
        sound_ab_list = LoadPuAudioList("bingofirework", sound_ab_list)
        ---加载背景音效
        local loadingAudio = UISound.load_sound_data_in_need("city1loadingover")
        if loadingAudio then
            table.insert(sound_ab_list, loadingAudio.asset_path)
        end
        ---加载倒计时时钟音效
        local countdown = UISound.load_sound_data_in_need("countdown")
        if countdown then
            table.insert(sound_ab_list, countdown.asset_path)
        end
        ---加载卡牌入场音效
        local cardgoin = UISound.load_sound_data_in_need("cardgoin")
        if cardgoin then
            table.insert(sound_ab_list, cardgoin.asset_path)
        end
        ---加载Pu入场音效
        local model = ModelList.BattleModel:GetCurrModel()
        if model and model:LoadGameData() then
            local powerUpData = model:LoadGameData().powerUpData
            if powerUpData and #powerUpData > 0 then
                sound_ab_list = LoadPuAudioList("powerupinplace", sound_ab_list)
                sound_ab_list = LoadPuAudioList("powerupok", sound_ab_list)
                sound_ab_list = LoadPuAudioList("powerupchargeover", sound_ab_list)
                sound_ab_list = LoadPuAudioList("powerupitem", sound_ab_list)
                sound_ab_list = LoadPuAudioList("powerupuse", sound_ab_list)
                sound_ab_list = LoadPuAudioList("powerupcharge", sound_ab_list)
                local gameType = ModelList.BattleModel:GetGameCityPlayID()
                local cdMusic = Csv.GetData("new_game_music", gameType, "power_cd")
                if cdMusic == "0" then
                    local lv = (#ModelList.BattleModel:GetCurrModel():GetPowerUps()) / 3
                    cdMusic = "powerupcd" .. lv
                end
                sound_ab_list = LoadPuAudioList(cdMusic, sound_ab_list)
            end
        end
        --- 加载卡包音效
        local cardIds = ModelList.BattleModel:CardIdsContainCardPack()
        if cardIds and #cardIds > 0 then
            -- 有卡包
            local gourmetbagfly = UISound.load_sound_data_in_need("gourmetbagfly")
            if gourmetbagfly then
                table.insert(sound_ab_list, gourmetbagfly.asset_path)
            end
            local gourmetbagreach = UISound.load_sound_data_in_need("gourmetbagreach")
            if gourmetbagreach then
                table.insert(sound_ab_list, gourmetbagreach.asset_path)
            end
            local gourmetbaggoin = UISound.load_sound_data_in_need("gourmetbaggoin")
            if gourmetbaggoin then
                table.insert(sound_ab_list, gourmetbaggoin.asset_path)
            end
        end

        --- 加载战斗背景音效
        local playId = ModelList.CityModel.GetPlayIdByCity()
        local city_music = Csv.GetData("new_city_play", playId, "music")
        if ModelList.BattleModel.GetIsJokerMachine() or ModelList.CityModel:IsMaxBetRate() then
            city_music = Csv.GetData("new_city_play", playId, "maxbet_music")
        end
        city_music = string.gsub(city_music, "[%_]", "")
        local city_music = UISound.load_sound_data_in_need(city_music)
        if city_music then
            table.insert(sound_ab_list, city_music.asset_path)
        end
        UISound.load_res(sound_ab_list, function()
            self.loadRes = self.loadRes + 1
            log.g("self.loadRes   " .. self.loadRes)
        end)
    end)
end

function SceneLoadingGameView:on_x_update_battle()
    if not self.is_load_next and ModelList.BattleModel:IsReadyEnterScene() then
        self.is_load_next = true
        self:SetTimer(1)
        self:LoadSceneAsync(self.enableParams)
    end
    if self.loadRes == 2 then
        self.loadRes = 3
        log.g("上一次加载记数为 2 || self.loadRes   " .. self.loadRes)
        -- log.g("self.loadRes   " .. self.loadRes)
        if not self.scenehandle then
            LuaTimer:SetDelayLoopFunction(0.5, 0.5, 20, function()
                if self.scenehandle then
                    self.scenehandle:UnSuspend()
                    ProcedureManager.ShowReadyView()
                    log.r("self.scenehandle.allowSceneActivation  true")
                end
            end)
        else
            self.scenehandle:UnSuspend()
            ProcedureManager.ShowReadyView()
            log.r(" self.scenehandl:UnSuspend ")
        end

    end
    self:CheckLoadError()
end

function SceneLoadingGameView:CheckLoadError()
    if self.enable_time then
        self.enable_time = self.enable_time + UnityEngine.Time.deltaTime
        if self.enable_time > 10 then
            if not self.scenehandle and self.loadRes == 1 and self.is_load_next and checkFrame > 0
                    and os.time() - checkFrame >= 20 and self.enable_time >= MCT.load_game_time_out - 5 then
                --- 重新再加载一次场景
                log.r("load game time error , try load scene again")
                checkFrame = os.time()
                self:SetTimer(1)
                self.is_load_next = false
                local uid = ModelList.PlayerInfoModel:GetUid() or ""
                Http.report_error("CheckLoadError_1", "enableTime:" .. tostring(self.enable_time) .. " uid:" .. uid)
            end
        end
        if self.enable_time >= MCT.load_game_time_out then
            self:SetTimer(1)
            log.r("load game time out " .. os.time())
            --- 返回大厅前，查一下pu，触发资源刷新
            local uid = ModelList.PlayerInfoModel:GetUid() or ""
            Http.report_error("CheckLoadError_2", "enableTime:" .. tostring(self.enable_time) .. " uid:" .. uid)
            ModelList.CityModel.C2S_FetchPowerUp()
            ModelList.BattleModel:SetEnterBattleFail(true)
            ModelList.BattleModel:BackToHallScene()
            UIUtil.show_common_global_popup(8004, true)
            self:FadeOut()
        end
    end
end

function SceneLoadingGameView:LoadSceneLoadingHome()
    log.r("self.loadRes  SceneLoadingHome  ")
    --LoadSceneAsync("SceneLoadingHome", ProcedureSceneLoadingHome:New(), function(operation)
    --    operation.allowSceneActivation = true
    --    --Event.Brocast(Notes.QUIT_BATTLE)
    --    ----UnityEngine.Resources.UnloadUnusedAssets()
    --    local lobby = require("Logic.Bundle.UnloadBattleBundle")
    --    for i = 1, #lobby.other do
    --        resMgr:UnloadAssetBundle(lobby.other[i], true)
    --    end
    --    for i = 1, #lobby.atlas do
    --        resMgr:UnloadAssetBundle(lobby.atlas[i], true)
    --    end
    --    ----UnityEngine.Resources.UnloadUnusedAssets()
    --    log.r("self.loadRes UnloadAssetBundle  SceneLoadingHome1  ")
    --    UISound.unload_machine_res()
    --    --UnityEngine.Resources.UnloadUnusedAssets()
    --    self:WaitLoadingHome()
    --end)
    self:CleanBattleBundle(true, true)
    --UnityEngine.AssetBundle.UnloadAllAssetBundles(false)

    self:WaitLoadingHome()
end

function SceneLoadingGameView:CleanBattleBundle(isThorough, isForce)
    local UnloadLobbyBundle = require("Logic.Bundle.UnloadLobbyBundle")
    if UnloadLobbyBundle then
        UnloadLobbyBundle:StopUnload()
    end
    local lobby = require("Logic.Bundle.UnloadBattleBundle")
    if lobby then
        lobby:StartUnload(isThorough, isForce)
        --for i = 1, #lobby.other do
        --    resMgr:UnloadAssetBundle(lobby.other[i], isThorough,isForce)
        --end
        --for i = 1, #lobby.atlas do
        --    resMgr:UnloadAssetBundle(lobby.atlas[i], isThorough,isForce)
        --end
    end
    ----UnityEngine.Resources.UnloadUnusedAssets()
    UISound.unload_sound_data_in_need(2)
    --UISound.unload_machine_res()
    -- --UnityEngine.Resources.UnloadUnusedAssets()
    Util.ClearMemory()
end

--function SceneLoadingGameView:CleanBattleBundle2(isThorough,isForce)
--    local lobby = require("Logic.Bundle.UnloadBattleBundle")
--    for i = 1, #lobby.other do
--        resMgr:UnloadAssetBundle(lobby.other[i], isThorough,isForce)
--    end
--    for i = 1, #lobby.atlas do
--        resMgr:UnloadAssetBundle(lobby.atlas[i], isThorough,isForce)
--    end
--end

function SceneLoadingGameView:WaitLoadingHome()
    LuaTimer:SetDelayFunction(1, function()
        self:LoadSceneHome()
    end)
end

function SceneLoadingGameView:LoadSceneHome()
    Event.AddListener(EventName.Event_enterhome_previous_finish, self.OnLoadSceneHomeComplete, self)
    LoadSceneAsync("SceneHome", ProcedureCityHome:New(),function(operation)
        self.scenehandle = operation
        -- self.scenehandle.allowSceneActivation = false 
        self:CancelCheckLoadHome()
        log.r("self.loadRes  SceneHome1  ")
        LuaTimer:Clear(LuaTimer.TimerType.Battle)
        LuaTimer:Clear(LuaTimer.TimerType.BattleUI)
        --UnityEngine.Resources.UnloadUnusedAssets()
        AssetManager.load_common_res(function()
            --加载通用ab资源
            AssetManager.load_lobby_res(function()
                --加载大厅资源和音效
                local playId = ModelList.CityModel.GetPlayIdByCity()
                local atlasName = string.format("LobbyPlay%sEntityAtlas", playId)
                --- 只有三个城市有LobbyPlay%sEntityAtlas
                if (playId == 1 or playId == 2 or playId == 3) then
                    local pName = string.format("Play%sHallBackground", playId)
                    Cache.Load_Atlas(AssetList[atlasName], atlasName, function(obj)
                        Cache.load_prefabs(AssetList[pName], pName, function(ret)
                            self.percent = 1
                            self.can_next_step = true
                        end)
                    end)
                else
                    local pName = string.format("Play%sHallBackground", playId)
                    Cache.load_prefabs(AssetList[pName], pName, function(ret)
                        self.percent = 1
                        self.can_next_step = true
                    end)
                end
            end)
        end)
    end)
end

function SceneLoadingGameView:OnLoadSceneHomeComplete()
    Event.RemoveListener(EventName.Event_enterhome_previous_finish, self.OnLoadSceneHomeComplete, self)
end

function SceneLoadingGameView:LoadSceneGame()
    if jumpSceneType == JumpSceneType.ToHomeScene then
        self.scenehandle = nil
        ModelList.BattleModel.UpdateBattleSuperMatchToggle(true)
        self:CheckLoadHome()
        self:LoadSceneLoadingHome()
    end
end

function SceneLoadingGameView:CheckLoadHome()
    self._checkLoadHomeScene = LuaTimer:SetDelayFunction(15, function()
        if self.scenehandle == nil and fun.get_active_scene().name ~= "SceneHome" and jumpSceneType == JumpSceneType.ToHomeScene then
            self:LoadSceneHome()
        end
    end)
end

function SceneLoadingGameView:CancelCheckLoadHome()
    if self._checkLoadHomeScene ~= nil then
        LuaTimer:Remove(self._checkLoadHomeScene)
        self._checkLoadHomeScene = nil
    end
end

function SceneLoadingGameView:LoadSceneLogin()
    if jumpSceneType == JumpSceneType.ToLogin then
        LoadSceneAsync("SceneLogin", ProcedureLogin:New(), function(operation)
            self.scenehandle = operation
            self.percent = 1
            self.can_next_step = true
        end)
    end
end

function SceneLoadingGameView:on_close()
end

function SceneLoadingGameView:OnDisable()
    log.r("SceneLoadingGameView:OnDisable")
    self:stop_x_update()
    self:InitParams()
    self:UnRegCommand()
end

function SceneLoadingGameView:OnDestroy()
    log.r("SceneLoadingGameView:OnDestroy")
    self:stop_x_update()
    self:InitParams()
    self:Close()
    self:UnRegister()
    self:UnRegCommand()
end

function SceneLoadingGameView:UnRegCommand()
    Facade.RemoveCommand(NotifyName.PreLoadMachineRes, CmdCommonList.CmdPreLoadMachineRes)
    --先暂时屏蔽，因为返回后主界面UI都隐藏了，有空再改
    Facade.RemoveCommand(NotifyName.SceneLoading.ExitLoadingGame, CmdCommonList.CmdExitSceneLoading)
end

function SceneLoadingGameView:RegCommand()
    Facade.RegisterCommand(NotifyName.PreLoadMachineRes, CmdCommonList.CmdPreLoadMachineRes)
    Facade.RegisterCommand(NotifyName.SceneLoading.ExitLoadingGame, CmdCommonList.CmdExitSceneLoading)
end

-------------------------------------------------enter Battle ----------------------------------

function SceneLoadingGameView:ReadyEnterBattle()
    Facade.SendNotification(NotifyName.PreLoadMachineRes)

    -- Cache.Load_Atlas(AssetList["BingoAtlas"], "bingoatlas")
    Cache.Load_Atlas(AssetList["BingoAtlas"], "BingoAtlas")
    Cache.Load_Atlas(AssetList["SettleAtlas"], "SettleAtlas")
end

function SceneLoadingGameView:on_init_battle_ui()

end

function SceneLoadingGameView:FadeOutForBattle()
    log.log("SceneLoadingGameView:FadeOutForBattle")
    UISound.unload_lobby_res()
    local canvas_group = fun.get_component(self.go, fun.CANVAS_GROUP)
    if canvas_group then
        Anim.canvas_group_do_fade_loop(canvas_group, 1, 0.3, 1, 0.2, 0, function()
            --UISound.stop("pop")
            if not string.is_empty(self.MusicName) then
                UISound.stop(self.MusicName)
            end
            self:OnLoadSceneBattleComplete()
            --self:Close();
            UISound.unload_loading_res()
            Facade.SendNotification(NotifyName.CloseUI, self)
            --Cache.unload_ab("SceneLoadingGameAtlas")
            --Cache.PrintLoadedAsset()
        end)
    else
        --UISound.stop("pop")
        if not string.is_empty(self.MusicName) then
            UISound.stop(self.MusicName)
        end
        self:OnLoadSceneBattleComplete()
        --self:Close();
        UISound.unload_loading_res()
        Facade.SendNotification(NotifyName.CloseUI, self)
        --Cache.unload_ab("SceneLoadingGameAtlas")
        --Cache.PrintLoadedAsset()
    end
    GlobalBattleMachineList.StartBattleGlobalMachine()
    --Facade.SendNotification(NotifyName.CloseUI, self)
end

--- 加载战斗场景完成,优先播放superMatch的表现
function SceneLoadingGameView:OnLoadSceneBattleComplete()
    log.log("SceneLoadingGameView:OnLoadSceneBattleComplete")
    --- 加载SuperMatch的资源
    if ModelList.BattleModel.GetBattleSuperMatch() then
        Cache.load_prefabs(AssetList["SuperMatchZhandou"], "SuperMatchZhandou", function(obj)
            if obj and not fun.is_null(obj) then
                local view = ModelList.BattleModel:GetCurrBattleView()
                local cookie = fun.get_instance(obj, view.go)
                local ref =  fun.get_component(cookie,fun.REFER)
                local mateNameLbl
                if ref then
                    ref:Get("imgHead1").sprite = AtlasManager:GetSpriteByName("HeadAtlas", ModelList.PlayerInfoModel:GetHeadIcon())
                    local head2 = ref:Get("imgHead2")
                    mateNameLbl = ref:Get("Name2")

                    fun.set_active(mateNameLbl, false)
                    fun.set_active(mateNameLbl, true, 1.7)
                    local serverData = ModelList.BattleModel:GetCurrModel():GetSuperMatchData()
                    local robotId = serverData and (serverData.matchId or serverData.robotId)
                    if fun.is_not_null(head2) and fun.is_not_null(robotId) then
                        local icon = Csv.GetData("robot_name", robotId, "icon")
                        local name = Csv.GetData("robot_name", robotId, "name")
                        local sysModel = ModelList.PlayerInfoSysModel
                        sysModel:LoadTargetHeadSprite(icon, head2)
                        if fun.is_not_null(mateNameLbl) then
                            mateNameLbl.text = name
                        end
                        --sysModel:LoadRobotTargetFrameSprite(robotId, self.headMask)
                    end
                end

                UISound.play("supermatchmatch")

                LuaTimer:SetDelayFunction(4, function()
                    Destroy(cookie)

                    local game_ui = fun.GameObject_find("Canvas/GameUI/NormalNode")
                    local getReadyView = fun.find_child(game_ui, "ReadyView")
                    fun.set_active(getReadyView.gameObject, true)
                    if self.fadeOutCallback then
                        self.fadeOutCallback()
                        self.fadeOutCallback = nil
                    end

                    ModelList.BattleModel:GetCurrBattleView():SetReadyForPreUseItem(10)
                end, nil, LuaTimer.TimerType.Battle)
            end
        end)
    else
        if self.fadeOutCallback then
            self.fadeOutCallback()
            self.fadeOutCallback = nil
        end
        LuaTimer:SetDelayFunction(2,function()
            ModelList.BattleModel:GetCurrBattleView():SetReadyForPreUseItem(10)
        end)
    end
end


--------------------------------------------------------------------------------------------------

function SceneLoadingGameView:SetTimer(timerType)
    if timerType == 1 then
        self.enable_time = 0
    elseif timerType == 11 then

    end
    self.timerState = (self.timerState and self.timerState or 0) + timerType
end



-------------------------------------------------enter Home ----------------------------------


function SceneLoadingGameView:ReadyEnterHall()
    self:LoadSceneGame()
end

function SceneLoadingGameView:on_init_home_ui()
    self.percent = 0
    self.curProcess = 0
    self.isLoad = false
    self.scenehandle = nil
    self.can_next_step = false
end

function SceneLoadingGameView:FadeOutForHome()
    Facade.SendNotification(NotifyName.CloseUI, self)
    UISound.unload_loading_res()
    GlobalBattleMachineList.StopBattleGlobalMachine()
end

function SceneLoadingGameView:FaceOutForLogin()
    Facade.SendNotification(NotifyName.CloseUI, self)
    UISound.unload_loading_res()
end

function SceneLoadingGameView:on_x_update_home()
    if self.scenehandle == nil then
        return
    end
    if self.can_next_step == true then
        self:load_scene()
        self:stop_x_update()
        --self:CleanBattleBundle2(false,false)
    end
end

--------------------------------------------------------------------------------------------------


function SceneLoadingGameView:CancelLoading()
    self.StopLoading = true
    jumpSceneType = JumpSceneType.ToHomeScene
    self:FadeOut()
end

function SceneLoadingGameView:Register()
    Event.AddListener(EventName.Event_Cancel_Loading_Game, self.CancelLoading, self)
    Event.AddListener(EventName.Event_Loading_Game_Receive_Battle_Data, self.OnReceiveBattleData, self)
    self:RegCommand()
end

function SceneLoadingGameView:UnRegister()
    Event.RemoveListener(EventName.Event_Cancel_Loading_Game, self.CancelLoading, self)
    Event.RemoveListener(EventName.Event_Loading_Game_Receive_Battle_Data, self.OnReceiveBattleData, self)
    self:UnRegCommand()
end

--- 偶现不执行OnEnable的情况，所以加了个延迟检查
function SceneLoadingGameView:CheckEnableAnima()
    self.isEnabled = false
    LuaTimer:SetDelayFunction(5, function()
        if self and not self.isEnabled then
            self:OnEnable()
        end
    end)
end

return this



