---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18/11/2024 下午 4:05
---


-- 棋盘的大小
local gridSize = 5
local colors = { "red", "green" } -- 定义可用颜色

-- 随机给每个格子涂色
function generateRandomColors()
    local grdiSignMap = {}
    --for i = 1, gridSize * gridSize do
    --    -- 随机选择一个颜色
    --    grdiSignMap[i] = colors[math.random(#colors)]
    --end
    grdiSignMap[1] = "1"
    grdiSignMap[2] = "1"
    grdiSignMap[3] = "1"
    grdiSignMap[4] = "1"
    grdiSignMap[5] = "1"
    grdiSignMap[6] = "1"
    grdiSignMap[7] = "1"
    grdiSignMap[8] = "1"
    grdiSignMap[9] = "1"
    grdiSignMap[10] = "1"
    grdiSignMap[11] = "1"
    grdiSignMap[12] = "1"
    grdiSignMap[13] = "1"
    grdiSignMap[14] = "1"
    grdiSignMap[15] = "1"
    grdiSignMap[16] = "1"
    grdiSignMap[17] = "1"
    grdiSignMap[18] = "1"
    grdiSignMap[19] = "1"
    grdiSignMap[20] = "1"
    grdiSignMap[21] = "0"
    grdiSignMap[22] = "0"
    grdiSignMap[23] = "1"
    grdiSignMap[24] = "1"
    grdiSignMap[25] = "1"



    return grdiSignMap
end

-- 检查给定的格子周围的区域是否能组成指定大小的形状
function checkPattern(grdiSignMap, startX, startY, width, height)
    --print("checkPattern  "..((startY * gridSize) + (startX + 1)))
    local firstColor = grdiSignMap[(startY * gridSize) + (startX + 1)] -- 获取左上角格子的颜色
    local first = (startY * gridSize) + (startX + 1)
    --if first == 8 then
    --    print("width " .. width .. "   height " .. height)
    --end
    for j = 0, height - 1 do
        for i = 0, width - 1 do
            local x = startX + i
            local y = startY + j
            --if first == 8 then
            --    print("x " .. x .. "   y " .. y .. "  index  " .. (y * gridSize) + (x + 1))
            --end


            if x < 0 or y < 0 or x > gridSize or y > gridSize then
                if first == 8 then print("超出边界") end
                return false -- 超出边界
            end
            if grdiSignMap[(y * gridSize) + (x + 1)] ~= firstColor then
                if first == 8 then
                    print("超出边界2")
                    print((y * gridSize) + (x + 1))
                end
                return false -- 颜色不一致
            end
        end
    end
    return true -- 找到一致的颜色区域
end

-- 检查可能的图案
function checkAllPatterns(grdiSignMap)
    local patterns = {
        { 3, 3 },
        { 3, 4 },
        { 3, 5 },
        { 5, 3 },
        { 4, 3 },
        { 4, 4 },
        { 4, 5 },
        { 5, 4 },
        { 5, 5 },
    }

    for _, pattern in pairs(patterns) do
        local width, height = pattern[1], pattern[2]
        --print("width111 " .. width .. "   height111 " .. height)
        for x = 0, width-1 do
            for y = 0, height - 1 do
                --print("x111 " .. x .. "   y111 " .. y)
                if checkPattern(grdiSignMap, x, y, width, height) then
                    print(string.format("找到一个 %dx%d 的图案，左上角格子序号: %d", width, height, (y * gridSize) + (x + 1)))
                end
            end
        end
    end
end

-- 主程序
function main()
    math.randomseed(os.time())                 -- 设置随机种子
    local grdiSignMap = generateRandomColors() -- 随机涂色

    -- 显示涂色后的棋盘
    print("涂色后的棋盘：")
    for y = 0, gridSize - 1 do
        for x = 0, gridSize - 1 do
            io.write(string.format("%s\t", grdiSignMap[(x * gridSize) + (y + 1)]))
        end
        io.write("\n")
    end

    -- 检查所有可能的图案
    checkAllPatterns(grdiSignMap)
end

-- 运行主程序
main()
