---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/11/14 11:37
---
--- 基础玩法卡牌逻辑数据

local BaseLogicCard = { name = "BaseLogicCard" }
BaseLogicCard.__index = BaseLogicCard
local this = BaseLogicCard
this.moduleName = "BaseLogicCard"
this.waitUploadData = nil

function BaseLogicCard:InitLogic()
    
end

function BaseLogicCard:New(name)
    local o = { name = name }
    setmetatable(o, { __index = BaseLogicCard })
    return o
end

function BaseLogicCard:BaseInit()
    self.rocketBingoCount = 0
end

function BaseLogicCard:Clear()
    self:BaseClear()
end

function BaseLogicCard:BaseClear()
    self.rocketBingoCount = 0
    self:ResetWaitUploadSettleData()
end

function BaseLogicCard:StatisticsRocketBingo()
    --if ModelList.BattleModel:IsRocket() then
    if not self.rocketBingoCount then
        self.rocketBingoCount = 1
    else
        self.rocketBingoCount = self.rocketBingoCount + 1
    end
    log.r("this.rocketBingoCount  " .. self.rocketBingoCount)
    --end
end

function BaseLogicCard:ReduceRocketBingo()
    --if ModelList.BattleModel:IsRocket() then
    if not self.rocketBingoCount then
        self.rocketBingoCount = 0
    else
        self.rocketBingoCount = self.rocketBingoCount - 1
        if self.rocketBingoCount < 0 then
            self.rocketBingoCount = 0
        end
    end
    log.r("this.rocketBingoCount22   " .. self.rocketBingoCount)
    --end
end

function BaseLogicCard:HasRocketBingo()
    --if ModelList.BattleModel:IsRocket() then
    if not self.rocketBingoCount or self.rocketBingoCount == 0 then
        return false
    end
    return true
    --end
    --return false
end

--- 检查是否还有没展示的Bingo
function BaseLogicCard:HasNoShowBingo()
    if not self.rocketBingoCount or self.rocketBingoCount == 0 then
        return false
    end
    return true
end

---清理数据 防止卡住
function BaseLogicCard:ResetWaitBingoCount()
    self.rocketBingoCount = 0
end

---战斗提前结束，进入结算流程
function BaseLogicCard:WaitUploadSettleData()
    if BingoBangEntry.IsInBattlePreSettle or BingoBangEntry.IsInBattleSettle then
        return
    end
    
    ModelList.BattleModel.SetQuitBattle(true)
    
    local CmdStartBattleSettle = require "Logic.Command.Battle.Settle.CmdStartBattleSettle"
    local cmd = CmdStartBattleSettle.New()
    cmd:Execute()
end

function BaseLogicCard:ResetWaitUploadSettleData()
    if this.waitUploadData then
        LuaTimer:Remove(this.waitUploadData)
    end
    this.waitUploadData = nil
end

function BaseLogicCard:Register()
    --Event.AddListener(EventName.Event_Logic_Collect_Item,self.AddLogicBowlDrink,self)
end

function BaseLogicCard:UnRegister()
    --Event.RemoveListener(EventName.Event_Logic_Collect_Item,self.AddLogicBowlDrink,self)
end

return this