---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 8/11/2024 上午 11:04
---

local IdleState = Clazz(BaseFsmState, "IdleState")
local this = IdleState

function IdleState:New()
    local o = {}
    setmetatable(o, { __index = IdleState })
    return o
end

function IdleState:InitState()
end

function IdleState:OnEnter(fsm, previous)
    log.EditorLog("enter  IdleState")
    self._fsm = fsm
    self._owner = fsm:GetOwner()
    self._owner:CollectData()
    self._owner:InitCellsValue()
    local isHighBet = ModelList.CityModel:GetBetRate() >= 8 or
    (ModelList.UltraBetModel:IsActivityValidForCurPlay() and true or false)
    self._owner:PlayEnterAnimation(isHighBet)
    local animaTime = isHighBet and 3 or 2
    LuaTimer:SetDelayFunction(animaTime + 2, function ()
        fsm:ChangeState("CoinsTurnState")
    end)
end

function IdleState:on_x_update()
    if anima then
        if anima:GetCurrentAnimatorStateInfo(0):IsName("idle") then
            this:stop_x_update()
            this:PlayOver()
        end
    end
end

function IdleState:Finish()

end

function IdleState:OnLeave(fsm)
    self._fsm = nil
    self._owner = nil
    self._posX = nil
end

function IdleState:Dispose()
    self:OnLeave(nil)
end

return this
