---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/12/5 10:05
---

local NewCityComingSoonView = BaseView:New('NewCityComingView');

local this = NewCityComingSoonView

function NewCityComingSoonView:New(view)
    local o = {};
    setmetatable(o, { __index = this })
    o.view = view
    return o
end


this.auto_bind_ui_items = {
    "btn_play",
}

function NewCityComingSoonView:Awake(obj, obj2)
    self:on_init()
end

function NewCityComingSoonView:OnEnable()
    self:SaveToday()
end

function NewCityComingSoonView.OnDisable()
    Event.Brocast(EventName.Event_popup_new_city_coming_finish)
end

function NewCityComingSoonView:on_btn_close_click()
    --Facade.SendNotification(NotifyName.CloseUI,self)
    self:closeWithAnimation()
end


function NewCityComingSoonView:on_btn_play_click()
    --Facade.SendNotification(NotifyName.CloseUI,self)
    self:closeWithAnimation()
end


--- �Ե�������Ϊֵ������ɱ�������
function NewCityComingSoonView:SaveToday()
    local today = os.date("%Y%m%d", os.time())
    fun.save_value("NewCityComingSoonView",today)
end

function NewCityComingSoonView:_close()
    Facade.SendNotification(NotifyName.CloseUI,self)
    self.__index:_close(self)
end

return this 