--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/1/11 15:15
---
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/1/11 15:24
---
require("View/Bingo/SettleModule/RocketState/BaseRocketState")

RocketStartFly2State = Clazz(BaseRocketState,"RocketStartFly2State")

function RocketStartFly2State:New()
    local o = {}
    setmetatable(o,{__index = RocketStartFly2State})
    return o
end

function RocketStartFly2State:OnEnter(fsm,prvious,...)
    local params = ({ ... })[1]
    ModelList.GameModel:SetOnlySaveBingoInfo()
    fsm:GetOwner():PlayRocketFly2()

end

function RocketStartFly2State:OnLeave(fsm)

end

function RocketStartFly2State:FinishOperate(fsm)
    if fsm then
        self:ChangeState(fsm,"RocketEndFly2State")
    end
end