---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/25 10:54
---
local GmViewDebug = {}
local this = GmViewDebug

function GmViewDebug:Excute()
    log.r("test")
end

return this