---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/3/16 18:41
---

--- 城市5技能

local BaseSkill =  require("View.Bingo.CardModule.Skill.BaseSkill")

local Play11Skill = BaseSkill:New("Play11Skill")
setmetatable(Play11Skill,BaseSkill)
local this = Play11Skill

function Play11Skill:ShowSkill(cardId, cellIndex, powerId,skillId)
    self:SaveSkillInfo(cardId,nil)
    local targetObj = self:GetCardPower().cardView:GetCardCell(tonumber(cardId), cellIndex)
    BattleEffectCache:GetSkillPrefabFromCache("Egyptskill", targetObj, function(obj)
        self:SaveSkillInfo(cardId, obj)
        UISound.play("city5_skill")
        fun.set_same_position_with_but_z_zero(obj, self:GetCardPower().cardView:GetCardCell(tonumber(cardId), cellIndex))
        self:SameScaleWithCard(obj, cardId)
        local data = Csv.GetData("skill", skillId, "skill_xyz")
        local ori_x = math.modf((cellIndex - 1) / 5)
        local ori_y = math.modf((cellIndex - 1) % 5)
        LuaTimer:SetDelayFunction(1.2, function()
            local offset = data[1]
            local new_x = ori_x + offset[1]
            local new_y = ori_y - offset[2]
            if new_x >= 0 and new_x <= 4 and new_y >= 0 and new_y <= 4 then
                local new_index = new_x * 5 + new_y + 1
                local IsNotSign = self:GetModel():GetRoundData(cardId, new_index):IsNotSign()
                if IsNotSign then
                    self:GetCardPower().cardView:OnClickCardIgnoreJudgeByIndex(cardId, new_index, powerId)
                    self:GetCardPower():ChangeCellState(cardId, new_index, self.CellState.Signed)
                end
            end
        end,nil,LuaTimer.TimerType.Battle)
        LuaTimer:SetDelayFunction(1.5, function()
            local offset = data[2]
            local new_x = ori_x + offset[1]
            local new_y = ori_y - offset[2]
            if new_x >= 0 and new_x <= 4 and new_y >= 0 and new_y <= 4 then
                local new_index = new_x * 5 + new_y + 1
                local IsNotSign = self:GetModel():GetRoundData(cardId, new_index):IsNotSign()
                if IsNotSign then
                    self:GetCardPower().cardView:OnClickCardIgnoreJudgeByIndex(cardId, new_index, powerId)
                    self:GetCardPower():ChangeCellState(cardId, new_index, self.CellState.Signed)
                end
            end
        end,nil,LuaTimer.TimerType.Battle)
        LuaTimer:SetDelayFunction(1.8, function()
            local offset = data[3]
            local new_x = ori_x + offset[1]
            local new_y = ori_y - offset[2]
            if new_x >= 0 and new_x <= 4 and new_y >= 0 and new_y <= 4 then
                local new_index = new_x * 5 + new_y + 1
                local IsNotSign = self:GetModel():GetRoundData(cardId, new_index):IsNotSign()
                if IsNotSign then
                    self:GetCardPower().cardView:OnClickCardIgnoreJudgeByIndex(cardId, new_index, powerId)
                    self:GetCardPower():ChangeCellState(cardId, new_index, self.CellState.Signed)
                end
            end
        end,nil,LuaTimer.TimerType.Battle)
        LuaTimer:SetDelayFunction(2, function()
            local offset = data[4]
            local new_x = ori_x + offset[1]
            local new_y = ori_y - offset[2]
            if new_x >= 0 and new_x <= 4 and new_y >= 0 and new_y <= 4 then
                local new_index = new_x * 5 + new_y + 1
                local IsNotSign = self:GetModel():GetRoundData(cardId, new_index):IsNotSign()
                if IsNotSign then
                    self:GetCardPower().cardView:OnClickCardIgnoreJudgeByIndex(cardId, new_index, powerId)
                    self:GetCardPower():ChangeCellState(cardId, new_index, self.CellState.Signed)
                end
            end
            self:RemoveSkillInfo(obj)
        end,nil,LuaTimer.TimerType.Battle)
    end,4,cardId)
end

return this