---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/7/26 12:11
---

local HangUpCardSwitchItem = BaseChildView:New() --Clazz(BaseChildView,"HangUpCardSwitchItem")
this = HangUpCardSwitchItem
this.items1 = {}
this.items2 = {}

function HangUpCardSwitchItem:New(go)
    local o = {}
    self.__index = self
    setmetatable(o,self)
    --self._data = cellData
    return o
end

function HangUpCardSwitchItem:InitMap(go,type)
    --self._gameObject = go
    local ref = fun.get_component(go.transform,fun.REFER)
    if ref then
        self.content = ref:Get("content")
        self.img_reap = ref:Get("img_reap")
    end

    for i = 1, 25 do
        local go = fun.get_instance(self.img_reap,self.content)
        fun.set_active(go,false,0)
        local img = go:GetComponent(fun.IMAGE)
        local cell = {obj = go,image = img}
        if type == 0 then
            table.insert(this.items1,cell)
        else
            table.insert(this.items2,cell)
        end
        local x = math.modf((i-1)/5)
        local y = math.modf((i-1)%5)
        fun.set_gameobject_pos(go,29.25*x,-28*y,0,true)
    end

    if type == 0 then
        --log.r("HangUpCardSwitchItem  Init "..(#this.items1))
    else
        --log.r("HangUpCardSwitchItem  Init "..(#this.items2))
    end
end


function HangUpCardSwitchItem:Refresh(newCard)
    --log.r("HangUpCardSwitchItem  ------------ "..type)
    --[[
    local str = ""
    for k,v in pairs(newCard) do
                    str = str.."   sign "..v.sign.."   "..v.index
    end
    log.r("Card****** "..str)
    --]]
    local items =  this.items1
    local isshowing = false
    for i = 1, #items do
        isshowing = false
        for j = 1, #newCard do
            if  i == newCard[j].index then
                isshowing = true
                items[i].obj.gameObject:SetActive(true)
                --log.r("Refresh  111 "..(i).."   "..newCard[j].sign)
                if newCard[j].sign  >1 then
                    items[j].image.sprite = AtlasManager:GetSpriteByName("BingoAtlas","b_bingo01_small")
                end
                break
            end
        end
        if not isshowing then
            items[i].obj.gameObject:SetActive(false)
            --log.r("Refresh 222  "..(i))
        end
    end
end


function HangUpCardSwitchItem:Refresh2(newCard)
  --  log.r("HangUpCardSwitchItem  ------------ "..type)
    --[[
    local str = ""
    for k,v in pairs(newCard) do
        str = str.."   sign "..v.sign.."   "..v.index
    end
    log.r("Card****** "..str)
    --]]
    local items =   this.items2
    local isshowing = false
    for i = 1, #items do
        isshowing = false
        for j = 1, #newCard do
            if  i == newCard[j].index then
                isshowing = true
                items[i].obj.gameObject:SetActive(true)
                --log.r("Refresh  111 "..(i).."   "..newCard[j].sign)
                if newCard[j].sign  >1 then
                    items[i].image.sprite = AtlasManager:GetSpriteByName("BingoAtlas","b_bingo01_small")
                end
                break
            end
        end
        if not isshowing then
            items[i].obj.gameObject:SetActive(false)
            --log.r("Refresh 222  "..(i))
        end
    end
end



function HangUpCardSwitchItem.OnDispose()
    --self._gameObject = nil
    this.items1 = {}
    this.items2 = {}
end

return HangUpCardSwitchItem