---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/12 17:50
---



require("View/Bingo/SettleModule/State/BaseSettleState")

SettleEvaluationState = Clazz(BaseSettleState,"SettleEvaluationState")
local this = SettleEvaluationState
function SettleEvaluationState:New(view)
    local o = {}
    setmetatable(o,{__index = SettleEvaluationState})
    o.view = view
    return o
end


function SettleEvaluationState:OnEnter(fsm,prvious,...)
  ---  this:OpenEvaluationView(self.view)
    self:ChangeState(fsm,"SettleDetailState")
end

function SettleEvaluationState:OpenEvaluationView( view)
    ViewList.SettleEvaluationView:SkipLoadShow(view)
end



--function SettleEvaluationState:on_x_update()
--
--end


function SettleEvaluationState:OnLeave(fsm)

end

function SettleEvaluationState:FinishOperate(fsm)
    if fsm then
        self:ChangeState(fsm,"SettleDetailState")
    end
end