---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/3/23 15:31

---  战斗声音管理 machine
---
---
require("Combat/BaseMachine")
BattleSoundMachine = BaseMachine:New("BattleSoundMachine")
local this = BattleSoundMachine
local need_common_bingo = false

function BattleSoundMachine:Start()
    local gameType = ModelList.BattleModel:GetGameCityPlayID()
    if gameType then
        local data = Csv.GetData("new_game_music", gameType)
        if data then
            need_common_bingo = data.need_common_bingo == 1 and true or false
            BattleSoundMachine.kick = data.kick
        end
    end
end

function BattleSoundMachine:Pause(isPause)

end

function BattleSoundMachine:Stop()

end

function BattleSoundMachine:PlayCallNumberAduio(num, isbingo)
    local play_name
    local eventName = EventName.Normal_Auto_Background_Click
    local gameType = ModelList.BattleModel:GetGameType()
    if gameType == PLAY_TYPE.PLAY_TYPE_AUTO_TICKET then
        play_name = "autocity1" .. num
        eventName = Notes.AUTO_CLICK_HANG_UP
    elseif gameType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        play_name = "autocity1" .. num
    elseif gameType == PLAY_TYPE.PLAY_TYPE_HORSE_RACE then
        play_name = "goldenman" .. num
    else
        play_name = "commonnormal" .. num
    end

    UISound.play(play_name)
    for _, v in pairs(Csv.audio) do
        if play_name == v.sound_name then
            local delayTime = v.length
            LuaTimer:SetDelayFunction(delayTime, function()
                Event.Brocast(eventName, num)
                UISound.unload_battle_call_number_sound_data(play_name)
            end)
            break
        end
    end
end

function BattleSoundMachine:PlayBingoAudio(bingo_table)
    if not need_common_bingo then
        return
    end
    --播放音效
    for k, v in pairs(bingo_table) do
        if v.jackpot > 0 then
            this.PlayJackpotSound()
        elseif v.bingo <= 3 and #v.th > 0 and v.th[1] > 0 then
            for p = 1, #v.th do
                if v.th[p] == 1 then
                    UISound.play("FirstPlaceBingo")
                elseif v.th[p] == 2 then
                    UISound.play("SecondPlaceBingo")
                elseif v.th[p] == 3 then
                    UISound.play("ThirdPlaceBingo")
                else
                    if v.bingo == 3 then
                        UISound.play("TripleBingo")
                    elseif v.bingo == 2 then
                        UISound.play("DoubleBingo")
                    elseif v.bingo == 1 then
                        UISound.play("Bingo")
                    end
                end
            end
        else
            local cityID = ModelList.BattleModel:GetGameCityPlayID()
            local cfg = table.find(Csv["new_bingo_reward"], function(key, value)
                if value.city_play_id ~= cityID then
                    return
                end
                return value.bingo == v.bingo
            end)
            if cfg then
                --有配置就用配置
                local audioName = Csv.GetData("audio", cfg.audio, "sound_name")
                UISound.play(audioName)
            elseif v.bingo >= 5 then
                UISound.play("JACKPOT")
            elseif v.bingo == 4 then
                UISound.play("QuadraBingo")
                --elseif v.bingo == 5 then
                --    UISound.play("PentaBingo")
            elseif v.bingo == 3 then
                UISound.play("TripleBingo")
            elseif v.bingo == 2 then
                UISound.play("DoubleBingo")
            elseif v.bingo == 1 then
                UISound.play("Bingo")
            end
        end
    end
end

function BattleSoundMachine.PlayJackpotSound()
    local playType = ModelList.BattleModel:GetGameType()
    if playType == PLAY_TYPE.PLAY_TYPE_VICTORY_BEATS then
        UISound.play("winzoneVictorybingo")
    else
        UISound.play("JACKPOT")
    end
end

function BattleSoundMachine.Register()
    Event.AddListener(EventName.SoundMachine_Call_Number_Audio, this.PlayCallNumberAduio)
    Event.AddListener(EventName.SoundMachine_Bingo_Audio, this.PlayBingoAudio)
    Event.AddListener(EventName.SoundMachine_Stop_City_Music, this.SetCityMusic)
end

function BattleSoundMachine.UnRegister()
    Event.RemoveListener(EventName.SoundMachine_Call_Number_Audio, this.PlayCallNumberAduio)
    Event.RemoveListener(EventName.SoundMachine_Bingo_Audio, this.PlayBingoAudio)
    Event.RemoveListener(EventName.SoundMachine_Stop_City_Music, this.SetCityMusic)
end

function BattleSoundMachine:SetCityMusic(isPlay)
    if isPlay then
        local playId = ModelList.CityModel.GetPlayIdByCity()
        local city_music = Csv.GetData("new_city_play", playId, "music")
        if playId == PLAY_TYPE.PLAY_TYPE_NORMAL then
            local sceneId = ModelList.CityModel.GetCity()
            city_music = Csv.GetData("new_city_play_scene", sceneId, "music")
        end
        UISound.play_loop(city_music)
    else
        UISound.stop("whisper")
        UISound.stop_bgm()
        UISound.play_bgm("settlementbgm")
    end
end

return this
