---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/19 9:53
---
--- super match 机器人叫号机
---
require("Combat/BaseMachine")

---@class SuperMatchCallNumberMachine  :   BaseMachine
local SuperMatchCallNumberMachine = BaseMachine:New("SuperMatchCallNumberMachine")
local this = SuperMatchCallNumberMachine

function SuperMatchCallNumberMachine:New()
    local o = {}
    setmetatable(o, { __index = SuperMatchCallNumberMachine });
    return o
end

function SuperMatchCallNumberMachine:Init()
    this.callNuberOrder = DeepCopy(ModelList.BattleModel:GetCurrModel():LoadGameData().matchData.userMarkPos)
    this.markTick = DeepCopy(ModelList.BattleModel:GetCurrModel():LoadGameData().matchData.markTick)
    this.callNum = DeepCopy(ModelList.BattleModel:GetCurrModel():LoadGameData().matchData.callNum)
    this:Register()
    if not EventName.Event_Card_Super_Match then
        local packageRequire = require("View/Bingo/UIView/SuperMatch/SuperMatchBattlePackage")
        packageRequire:Init()
    end
end

--- 玩家叫号数量和号码,检查是否能给机器人盖章
function SuperMatchCallNumberMachine:CheckSuperMatchNumber(callCount, number)
    this:OnCallPlayerNumber(callCount)
    return this:OnCallNumber(callCount, number)
end

function SuperMatchCallNumberMachine:Start()
    --this.callNuberOrder = ModelList.BattleModel:GetCurrModel():LoadGameData().matchData.callNuberOrder
end

function SuperMatchCallNumberMachine:Stop()
    this:UnRegister()
end

function SuperMatchCallNumberMachine:Pause(Pause)

end

function SuperMatchCallNumberMachine:IsInRange(number, pos)
    if pos <= 5 then
        if number <= 15 then
            return true
        end
    elseif pos <= 10 then
        if number > 15 and number <= 30 then
            return true
        end
    elseif pos <= 15 then
        if number > 30 and number <= 45 then
            return true
        end
    elseif pos <= 20 then
        if number > 45 and number <= 60 then
            return true
        end
    else
        if number > 60 then
            return true
        end
    end
    return false
end

function SuperMatchCallNumberMachine:OnCallNumber(totalCall, callNumber)
    local callSuccess = false
    if this.callNuberOrder and #this.callNuberOrder > 0 then
        if totalCall >= this.callNuberOrder[1].callOrder then
            local signInfo = {}
            local nextRoundSign = {}
            for i = 1, #this.callNuberOrder[1].markPos do
                for m = 1, #this.callNuberOrder[1].markPos[i].pos do
                    local cardId = this.callNuberOrder[1].markPos[i].cardId
                    if (this:IsInRange(callNumber, ConvertServerPos(this.callNuberOrder[1].markPos[i].pos[m]))) then
                        if not signInfo[cardId] then
                            signInfo[cardId] = { this.callNuberOrder[1].markPos[i].pos[m] }
                        else
                            table.insert(signInfo[cardId], this.callNuberOrder[1].markPos[i].pos[m])
                        end
                    else
                        if not nextRoundSign[cardId] then
                            nextRoundSign[cardId] = { this.callNuberOrder[1].markPos[i].pos[m] }
                        else
                            table.insert(nextRoundSign[cardId], this.callNuberOrder[1].markPos[i].pos[m])
                        end
                    end
                end
            end
            table.remove(this.callNuberOrder, 1)
            if #signInfo > 0 then
                Event.Brocast(EventName.Event_Trigger_Super_Match, signInfo)
                callSuccess = true
            end
            if #nextRoundSign > 0 then
                Event.Brocast(EventName.Event_Trigger_Super_Match_Next_Click, nextRoundSign)
                callSuccess = false
            end
        end
    end
    return callSuccess
end

function SuperMatchCallNumberMachine:on_x_update(tickTime)
    this.CheckTick(tickTime)
end

---
function SuperMatchCallNumberMachine.CheckTick(tickTime)
    if this.markTick and #this.markTick > 0 then
        if tickTime >= this.markTick[1].tick * 0.01 then
            if EventName.Event_Super_Match_Tick_Sign_Card then
                Event.Brocast(EventName.Event_Super_Match_Tick_Sign_Card, this.markTick[1].markPos)
                table.remove(this.markTick, 1)
                this.CheckTick(tickTime)
                this.CheckOmissionsTick()
            end
        end
    end
end

function SuperMatchCallNumberMachine.CheckOmissionsTick()
    if this.omissions and #this.omissions > 0 then
        for k, v in pairs(this.omissions) do
            for i = 1, #v do
                Event.Brocast(EventName.Event_Sign_Super_Match_Card, k, ConvertServerPos(v[i]))
            end
        end
    end
    this.omissions = nil
end

--- 保存漏号的信息
function SuperMatchCallNumberMachine:SaveOmissions(signInfo)
    this.omissions = signInfo
end

--- 机器人叫号，对玩家盖章
function SuperMatchCallNumberMachine:OnCallPlayerNumber(totalCall)
    if this.callNum and #this.callNum > 0 then
        if totalCall >= this.callNum[1].callOrder then
            Event.Brocast(EventName.Event_Trigger_Super_Match_Robot_Call_Number, this.callNum[1].number)
            table.remove(this.callNum, 1)
        end
    end
end

function SuperMatchCallNumberMachine:Register()
    Event.AddListener(EventName.Event_Trigger_Super_Match_Next_Click, self.SaveOmissions, self)
end

function SuperMatchCallNumberMachine:UnRegister()
    Event.RemoveListener(EventName.Event_Trigger_Super_Match_Next_Click, self.SaveOmissions, self)
end

return this
