---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/4/21 12:20
---

local CompetitionCookieReadyRankItem = BaseView:New("CompetitionCookieReadyRankItem")
local this = CompetitionCookieReadyRankItem
this.viewType = CanvasSortingOrderManager.LayerType.None

local reward_item = nil

this.auto_bind_ui_items = {
    "img_head",
    "text_thValue",
    "text_userName",
    "text_rewards",
    "TopRank1",
    "TopRank2",
    "TopRank3",
    "RewardType",
    "DoubleGift",
    "DoubleCollect",
    "imageFrame",
}


function CompetitionCookieReadyRankItem:New(isSettle)
    local o = {}
    self.__index = self
    setmetatable(o,self)
    return o
end

function CompetitionCookieReadyRankItem:Awake()
    self:on_init()
end

function CompetitionCookieReadyRankItem:OnDispose()
    reward_item = nil
end

function CompetitionCookieReadyRankItem:OnEnable()
    --self._init = true
    --self:SetRankData(self._data)
end

function CompetitionCookieReadyRankItem:SetOrderSuffix()
    local order = self._data.order
    self.text_thValue.text = tostring(self._data.order)
    self:SetRankOrder(order)
end

function CompetitionCookieReadyRankItem:SetRankOrder(order)
    fun.set_active(self.TopRank1,order == 1)
    fun.set_active(self.TopRank2,order == 2)
    fun.set_active(self.TopRank3,order == 3)
    fun.set_active(self.text_thValue,order >3)
end

function CompetitionCookieReadyRankItem:SetRankData(data,rankIndex)
    self._data = data or self._data
    if  self._data and self.img_head then
        self:SetOrderSuffix()
        if self._data.nickname == nil or self._data.nickname == "" then
            self.text_userName.text = self:GetNickName()
        else
            self.text_userName.text = self._data.nickname
        end
        self.text_rewards.text = fun.NumInsertComma(self._data.score)
        local avatar = self:GetHeadIcon()
        if data.robot == 0 then
            ModelList.PlayerInfoSysModel:LoadOwnHeadSprite(self.img_head)
        else
            Cache.SetImageSprite("HeadAtlas",avatar,self.img_head)
        end

        self:SetHeadFrame(data)
        self:SetRewardItem()
        fun.SetAsLastSibling(self.go)
    end
end

function CompetitionCookieReadyRankItem:SetHeadFrame(data)
    local myUid = ModelList.PlayerInfoModel:GetUid()
    local model = ModelList.PlayerInfoSysModel
    if myUid == tonumber(data.uid) then
        model:LoadOwnFrameSprite(self.imageFrame)
    else
        local useFrameName = model:GetCheckFrame(nil , data.uid)
        model:LoadTargetFrameSpriteByName(useFrameName ,self.imageFrame)
    end
end


function CompetitionCookieReadyRankItem:RequestPlayerTournamentInfo()
    --点击自己不弹出玩家信息
end


function CompetitionCookieReadyRankItem:GetHeadIcon()
    local avator = fun.get_strNoEmpty(self._data.avatar, Csv.GetData("robot_name",tonumber(self._data.uid) ,"icon"))
    return fun.get_strNoEmpty(avator, "xxl_head016")
end


function CompetitionCookieReadyRankItem:GetNickName()
    local avator = fun.get_strNoEmpty(self._data.nickname, Csv.GetData("robot_name",tonumber(self._data.uid),"name"))
    return fun.get_strNoEmpty(avator, string.format("User_%s",self._data.uid))
end

function CompetitionCookieReadyRankItem:SetRewardItem(tiers,difficulty,order)
    local view = require("View/CommonView/CollectRewardsItem")
    if not tiers or not difficulty  then
        tiers,difficulty = ModelList.TournamentModel:GetTiers()
    end
    if not order then
        order = self._data.order
    end
    if reward_item == nil then
        reward_item = {}
    end
end

return this