---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/7/9 17:48
---

---@短令牌任务完成

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder, "")
local this = PopupOrder

function PopupOrder.Execute(arg)
    local isOpen = ModelList.VolcanoMissionModel:IsOpenActivity()
    log.r("PopupOrder.Execute isOpen   " .. tostring(isOpen))
    if (not isOpen) then
        ---增加新需求:不在活动时间内,主动删除火山活动礼包数据  2022-07-09 17:48:30
        ModelList.GiftPackModel:RemoveVolcanoMissionPack()
        PopupOrder.Finish()
        return
    end

    local endTime = ModelList.VolcanoMissionModel:GetRemainTime()
    log.r("PopupOrder.Execute endTime   " .. endTime)
    if (endTime == nil or endTime <= 0) then
        PopupOrder.Finish()
        return
    end


    ---判断是否当日首次
    local isDayFirst = false
    local popDay = fun.read_value("volcanomission_popday", "")
    local currentDate = os.date("%Y-%m-%d")
    if (popDay == "" or popDay ~= currentDate) then
        isDayFirst = true
    end

    local isInit = ModelList.VolcanoMissionModel.IsInit()
    log.r("PopupOrder.Execute isInit   " .. tostring(isInit))
    if (isDayFirst and isInit == true and ModelList.VolcanoMissionModel:IsDataChange()
            or (isInit == true and ModelList.VolcanoMissionModel:IsLevelUp())
        ) then
        Facade.SendNotification(NotifyName.ShowUI, ViewList.VolcanoMissionMainView)
        PopupOrder.RefreshPopDay("volcanomission_popday")
    elseif (isDayFirst and isInit == true and ModelList.VolcanoMissionModel:IsFinalStep()) then
        Facade.SendNotification(NotifyName.ShowUI, ViewList.VolcanoMissionMainView) --特殊情况未领奖也弹
        PopupOrder.RefreshPopDay("volcanomission_popday")
    elseif (
            (ModelList.VolcanoMissionModel:IsFaild()
                or ModelList.VolcanoMissionModel:NeedShowMain()
            )
            and isInit == true) then
        ModelList.VolcanoMissionModel:ResetShowMainStatu(0)
        Facade.SendNotification(NotifyName.ShowUI, ViewList.VolcanoMissionMainView) --玩家被淘汰时，拉起活动界面
    elseif (isInit == false or isInit == nil) then
        Facade.SendNotification(NotifyName.ShowUI, ViewList.VolcanoMissionStartView)
    else
        PopupOrder.Finish()
    end
    this:RegisterEvent()
    -- PopupOrder.Finish()
end

function PopupOrder.RegisterEvent()
    Event.AddListener(EventName.Event_VolcanoMission_PopuEnd, this.OnPopupEnd, this)
end

function PopupOrder:OnPopupEnd(code, data)
    this.Finish()
end

function PopupOrder.Finish()
    Event.RemoveListener(EventName.Event_VolcanoMission_PopuEnd, this.OnPopupEnd, this)
    Event.Brocast(EventName.Event_popup_order_finish, true)
end

return PopupOrder
