---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/7/6 16:36
---
---@每日登陆奖励

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder,"")
local this = PopupOrder
local addEvent = false

function PopupOrder.Execute(arg)
    PopupOrder.Finish()
    --local isReward = ModelList.PlayerInfoModel.get_cur_daily_info()
    --local openLv = Csv.GetData("level_open",12,"openlevel")
    --if isReward and  isReward == 1 and ModelList.PlayerInfoModel:GetLevel() >= openLv then
    --    Event.AddListener(EventName.Event_popup_daily_reward_finish,PopupOrder.Finish,this)
    --    Facade.SendNotification(NotifyName.ShowUI,ViewList.DailyRewardView)
    --    addEvent = true
    --else
    --    PopupOrder.Finish()
    --end
end

function PopupOrder.Finish()
    if addEvent then
        Event.RemoveListener(EventName.Event_popup_daily_reward_finish,PopupOrder.Finish,this)
    end
    log.g("brocast  EventName.Event_popup_order_finish Event_popup_daily_reward_finish ")
    Event.Brocast(EventName.Event_popup_order_finish,true)
end

return PopupOrder