---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/12/11 16:29
---
--- 2023/12/11 副玩法推荐弹窗

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder,"")
local this = PopupOrder
local isPreFinish = false

function PopupOrder.Execute(args,orderData)
    isPreFinish = false
    local recommendModuleId =  ModelList.CityModel:GetRecommendModule()
   if recommendModuleId and not ModelList.GuideModel:IsGuiding() then
       local pId = ModelList.CityModel:GetRecommendPop()
       local featureData = Csv.GetData("feature_enter",pId)
       if not pId or not featureData then
           pId = Csv.getSGPPop()
       end
       if not this.IsAllowPop("last_feature_pop_time"..pId,orderData) then
           this.Finish()
           return
       end
       Event.AddListener(EventName.Event_popup_new_play_type_open,this.Finish)
       local params = {
           pId = pId,
           isfromPopup = true,
       }
       Facade.SendNotification(NotifyName.ShowUI, ViewList.SpecialGameplayEnter,nil,nil,params)
       this.RefreshPopTime("last_feature_pop_time"..pId,orderData)
   else
        this.Finish()
    end
end

function PopupOrder.Finish(owner,isChangePreFinish)
    if isChangePreFinish then
        isPreFinish = isChangePreFinish
    end
    log.g("brocast  EventName.Event_popup_order_finish ")
    Event.RemoveListener(EventName.Event_popup_new_play_type_open,this.Finish)

    this.NotifyCurrentOrderFinish()
end

function PopupOrder.IsPreOrderFinish()
    return isPreFinish
end

return this