---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/2/6 15:35
---   评分界面


local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder,"")
local this = PopupOrder

function PopupOrder.Execute()
    if ModelList.PlayerInfoModel.GetShowScore() then
        Event.AddListener(EventName.Event_popup_EvaluateUs_finish,PopupOrder.Finish,this)
        local platform = UnityEngine.Application.platform 
        if platform == UnityEngine.RuntimePlatform.IPhonePlayer then 
           
            Facade.SendNotification(NotifyName.ShowUI,ViewList.EvaluateUsIOSView)
        else 
            Facade.SendNotification(NotifyName.ShowUI,ViewList.EvaluateUsView)
        end 
        
      

        --EvaluateUsIOSView
        --PopupOrder.Finish()
    else
        PopupOrder.Finish()
    end
end

function PopupOrder.Finish()
    Event.RemoveListener(EventName.Event_popup_EvaluateUs_finish,PopupOrder.Finish)
    log.g("brocast  EventName.Event_popup_order_finish ")
    Event.Brocast(EventName.Event_popup_order_finish,true)
end

return PopupOrder