--
--require "View/MakeFood/KitchenIngredientView"
--
--require "View/MakeFood/ketchenState/BaseMakeFoodKitchenState"
--require "View/MakeFood/ketchenState/MakeFoodKitchenOriginalState"
--require "View/MakeFood/ketchenState/MakeFoodKitchenEnterState"
--require "View/MakeFood/ketchenState/MakeFoodKitchenExitState"
--
--MakeFoodKitchenView = BaseView:New("MakeFoodKitchenView","MakeFoodAtlas")
--local this = MakeFoodKitchenView
--this.viewType = CanvasSortingOrderManager.LayerType.TopConsole
--
--local kitchenIngredient_cache = nil
--
--this.auto_bind_ui_items = {
--    "anima",
--    "btn_goback",
--    "ingredients3",
--    "ingredients4",
--    "ingredients5",
--    "ingredients6",
--    "makeFoodCut",
--    "makeFoodJuice",
--    "makeFoodEgg",
--    "makeFoodPot",
--    "makeFoodOven",
--    "makeFoodDant"
--}
--
--local AnimationCurve = UnityEngine.AnimationCurve
--local Keyframe = UnityEngine.Keyframe
--local Time = UnityEngine.Time
--
--local animDataList = nil
--local ingredient_count = nil
--
--local food_audio = nil
--
--function MakeFoodKitchenView:Awake()
--    self.update_x_enabled = true
--    self:on_init()
--end
--
--function MakeFoodKitchenView:OnEnable()
--    Facade.RegisterView(self)
--    Util.SetMaterialFloat(self.makeFoodCut.gameObject, "_UseCanvasGroup",0)
--    self:BuildFsm()
--    self._fsm:GetCurState():Enter(self._fsm)
--    ModelList.ApplicationGuideModel:LoadGuide("MakeFoodKitchenView")
--end
--
--function MakeFoodKitchenView:OnDisable()
--    Facade.RegisterView(self)
--    self:Stop_makefood_audio()
--
--    animDataList = nil
--    ingredient_count = nil
--    food_audio = nil
--
--    if self.coroutine then
--        coroutine.stop(self.coroutine)
--        self.coroutine = nil
--    end
--    Util.SetMaterialFloat(self.makeFoodCut.gameObject, "_UseCanvasGroup", 0)
--end
--
--function MakeFoodKitchenView:on_x_update()
--    if animDataList then
--        local time = 0
--        for key, value in pairs(animDataList) do
--            if not value.finish then
--                time = Time.time - value.time
--                value.go.transform.localPosition = Vector3.New(value.kf_x:Evaluate(time),value.kf_y:Evaluate(time),0)
--                value.go.transform.localScale = Vector3.New(value.kf_s:Evaluate(time),value.kf_s:Evaluate(time),1)
--                value.alpha.alpha = value.kf_a:Evaluate(time)
--                if time >= 1 and not value.isOpen then
--                    value.isOpen = true
--                    value.open()
--                end
--                if time >= value.kf_a[value.kf_a.length - 1].time then
--                    value.finish = true
--                    fun.set_active(value.go.transform,false,false)
--                    value.close()
--                    animDataList[key] = nil
--                end
--            end
--        end
--    end
--end
--
--function MakeFoodKitchenView:BuildFsm()
--    self:DisposeFsm()
--    self._fsm = Fsm.CreateFsm("MakeFoodKitchenView",self,{
--        MakeFoodKitchenOriginalState:New(),
--        MakeFoodKitchenEnterState:New(),
--        MakeFoodKitchenExitState:New()
--    })
--    self._fsm:StartFsm("MakeFoodKitchenOriginalState")
--end
--
--function MakeFoodKitchenView:DisposeFsm()
--    if self._fsm then
--        self._fsm:Dispose()
--        self._fsm = nil
--    end
--end
--
--function MakeFoodKitchenView:PlayEnter()
--    AnimatorPlayHelper.Play(self.anima,"MakeFoodKitchenViewenter",false,function()
--        self:SetCurrentCuisines()
--        self._fsm:GetCurState():Accomplish(self._fsm)
--        Util.SetMaterialFloat(self.makeFoodCut.gameObject, "_UseCanvasGroup",1)
--    end)
--end
--
--function MakeFoodKitchenView:PlayExit()
--    local count = 0
--    local num = #kitchenIngredient_cache
--    local exit_callback = function()
--        count = count + 1
--        if count == num then
--            local kitchen_ware = {this.makeFoodCut,this.makeFoodJuice,this.makeFoodEgg,this.makeFoodPot,this.makeFoodOven,this.makeFoodDant}
--            for key, value in pairs(kitchen_ware) do
--                value:SetAnimation("idle",nil)
--            end
--            Util.SetMaterialFloat(self.makeFoodCut.gameObject, "_UseCanvasGroup",0)
--            AnimatorPlayHelper.Play(self.anima,{"MakeFoodKitchenViewexit","MakeFoodKitchenViewenter"},false,function()
--                Facade.SendNotification(NotifyName.CloseUI,this)
--            end,0,1)
--        end
--    end
--    local delay = 0
--    for key, value in pairs(kitchenIngredient_cache) do
--        local exit_coroutine = function()
--            delay = delay + 0.05
--            coroutine.wait(delay)
--            value:PlayExit(exit_callback)
--        end
--        self.coroutine = coroutine.resume(coroutine.create(exit_coroutine))
--    end
--end
--
--function MakeFoodKitchenView:SetCurrentCuisines()
--    local cuisinesId = ModelList.ItemModel:GetMakeFoodCurrentCuisines()
--    if cuisinesId then
--        local cuisinesData = Csv.GetData("city_recipe",cuisinesId)
--        if cuisinesData then
--            local count = #cuisinesData.item
--            local ingredien_go = {self.ingredients3,self.ingredients4,self.ingredients5,self.ingredients6}
--            local ingredien_parent = ingredien_go[math.min(math.max(count - 2 ,0), 6)]
--            fun.set_active(ingredien_parent.transform,true,false)
--            local delay = 0
--            kitchenIngredient_cache = {}
--            for index, value in ipairs(cuisinesData.item) do
--                local creat_ingredient = function()
--                    delay = delay + 0.05
--                    coroutine.wait(delay)
--                    local go = fun.get_child(ingredien_parent,index - 1)
--                    local view = KitchenIngredientView:New(value,index)
--                    view:SkipLoadShow(go.gameObject)
--                    table.insert(kitchenIngredient_cache,view)
--                    ingredient_count = (ingredient_count or 0) + 1
--                end
--                self.coroutine = coroutine.resume(coroutine.create(creat_ingredient))
--            end
--        end
--    end
--end
--
--function MakeFoodKitchenView:on_btn_goback_click()
--    self._fsm:GetCurState():Exit(self._fsm)
--    ModelList.ApplicationGuideModel:UnloadGuide("MakeFoodKitchenView")
--    Facade.SendNotification(NotifyName.FoodIngredientView.GoBackRestaurant)
--end
--
--function MakeFoodKitchenView.OnFlyIngredient(itemId,transform,goList)
--    if ingredient_count and ingredient_count > 0 then
--        ingredient_count = ingredient_count - 1
--        local cooking = Csv.GetData("item",itemId,"cooking")
--        local kitchen_ware = {
--            {this.makeFoodCut,false},
--            {this.makeFoodJuice,false},
--            {this.makeFoodEgg,false},
--            {this.makeFoodPot,false},
--            {this.makeFoodOven,true},
--            {this.makeFoodDant,true}
--        }
--        local audio = {
--            "food_cut",
--            "food_blender",
--            "food_stir",
--            "food_fried",
--            "food_oven",
--            "food_boil"
--        }
--
--        local item_count = #goList
--
--        local targetPos = transform:InverseTransformPoint(kitchen_ware[cooking][1].transform.position)
--
--        local keyFrame_pos = {this:GetItem1PosKeyFrame(targetPos,item_count),this:GetItem2PosKeyFrame(targetPos,item_count),this:GetItem3PosKeyFrame(targetPos,item_count)}
--        if animDataList == nil then
--            animDataList = {}
--        end
--        for index, value in ipairs(goList) do
--            local animData = {
--                go = value,
--                alpha = fun.get_component(value.transform,fun.CANVAS_GROUP),
--                time = Time.time,
--                kf_x = keyFrame_pos[index][1],
--                kf_y = keyFrame_pos[index][2],
--                kf_s = this:GetItemScaleFrame(),
--                kf_a = this:GetItemAlphaFrame(),
--            }
--            if index == 1 then
--                animData.open = function()
--                    kitchen_ware[cooking][1]:SetAnimation("open",nil,false,0)
--                end
--                animData.close = function()
--                    kitchen_ware[cooking][1]:SetAnimation("closure",nil,false,0)
--                    kitchen_ware[cooking][1]:AddAnimation("start",nil,true,0)
--                    this.Play_makefood_audio(audio[cooking])
--                end
--            else
--                animData.open = function()end
--                animData.close = function()end
--            end
--            table.insert(animDataList,animData)
--        end
--    end
--    if ingredient_count == 0 then
--        this.coroutine = coroutine.resume(coroutine.create(function()
--            fun.set_active(this.btn_goback.transform,false,false)
--            coroutine.wait(3)
--            this.Stop_makefood_audio()
--            Facade.SendNotification(NotifyName.ShowUI,ViewList.MakeFoodProductView)
--        end))
--    end
--end
--
--function MakeFoodKitchenView.Play_makefood_audio(audio)
--    UISound.play_loop(audio)
--    if food_audio == nil then
--        food_audio = {}
--    end
--    table.insert(food_audio,audio)
--end
--
--function MakeFoodKitchenView.Stop_makefood_audio()
--    if food_audio then
--        for key, value in pairs(food_audio) do
--            UISound.stop_loop(value)
--        end
--        food_audio = nil
--    end
--end
--
--function MakeFoodKitchenView:GetItem1PosKeyFrame(pos,count)
--    if count == 2 then
--        return {
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,-41),Keyframe.New(0.77,-41),Keyframe.New(1.65,pos.x)),
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,25),Keyframe.New(0.77,25),Keyframe.New(1.65,pos.y + 66))
--        }
--    else
--        return {
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,-52),Keyframe.New(0.77,-52),Keyframe.New(1.65,pos.x)),
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,30),Keyframe.New(0.77,30),Keyframe.New(1.65,pos.y + 66))
--        }
--    end
--end
--
--function MakeFoodKitchenView:GetItem2PosKeyFrame(pos,count)
--    if count == 2 then
--        return {
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,34),Keyframe.New(0.77,34),Keyframe.New(1.65,pos.x - 50)),
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,-11),Keyframe.New(0.77,-11),Keyframe.New(1.65,pos.y + 40))
--        }
--    else
--        return {
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,34),Keyframe.New(0.77,34),Keyframe.New(1.65,pos.x - 50)),
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,41),Keyframe.New(0.77,41),Keyframe.New(1.65,pos.y + 40))
--        }
--    end
--end
--
--function MakeFoodKitchenView:GetItem3PosKeyFrame(pos,count)
--    if count == 2 then
--        return nil
--    else
--        return {
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,-5),Keyframe.New(0.77,-5),Keyframe.New(1.65,pos.x)),
--            AnimationCurve.New(Keyframe.New(0,0),Keyframe.New(0.52,-11),Keyframe.New(0.77,-11),Keyframe.New(1.65,pos.y))
--        }
--    end
--end
--
--function MakeFoodKitchenView:GetItemScaleFrame()
--    return AnimationCurve.New(Keyframe.New(0,1),Keyframe.New(0.22,1),Keyframe.New(0.52,0.5),Keyframe.New(0.77,0.5),Keyframe.New(1.1,1),Keyframe.New(1.45,1),Keyframe.New(1.65,0))
--end
--
--function MakeFoodKitchenView:GetItemAlphaFrame()
--    return AnimationCurve.New(Keyframe.New(0,1),Keyframe.New(1.45,1),Keyframe.New(1.65,0))
--end
--
--function MakeFoodKitchenView.OnClaimRewardSucceed()
--    Facade.SendNotification(NotifyName.CloseUI,this)
--end
--
--this.NotifyList =
--{
--    {notifyName = NotifyName.FoodIngredientView.ExchangeSucceed, func = this.OnClaimRewardSucceed},
--    {notifyName = NotifyName.FoodIngredientView.FlyIngredient,func = this.OnFlyIngredient}
--}
--
--return this