---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/8/11 17:17
---

local SevenDayLoginExitState = Clazz(BaseFsmState,"SevenDayLoginExitState")

function SevenDayLoginExitState:OnEnter(fsm,previous,...)
    log.g("OnEnter SevenDayLoginExitState")
    fsm:GetOwner():EnableExitButton()
    self._fsm = fsm


end

function SevenDayLoginExitState:OnLeave(fsm)

end

function SevenDayLoginExitState:GetReward()

end

function SevenDayLoginExitState:OnContinue()
    if   self._fsm then
        self._fsm:GetOwner():PlayExit()
    end
    LuaTimer:SetDelayFunction(0.8,function()
        Facade.SendNotification(NotifyName.CloseUI,ViewList.SevenDayLoginView)
        Event.Brocast(EventName.Event_popup_seven_day_login_finish)
    end)
end

function SevenDayLoginExitState:GetGiftReward(boxId)
end

return SevenDayLoginExitState