---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/2/7 15:22
---


---  夏威夷玩法 格子盖章效果
local BaseSignEffect =  require("View.Bingo.EffectModule.Card.SignEffect.BaseSignEffect")
local SingleWolfSignEffect = BaseSignEffect:New("SingleWolfSignEffect")
setmetatable(SingleWolfSignEffect,BaseSignEffect)
local this = SingleWolfSignEffect
local wolfList = {7, 17, 9, 19}

function SingleWolfSignEffect:RegisterEvent()
    Event.AddListener(EventName.Event_Christmas_Sign_Cell_Background, self.CellBgEffect, self)
end

function SingleWolfSignEffect:UnRegisterEvent()
    Event.RemoveListener(EventName.Event_Christmas_Sign_Cell_Background, self.CellBgEffect, self)
end

--圆月技能表现
function SingleWolfSignEffect:TriggerSingleBingo(cardId, cellIndex)
    cardId = tonumber(cardId)

    local logicModule = BattleLogic.GetLogicModule(LogicName.Card_logic)
    if logicModule:IsJackpot(cardId) then
        return
    end
    
    local curModel, cardView = ModelList.BattleModel:GetCurrModel(), self:GetCardView()
    local target, wolfPos = cardView:GetCardMap((cardId))
    
    if ModelList.BattleModel:IsRocket() then
        --在小火箭界面使用5036里的数据
        local data = curModel:GetSettleExtraInfo("wolfMoon")
        data = table.find(data, function(k, v)
            local cellID = ConvertServerPos(v.pos)
            return v.cardId == cardId and cellID == cellIndex
        end)
        if data then
            wolfPos = ConvertServerPos(data.wolfPos)
        else
            wolfPos = curModel:GetValidWolfForMoonSkill(cardId, cellIndex)
        end
    else
        wolfPos = curModel:GetValidWolfForMoonSkill(cardId, cellIndex)
    end
    
    --添加ExtraData，结算时通知服务器
    curModel:GetRoundData(cardId):AddExtraUpLoadData("wolfMoon", {
        cardId = cardId,
        pos = ConvertCellIndexToServerPos(cellIndex),
        wolfPos = ConvertCellIndexToServerPos(wolfPos),
    }, "pos")
    
    --wolfPos的狼人破坏全部锁链
    --数据层更新
    BattleLogic.GetLogicModule(LogicName.Card_logic):ReduceAllLogicPrison(cardId, wolfPos)

    --技能效果
    BattleEffectCache:GetSkillPrefabFromCache("SingleWolfskillyuanyue", target, function(obj)
        UISound.play("werewolf_moon")
        
        if ModelList.BattleModel:IsRocket() then
            fun.set_gameobject_scale(obj,0.6,0.6,0.6)
        end
        
        local index = fun.get_index(wolfList, wolfPos)
        local animaName = string.format("in%s", index)
        local anima = fun.get_component(obj, fun.ANIMATOR)
        if anima then
            anima:Play(animaName)
        end
        
        --表现层更新
        LuaTimer:SetDelayFunction(3,function()
            curModel:RefreshSignLogicDelayTime()
            cardView:ReduceAllPrison(cardId, wolfPos)
        end)
    end, 3.33, cardId)
end

--格子盖章效果
function SingleWolfSignEffect:SignCardEffect(cardId,index, cardCell, signType, delay, self_bingo, giftLen)
    signType = signType or 0
    if self:CannotSignCell(cardId, index, signType) then return end
    delay = delay or 0
    for i = 1, fun.get_child_count(cardCell) do
        fun.set_active(fun.get_child(cardCell,i-1),false)
    end
    self:HideCellChild(cardCell, cardId)
    
    Event.Brocast(EventName.Magnifier_Close_Single_Cell, cardCell, false)
    
    if self_bingo then
        self:TriggerSingleBingo(cardId, index)
    end
    Event.Brocast(EventName.Event_Collect_Item_By_Sign, cardId, index)
end

function SingleWolfSignEffect:HideCellChild(cardCell, cardId)
    local ref_temp = fun.get_component(cardCell, fun.REFER)
    local number1 = ref_temp:Get("number1")
    fun.set_active(number1, false)
    local number2 = ref_temp:Get("number2")
    fun.set_active(number2, false)
    local number3 = ref_temp:Get("number3")
    fun.set_active(number3, false)
    local number4 = ref_temp:Get("number4")
    fun.set_active(number4, false)
    local doublebg = ref_temp:Get("doublebg")
    fun.set_active(doublebg, false)
    local gift = ref_temp:Get("gift")
    fun.set_active(gift, false)
    local bg_tip = ref_temp:Get("bg_tip")
    fun.set_active(bg_tip, false)

    self:HideJoker(ref_temp, cardId)
end

-- 盖章后地板效果
local function GetDiEffectName(drinkType)
    if drinkType == 1 then
        return "Christmasdiwazi"
    elseif drinkType == 2 then
        return "Christmasdilingdang"
    elseif drinkType == 3  then
        return "Christmasdiguaizhang"
    else
        return "Christmasdixueqiu"
    end
end

--- 格子底部印章效果
function SingleWolfSignEffect:CellBgEffect(drinkType, cardId, cellIndex)
    local diEffect = BattleEffectPool:Get(GetDiEffectName(drinkType))
    fun.set_parent(diEffect, self:GetCardView():GetCardCell(tonumber(cardId), cellIndex), true)
    if self.cardView then
        self.cardView:StorageCellBgEffect(tonumber(cardId) ,cellIndex,diEffect)
    end
end

return this