---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/3/15 12:25
---

--- 随机盖章

local BaseSkill =  require("View.Bingo.CardModule.Skill.BaseSkill")

local Play10Skill = BaseSkill:New("Play10Skill")
setmetatable(Play10Skill,BaseSkill)
local this = Play10Skill

this.skillRocketGetIndex = 1
local function CurrRocketIndex()
    local index = this.skillRocketGetIndex
    this.skillRocketGetIndex = this.skillRocketGetIndex +1
    if this.skillRocketGetIndex>3 then this.skillRocketGetIndex = 1 end
    return index
end

function Play10Skill:ShowSkill (cardId, cellIndex, powerId,serverExtraPos)
    local pos = ConvertCellIndexToServerPos(cellIndex)
    local extraPos = { }
    local skillXYZ = Csv.GetData("skill", 108, "skill_xyz")
    local ori_x = math.modf((cellIndex - 1) / 5)
    local ori_y = math.modf((cellIndex - 1) % 5)
    for i = 1, #skillXYZ do
        local new_x = ori_x + skillXYZ[i][1]
        local new_y = ori_y - skillXYZ[i][2]
        if new_x >= 0 and new_x <= 4 and new_y >= 0 and new_y <= 4 then
            local new_index = new_x * 5 + new_y + 1
            table.insert(extraPos,new_index)
        end
    end

    if #extraPos > 0 then
        this.cardView = ModelList.BattleModel:GetCurrBattleView():GetCardView()
        this.cardPower = self:GetCardPower()
        local targetObj = this.cardView:GetCardCell(tonumber(cardId), cellIndex)
        BattleEffectCache:GetSkillPrefabFromCache("floridaSkillTaril", targetObj, function(obj)
            UISound.play("city4_skill")
            LuaTimer:SetDelayFunction(2, function()
                for i = 1, #extraPos do
                    local newPos = extraPos[i]
                    local endPos = this.cardView:GetCardCell(tonumber(cardId),  extraPos[i])
                    BattleEffectCache:GetSkillPrefabFromCache("floridaSkillGet", endPos, function(ob)
                        local objAnima = fun.get_component(ob, fun.ANIMATOR)
                        if objAnima then
                            objAnima:Play("Get" .. CurrRocketIndex())
                        end
                        LuaTimer:SetDelayFunction(1.6, function()
                            this.cardView:OnClickCardIgnoreJudgeByIndex(cardId, newPos, powerId)
                            this.cardPower:ChangeCellState(cardId, newPos, this.CellState.Signed)
                        end,nil,LuaTimer.TimerType.Battle)
                    end, 3)
                end
            end,nil,LuaTimer.TimerType.Battle)
        end, 5, cardId)
    end
end

return this