---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18/11/2024 ÏÂÎç 2:43
---

local ProcedureChristmasSynthesis = Clazz(BaseProcedure,"ProcedureChristmasSynthesis")
local isEnter = false
local isShowReady = false
function ProcedureChristmasSynthesis:New()
    local o = {}
    setmetatable(o,{__index = ProcedureChristmasSynthesis})
    return o
end

function ProcedureChristmasSynthesis:OnEnter(fsm, previous)
    isEnter = true
    ProcedureChristmasSynthesis:StartShow()
end

function ProcedureChristmasSynthesis:ShowReadyView()
    isShowReady = true
    ProcedureChristmasSynthesis:StartShow()
end

function ProcedureChristmasSynthesis:StartShow()
    if isShowReady and isEnter then
        local game_ui = fun.GameObject_find("Canvas/GameUI/NormalNode")
        local gameBingoView = fun.find_child(game_ui,"ChristmasSynthesisBingoView")
        Facade.SendNotification(NotifyName.SkipLoadShowUI, ViewList.ChristmasSynthesisBingoView, gameBingoView)


        local game_ui = fun.GameObject_find("Canvas/GameUI/NormalNode")
        local getReadyView =  fun.find_child(game_ui,"ChristmasSynthesisReadyView")
        Facade.SendNotification(NotifyName.SkipLoadShowUI,ViewList.SpecialPlayReadyView, getReadyView)
        if ViewList.SceneLoadingGameView and ViewList.SceneLoadingGameView.go then
            ViewList.SceneLoadingGameView:FadeOut()
        end

    end

end

function ProcedureChristmasSynthesis:OnLeave(fsm)
    Facade.RemoveCommand(NotifyName.Bingo.ShowBingoView)
end

function ProcedureChristmasSynthesis:ProcedureName()
    return "ProcedureChristmasSynthesis"
end

function ProcedureChristmasSynthesis:GetCurrentSceneName()
    return "SceneChristmasSynthesis"
end

return ProcedureChristmasSynthesis
