--
--ProcedureTest = Clazz(BaseProcedure,"ProcedureTest")
--
--function ProcedureTest:New()
--    local o = {}
--    setmetatable(o,{__index = ProcedureTest})
--    return o
--end
--
--function ProcedureTest:OnEnter(fsm)
--    local game_ui = fun.find_gameObject_with_tag("NormalUiRoot")
--        local TestView =  fun.find_child(game_ui,"TestView")
--        Facade.SendNotification(NotifyName.SkipLoadShowUI,ViewList.TestView,TestView,nil,function()
--
--        end)
--end
--
--function ProcedureTest:OnLeave(fsm)
--end