---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/8/13 21:14
---

local LoginView = BaseView:New("LoginView")
local this = LoginView
this.isCleanRes = true
local LoginState = {loadScene = 1, preLoadResource = 2,finish = 3,closeSelf = 4,none = 5}
local currentLoginState = nil

local operation_progress = nil
local login_progress = nil

this.auto_bind_ui_items = {
    "game_lider",
    "txt_percent",
    "txt_uid",
    "Canvas",
    "txt_tips",
    "btn_facebook_login",
    "btn_AppleSignIn_login",
    "btn_guest_login",
    "txt_version"
}

function LoginView:Awake()
    Facade.RegisterView(this)
    this:on_init()
end

function LoginView:SetPlatform()
    if not ModelList.PlayerInfoModel:IsFaceBookOpen() then
        fun.set_active(self.btn_facebook_login,false)
    end

    local platform = UnityEngine.Application.platform

    if platform == UnityEngine.RuntimePlatform.IPhonePlayer then
        fun.set_active(self.btn_AppleSignIn_login,true)
    else 
        fun.set_active(self.btn_AppleSignIn_login,false )
    end 

end

function LoginView:OnLoginSuccess()
    this:LoadSceneHome()
end

function LoginView:OnLoginFaild()

end

function LoginView:LoadSceneHome()
    if fun.get_active_self(self.btn_facebook_login) == false and ModelList.PlayerInfoModel:IsFaceBookOpen() == true then 
        return ;
    end 

    if ModelList.GuideModel:IsGuideMainView() then
        log.r("LoginView:LoadSceneHome" )
        fun.set_active(self.btn_facebook_login,false)
        fun.set_active(self.btn_AppleSignIn_login,false)
        fun.set_active(self.btn_guest_login,false)
        ViewList.GuideView:Close()
        local empty = UnityEngine.GameObject.New()
        Facade.SendNotification(NotifyName.SkipLoadShowUI, ViewList.GuideSceneLoadingGameView,empty)
        ModelList.GameModel:ReqEnterGame()
    else
        log.r("LoginView:LoadSceneHomeAsync" )
        self:LoadSceneHomeAsync()
    end 
end

function LoginView:OnEnable()
    this:SetPlatform()
    self.txt_version.text = "v"..UIUtil.get_client_version()
    ModelList.ClearModelList()
    Network.Close()
end

function LoginView:OnDisable()
    Facade.RemoveView(this)
    self.doLogin = nil
    self.LoginSuccess = nil
    this.operation = nil
    currentLoginState = nil
    operation_progress = nil
    login_progress = nil
    self:StopTimer()
end

function LoginView:StopTimer()
    if self.timer then
        self.timer:Stop()
        self.timer = nil
    end
end

function LoginView:SetTimer()
    self.timer = Invoke(function()
        log.r("LoginView:SetTimer()")
        self.doLogin = false
    end,5)
end

function LoginView:OnDestroy()
    this:Close()
end

function LoginView:on_btn_Sign_Apple_click()
end

function LoginView:on_btn_Sign_FaceBook_click()
    local platform = UnityEngine.Application.platform
    if platform == UnityEngine.RuntimePlatform.WindowsEditor or platform == UnityEngine.RuntimePlatform.OSXEditor then
        UIUtil.show_common_error_popup(8010,true,nil)
    else
        ModelList.loginModel.FbLogin(function()
            UIUtil.show_common_error_popup(8010,true,nil)
        end)
    end
end

function LoginView:on_btn_guest_login_click()
    if not self.doLogin then
        self.doLogin = true
        self:SetTimer()
        ModelList.loginModel.GuestLogin(function()
            self:StopTimer()
            self.doLogin = false
            UIUtil.show_common_error_popup(8010,true,nil)
        end,function()
            if Network.isConnect and  Network.SendConnectState < 3 then
                log.r("guest_login  =>>> guest_login")
                self:OnLoginSuccess()
            end
        end)
    end
end

function LoginView:on_btn_facebook_login_click()
    local platform = UnityEngine.Application.platform
    if platform == UnityEngine.RuntimePlatform.WindowsEditor or platform == UnityEngine.RuntimePlatform.OSXEditor then
        UIUtil.show_common_error_popup(8010,true,nil)
    else
        if not self.doLogin then
            self.doLogin = true
            self:SetTimer()
            ModelList.loginModel.FbLogin(function(code)
                self:StopTimer()
                self.doLogin = false
                if code and code == RET.RET_ACCOUNT_BIND_NOT_CURRENT then
                    UIUtil.show_common_error_popup(9037,true,nil)
                else
                    UIUtil.show_common_error_popup(8010,true,nil)
                end
            end,function()
                if Network.isConnect then
                    self:OnLoginSuccess()
                end
            end)
        end
    end
end

function LoginView:on_btn_AppleSignIn_login_click()
    local platform = UnityEngine.Application.platform

    if platform == UnityEngine.RuntimePlatform.IPhonePlayer then
        if not self.doLogin then
            self.doLogin = true
            self:SetTimer()
            ModelList.loginModel.AppleLogin(function(code)
                self:StopTimer()
                self.doLogin = false
                if code and code == RET.RET_ACCOUNT_BIND_NOT_CURRENT then
                    UIUtil.show_common_error_popup(9037,true,nil)
                else
                    UIUtil.show_common_error_popup(8010,true,nil)
                end
            end,function()
                if Network.isConnect then
                    self:OnLoginSuccess()
                end
            end,true)
        end
    else 
        UIUtil.show_common_error_popup(8010,true,nil)
    end 
end

function LoginView:getNextSceneName()
    return "SceneHome"
end

function LoginView:CanAddSceneViewManager()
    return false
end

function LoginView:LoadSceneHomeAsync()
    if not this.operation then
            fun.set_active(self.btn_facebook_login,false)
            fun.set_active(self.btn_AppleSignIn_login,false)
            fun.set_active(self.btn_guest_login,false)
            fun.set_active(self.game_lider,true)
        LoadSceneAsync(this:getNextSceneName(),ProcedureCityHome:New(),function(operation)
            this.operation  = operation
            -- this.operation.allowSceneActivation = false
            currentLoginState = LoginState.loadScene
            this.update_x_enabled = true
            this:start_x_update()
        end)
    end
end

function LoginView:LoadCommonResource()
    currentLoginState = LoginState.none
    AssetManager.load_common_res(function() --加载通用ab资源
        AssetManager.load_lobby_res(function () --加载大厅资源和音效
            currentLoginState = LoginState.finish
        end)
    end)
end

function LoginView:SetParentToGlobalUICamera()
    if this.go == nil then 
        return 
    end 
    local parent =  UnityEngine.GameObject.FindWithTag("GlobalUiRoot")
    fun.set_child_layer(this.go,"FakeUI")
    this.go.transform:SetParent(parent.transform)
    this.go.transform.localScale = Vector3.New(1,1,1)
    this.go.transform.localPosition = Vector3.New(0,0,0)
    local rect = fun.get_component(this.go,fun.RECT)
    if rect then
        rect.offsetMin = Vector2.New(0, 0)
        rect.offsetMax = Vector2.New(0, 0)
    end
end

function LoginView:FadeOut()
    Anim.canvas_group_do_fade_loop(this["Canvas"],1, 0, 0.5,1,0, function()
        this:Close();
    end)
end

function LoginView:SetSliderProgress(progressValue,maxProgress)
    local progress = math.min((progressValue or 0) + 0.3 * ArtConfig.EnterGameLoading_Process_Move_Speed, maxProgress or 0)
    self.game_lider.value = progress
    self.txt_percent.text = string.format("%.2f%s",progress * 100,"%")
    return progress
end

function LoginView:on_x_update()
    if this.operation == nil then
        return
    end
    if this.operation.Progress > 0.01 then
        operation_progress = this.operation.Progress    
    end
    if currentLoginState == LoginState.loadScene then
        login_progress = self:SetSliderProgress(login_progress,operation_progress)
        if login_progress >= 0.89 then
            currentLoginState = LoginState.preLoadResource
        end
    elseif currentLoginState == LoginState.preLoadResource then
        self:SetParentToGlobalUICamera()
        self:LoadCommonResource()    
    elseif currentLoginState == LoginState.finish then
        login_progress = self:SetSliderProgress(login_progress,1.00)
        if login_progress >= 1.00 then
            -- this.operation.allowSceneActivation = true
            this.operation:UnSuspend()
            currentLoginState = LoginState.closeSelf
        end
    elseif currentLoginState == LoginState.closeSelf then
        currentLoginState = LoginState.none
        Invoke(function()
            self:FadeOut()
        end,1)
    end
end

this.NotifyList = {
    {notifyName = NotifyName.Login.LoginSuccess, func = this.OnLoginSuccess},
}
return this

