---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/8/29 20:44
---

CityDragRightState = Clazz(CityDragBaseState,"CityDragRightState")

function CityDragRightState:OnEnter(fsm,lastName,...)
    self._fsm = fsm
    self._owner = fsm:GetOwner()
    if self._owner then
        self._owner:OnDragRight()
    end
    local params = ({ ... })[1]
    if params then
        self._posX = params
    else
        self._posX = self._owner:GetHangPointPosX()
    end
end

function CityDragRightState:OnLeave(fsm)
    self._fsm = nil
    self._owner = nil
    self._posX = nil
end

function CityDragRightState:Dispose()
    self:OnLeave(nil)
end

function CityDragRightState:OnDragCity(state,go,startPos,pos,deltaTime)
    if state == LuaEasyTouchDragState.enddrag then
        self:ChangeState(self._fsm,"CityDragRightEndState")
        return
    end
    if state == LuaEasyTouchDragState.dragging then
        if startPos.x > pos.x then
            if self._owner:IsDragLeftMax() then
                self:ChangeState(self._fsm,"CityDragLeftLimitState",self._posX)
            else
                self:ChangeState(self._fsm,"CityDragLeftState",self._posX)
            end
            return
        end
        self._owner:OnDragRightMove(pos)
    end
end