---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2023/5/19 14:25
---
local BaseCardJokerEffect  =  require("View.Bingo.EffectModule.CardJoker.BaseCardJokerEffect")

local JokerballInjectionEffect = BaseCardJokerEffect:New()
local this = JokerballInjectionEffect

function JokerballInjectionEffect:New()
      local o = { isLoaded = false, changeSceneClear = true}
        self.__index = self
        setmetatable(o, self)
        return o
end

function JokerballInjectionEffect:Play()

end


return this