---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/9/1 14:13
---
require "State/PowerUpCardEntityView/DrawCardsBaseState"

DrawCardsFlyState = Clazz(DrawCardsBaseState,"DrawCardsFlyState")

function DrawCardsFlyState:OnEnter(fsm,previous,index,lenth)
    self.index = index
    self.lenth = lenth 
    fsm:GetOwner():DrawCardMovePosition()
end

function DrawCardsFlyState:OnLeave(fsm)
    self.index = nil
    self.lenth = nil 
end

function DrawCardsFlyState:Dispose()
    self:OnLeave(nil)
end

function DrawCardsFlyState:OnFlyComplete(fsm)
    self:ChangeState(fsm,"DrawCardsTurnaroundState",self.index,self.lenth)
    UISound.play("powerup_put")
end
