---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/2/7 10:22
---

local SettleSuperMatchBangEnterState = require("State/SettleSuperMatchBange/SettleSuperMatchBangEnterState")
local SettleSuperMatchBangEffectState = require("State.SettleSuperMatchBange.SettleSuperMatchBangEffectState")
local SettleSuperMatchBangExitState = require("State.SettleSuperMatchBange.SettleSuperMatchBangExitState")

local SGSuperMatchMainView = BaseView:New('SGSuperMatchMainView', 'SGSuperMatchMainAtlas');
local this = SGSuperMatchMainView;
this.viewType = CanvasSortingOrderManager.LayerType.TopConsole


this.auto_bind_ui_items = {
    "root",
    "BrightBlock1",
    "BrightBlock2",
    "BrightBlock3",
    "BrightBlock4",
    "BrightBlock5",
    "BrightBlock6",
    "BrightBlock7",
    "BrightBlock8",
    "BrightBlock9",
    "BrightBlock10",
    "RewardTxt",
    "Chuizi",
    "Guo",
    "shitou",
    "tubiao",
    "topBg",
    "background",
    "btn_Anniu",
    "RewardIcon",
    "rwardTxt6",
    "rwardTxt5",
    "rwardTxt4",
    "rwardTxt3",
    "rwardTxt2",
    "rwardTxt1",
    "rwardTxt10",
    "rwardTxt9",
    "rwardTxt8",
    "rwardTxt7",
    "shu1",
    "shu2",
    "shu3",
    "shu4",
    "shu5",
    "shu6"
}



function SGSuperMatchMainView.Awake(obj)
    this:on_init()
end

function SGSuperMatchMainView:OnEnable(params)
    this.oriTimeScale = Time.timeScale
    Time.timeScale = 1
    if params then
        this._exit_callback = params
    end
    this.rewardInfo = ModelList.BattleModel:GetCurrModel():GetSettleExtraInfo("SuperMatchSmash")
    --测试模拟数据
    --this.rewardInfo = {
    --    rewardList = {  5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000 },
    --
    --    hitLevel = 5,
    --    itemId = 37034,
    --    progress = { 5, 8, 10 }
    --}
    --this.rewardInfo.rewardList["1"] = 5000
    --this.rewardInfo.rewardList["2"] = 10000
    --this.rewardInfo.rewardList["3"] = 15000
    --this.rewardInfo.rewardList["4"] = 20000
    --this.rewardInfo.rewardList["5"] = 25000
    --this.rewardInfo.rewardList["6"] = 30000
    --this.rewardInfo.rewardList["7"] = 35000
    --this.rewardInfo.rewardList["8"] = 40000
    --this.rewardInfo.rewardList["9"] = 45000
    --this.rewardInfo.rewardList["10"] = 50000

    this.itemType = this.rewardInfo.itemId == 37032 and 1 or (this.rewardInfo.itemId == 37033 and 2 or 3)
    this:ChangeBangType(this.itemType)
    this:RegisterEvent()
    this.rewardCoin = this.rewardInfo.rewardList[tostring(this.rewardInfo.hitLevel)] or 1
    FsmCreator:Create("SGSuperMatchMainView", this, {
        SettleSuperMatchBangEnterState,
        SettleSuperMatchBangEffectState,
        SettleSuperMatchBangExitState, }
    )
    this._fsm:StartFsm("SettleSuperMatchBangEnterState")
end

--- 根据itemtype改变界面背景图
function SGSuperMatchMainView:ChangeBangType(itemType)
    --this.tubiao.sprite = AtlasManager:GetSpriteByName("SettleSuperMatchBangAtlas", "JsClqCz" .. itemType)
    this.topBg.sprite = AtlasManager:GetSpriteByName("SGSuperMatchMainAtlas", "JsClq03" .. itemType)
    Cache.load_texture(AssetList["JsClq01" .. itemType], "JsClq01" .. itemType, function (objs)
        if this.background then
            this.background.texture = objs
        end
    end)
    local animaName = this.itemType == 1 and "enter1chuizi" or this.itemType == 2 and "enter2Guo" or "enter3Shitou"
    this.root:Play(animaName)
end

function SGSuperMatchMainView:OnDisable()
    FsmCreator:DisposeFsm(this)
    this:UnRegisterEvent()
end

function SGSuperMatchMainView.OnDestroy()
    this:Destroy()
end

---
function SGSuperMatchMainView:RegisterEvent()
end

---
function SGSuperMatchMainView:UnRegisterEvent()
end

--- 设置锤力器数据
function SGSuperMatchMainView:SetData()
    for i = 1, 10 do
        this["rwardTxt" .. i].text = fun.format_number(this.rewardInfo.rewardList[tostring(i)])
    end
    for i = 1, 6 do
        this["shu" .. i].text = fun.format_number(this.rewardInfo.rewardList[tostring(i)])
    end
    this.target = this.rewardInfo.hitLevel
    this.RewardTxt:SetValue(0)
end

--- 播放锤力器动画
function SGSuperMatchMainView:PlayAnimation()
    local animaName = this.itemType == 1 and "1chuizi" or this.itemType == 2 and "2Guo" or "3Shitou"
    local itemAudio = this.itemType == 1 and "smashhummer" or this.itemType == 2 and "smashpan" or "smashanvil"
    this.root:Play("act" .. animaName)
    UISound.play(itemAudio)
    LuaTimer:SetDelayFunction(2, function ()
        --this._fsm:ChangeState("SettleSuperMatchBangEnterState")
        --播放进度条上涨
        --this.target = 8
        coroutine.start(function ()
            local slider = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }
            table.each(slider, function (index)
                if index < this.target then
                    if this then
                        fun.set_active(this["BrightBlock" .. index], true)
                    end
                    WaitForSeconds(0.3)
                elseif index == this.target then
                    if this then
                        fun.set_active(this["BrightBlock" .. index], true)
                        this["BrightBlock" .. index]:Play("over")
                        this:RandomPlayAnima()
                        --this:PlayCoinEffect(this["BrightBlock" .. index].transform.position)
                        LuaTimer:SetDelayFunction(3, function ()
                            log.r("播放奖励弹窗 "..this.target)
                            if this and  fun.is_not_null(this["BrightBlock" .. this.target]) then
                                this:PlayCoinEffect(this["BrightBlock" .. this.target].transform.position)
                            end
                        end)
                    end
                else
                    --this:ResetStateIdle()
                end
            end)
        end)
    end)
end

--- 随机上一格或下一格播放动画
function SGSuperMatchMainView:RandomPlayAnima()
    local nextTarget = this.target
    local shanType = 1
    if this.target == 10 then
        nextTarget = 9
        shanType = 1
    elseif this.target == 1 then
        nextTarget = 2
        shanType = 2
    else
        if (math.random(1, 10) > 5) then
            nextTarget = this.target + 1
            shanType = 2
        else
            nextTarget = this.target - 1
            shanType = 1
        end
    end
    log.r("nextTarget  " .. nextTarget .. "      " .. this.target)
    fun.set_active(this["BrightBlock" .. (nextTarget)], true)
    this["BrightBlock" .. (nextTarget)]:Play("shan" .. shanType)
    LuaTimer:SetDelayFunction(1.5,function()
        UISound.play("smashwin")
    end)
end

--弹出奖励弹窗
function SGSuperMatchMainView:ShowRewardView()
    Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward, PopupViewType.show,
        ClaimRewardViewType.CollectReward,
        { { id = 2, value = this.rewardInfo.rewardList[tostring(this.rewardInfo.hitLevel)] } }, function ()
            Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward, PopupViewType.hide,
                ClaimRewardViewType.CollectReward)
            this:CloseAnimation()

        end)
end

--播放界面退场动画
function SGSuperMatchMainView:CloseAnimation()
    LuaTimer:SetDelayFunction(1.2,function()
        this.root:Play("end")
        LuaTimer:SetDelayFunction(1,function()
            if ViewList.SGSuperMatchMainView then
                Facade.SendNotification(NotifyName.CloseUI,ViewList.SGSuperMatchMainView)
                ViewList.SGSuperMatchMainView = nil
            end
            --- 结束的时候恢复原始速度
            if this.oriTimeScale then
                Time.timeScale = this.oriTimeScale
                this.oriTimeScale = nil
            end

            if this._exit_callback then
                this._exit_callback()
                this._exit_callback = nil
            end
        end)
    end)
end


--播放界面退场动画
function SGSuperMatchMainView:ForceExit()
    if this._exit_callback then
        this._exit_callback()
        this._exit_callback = nil
    end
    if ViewList.SGSuperMatchMainView then
        Facade.SendNotification(NotifyName.CloseUI,ViewList.SGSuperMatchMainView)
        ViewList.SGSuperMatchMainView = nil
    end
    --- 结束的时候恢复原始速度
    if this.oriTimeScale then
        Time.timeScale = this.oriTimeScale
        this.oriTimeScale = nil
    end
end

---播放金币爆开效果
function SGSuperMatchMainView:PlayCoinEffect(startPos)
    Facade.SendNotification(NotifyName.ShopView.FlyRewardEffcts, startPos, 2, function ()
        ---播放金币数字变化效果
        this:PlayCoinNumEffect()
    end, nil, nil, this.RewardIcon.transform.position)
end

---播放金币爆开效果
function SGSuperMatchMainView:PlayCoinNumEffect()
    if fun.is_not_null(this.RewardTxt) then
        this.RewardTxt:RollByTime(this.rewardCoin, 1, function ()
            LuaTimer:SetDelayFunction(0.5,function()
                this:ShowRewardView()
            end)
        end)
    else
        this:ShowRewardView()
    end
end

function SGSuperMatchMainView:ResetStateIdle()
    self._fsm:ChangeState("SettleSuperMatchBangEnterState")
end

function SGSuperMatchMainView:on_btn_Anniu_click()
    --self._fsm:ChangeState("SettleSuperMatchBangEffectState")
    if not this.lastClickTime then this.lastClickTime = 0 end
    if os.time() - this.lastClickTime < 2 then return end
    if self._fsm:GetCurName() ~= "SettleSuperMatchBangEnterState" then return end
    ModelList.SuperMatchModel.ReqSmashReward()
end

function SGSuperMatchMainView:PlayBangStart()
    self._fsm:ChangeState("SettleSuperMatchBangEffectState")
end

return this

