---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/7/27 11:21
---
------ 显示局部弹窗
local CommonPopupView = require("View.CommonTipView.CommonPopupView")
local Command = {};

---@param oktype 1:单按钮  2:双按钮错误层级弹窗  3:单按钮错误级弹窗 4:双按钮全局弹窗  5:单按钮全局弹窗
function Command.Execute(notifyName,content,oktype,sure_callback,cancel_cb,return_callback,...)
    local _view = nil
    if oktype<2 then
        _view = CommonPopupView:NewPop(CanvasSortingOrderManager.LayerType.Popup_Dialog)
        ModelList.PopupModel:AddPopupView(_view,3)
    else
        _view = CommonPopupView:NewPop(CanvasSortingOrderManager.LayerType.ErrorDialog)
        ModelList.PopupModel:AddPopupView(_view,4)
    end
    if return_callback then
        return_callback(_view)
    end
    local args = {...}
    _view:ShowDialog(nil,function()
        _view:SetInfo(nil, content,oktype,sure_callback,cancel_cb,args)
     end,false)
end

return Command