---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/8/15 13:08
---

local SevenDayLoginHistoryState = Clazz(BaseFsmState,"SevenDayLoginHistoryState")

function SevenDayLoginHistoryState:OnEnter(fsm,previous,...)
    log.g("OnEnter SevenDayLoginHistoryState")
    --Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward,PopupViewType.show,ClaimRewardViewType.sevenDayReward,nil,function()
    --    --this:GetReward()
    --end,nil,ClaimRewardAnimation.sevenDayLogin)
    local data = fsm:GetOwner():GetHistroyRewards()
    Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward,PopupViewType.show,ClaimRewardViewType.sevenDayReward,data,function()
        Facade.SendNotification(NotifyName.ClaimReward.PopupClaimReward, PopupViewType.hide, ClaimRewardViewType.sevenDayReward)
        ViewList.SevenDayLoginView:ShowReward()
    end,true,ClaimRewardAnimation.sevenDayHistory)

    fsm:GetOwner().ReqReward()
    self.fsm = fsm
end

function SevenDayLoginHistoryState:OnLeave(fsm)

end

function SevenDayLoginHistoryState:GetReward()
    self.fsm:GetOwner().ReqReward()
end


function SevenDayLoginHistoryState:GetGiftReward(boxId)
end

function SevenDayLoginHistoryState:OnContinue()
end

return SevenDayLoginHistoryState