---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2024/1/17 15:21
---

local FlyRewardEffectsView = require "View/FlyRewardEffectsView/FlyRewardEffectsView"
local FlyWinZoneMusicEffectsView = FlyRewardEffectsView:New("FlyWinMusicEffectsView",nil)
local this = FlyWinZoneMusicEffectsView
this.viewType = CanvasSortingOrderManager.LayerType.PackageDialog

function FlyWinZoneMusicEffectsView:New()
    local o = {}
    self.__index = self
    setmetatable(o,self)
    return o
end

function FlyWinZoneMusicEffectsView:GetFlyTargetPos()
    return GetTopRocketIconPos()
end

function FlyWinZoneMusicEffectsView:GetAnimationName()
    return "shopbuyCommon"
end

function FlyWinZoneMusicEffectsView:GetDurations()
    return {0.35,0.383,0.5,0.6,0.5,0.5,0.383,0.4,0.62,0.5,0.383,0.5,0.61,0.45,0.37,0.5,0.5}
end

return FlyWinZoneMusicEffectsView