---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/4/9 18:26
---



local ClimbRankBingoState = Clazz(BaseFsmState, "ClimbRankBingoState")
local this = ClimbRankBingoState

local PlayTime = {1.5,1.5,1.5}
local RewardType = {Bingo = 1, DoubleBingo =2,TripleBingo = 3,BingoRampage = 4}

function ClimbRankBingoState:New()
    local o = {}
    setmetatable(o, { __index = ClimbRankBingoState })
    return o
end

function ClimbRankBingoState:InitState()
end

local baseSettleReward = nil
local addCound = 0
local cardCount = 0
local needShowList ={}

function ClimbRankBingoState:OnEnter(fsm, previous )
    local settleData = ModelList.BattleModel:GetCurrModel():GetSettleData().groupSettleReward
    baseSettleReward = settleData.bingoSettleReward
    addCound = 0
    needShowList ={}
    cardCount = #fsm:GetOwner():GetCards()
    this._fsm = fsm
    --CalculateBingoMachine.totalBingoCount ={1,2,3,4}
    this:PlayBingo(fsm)
end

---@see 展示点击金币奖励
local CheckBingo = function(cardId)
    local totalCount = CalculateBingoMachine.GetTotalBingoCount(cardId)
    local count = totalCount == 1 and 1 or 0

    if count >0 then
        this._fsm:GetOwner():SetAddReward(cardId, 4,count )
        table.insert(needShowList,cardId)
        return true
    end
    return false
end

---@see 展示快速点击金币奖励
local CheckDoubleBingo = function(cardId)
    local totalCount = CalculateBingoMachine.GetTotalBingoCount(cardId)
    local count = totalCount == 2 and 1 or 0

    if count >0 then
        this._fsm:GetOwner():SetAddReward(cardId, 5,count )
        table.insert(needShowList,cardId)
        return true
    end
    return false
end

---@see 展示完美点击金币奖励
local CheckTripleBingo = function(cardId)
    local totalCount = CalculateBingoMachine.GetTotalBingoCount(cardId)
    local count = totalCount == 3 and 1 or 0

    if count >0 then
        this._fsm:GetOwner():SetAddReward(cardId, 6,count )
        table.insert(needShowList,cardId)
        return true
    end
    return false
end

---@see 展示完美点击金币奖励
local CheckBingoRampage = function(cardId)
    local totalCount = CalculateBingoMachine.GetTotalBingoCount(cardId)
    local count = totalCount >= 4 and 1 or 0

    if count >0 then
        this._fsm:GetOwner():SetAddReward(cardId, 7,count )
        table.insert(needShowList,cardId)
        return true
    end
    return false
end

local GetRewardContent = function(cardId)
    if CheckBingo(cardId) or CheckDoubleBingo(cardId) or CheckTripleBingo(cardId) or CheckBingoRampage(cardId) then

    end
end



function ClimbRankBingoState:PlayBingo(fsm )
    for i = 1, cardCount do
        GetRewardContent(i,RewardType.Bingo,fsm)
    end
    for i = 1, cardCount do
        if not fun.is_include(i,needShowList) then
            this._fsm:GetOwner():SetAddReward(i, 6,0 )
        end
    end
    if #baseSettleReward.bingo > 0 and baseSettleReward.bingo[1].value > 0 then
        addCound  = addCound + baseSettleReward.bingo[1].value
    end
    if #baseSettleReward.doubleBingo > 0 and baseSettleReward.doubleBingo[1].value > 0 then
        addCound  = addCound+ baseSettleReward.doubleBingo[1].value
    end
    if #baseSettleReward.tripleBingo > 0 and baseSettleReward.tripleBingo[1].value > 0 then
        addCound  = addCound + baseSettleReward.tripleBingo[1].value
    end
    if #baseSettleReward.bingoRampage > 0 and baseSettleReward.bingoRampage[1].value > 0 then
        addCound  = addCound + baseSettleReward.bingoRampage[1].value
    end
    if addCound > 0 then
        fsm:GetOwner():SetAddCountTxt(addCound)
        local PlayNext = function()
            this:PalyEnd()
        end
        fsm:GetOwner():PlayRewardJump(PlayNext)
    else
        this:PalyEnd()
    end
end


function ClimbRankBingoState:PalyEnd( )
    self:ChangeState(this._fsm,"ClimbRankPowerState")
end




function ClimbRankBingoState:OnLeave(fsm)
    this._fsm = nil
    self._owner = nil
    self._posX = nil
end

function ClimbRankBingoState:Dispose()
    self:OnLeave(nil)
end

return this