---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/4/9 18:26
---



local ClimbRankEndState = Clazz(BaseFsmState, "ClimbRankEndState")
local this = ClimbRankEndState

local RewardType = {Jackpot = 1}

function ClimbRankEndState:New()
    local o = {}
    setmetatable(o, { __index = ClimbRankEndState })
    return o
end

function ClimbRankEndState:InitState()
end

local baseSettleReward = nil
local addCound = 0
local cardCount = 0

function ClimbRankEndState:OnEnter(fsm, previous )
    this._fsm = fsm
    this:PlayWinFinal(fsm)
	--this:PlayWinFinal(fsm)
    log.log("dghdgh00008 ClimbRankEndState:OnEnter")
end

local GetCoinItemCount = function(gift)
    local count = 0
    for i = 1, #gift do
        if gift[i] == 1005 or gift[1] == 1006 or gift[1] == 1007 then
            count = count +1
        end
    end
    return count
end


---@see 展示点击金币奖励
local GetRefundCoin = function(cardId)
    local data = ModelList.BattleModel:GetCurrModel():GetRoundData(cardId)
    local itemCount = 0
    if data.isJackpot then
        itemCount = 1
    end
    itemCount = 1
    this._fsm:GetOwner():SetAddReward(cardId, 9,itemCount )
end



local GetRewardContent = function(cardId,rewardType)
    if rewardType == RewardType.Jackpot then
        GetRefundCoin(cardId)
    end
end



function ClimbRankEndState:PlayJackpot(fsm )
    -- if #baseSettleReward.jackpot > 0 and baseSettleReward.jackpot[1].value > 0 then
    --     for i = 1, cardCount do
    --         GetRewardContent(i,RewardType.Jackpot,fsm)
    --     end
    --     addCound  = baseSettleReward.jackpot[1].value
    --     fsm:GetOwner():SetAddCountTxt(addCound)
    --     local PlayNext = function()
    --         this:PalyEnd()
    --     end
    --     fsm:GetOwner():PlayRewardJump(PlayNext)
    -- else
    --     this:PalyEnd()
    -- end
    this:PalyEnd()
end

--中间再穿插最后的效果
function ClimbRankEndState:PlayWinFinal(fsm)
    if  fsm:GetOwner():IsBigWin() or fsm:GetOwner():IsNormalWin() then 
        local PlayNext = function()
            fsm:GetOwner():PlayCoinFly()
        end

        fsm:GetOwner():PlayRewardFinal(PlayNext)
    else 
        fsm:GetOwner():PlayCoinFly() -- 普通直接退出
    end 

end


function ClimbRankEndState:PalyEnd( )
  
end


function ClimbRankEndState:Finish()

end


function ClimbRankEndState:OnLeave(fsm)
    this._fsm = nil
    self._owner = nil
    self._posX = nil
end

function ClimbRankEndState:Dispose()
    self:OnLeave(nil)
end

return this