---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/4/9 15:11
---


local ClimbRankEnterState = Clazz(BaseFsmState, "ClimbRankEnterState")
local this = ClimbRankEnterState

function ClimbRankEnterState:New()
    local o = {}
    setmetatable(o, { __index = ClimbRankEnterState })
    return o
end

function ClimbRankEnterState:InitState()
end

function ClimbRankEnterState:OnEnter(fsm, previous )
    self._fsm = fsm
    --if fsm:GetOwner().IsFromRocketView  then
    --    --this:PlayCardDrop(fsm)
    --else
    --    this:ResetCards(fsm)
    --end
    this:PlayEnterAnima(fsm)
end

local anima = nil
function ClimbRankEnterState:PlayEnterAnima( fsm)
    local cardCount =  ModelList.BattleModel:GetCurrModel():GetCardCount()
    if ModelList.BattleModel:GetCurrBattleView():IsAuto() then
        fsm:GetOwner().view:Play("8enterguaji")
    else
        fsm:GetOwner().view:Play(cardCount.."enter")
    end
    anima = fsm:GetOwner().view
    this:start_x_update()
end

function ClimbRankEnterState:on_x_update()
    if anima then
        if  anima:GetCurrentAnimatorStateInfo(0) :IsName("idle") then
            this:stop_x_update()
            this:PlayOver()
        end
    end
end

--function ClimbRankEnterState:PlayCardDrop( fsm)
--    local cardList = fsm:GetOwner():GetCards()
--    local dropTime = 1
--    for i = 1, #cardList do
--
--        LuaTimer:SetDelayFunction(dropTime,function()
--            this:PlayOver()
--        end)
--    end
--end

function ClimbRankEnterState:ResetCards(fsm)
    local cardList = fsm:GetOwner():GetCards()
    for i = 1, #cardList do
        fun.set_gameobject_pos(cardList[i].gameObject,0,0,0,true)
        fun.set_gameobject_scale(cardList[i].gameObject,1,1,1)
    end
    this:PlayOver()
end

function ClimbRankEnterState:PlayOver()

    self:ChangeState(self._fsm,"ClimbRankDaubState")
end

function ClimbRankEnterState:ResetRank(fsm )

end

function ClimbRankEnterState:Finish()

end


function ClimbRankEnterState:OnLeave(fsm)
    self._fsm = nil
    self._owner = nil
    self._posX = nil
end

function ClimbRankEnterState:Dispose()
    self:OnLeave(nil)
end

return this