---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/4/9 18:26
---



local ClimbRankDaubState = Clazz(BaseFsmState, "ClimbRankDaubState")
local this = ClimbRankDaubState

local PlayTime = {1.5,1.5,1.5}
local RewardType = {Duba = 1, FastDuba =2,PerfectDuba = 3}

function ClimbRankDaubState:New()
    local o = {}
    setmetatable(o, { __index = ClimbRankDaubState })
    return o
end

function ClimbRankDaubState:InitState()
end

local baseSettleReward = nil
local addCound = 0
local cardCount = 0

function ClimbRankDaubState:OnEnter(fsm, previous )
    --- 修复bug View/Bingo/SettleModule/State/ClimbRank/ClimbRankDaubState:29: attempt to index a nil value
    if not ModelList.BattleModel:GetCurrModel() or  not ModelList.BattleModel:GetCurrModel():GetSettleData() then
        self:PalyEnd()
        return
    end
    local settleData = ModelList.BattleModel:GetCurrModel():GetSettleData().groupSettleReward
    if not settleData or not settleData.baseSettleReward then
        self:PalyEnd()
        return
    end
    baseSettleReward = settleData.baseSettleReward
    addCound = 0
    cardCount = #fsm:GetOwner():GetCards()
    this._fsm = fsm
    this:PlayDuba(fsm,baseSettleReward)
    GoPool.destroy_go_pool_unactive_dic()
end

---@see 展示点击金币奖励
local GetClickDuba = function(cardId)
    local data = ModelList.BattleModel:GetCurrModel():GetRoundData(cardId)
    local dubaCount = 0
    for i = 1, #data.cards do
        if data.cards[i].sign > 0 then
            dubaCount = dubaCount + 1
        end
    end
    ---去掉默认盖章的格子
    this._fsm:GetOwner():SetAddReward(cardId, 1, dubaCount - 1)
end

---@see 展示快速点击金币奖励
local GetFastDuba = function(cardId)
    local fastDuba = CallNumberMachine.GetFastClickDataByCardId()
    local dubaCount = 0
    cardId = tonumber(cardId)
    if fastDuba[cardId]  and fastDuba[cardId]>0 then
        dubaCount = fastDuba[cardId]
    end
    this._fsm:GetOwner():SetAddReward(cardId, 2,dubaCount)
end

---@see 展示完美点击金币奖励
local GetPerfectDuba = function(cardId)
    local perfectDuba = ModelList.BattleModel:GetCurrModel():GetPerfectInfo(cardId)
    this._fsm:GetOwner():SetAddReward(cardId, 3,perfectDuba and 1 or 0)
end

local GetRewardContent = function(cardId,rewardType)
    if rewardType == RewardType.Duba then
        GetClickDuba(cardId)
    elseif rewardType == RewardType.FastDuba then
        GetFastDuba(cardId)
    elseif rewardType == RewardType.PerfectDuba then
        GetPerfectDuba(cardId)
    end
end



function ClimbRankDaubState:PlayDuba(fsm )
    if #baseSettleReward.daub > 0 and baseSettleReward.daub[1].value > 0 then
        for i = 1, cardCount do
            GetRewardContent(i,RewardType.Duba,fsm)
        end
        addCound  = addCound +baseSettleReward.daub[1].value
        fsm:GetOwner():SetAddCountTxt(addCound)
        local PlayNext = function()
            this:PlayFastDuba()
           
        end
        fsm:GetOwner():PlayRewardJump(PlayNext)
    else
        this:PlayFastDuba()
    end
end

function ClimbRankDaubState:PlayFastDuba( )
    if #baseSettleReward.quickDaub > 0 and baseSettleReward.quickDaub[1].value > 0 then
        for i = 1, cardCount do
            GetRewardContent(i,RewardType.FastDuba,this._fsm)
        end
        addCound  = addCound +baseSettleReward.quickDaub[1].value
        this._fsm:GetOwner():SetAddCountTxt(baseSettleReward.quickDaub[1].value)
        local PlayNext = function()
            this:PlayPerfectDuba()
        end
        this._fsm:GetOwner():PlayRewardJump(PlayNext)
    else
        this:PlayPerfectDuba()
    end
end

function ClimbRankDaubState:PlayPerfectDuba( )
    if #baseSettleReward.perfectDaub > 0 and baseSettleReward.perfectDaub[1].value > 0 then
        for i = 1, cardCount do
            GetRewardContent(i,RewardType.PerfectDuba,this._fsm)
        end
        addCound  = addCound +baseSettleReward.perfectDaub[1].value
        this._fsm:GetOwner():SetAddCountTxt(baseSettleReward.perfectDaub[1].value)
        local PlayNext = function()
            this:PalyEnd()
        end
        this._fsm:GetOwner():PlayRewardJump(PlayNext)
    else
        this:PalyEnd()
    end
end

function ClimbRankDaubState:PalyEnd()
      self:ChangeState(this._fsm,"ClimbRankBingoState")
    if addCound <= 0 then

    else

    end
end


function ClimbRankDaubState:Finish()

end


function ClimbRankDaubState:OnLeave(fsm)
    this._fsm = nil
    self._owner = nil
    self._posX = nil
end

function ClimbRankDaubState:Dispose()
    self:OnLeave(nil)
end

return this
