---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 25/10/2024 下午 3:51
---

---
---@class ScratchWinnerExtraBallEffect : BaseChildView
local ScratchWinnerExtraBallEffect = BaseChildView:New()
local this = ScratchWinnerExtraBallEffect
this.__index = this

this.auto_bind_ui_items = {
    "Anima",
    "number1",
    "number2",
    "Icon",
    "Text",

}

function ScratchWinnerExtraBallEffect:New()
    local o = {}
    setmetatable(o, { __index = this })
    return o
end

--@param cardId 卡牌ID
--@param cellIndex 格子位置索引
--@param effectIndex 效果类型 1:星星 2:铃铛 3:熊娃娃 4:美元 5:钻石
--@param num 格子数字
function ScratchWinnerExtraBallEffect:SetType(cardId, cellIndex, effectIndex, num,isBigIdle)
    local iconName = "ScratchJSIcon0" .. effectIndex
    self.Icon.sprite = AtlasManager:GetSpriteByName("ScratchWinnerExtraBallAtlas", iconName)
    self.Text.text = "+" .. ModelList.ScratchWinnerModel:GetBingoReward(effectIndex, true)
    if num <= 9 then
        self.number1.sprite = AtlasManager:GetSpriteByName("BattleExtraAtlas", "nub_" .. num)
        fun.set_rect_local_pos(self.number1, 0, 0, 0)
        fun.set_active(self.number2, false)
    else
        self.number1.sprite = AtlasManager:GetSpriteByName("BattleExtraAtlas", "nub_" .. math.floor(num / 10))
        self.number2.sprite = AtlasManager:GetSpriteByName("BattleExtraAtlas", "nub_" .. math.fmod(num, 10))
    end
    if isBigIdle then
        self.Anima:Play("idleda",0,0)
        if fun.is_not_null(self.go) then
            fun.SetAsLastSibling(self.go)
        end
        self.isBigIdle =true
    else
        self.Anima:Play("idlexiao",0,0)
        self.isBigIdle =false
    end
end

--- 是否是大的idle动画
function ScratchWinnerExtraBallEffect:IsBigIdle()
    return self.isBigIdle
end

--- 是否是大的idle动画
function ScratchWinnerExtraBallEffect:PlayIdle(isBig)
    if isBig then
        self.Anima:Play("idleda",0,0)
        self.isBigIdle =true
        if fun.is_not_null(self.go) then
            fun.SetAsLastSibling(self.go)
        end
    else
        self.Anima:Play("idlexiao",0,0)
        self.isBigIdle =false
    end
end

--- 隐藏
function ScratchWinnerExtraBallEffect:SetActive(isActive)
    if self then
        fun.set_active(self.go, isActive)
    end
end

--播放命中动画
function ScratchWinnerExtraBallEffect:PlayHit()
    if self then
        self.Anima:Play("zhong")
    end
end


function ScratchWinnerExtraBallEffect.RefreshSelfData(item, rank, reward)
    item.text_ranked.text = rank
    item.text_reward.text = fun.formatNum(reward)
end

function ScratchWinnerExtraBallEffect.RefreshOtherData(item, rank)
    item.text_ranked.text = rank
end

function ScratchWinnerExtraBallEffect.RefreshOtherPlayerTrophy(item, tiers)
    if tiers and tiers ~= 0 then
        fun.set_active(item.image_trophy, true)
        local trophyName = fun.GetCurrTournamentActivityImg(tiers)

        Cache.load_sprite(AssetList["trophyName"], trophyName, function (sprite)
            if fun.is_not_null(sprite) and fun.is_not_null(item.image_trophy) then
                item.image_trophy.sprite = sprite
            end
        end)
    else
        fun.set_active(item.image_trophy, false)
    end
end

function ScratchWinnerExtraBallEffect.RefreshMyTrophy(item, tiers)
    if ModelList.TournamentModel:CheckOpenTournament() then
        item:RefreshOtherPlayerTrophy(tiers)
    else
        fun.set_active(item.image_trophy, false)
    end
end

return this
