---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/8/22 20:14
---



TopVipSliderGrowMaxState =  Clazz(BaseFsmState,"TopVipSliderGrowMaxState")

function TopVipSliderGrowMaxState:New()
    local o = {}
    self.__index = self
    setmetatable(o,self)
    return o
end

function TopVipSliderGrowMaxState:InitState()
end

function TopVipSliderGrowMaxState:OnEnter(fsm)
    --log.r("TopVipSliderGrowMaxState")
    fsm:GetOwner():GrowSlider()
end

function TopVipSliderGrowMaxState:Dispose()

end

function TopVipSliderGrowMaxState:OnLeave(fsm)

end

function TopVipSliderGrowMaxState:FinishStiff(fsm)

end

function TopVipSliderGrowMaxState:Finish(fsm)

end