---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/7/3 9:39
---

---@class BaseFsmState
BaseFsmState = Clazz()

FsmState = {Init = 1,Enter_start = 2,Enter_end = 3,Leave_start = 4,Leave_end = 5}

function BaseFsmState:InitState(fsm)
    if self.OnInit then
        self:OnInit(fsm)
        self._fsmState = FsmState.Init
    end
end

---
---子类重写
---
function BaseFsmState:OnInit(fsm)

end

function BaseFsmState:EnterState(fsm,previous,...)
    if self.OnEnter then
        self._fsmState = FsmState.Enter_start
        self:OnEnter(fsm,previous,...)
        self._fsmState = FsmState.Enter_end
        if self._waitAction then
            self._waitAction()
            self._waitAction = nil
        end
    end
end

---
---子类重写
---
function BaseFsmState:OnEnter(fsm,previous,...)

end

---
---子类重写
---
function BaseFsmState:RepeatedEnter(fsm,...)
    
end

function BaseFsmState:LeaveState(fsm)
    self:stop_x_update()
    if self.OnLeave then
        self._fsmState = FsmState.Leave_start
        self:OnLeave(fsm)
        self._fsmState = FsmState.Leave_end
    end
end

---
---子类重写
---
function BaseFsmState:OnLeave(fsm)

end

function BaseFsmState:ChangeState(fsm,stateName,...)
    if fsm then
        fsm:ChangeState(stateName,...)
    end
end

function BaseFsmState:WaitActionComplete(callback)
    self._waitAction = callback
end

function BaseFsmState:start_x_update()
    self:stop_x_update()
    self.start_time = fun.get_real_time_since_startup()
    self.update = xp_call(function()
        self:on_x_update()
    end)

    self.update_x_handler = UpdateBeat:CreateListener(self.update)
    UpdateBeat:AddListener(self.update_x_handler)
end

function BaseFsmState:stop_x_update()
    if self.update_x_handler then
        UpdateBeat:RemoveListener(self.update_x_handler)
        self.update_x_handler = nil
    end
end

---
---子类重写
---
function BaseFsmState:on_x_update()

end

function BaseFsmState:Dispose()
    self:stop_x_update()
    self._fsmState = nil
    if self.OnDispose then
        self:OnDispose()
    end
end

function BaseFsmState:OnDispose()
    
end

function BaseFsmState:IsDispose()
    return self._fsmState == nil
end

function BaseFsmState:FsmState()
    return self._fsmState or 0
end