---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2024/3/5 10:24
---


local BasePassTaskReward = BaseView:New("BasePassTaskReward")
local this = BasePassTaskReward
this.viewType = CanvasSortingOrderManager.LayerType.None
this._cleanImmediately = true 
this.auto_bind_ui_items = {
    "stage_slider",
    "rewardIcon",
    "text_stage_tip",
    "rewardCount",
}

function BasePassTaskReward:New()
    local o = {}
    self.__index = self
    setmetatable(o,self)
    return o
end

function BasePassTaskReward:Awake()
    self:on_init()
end

function BasePassTaskReward:OnEnable()
    self._init = true
    self:SetStageReward(self._taskStage)
end

function BasePassTaskReward:OnDisable()
    self._init = nil
    self._taskStage = nil
end

function BasePassTaskReward:SetStageReward(taskType)
    self._taskStage = taskType
    if self._init and taskType then
        local exp = ModelList.GameActivityPassModel.GetCurrExp()
        self._exp = exp
        local  GetCurrentId = ModelList.GameActivityPassModel.GetCurrentId()
        self._currPassId = ModelList.GameActivityPassModel.GetCurrPassId(GetCurrentId )
        taskType = taskType + 1
        local passreward = ModelList.GameActivityPassModel.GetCurrentPassRewardById(taskType)
        self.targetExp = nil
        if passreward then
            self.targetExp =   passreward.exp--     Csv.GetData("task_pass",taskType,"exp")
        end
        if not self.targetExp then
            taskType = taskType - 1
            self.targetExp = ModelList.GameActivityPassModel.GetCurrentPassRewardById(taskType).exp--Csv.GetData("task_pass",taskType,"exp")
        end
        self._process = exp / math.max(self.targetExp,1)
        self.stage_slider.value = self._process
        self.text_stage_tip.text = string.format("%s/%s",exp,self.targetExp)
        local data = ModelList.GameActivityPassModel.GetCurrentPassRewardById(taskType)
        self.rewardIcon.sprite = AtlasManager:GetSpriteByName("ItemAtlas", data.pay_reward_icon)

  
        self.rewardCount.text = fun.FormatText({id =data.pay_reward[1][1],value =  data.pay_reward[1][2]})
    end
end

function BasePassTaskReward:IsRewarding()
    if self.isRewarding then
        return true
    end
    return false
end

function BasePassTaskReward:SetSliderChange()
    local oldExp = self._exp
    local oldPassId = self._currPassId
    self._showPassId = self._currPassId
    local oldTargetExp = self.targetExp
    self._exp = ModelList.GameActivityPassModel.GetCurrExp()
    --local  GetCurrentId = ModelList.GameActivityPassModel.GetCurrentId()
    self._currPassId = ModelList.GameActivityPassModel.GetCurrPassId( )
    local passCout = ModelList.GameActivityPassModel.GetCurrPassCout( )
    self.targetExp =  ModelList.GameActivityPassModel.GetCurrentPassRewardById(math.min(self._currPassId+1,passCout) ).exp--Csv.GetData("task_pass",self._currPassId+1,"exp")
    --log.y("oldexp "..oldExp.." oldPassId "..oldPassId.." oldTargetExp "..oldTargetExp)
    --        log.y( " self._exp "..self._exp.." self._currPassId "..self._currPassId.. " self.targetExp "..self.targetExp)
    if not self.targetExp then
        self.targetExp =  ModelList.GameActivityPassModel.GetCurrentPassRewardById(self._currPassId).exp --Csv.GetData("task_pass",self._currPassId,"exp")
    end
    if oldPassId ~= self._currPassId then
        --Anim.slide_to_num(self.stage_slider,self.text_stage_tip, oldTargetExp,oldTargetExp,1,function()
        --    self:PlayTurnPage(true)
        --end)
        self:LoopPlayTurnPage()
    else
        Anim.slide_to_num(self.stage_slider,self.text_stage_tip, self._exp,self.targetExp,1,function()
            Event.Brocast(EventName.Event_PassGetTaskRefreshIcon)
        end)
    end
end

function BasePassTaskReward:LoopPlayTurnPage()
    if self and fun.is_not_null(self.stage_slider) then
        self.targetExp =  ModelList.GameActivityPassModel.GetCurrentPassRewardById(self._showPassId+1).exp--Csv.GetData("task_pass",self._showPassId+1,"exp")
        if not self.targetExp then
            self.targetExp =  ModelList.GameActivityPassModel.GetCurrentPassRewardById(self._showPassId).exp  -- Csv.GetData("task_pass",self._showPassId,"exp")
        end
        Anim.slide_to_num(self.stage_slider,self.text_stage_tip, self.targetExp,self.targetExp,1,function()
            self._showPassId = self._showPassId + 1
            Event.Brocast(EventName.Event_PassGetTaskRefreshRewardIcon)
            if self._showPassId == self._currPassId then
                self:PlayTurnPage()
            else
                self:LoopPlayTurnPage()
            end
        end)
    end
end


function BasePassTaskReward:PlayTurnPage()
    local exp = ModelList.GameActivityPassModel.GetCurrExp()
    --local  GetCurrentId = ModelList.GameActivityPassModel.GetCurrentId()
    --local passTaskId = ModelList.GameActivityPassModel.GetCurrPassId(GetCurrentId)
    self.stage_slider.value = 0
    --local targetExp = Csv.GetData("task_pass",passTaskId,"exp")
    --log.y("exp "..exp.." targetExp "..self.targetExp)
    Anim.slide_to_num(self.stage_slider,self.text_stage_tip, exp,self.targetExp,1,function()
        Event.Brocast(EventName.Event_PassGetTaskRefreshIcon)
    end)
end

--function BasePassTaskReward:AddEvent()
--    Event.AddListener(EventName.Event_GetTaskRewardSucceed,self.ClaimRewardResult,self)
--end
--
--function BasePassTaskReward:RemoveEvent()
--    Event.RemoveListener(EventName.Event_GetTaskRewardSucceed,self.ClaimRewardResult,self)
--end

return this