---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/10/13 14:20
---

--- 整局的卡面数据

local CardData = require("Combat.Data.CardData")
local CellData = require("Combat.Data.CellData")

local RoundData = {}
local this = RoundData
RoundData.__index = RoundData
this.roundData = {}

function RoundData:CreateRoundData()
    local mindex = ""
    this.roundData = {}
    this.num_to_index = {}
    local cardsInfo = ModelList.BattleModel:GetCurrModel():GetCards()
    for i = 1, #cardsInfo do
        --- 历史原因 之前的cardId是很长的一个字符串，以后可以优化成int
        mindex = tostring(cardsInfo[i].cardId)
        local id_index_temp = {}
        --- 单张卡牌的信息
        this.roundData[mindex] = CardData:New(i)
        --- 单个格子的信息
        for j = 1, #cardsInfo[i].numbers do
            local cell = CellData:New(cardsInfo[i].numbers[j], j, cardsInfo[i].cardId)
            table.insert(this.roundData[mindex].cards, cell)
            id_index_temp[cardsInfo[i].numbers[j]] = j
        end
        this.num_to_index[mindex] = id_index_temp
    end
    this.ext = {}
end

---获取单张卡牌
function RoundData:GetCard(cardid)
    cardid = tostring(cardid)
    return this.roundData[cardid]
end

---获取单个格子
function RoundData:GetCell(cardid, index)
    cardid = tostring(cardid)
    local cardData = this.roundData[cardid]
    if cardData and cardData.cards then
        return cardData.cards[index]
    end
end

---获取卡牌所有格子
function RoundData:GetCells(cardid)
    cardid = tostring(cardid)
    return this.roundData[cardid].cards
end

---设置放大镜显示状态
function RoundData:SetMirror2(cardid, index)
    this:GetCell(cardid, index):SetMirror2()
end

--- 格子放大镜是否正在显示状态
function RoundData:IsMirror2(cardid, index)
    --local mindex = tostring(cardid)
    --return not this.roundData[mindex].cards[index].is_mirror
    return this:GetCell(cardid, index):IsMirror2()
end

--- 单元格开启美食篮子
function RoundData:SetCellBasketInfo(card_id, cellIndex, basketInfo, itemId)
    local cardid = tostring(card_id)
    this:GetCell(cardid, cellIndex):AddBaseket(basketInfo, itemId)
end

function RoundData:GetCellBasketReward(card_id, cellIndex, itemId)
    local cardid = tostring(card_id)
    return this:GetCell(cardid, cellIndex):GetCellBasketReward(itemId)
end

function RoundData:GetWishState(card_id, cellIndex)
    return this:GetCell(card_id, cellIndex).wishState
end

function RoundData:GetRoundDataByNum(cardid, num)
    if num then
        local card_id = tostring(cardid)
        for i = 1, #this.roundData[card_id].cards do
            local card = this.roundData[card_id].cards[i]
            if card.num == num or card.double_num == num then
                return card
            end
        end
    elseif cardid then
        local card_id = tostring(cardid)
        --return this.roundData[card_id]
        return this:GetCard(cardid)
    else
        return this.roundData
    end
end

--- 设置格子双数字
function RoundData:SetDoubleData(card_id, cell_index, new_number)
    --this.roundData[card_id].cards[cell_index].double_num = new_number
    this:GetCell(card_id, cell_index):SetDouble(new_number)
end

--- 设置格子mark状态
function RoundData:SetCellMark(card_id, cell_index, mark)
    this:GetCell(card_id, cell_index):SetMark(mark)
end

---单张卡获得bingo
function RoundData:CardBeBingo(card_id)
    this:GetCard(card_id):BeBingo()
end

---单张卡获得jackpot
function RoundData:CardBeJackpot(card_id)
    this:GetCard(card_id):BeJackpot()
end

---格子增加新道具
function RoundData:SetNewGift(cardId, cellIndex, newGift)
    if self and self["GetCell"] then
        local cellData = self:GetCell(cardId, cellIndex)
        if cellData then
            cellData:AddGift(newGift)
        end
        Facade.SendNotification(NotifyName.RewardCollect.OnPutRewardToCell, cardId, cellIndex, newGift)
    end
end

---格子删除道具
function RoundData:RemoveGift(itemID, cardId, cellIndex)
    if self and self["GetCell"] then
        table.walk(this.roundData, function(cardData, k1)
            table.walk(cardData.cards, function(cellData, k2)
                if cardId ~= k1 and cellIndex ~= k2 then
                    local remove = cellData:RemoveGift(itemID)
                    if remove then
                        Event.Brocast(EventName.Remove_Cell_Item, k1, k2, itemID)
                    end
                end
            end)
        end)
    end
end

--- 隐藏不显示的道具
function RoundData:SetHideGift(cardId, cellIndex, hideGift, count)
    if self and self["GetCell"] then
        local cellData = self:GetCell(cardId, cellIndex)
        if cellData then
            cellData:AddHideGift(hideGift, count)
        end
    end
end

--- 格子增加新技能
function RoundData:SetNewSkill(cardId, cellIndex, skill_id)
    if self and self["GetCell"] then
        local cellData = self:GetCell(cardId, cellIndex)
        if cellData then
            cellData:AddSkill(skill_id)
        end
    end
end

--- 自身获取bingo
function RoundData:SetSelfBingo(cardId, cellIndex)
    if self and self["GetCell"] then
        local cellData = self:GetCell(cardId, cellIndex)
        if cellData then
            cellData:SelfBingo()
        end
    end
end

---增加pu
function RoundData:AddPowerId(cardId, cellIndex, powerId, extraPos)
    if self and self["GetCell"] then
        local cellData = self:GetCell(cardId, cellIndex)
        if cellData then
            cellData:AddPowerupId(powerId, extraPos)
        end
    end
end

--- 改变wish状态
function RoundData:ChangeWishState(cardId, cellIndex, state)
    if self and self["GetCell"] then
        local cellData = self:GetCell(cardId, cellIndex)
        if cellData then
            cellData:ChangeWishState(state)
        end
    end
end

--- 单个格子是否又道具
function RoundData:HasCardCellGift(card_id, cell_index)
    local cardId = tostring(card_id)
    if #this.roundData[cardId].cards[cell_index].gift > 0 then
        for i = 1, #this.roundData[cardId].cards[cell_index].gift do
            local giftId = this.roundData[cardId].cards[cell_index].gift[i]
            local boxType = Csv.GetData("item", giftId, "box_type")
            if boxType ~= "0" then
                return true
            end
        end
    else
        return false
    end
    return false
end

---是否已经签名过,使用格子数字
function RoundData:IsSigned(cardid, num)
    local cells = this:GetCells(cardid)
    for i = 1, #cells do
        if cells[i]:IsSignedByNum(num) then
            return true
        end
    end
    return false
end

---是否已经签名过,使用索引
function RoundData:CanSignByIndex(cardid, index)
    if this:GetCell(cardid, index).sign == 0 then
        return true
    end
    return false
end

---获取整局数据
function RoundData:GetRoundData()
    return this.roundData
end

---使用数字查找卡牌索引
function RoundData:GetIndexByNum(card_id, num)
    local cardid = tostring(card_id)
    return this.num_to_index[cardid][num]
end

---增加双数字的数据
function RoundData:AddDoubleNum(data)
    table.walk(data, function(v)
        local cardId, effectData, temp = v.cardId, v.effectData, {}
        local posList = effectData.posList
        local extraData = JsonToTable(effectData.extra or "")
        local numberList = extraData.numbers or {}
        
        if cardId and GetTableLength(posList) > 0 and GetTableLength(numberList) > 0 then
            local pos = posList[1]
            local find = table.find(numberList, function(k, d)
                return d.pos == pos
            end)
            local doubleNum = find and find.number or 0
            self:GetCard(cardId):AddDoubleNumExtData(cardId, pos, doubleNum)
        end
    end)
end

return this
