---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/7/9 17:48
---

---@每日登陆奖励

local BaseOrder = require "PopupOrder/BaseOrder"
local PopupOrder = Clazz(BaseOrder,"")
local this = PopupOrder

function PopupOrder.Execute(arg)
    local daily_reddot = ModelList.TaskModel.GetRewardInfo(TaskToggle.daily)
    local weekly_reddot = ModelList.TaskModel.GetRewardInfo(TaskToggle.weekly)
    if  (daily_reddot.canGetReward) or (weekly_reddot.canGetReward) then
      
     
        if (daily_reddot.isUpdata or weekly_reddot.isUpdata)  then
            daily_reddot.isUpdata = nil
            weekly_reddot.isUpdata = nil
            Event.AddListener(EventName.Event_popup_task_tip_finish,PopupOrder.Finish,this)
            Facade.SendNotification(NotifyName.ShowUI,ViewList.TaskView,nil,nil,false)
        else
            PopupOrder.Finish()
        end
    else

        local nextCanShowTaskUnix = 0;
        local dataTime = Csv.GetControlByName("task_progress_cd")[1][1]
        local flag = false 
        nextCanShowTaskUnix = fun.read_value("nextCanShowTaskUnix",0);

        if (os.time() - nextCanShowTaskUnix >dataTime) then 
            flag = true 
            nextCanShowTaskUnix =os.time()
            fun.save_value("nextCanShowTaskUnix",nextCanShowTaskUnix);
        end 

        if flag then 
            local tipState = fun.read_value(DATA_KEY.task_today_show_state)
            local data = ModelList.TaskModel.GetDailyTask()
            local loginShow = tipState == 2 and ( data ) and #data > 0
            if loginShow  or  (ModelList.TaskModel.NeedShowDailyTipShow() ) then
                Event.AddListener(EventName.Event_popup_task_tip_finish,PopupOrder.Finish,this)
                Event.Brocast(EventName.Event_TaskTipUpdate)
                return
            end
        end 

     
        PopupOrder.Finish()
    end
end

function PopupOrder.Finish()
    Event.RemoveListener(EventName.Event_popup_task_tip_finish,PopupOrder.Finish,this)
    log.g("brocast  EventName.Event_popup_order_finish ")
    Event.Brocast(EventName.Event_popup_order_finish,true)
end

return PopupOrder