---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2021/12/14 17:08
---
---
local CallNumberBaseState = require("View/Bingo/CallNumberState/CallNumberBaseState")
local CallNumberIdleState = Clazz(CallNumberBaseState,"CallNumberIdleState")
local this = CallNumberIdleState
function CallNumberIdleState:New()
    local o = {}
    setmetatable(o,{__index = CallNumberIdleState})
    return o
end

function CallNumberIdleState:InitState()
end

function CallNumberIdleState:OnEnter(fsm)
    --self._fsm = fsm
    --self._owner = fsm:GetOwner()
end

function CallNumberIdleState:OnLeave(fsm)
    --self._fsm = nil
    --self._owner = nil
    --self._posX = nil
end

function CallNumberIdleState:Dispose()
    self:OnLeave(nil)
end

return this