---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PC.
--- DateTime: 2022/3/24 20:48
---

BattleTool = {}

function BattleTool.ConvertedToServerPosList(cellIndexList)
    local ret = {}
    table.each(cellIndexList, function(cellIndex)
        local index = ConvertCellIndexToServerPos(cellIndex)
        table.insert(ret, index)
    end)
    return ret
end

function BattleTool.GetFromServerPos(posList)
    local empty_cell = {}
    for i = 1, #posList do
        local index = ConvertServerPos(posList[i])
        table.insert(empty_cell, index)
    end
    return empty_cell
end

function BattleTool.PrintList (posList)
    local content = ""
    for i = 1, #posList do
        content = content .."  "..posList[i]
    end
    return content
end

--- 转化在小火箭收到的额外盖章位置信息
function BattleTool.GetExtraPos (serverExtraPos)
    local extraPos = {}
    if serverExtraPos  then
        if  type(serverExtraPos) == "string"  and  #tostring(serverExtraPos) > 2 then
            serverExtraPos = tostring(serverExtraPos)
            for i = 1, string.len(serverExtraPos) / 2 - 1 do
                table.insert(extraPos, tonumber(string.sub(serverExtraPos, 3 + (i - 1) * 2, 4 + (i - 1) * 2)))
            end
        elseif  type(serverExtraPos) == "table" then
            extraPos = serverExtraPos
        else
            log.r("不知类型的额外数据，请检查", serverExtraPos)
        end
    end
    return extraPos
end


function BattleTool.CheckEffectPlayOver ()
    if not ModelList.BattleModel:GetCurrModel():IsBingoShowComplete() then
        return false
    end
    local gameType = ModelList.BattleModel:GetGameCityPlayID()
    local transition_check_effect = Csv.GetData("new_game_settle",gameType,"transition_check_effect")
    if transition_check_effect == 2   then
        local condition1 = BattleEffectCache:CheckEffectAllHideWithoutJackpot()
        local condition2 = BattleEffectPool:IsCardHideAllBindEffect()
        log.log("BattleTool.CheckEffectPlayOver effect2 c1, c2", condition1, condition2)
        return condition1 and condition1
    elseif transition_check_effect == 3   then
        return BattleEffectCache:CheckEffectAllHideWithoutBingo()  and BattleEffectPool:IsCardHideAllBindEffect()
    else
        return BattleEffectCache:CheckEffectAllHide() and BattleEffectPool:IsCardHideAllBindEffect()
    end
end

function BattleTool.CheckEffectPlayOver2 ()
    if not ModelList.BattleModel:GetCurrModel():IsBingoShowComplete() then
        return false
    end
    local gameType = ModelList.BattleModel:GetGameCityPlayID()
    local transition_check_effect = Csv.GetData("new_game_settle",gameType,"transition_check_effect")
    if transition_check_effect == 2   then
        return BattleEffectCache:CheckEffectAllHideWithoutJackpot()  and BattleEffectPool:IsCardHideAllBindEffect()
    elseif transition_check_effect == 3   then
        return BattleEffectCache:CheckEffectAllHideWithoutBingo()  and BattleEffectPool:IsCardHideAllBindEffect()
    else
        return BattleEffectCache:CheckEffectAllHide() and BattleEffectPool:IsCardHideAllBindEffect() and ModelList.BattleModel:GetCurrBattleView():GetCardView():OutFrame()
    end
end


--- 结算过渡界面，检查是否完成特效展示
function BattleTool.CheckEffectPlayOver3 ()
    return true
    --if not ModelList.BattleModel:GetCurrModel():IsBingoShowComplete() then return false end
    --local gameType = ModelList.BattleModel:GetGameCityPlayID()
    --local transition_check_effect = Csv.GetData("new_game_settle",gameType,"transition_check_effect")
    --if transition_check_effect == 2  then
    --    return BattleEffectCache:CheckEffectAllHideWithoutJackpot()
    --elseif transition_check_effect == 3   then
    --    return BattleEffectCache:CheckEffectAllHideWithoutBingo()
    --else
    --    return BattleEffectCache:CheckEffectAllHide()
    --end
end

--- 计算下一个pu可能投放的位置
function BattleTool.GetNextPowerUpPos(cardId)
    local cardPower, pos = BattleModuleList.GetModule("CardPower"), {}
    
    local cardAllHitPos = cardPower:GetCardAllHitPosData(cardId)
    local puHitPos = CallNumberMachine:GetCellHoldByPu(cardId)
    local freePos, find = {}
    if cardAllHitPos then
        for i = 1, #cardAllHitPos do
            if not fun.is_include(cardAllHitPos[i].index ,puHitPos) then
                if  cardPower:GetSign(cardId, cardAllHitPos[i].index ) == 0  and
                        cardPower:GetGiftCount(cardId, cardAllHitPos[i].index ) == 0 then
                    table.insert(pos, cardAllHitPos[i].index)
                    find = true
                    break
                end
                table.insert(freePos,cardAllHitPos[i].index)
            end
        end
    end
    if not find and #freePos > 0 then
        table.insert(pos, freePos[1])
    end

    local otherPos = cardPower:GetNoHitPos(cardId, 1, 2)
    if otherPos and #otherPos > 0 then
        table.insert(pos, otherPos[1])
    end
    
    return pos
end
